### ISSUE TITLE
Does it work with PostgreSQL?

### ISSUE THREAD

**Issue by karimmtarek** [owen2345/camaleon-cms#1]
I tried to set it up with Postgres instead of MySql, and it threw and error, is there a way to make it work with Postgres?

**Comment by owen2345** [comment]
With postgress the latest changes I have not tested. Please let me fix that today!

**Comment by owen2345** [comment]
Done!, Camaleon CMS supports postgress database.

**Comment by karimmtarek** [comment]
Thanks @owen2345
