### ISSUE TITLE
Images upload on heroku

### ISSUE THREAD

**Issue by hildevestol** [owen2345/camaleon-cms#100]
It would be sweet to have some settings for uploading images to amazone.. the one click install to heroku kinda falls apart without having a solution for images. 

If there is an easy way to do this manually by using carrierwave or something, then a little small note on that in the readme would be good :smile:

**Comment by hildevestol** [comment]
Is perhaps this plugin the solution? http://camaleon.tuzitio.com/store/plugins/11

**Comment by owen2345** [comment]
Please V2: it comes with AWS integration by default

**Comment by hildevestol** [comment]
Nice! :+1: I will check out the new version :smile:
