### ISSUE TITLE
OAuth api 

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#101]
Hi!

Exist any way to login using external application, using an api rest connector, for example?

Regards!

**Comment by cmckni3** [comment]
There's an `auth_token` that each user receives after signing up. You should be able to put that into the `Cookie` header for requests. I would suggest creating a separate user for this. I'm not sure where/if this token is shown in the admin UI.

I have also recommended switching to [Devise](https://github.com/owen2345/camaleon-cms/issues/103) to reduce security risks and allow single sign on, such as, OAuth.

**Comment by raulanatol** [comment]
Thanks @cmckni3 I think just like you about Devise.

I've been testing with https://github.com/doorkeeper-gem/doorkeeper and the current authentication flow and I'm having a lot of problems.

**Comment by cmckni3** [comment]
@raulanatol Interesting. I have heard a lot of positive things about doorkeeper. I have used Devise in every Rails app I have built so far with no problems.

Recently, I worked with [Macaroons](http://hackingdistributed.com/2014/05/16/macaroons-are-better-than-cookies/) to create a single sign on solution. Users sign into an auth server that generates and verifies Macaroons and they receive the Macaroon as a cookie to use at two other applications. I wrote the [PHP](https://github.com/immense/php-macaroons) implementation.

**Comment by owen2345** [comment]
There is a method to do that:
login_user(user, remember_me = false, redirect_url = nil)
# log in the user in to system
# user: User model
# remember_me: true/false (remember session permanently)
# redirect url after session created.

**Comment by cmckni3** [comment]
@owen2345 yeah but he's talking about from another service/application/server.

Technically, how it works right now you could do a `post` to the login URL, get the cookie that was returned, and use that until it is expired. This is what I do in my integration with [jasperserver](https://github.com/cmckni3/rails-jasperserver/blob/master/lib/jasperserver-rails/jasperserver-dsl.rb#L47)

**Comment by owen2345** [comment]
Ok, I am sorry!

**Comment by owen2345** [comment]
I don't know if device include this, do you know if device gem include this?

**Comment by cmckni3** [comment]
Devise had `token_authenticable` but it was removed.

https://github.com/plataformatec/devise/wiki/How-To:-Simple-Token-Authentication-Example

**Comment by cmckni3** [comment]
GitLab has private tokens per user for interacting with the API. They have a UI that allows the user to regenerate it as well.

GitLab is also an oauth provider, so, you can use GitLab as a means of authentication (basically an auth server).

**Comment by owen2345** [comment]
mmm maybe we need a plugin to support that

**Comment by cmckni3** [comment]
Ugh, plugins...I'm not a huge fan of plugins because they complicate things IMO.

**Comment by owen2345** [comment]
Jeje

**Comment by raulanatol** [comment]
Hi guys!

I have been working in doorkeeper integration. https://github.com/raulanatol/camaleon-cms/tree/doorkeeper and I need your help.

Currently I can login using grant_type="password" but I implemented a couple of dummy methods.
**user.valid_password?** is one of them.

Furthermore I have a problem with gem dependencies and I need put the doorkeeper gems again in the rails project.

Attach a little tutorial to add doorkeeper using the gem of this repo: https://github.com/raulanatol/camaleon-cms/tree/doorkeeper

Add to Gemfile:
```
gem 'doorkeeper'
gem 'responders', '~> 2.0'
```

Create an application: http://localhost:3000/oauth/applications

If any problems with CORS install rack-cors:
gem 'rack-cors', :require => 'rack/cors'
- Add config/application.rb
config.middleware.insert_before 0, 'Rack::Cors' do
  allow do
    origins '*'
    resource '*', :headers => :any, :methods => [:get, :post, :options]
  end
end

Thx!

**Comment by raulanatol** [comment]
Hi! 

I finished this integration.

Regards!

**Comment by cmckni3** [comment]
Saw it was merged too f:+1:

**Comment by owen2345** [comment]
Hey @raulanatol,
 I separated the oauth module into Camaleon CMS plugin, please tell me if it works well.
repository: https://github.com/owen2345/camaleon_oauth
Regards!

**Comment by raulanatol** [comment]
Hi @owen2345.
I will testing it in this weekend. 
I can see that this plugin contains the rest api modules also. It's a good idea.
Thx!
Regards

**Comment by raulanatol** [comment]
Hi @owen2345.

When I try to enable the plugin:
![undefined](https://cloud.githubusercontent.com/assets/2389019/11165224/658346da-8b01-11e5-88b0-6b2fb71d2746.png)

I'm using camaleon_cms (moduler branch).

Regards!

**Comment by raulanatol** [comment]
I think that the problem is here: https://github.com/owen2345/camaleon-cms/blob/moduler/lib/plugin_routes.rb#L325 because the plugin key is "camaleon_oauth-0.0.1" and the enabled link generated is http://localhost:3000/admin/plugins/toggle?id=camaleon_oauth-0.0.1&status=false 

When fail the plugin slug is = *camaleon_oauth-0-0-1* and not *camaleon_oauth-0.0.1*
Regards!

**Comment by owen2345** [comment]
@raulanatol I tested using this:
```
gem 'camaleon_oauth', github:  'owen2345/camaleon_oauth'
```
and it works well for me.

**Comment by raulanatol** [comment]
Hi @owen2345.

This way works fine but if I create the gem and I used it this fail.

# Github gem
In https://github.com/owen2345/camaleon-cms/blob/moduler/lib/plugin_routes.rb#L325
p["key"] = "camaleon_oauth-4212be49348d"

In https://github.com/owen2345/camaleon-cms/blob/moduler/app/helpers/camaleon_cms/plugins_helper.rb#L39
current_site.plugins.where(slug: "camaleon_oauth-4212be49348d").first.settings **EXISTS**

# Build gem
In https://github.com/owen2345/camaleon-cms/blob/moduler/lib/plugin_routes.rb#L325
p["key"] = "camaleon_oauth-0.0.1"

In https://github.com/owen2345/camaleon-cms/blob/moduler/app/helpers/camaleon_cms/plugins_helper.rb#L39
current_site.plugins.where(slug: "camaleon_oauth-0.0.1").first.settings **undefined method `settings' for nil:NilClass**

Failed in: 
```
 def plugin_install(plugin_key)
    plugin_model = current_site.plugins.where(slug: plugin_key).first_or_create!
    plugin_model.installed_version= plugin_model.settings["version"]
```

**Comment by owen2345** [comment]
I changed the Camaleon CMS: https://github.com/owen2345/camaleon-cms/blob/moduler/lib/plugin_routes.rb#L325

please let me know if the error persist.

**Comment by raulanatol** [comment]
It works well for me @owen2345.

Thxs!

**Comment by owen2345** [comment]
great!
