### ISSUE TITLE
Incompatibility with newer versions of sprockets-rails

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1013]
When upgrading from sprockets-rails 3.2.2 to 3.4.1 or 3.4.2, font awesome font urls are incorrectly fetched in production. Unfortunately I haven't been able to reproduce in development.

To reproduce, install an affected version of sprockets, start a production server and visit the admin panel. Icons in the sidebar will not render. In the devtools network panel, font awesome urls will show 404. Click on one, and you should see:

- **Expected**
  - my-host/font-awesome-url.woff2
- **Actual**
  - my-host/my-host/font-awesome-url.woff2

@texpert you did some work on non-digest assets, would you be able to take a look at this as well? I have a feeling you might be able to figure this out faster than me 😃 

**Known affected versions of sprockets-rails:**
- 3.4.1
- 3.4.2

**Known unaffected versions of sprockets-rails:**
- 3.2.2 and below

**Comment by texpert** [comment]
@brian-kephart , I am on Ruby 2.7.5 and Rails 6.1.4.1 and have no such problems with sprockets-rails 3.4.2 - are you talking maybe of Rails 7.0-alpha?

sprockets-rails has introduced [the `resolve_assets_in_css_urls=false` option to opt out of adding the digest to CSS filenames](https://github.com/rails/sprockets-rails/pull/489) so we could possibly remove the 'non-digest-assets'. gem. But I am not at all certain if it is a good thing, turning off the assets digesting globally.

**Comment by brian-kephart** [comment]
Thanks @texpert for looking at this. I tried version 3.4.2 again while also expiring my assets and all seems to be well with that small change. 3.4.2 must have been caching the bad urls that were built with the problematic version 3.4.1. I would have chased that around all day if you hadn't responded that it worked in your case.
