### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [owen2345/camaleon-cms#1014]
Hey there!

I belong to an open source security research community, and a member (@khanhchauminh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
Just for reference, the report can be found directly here:
https://huntr.dev/bounties/fb43ee5c-c9bb-4138-b241-ce29035de0d0/

**Comment by brian-kephart** [comment]
Thanks for your report. Can you please send me a version that's not behind a login wall?

**Comment by brian-kephart** [comment]
Thank you for the report. Since this issue doesn't appear to put users or data at risk, and fixing it would be a breaking change, I created #1015 to address this at the next major version bump.

**Comment by JamieSlome** [comment]
@brian-kephart - thanks for the update! If possible, could you update the status of the report using the magic link?
