### ISSUE TITLE
Glyphicons in admin panel

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1016]
Some time ago glyphicons stopped being loaded for me in the admin panel. I have a fix, but I just modified the minified Bootstrap CSS, which seems a bit hacky. I'll merge it if no one has a better solution.

This affects me on multiple apps, as well as the sample app.

@texpert have you experienced this at all?

**Comment by texpert** [comment]
@brian-kephart , not sure where to look for the glyphicons, but I see mce-icons has issues as well - some of them garbled, some missing.

<img width="1430" alt="Screenshot 2022-03-11 at 23 33 28" src="https://user-images.githubusercontent.com/2990033/157973486-3cf3b121-82fe-4125-a41d-0499733ef8b1.png">

**Comment by brian-kephart** [comment]
Are you on the latest release? I had a problem with the TinyMCE fonts, and that fix is in 2.6.2. I did not merge the glyphicon fix yet because I was less sure of the source of the problem.

**Comment by texpert** [comment]
Yes, I'm on 2.6.2

**Comment by texpert** [comment]
<img width="1680" alt="Screenshot 2022-03-11 at 23 43 48" src="https://user-images.githubusercontent.com/2990033/157974661-b2e4b922-c9b1-49ff-93d6-b75d83ae727b.png">

**Comment by brian-kephart** [comment]
That is the issue 2.6.2 was intended to fix. After your reply I found the same problem in one of my apps. I fixed it by expiring my assets and clearing the build cache. Please let me know if that doesn't fix the problem for you. The TinyMCE fix altered the config but not any of the actual asset files, so I think that's why the purge is necessary because the pipeline doesn't recognize that anything changed.

The place I notice glyphicons in the admin panel is in the datepicker elements when the visibility posts plugin is enabled. In this screenshot, the datepicker should show a calendar icon instead of a square on the right side. Compare the screenshots below, one from the current release, and the other with the patch applied.

<img width="362" alt="Screen Shot 2022-03-11 at 4 12 12 PM" src="https://user-images.githubusercontent.com/21235090/157978872-51f3dc41-e3c6-473a-a6f3-403099083d82.png">
<img width="357" alt="Screen Shot 2022-03-11 at 4 13 40 PM" src="https://user-images.githubusercontent.com/21235090/157979255-5b460a48-218c-4f70-8dc1-6916c8b5c86a.png">

**Comment by texpert** [comment]
Yeah, the `Rails.application.config.tinymce.install = :copy` "copies the TinyMCE assets directly into public/assets". 

But in the manifest I've found only `"tinymce/skins/lightgray/fonts/tinymce-small.svg":"tinymce/skins/lightgray/fonts/tinymce-small.svg", "tinymce/skins/lightgray/fonts/tinymce.svg":"tinymce/skins/lightgray/fonts/tinymce.svg"`

**Comment by texpert** [comment]
Ah, will try now to wipe the cache and the assets.

**Comment by texpert** [comment]
Yes, rebuilding the cash has fixed the issue with `tinymce` fonts.

Now seems that `glyphicons` should be moved to either `assets/fonts`, or to `assets/camaleon_cms/fonts`. Will try now.

**Comment by texpert** [comment]
Fixed.

**Comment by owen2345** [comment]
Hey @texpert could you please tell me which ruby, rails version did you have this issue? I tried to reproduce in rails 5, 6 and 7 and there is no issue (for the testing I excluded the PR #https://github.com/owen2345/camaleon-cms/pull/1017)

**Comment by texpert** [comment]
> Hey @texpert could you please tell me which ruby, rails version did you have this issue? I tried to reproduce in rails 5, 6 and 7 and there is no issue (for the testing I excluded the PR ##1017)

@owen2345 , it was Ruby 2.7.5, Rails 7.0.2.3 and Camaleon 2.6.2

**Comment by owen2345** [comment]
Thank you @texpert. I found the issue. I created the PR and waiting for the new release: https://github.com/spohlenz/tinymce-rails/pull/295
Once merged, we can revert the above PR and reduce dependencies
