### ISSUE TITLE
Menu builder customization

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#102]
It would be nice to be able customize menu items inside of the menu builder. For example, I want to add an icon to menu items.

**Comment by owen2345** [comment]
I like the idea!

**Comment by owen2345** [comment]
done!

**Comment by cmckni3** [comment]
It's cool that the custom fields were added but how are they used on the frontend? Is there a partial I can override to render them appropriately?

**Comment by owen2345** [comment]
to show a menu you need to use the function "show_menu(args)"
you need to pass argument: "callback_item:    lambda{|args| }":
```
<%= raw draw_menu({menu_slug: "right_main_menu", container_class: "nav navbar-nav navbar-right", item_current: "active", callback_item: lambda{|args| args[:settings][:after] = "<span class='icon'>#{args[:menu_item].the_field("my_field_slug")}</span>" if args[:has_children];  }}) %>
```

More info:
http://camaleon.tuzitio.com/api-methods.html

**Comment by cmckni3** [comment]
Neat. I'll give it a try

**Comment by cmckni3** [comment]
How do I allow frontend routes from plugins that are post types to be added to a menu?

The post types show up but the available options are empty.

**Comment by owen2345** [comment]
Can you send me a screenshot?

**Comment by cmckni3** [comment]
Getting an error when trying to use nav menu item custom fields

```
undefined method `the_field' for #<NavMenuItem:0x007fb0b298f200>
```

**Comment by cmckni3** [comment]
![2015-09-29_15-59-50](https://cloud.githubusercontent.com/assets/735717/10178045/20ceb7ac-66c3-11e5-80bd-155a51312fa3.png)

**Comment by owen2345** [comment]
fixed:
```
undefined method `the_field' for #<NavMenuItem:0x007fb0b298f200>
```

**Comment by cmckni3** [comment]
Still receiving the error

**Comment by cmckni3** [comment]
Sending pull request

**Comment by cmckni3** [comment]
@owen2345 How do I allow frontend routes from plugins that are post types to be added to a menu?

See previous screenshot

**Comment by cmckni3** [comment]
Looks like [this code](https://github.com/owen2345/camaleon-cms/blob/master/app/views/admin/appearances/nav_menus/index.html.erb#L48) would have to change or I would have to add pages from within the plugin.

Adding pages from within the plugin seems really hacky.
