### ISSUE TITLE
The Camaleon website is gone

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1022]
http://camaleon.tuzitio.com appears to no longer exist. @owen2345 can you please say whether this is permanent? I need to update the README if the site is not coming back.

**Comment by owen2345** [comment]
Hey @brian-kephart 
Already renewed the domain, waiting for the propagation.

**Comment by texpert** [comment]
Yeah, it's working now!

Though, no `https`, `http`-only.
