### ISSUE TITLE
Image auto crop broken

### ISSUE THREAD

**Issue by tataurov** [owen2345/camaleon-cms#1023]
```
NoMethodError (private method `open' called for #<URI::Generic /usr/src/app/public/media/1/1440x480-02.png>):
camaleon_cms (2.6.0.1) app/helpers/camaleon_cms/uploader_helper.rb:237:in `cama_tmp_upload'
camaleon_cms (2.6.0.1) app/controllers/camaleon_cms/admin/media_controller.rb:82:in `actions'
```
i think here https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/uploader_helper.rb#L237 need to change `URI(uploaded_io).open` => `URI.open(uploaded_io)`

**Comment by brian-kephart** [comment]
@tataurov Sorry that I didn't see this before. I was unable to reproduce this. Auto-crop is working for me both with local file uploads and uploads from URLs. If this is still an issue for you, please indicate what version of Ruby you are using, and if possible steps to reproduce the issue.
