### ISSUE TITLE
Switch to Devise

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#103]
I think devise would simplify the authentication code and reduce security risks. It would also allow `omniauth` strategies to be used as well.

**Comment by raulanatol** [comment]
+1

**Comment by owen2345** [comment]
ok, in next versions I will add device to manage sessions.

**Comment by williamrussell-grindr** [comment]
Did you ever think about implementing this?

**Comment by owen2345** [comment]
I am sorry, I have planned to work with this the next month.
Cheers!

**Comment by b264** [comment]
This would be a highly beneficial addition

**Comment by merongivian** [comment]
@owen2345 any news so far for this feature

**Comment by owen2345** [comment]
Hi @merongivian,
please check this: https://github.com/owen2345/camaleon-cms/issues/434#issuecomment-263279521
