### ISSUE TITLE
RuboCop

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1040]
In a previous discussion, @owen2345 and @texpert supported using RuboCop to enforce a Ruby code style. I supported using StandardRB, which is really just RuboCop with a predetermined, non-alterable configuration. I'm fine with using RuboCop as well, but then we need to decide if we're using the default config or customizing it. Any opinions?

**Comment by brian-kephart** [comment]
Results of RuboCop with the default config:
<img width="832" alt="Screenshot 2023-02-07 at 4 47 24 PM" src="https://user-images.githubusercontent.com/21235090/217384354-f2a90638-64bf-4ed8-a4c0-2b7b5c240478.png">

😳

**Comment by owen2345** [comment]
Wow that is a lot :D 
I propose to ignore some non-priority rules like: `Style/Documentation, Lint/MissingSuper`, also `Metrics/BlockLength` from test files

**Comment by brian-kephart** [comment]
One of the files sent RuboCop into an infinite loop. I've never seen that 🤣

**Comment by texpert** [comment]
Yeah, we should customize the config, starting with what @owen2345 has proposed to ignore.
