### ISSUE TITLE
Are emails broken?

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1049]
I can't get test emails to work on any of my sites. Gmail seems to no longer support SMTP with basic password authentication, so that broke my old integrations. I can't get a non-gmail address to work either, though.

Can anyone out there try the test email function and see if it's working for you?

The error reads "535-5.7.8 Username and Password not accepted. Learn more at"
<img width="670" alt="Screenshot 2023-05-10 at 12 47 49 PM" src="https://github.com/owen2345/camaleon-cms/assets/21235090/cbbd4e5c-8b58-40fa-afd7-7074f42ebb7c">

**Comment by brian-kephart** [comment]
In dev mode I can see the email rendered in the terminal and no error is raised, but nothing is sent.

**Comment by texpert** [comment]
Hi, @brian-kephart !

Seems this should be fixed on your Google account side, getting an APP_PASSWORD - https://stackoverflow.com/questions/23137012/535-5-7-8-username-and-password-not-accepted

I've just checked mine - doesn't work as well. I'll have to also fix it on my Google.

**Comment by brian-kephart** [comment]
Using an app password changes the error message to this:
<img width="628" alt="Screenshot 2023-05-10 at 3 31 43 PM" src="https://github.com/owen2345/camaleon-cms/assets/21235090/c6edc930-fe90-41ba-ae7b-d29a4d324d6f">

And yes, despite the error message, I am using the app-specific password. Plus, like I said, non-gmail email isn't working either.

Please reply if you get yours to work @texpert. Hopefully this is just a problem for me, but I worry that a dependency update might have broken something.

**Comment by brian-kephart** [comment]
Ok, it turns out I needed to restart my server. That's weird, and seems like a bug, but it's much less bad than I feared. I'll poke around and see if that can be fixed.

There is another bug. The controller that sends the test email doesn't pass the site to the mailer, so all emails are sent from the main site. That one should be an easy fix.
