### ISSUE TITLE
Add Sitemap information from plugins

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#106]
Is there any way for a plugin add their own content to the RSS feed?

**Comment by cmckni3** [comment]
Would also need plugins to be able to add sitemap information.

**Comment by cmckni3** [comment]
I think we should get rid of dynamic sitemaps. It's really weird and unnecessary to regenerate the sitemap at certain time intervals.

**Comment by owen2345** [comment]
the rss feed customizarion is easy:
create your templates html.erb with rss.builder and create your content.
Sample index.html.erb (default)
```
xml.instruct! :xml, :version => "1.0"
xml.rss :version => "2.0" do
  xml.channel do
    xml.title current_site.the_title
    xml.description current_site.the_excerpt
    xml.link current_site.the_url


    for post in current_site.the_contents.paginate(:page => params[:page], :per_page => current_site.front_per_page).decorate
      xml.item do
        xml.title post.the_title
        xml.description post.the_excerpt
        xml.pubDate post.the_created_at
        xml.upDate post.the_updated_at
        xml.link post.the_url
        xml.guid post.the_id
        xml.thumb post.the_thumb_url
      end
    end
  end
end
```

**Comment by owen2345** [comment]
About sitemaps, when they should generated?
I was using "dynamic_sitemaps" gem to generate every day and ping to google and yahoo with the changes.

**Comment by owen2345** [comment]
Also, there is a hook "sitemap" to add custom sitemaps

**Comment by cmckni3** [comment]
I want a way to add content to the sitemap that comes out of the CMS without having to repeat all of the code that handles the CMS content.

**Comment by cmckni3** [comment]
For search engines, they can just be generated whenever the route `/sitemap.xml` is requested. Typically, generating sitemaps is fast.

**Comment by cmckni3** [comment]
Is there a place for users to view the sitemap? I don't think modern sites do this anymore but it used to be common in older content management systems, such as, PHP Nuke, joomla, etc.

**Comment by owen2345** [comment]
I will remove the cronjob for sitemaps and move all to render inline.
For now, you can see like this url:
http://camaleon.tuzitio.com/sitemap

**Comment by cmckni3** [comment]
So plugins actually don't need to add information to the rss feed. It appears that RSS only contains things that are changed frequently.

In the case of a CMS, posts and categories change. We just need rss to render the appropriate xml and put category tags within each post `item`.

**Comment by cmckni3** [comment]
Is the sitemap generated from the navigation menus?

**Comment by cmckni3** [comment]
@owen2345 Is the sitemap generated from the navigation menus?

**Comment by owen2345** [comment]
no, it takes all group of contents, categories and post's.

**Comment by cmckni3** [comment]
What about pages and post types?

**Comment by owen2345** [comment]
you can customize your sitemap template with hook "on_render_sitemap".
Arguments: {layout: (params[:format] == "html" ? (self.send :_layout) : false), render: "sitemap"}

```
def my_on_render_sitemap(args)
 args[:render] = "path_to_my_template"
end
```

**Comment by cmckni3** [comment]
Doesn't that completely overwrite the sitemap though?

**Comment by cmckni3** [comment]
I would want to append to the `urlset` of the existing xml generated by default

**Comment by owen2345** [comment]
mmm for that would be to add a hook in the template, what do you think?

**Comment by cmckni3** [comment]
Yeah, that's the only way to accomplish it that I can think of

**Comment by owen2345** [comment]
sample:
Ready: you need to use this hook "on_render_sitemap", where this receives: {layout, render, custom = (String), format =(String) html | xml}
```
def my_on_render_sitemap(args)
if args[:format] != "html"
  args[:custom] << " 
    xml.url do
        xml.loc 'http://myhost.com'
        xml.lastmod '2015-09-19 03:06:44'
        xml.changefreq 'monthly'
        xml.priority '0.5'
   end"
end
```

**Comment by cmckni3** [comment]
@owen2345 That's pretty hacky putting Ruby into a string and then calling `instance_eval` on it.

I think it would be better to return a datastructure (a Hash in this case) and have the renderer (view) handle the formatting whether it's html or xml. This would also eliminate the need for the `if`.

**Comment by owen2345** [comment]
I am agree with you Chris.
I changed in to Hash and you should add a Hash like this (in your hook):
```
args[:custom][:my_url] = {
url: "my url",
title: "the title",
lastmod: "date",
changefreq: "monthly",
priority: "0.2"
}
```
Also check new params to filter objects #157

**Comment by cmckni3** [comment]
@owen2345  Sweet! :+1:

N.B. priority in sitemaps is optional and defaults to 0.5.
