### ISSUE TITLE
http://camaleon.tuzitio.com seems to be down

### ISSUE THREAD

**Issue by yohio** [owen2345/camaleon-cms#1067]
A certificate has expired, and the website is not live.
Documentation and other vital platform aspects, like downloading plugins and extensions, are inaccessible.

**Comment by texpert** [comment]
We're aware that http://camaleon.tuzitio.com is down, thank you, @yohio!

Further notifications will come when this will be solved.

**Comment by GenericOctopus** [comment]
Any update available on the site's status?

**Comment by texpert** [comment]
Finally, the site is up on new location - https://camaleon.website/

Everybody welcome back, but some links may still be pointing to the old URL, we'll fix them soon.

**Comment by yohio** [comment]
Woot woot!! I'm closing the issue then
