### ISSUE TITLE
All Websites Down? 

### ISSUE THREAD

**Issue by JessMTermini** [owen2345/camaleon-cms#1068]
Hello, I was just stopping by with a possible interest in this project but I am noticing every website under the current project domain  is currently offline/down (which is everything unfortunately, all documentation and working demos etc.), but I do notice people have committed pretty recently as of 2 months ago, so I think my main question here is, is this project still being maintained? And is there any hope of getting all the things back online any time soon? Just curious, as it does make things go a bit faster when you can read a bit and maybe demo a demo. 

Ok well, just a friendly hello. Hope all is well and everything is back to normal soon. Well if that's what the plan is anyways...

Thank you!!!

**Comment by texpert** [comment]
Hello, @JessMTermini!

Thanks for interest in this project!

The product is maintained. Currently, we have moved the site to https://camaleon.website/ - we'll announce and change all the links in the repo when everything will be settled down.

**Comment by epipheus** [comment]
took me a while to find the site on my own. please change this

**Comment by texpert** [comment]
Closing, as the info about the new, https://camaleon.website/ site has been updated everywhere across the repo.
