### ISSUE TITLE
Alternative File Manager?

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#107]
I'm not a big fan of elfinder. Can we use an alternative?

I like angular-filemanager but I'm not sure how you feel about angular.

Suggestions:
- https://github.com/joni2back/angular-filemanager
- https://github.com/trippo/ResponsiveFilemanager

**Comment by cmckni3** [comment]
https://github.com/trippo/ResponsiveFilemanager

**Comment by owen2345** [comment]
It looks good, maybe in next versions I can add, before I need to review cloud support like this:
http://camaleon.tuzitio.com/store/plugins/11

**Comment by cmckni3** [comment]
Well, these are just the UI portion. On the server side, uploads would be handled by carrierwave or some other gem that handles uploads.

**Comment by owen2345** [comment]
yes, I am agree with you!

**Comment by raulanatol** [comment]
Good!
I have a lot of problems to permit save files from elfinder to S3.
Maybe using carrierwave, fog...

**Comment by cmckni3** [comment]
Yeah fog makes it easy to store the files on S3, Rackspace or Google.

**Comment by owen2345** [comment]
Yes, I used it in several projects.

**Comment by raulanatol** [comment]
Any news?
Is there anything I can help you?
Regards.

**Comment by owen2345** [comment]
Not yet, I was working in the support for jruby but without success for now.

**Comment by raulanatol** [comment]
Ok no problem.

I could create a branch and work on it.
Do you have any preference in the file manager?
- https://github.com/joni2back/angular-filemanager
- https://github.com/trippo/ResponsiveFilemanager
- Other?

**Comment by owen2345** [comment]
I was reviewing the angular version, because it appears simple and clean.
Additionally I was analyzing which cloud gems to integrate: carrierwave with any cloud uploader or directly to use fog gem: (local, AWS, ...).
Please let me know if you need any help or you have any question.
Thank you Raul!

**Comment by raulanatol** [comment]
You're welcome. 

I will try to do it. ;)
The angular version have a problem: https://github.com/joni2back/angular-filemanager/issues/56 but I will try to test it.

Regards.

**Comment by raulanatol** [comment]
Hi guys!

Do you know another file manager?
I had problems with both :(

- https://github.com/joni2back/angular-filemanager: require include angularjs in the application (a lot of changes only for an file manager)
- https://github.com/trippo/ResponsiveFilemanager: strongly related with a lot of php scripts

I'm thinking to adapt the https://github.com/raulanatol/el_finder_s3 plugin for to use Fog and try to change the UI of elFinder.

Another idea? Thanks 
Regards!

**Comment by cmckni3** [comment]
I like angular-filemanager the best. Someone should be able to make a tinymce plugin for it.

I wasn't too impressed by responsive-file-manager. It seems like a less polished version of [jquery-file-upload](https://github.com/blueimp/jQuery-File-Upload).

I only considered responsive-file-manager because it already had support for ckeditor and tinymce.

**Comment by cmckni3** [comment]
We could just keep elfinder for the UI. I'm not too fond of it but it has a decent UI.

Definitely need to clean up the backend and use something like carrierwave though.

**Comment by owen2345** [comment]
The tinymce script is easy, first we need to integrate the file manager in "Media" section.

**Comment by raulanatol** [comment]
I can integrate angular into the backend but It can be cumbersome.

**Comment by raulanatol** [comment]
Hi guys!

I have created a new branch (https://github.com/raulanatol/camaleon-cms/tree/file_manager) with the first step of this changes (file manager in "Media" section).

Now I will to change the "handler" for to use Fog (with local filesystem, aws s3...)

Regards

**Comment by owen2345** [comment]
great!

**Comment by raulanatol** [comment]
Hi!
I have upload new changes.
- Fog integration
- General site settings

To do: 
 - Look and feel errors
 - File manager permissions
 - File manager compress action
 - Tinymce integration

Could you give me feedback?
Exist more todos?

Thx!

![filesystem](https://cloud.githubusercontent.com/assets/2389019/10522116/5cba96aa-736b-11e5-973a-fdd780285a46.png)

**Comment by owen2345** [comment]
It appears great!

Not priority:
It would be good if you can add search field and filter certain file formats by extension or mimetypes.

**Comment by raulanatol** [comment]
Ok @owen2345 it's a good idea.

I will work in:
- Look and feel errors
- File manager permissions
- File manager compress action
- search field
- formats filters

Could you work in the Tinymce integration? I was at something of a loss as to how to do it :(

Regards.

**Comment by joni2back** [comment]
Hello, Im the author of angular-filemanager.
If you have any doubt to implement it, feel free to let me know. Regards.

**Comment by owen2345** [comment]
I am working in the module version, which move all files (controllers, models, views, ...) in to camaleon_cms module and also you can indicate the prefix for the database table names, which permit to integrate an existent rails project into camaleon_cms without problems to overwrite models/controlls/... or database tables.
@raulanatol, Please commit your new file manager in the "moduler" branch to add your changes in this version.

**Comment by raulanatol** [comment]
Ok I'm working to adapt the differing views, only selection (with filters: video, audio...) and the default view of angular-filemanager.

Regards!

**Comment by raulanatol** [comment]
Hi!

I have created a PR to angular-filemanager (https://github.com/joni2back/angular-filemanager/issues/76). I hope to be merged soon.

I have created a PR (https://github.com/owen2345/camaleon-cms/pull/187) into the moduler branch with all the changes (AWS S3 compatibility included).

Regards!

**Comment by joni2back** [comment]
Hi, regarding PR ***"Custom Changes"***, besides the code, can you give a brief description the changes?

**Comment by raulanatol** [comment]
Hi @joni2back!

In this PR we have added:
 - Filter by mime types (to permit show only images, only videos...) In camaleon-cms is used for to show only images in the explorer to select one.
 - Layout feature (default & selection). In camaleon-cms is used **default layout** to show all files in the server (media section on administration view) and in camaleon-cms is used **selection layout** like a modal after that click in select file dialog (for example in the edit page panel: http://camaleon.tuzitio.com/media/132/multi-language.png)
- Added event dispatcher on smartClick event. With this feature in camaleon-cms we can know when an user select an item from the angular-filemanager.
- We added customization attributes (navbar and tablecolumn) to permit hide or show actions of angular-filemanager in any case. For example to select an user avatar is not necessary show the create folder action in the navbar.
- We added attribute type in remove handler method (We added documentation in API.md file)
- We created two more attributes (autoEditFile and autoImagePreview) to enable o disable "edit file" and "show image preview" respectively.

Regards.

**Comment by joni2back** [comment]
Great, I like very much the idea of use in a kind of "iframe" to select a file/folder for another application.

I'm in vacations right now, but in a few days I'll be merging this PR!!

**Comment by owen2345** [comment]
@raulanatol I pushed all my changes for 2.0, please let me know if I can help you with anything, and dont forget to remove all files of elfinder.
Regards,

**Comment by raulanatol** [comment]
Hi @owen2345 

I'm so sorry for the long delay for the response (need more hours in the day ;) ).
I will do it as soon as possible.

Regards.

**Comment by raulanatol** [comment]
Hi @owen2345 

I have created a new PR: https://github.com/owen2345/camaleon-cms/pull/195

Regards.
