### ISSUE TITLE
Image uploading failure

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#1097]
After upgrading to 2.8.2, my image uploads are failing when uploading to a folder with the AWS uploader. Uploads to the root media folder still work.

I know that a recent PR addressed file uploads to arbitrary paths, so I wonder if this is related.

<img width="381" alt="Screenshot 2024-09-12 at 3 36 24 PM" src="https://github.com/user-attachments/assets/804d1b9f-ae93-4756-a274-017fd19bd747">

**Comment by texpert** [comment]
Hope I'll have some time to have a look this weekend.
