### ISSUE TITLE
Implement new admin template

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#111]
We want to switch to using https://github.com/almasaeed2010/AdminLTE for the admin interface.

See https://github.com/owen2345/camaleon-cms/issues/65 for details

**Comment by owen2345** [comment]
I am working in that..

**Comment by cmckni3** [comment]
Have you made any progress on it? Sorry for being impatient.

**Comment by owen2345** [comment]
50%, I think to have finished this weekend.

**Comment by owen2345** [comment]
I will publish the next version with this change and also adding I18njs to manage clear the javascript translations.

**Comment by owen2345** [comment]
Also, I was working in the functionality to support plugins in gem version.

**Comment by cmckni3** [comment]
Support plugins?

**Comment by owen2345** [comment]
yes, you can create plugins like gems, sample:
gem "camaleon-plugin-ecommerce"

Note: this is in progress.

**Comment by raulanatol** [comment]
@owen2345 this sounds good!
If I can help with anything...

**Comment by owen2345** [comment]
done!
