### ISSUE TITLE
Post types

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#114]
Is there a helper for a post type to show the WYSIWYG editor? Is this supported?

**Comment by owen2345** [comment]
where would you like to show the editor?

**Comment by cmckni3** [comment]
On an admin form for a post type from a plugin. I think we discussed this before about custom post types having a `content` or `description` WYSIWYG field.

**Comment by cmckni3** [comment]
Closing as duplicate. See #129
