### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#117]
I think theming can be improved. I find friction when building themes which contain various layouts, such as, 1 column, 2 column, and 3 column layouts.

The idea is that 1 column layouts should just show the content of a page/post surrounded by the navigation (and anything else that belongs outside of body), body, and a wrapper.

With a 2 column layout, I essentially expand upon the 1 column layout but introduce a sidebar by using a block.

I find it cumbersome to switch between the layouts by using hooks. I want to be able to use `theme_layout` inside of a template but I'm not quite sure how I feel about place it there.

Also, I wish the CMS allowed you to change the layout of posts and pages. The ability to specify a default layout for posts and pages and then allow that to be overridden would alleviate some of my issues.

**Comment by CBlaize** [comment]
I agree with Chris.  I'm currently using the hook on_render_post to swap between layouts. It works but it seems more of a workaround then a solution.

**Comment by owen2345** [comment]
mmmm I would add layout selector like templates. What do you think about that?

**Comment by cmckni3** [comment]
@owen2345 Sounds good.

**Comment by owen2345** [comment]
done!
