### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#119]
Where exactly are hooks defined?

**Comment by owen2345** [comment]
hooks are defined everywhere, depend of the necessity.

**Comment by cmckni3** [comment]
Hmm, I would think they would come from one place.

**Comment by cmckni3** [comment]
@owen2345 Do you have an answer for this?

**Comment by owen2345** [comment]
It is not possible to put all hooks in a single place.
