### ISSUE TITLE
Admin login page puts asterisks in password field

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#120]
When logging into the admin page, a bunch of asterisks are put into the password field when pressing submit. This is very strange.

**Comment by owen2345** [comment]
It is parsing your password into AES security

**Comment by cmckni3** [comment]
Why are you computing that in the frontend? Sounds like a security risk...

**Comment by owen2345** [comment]
To avoid copy your password by proxies or similar situations.
This is good when you are not using ssl.

**Comment by cmckni3** [comment]
I still think this is unnecessary. It's just security through obscurity.
