### ISSUE TITLE
uninitialized constant CamaleonCms::VERSION

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#121]
```ruby
NameError in Admin#dashboard

uninitialized constant CamaleonCms::VERSION
```

**Comment by jun1st** [comment]
yeah, I got this bug too

**Comment by owen2345** [comment]
Checking...

**Comment by owen2345** [comment]
I pushed a fix, please let me know if that was solved.

**Comment by cmckni3** [comment]
I see. It's commented out for now. Works for me now.

**Comment by owen2345** [comment]
great!
These days I will update the documentation.

**Comment by cmckni3** [comment]
#122

**Comment by cmckni3** [comment]
Yeah, I was going to update the documentation but I'm trying to get a project finished up.
