### ISSUE TITLE
Theme field on contact form

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#123]
What is the theme field used for on the contact form?

**Comment by owen2345** [comment]
Hello Chris,
I don't understand your question, 
Note: contact form is a plugin that generates a shortcode to paste anywhere.
Regards,

**Comment by cmckni3** [comment]
There's a select box that says "Themes" but the select box is empty.

![2015-09-28_14-55-23](https://cloud.githubusercontent.com/assets/735717/10146955/02f4d298-65f1-11e5-960a-e95181eaa4d6.png)

**Comment by cmckni3** [comment]
ohh, there's a javascript error too.

```
Uncaught ReferenceError: lang is not defined
lang.message_no_response_fields
```

**Comment by owen2345** [comment]
fixed on github

**Comment by owen2345** [comment]
the template you need to create in:
your theme/views/html_mailer/my_template.html.erb

**Comment by cmckni3** [comment]
Is that for the frontend view or the email that goes out?

**Comment by cmckni3** [comment]
Might not need #125 if it's the formatting of the email that is sent.

**Comment by owen2345** [comment]
great!

**Comment by cmckni3** [comment]
or by theme on the form, do you mean layout?

**Comment by owen2345** [comment]
you can customize all your emails like this:
layout: create a file called layouts/mailer.html.erb
template: create a file called views/html_mailer/mailer.html.erb

check samples:
[template.txt](https://github.com/owen2345/camaleon-cms/files/3982/template.txt)
[layout.txt](https://github.com/owen2345/camaleon-cms/files/3983/layout.txt)

**Comment by owen2345** [comment]
the other option is not working well and will be removed.
This part of code was built for my collaborator the code is a little ugly, I will rebuilt in future versions.

**Comment by cmckni3** [comment]
Ah ok, I just wrapped a template with `render_to_string`

Would be nice if it used action_mailer.

**Comment by cmckni3** [comment]
Hmm, what you are describing is a bit too generic though but my solution is a bit generic as well. I think contact form 7 has the same issue though.

**Comment by owen2345** [comment]
Would you like a template selector in the contact form?

**Comment by cmckni3** [comment]
I was thinking about that. That might be the only way to make it really flexible.
