### ISSUE TITLE
New plugins format

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#126]
Hi!

Is there a tutorial for creating new plugins?
I try to create using:

```
rails g cplugin <your_plugin_name> 
```

But it's the old way.

Regards.

**Comment by owen2345** [comment]
I am working in the documentation.
the new way is:
rails g camaleon_cms:gem_plugin post_reorder

**Comment by raulanatol** [comment]
This is enough.

Thx!

**Comment by raulanatol** [comment]
Hi @owen2345!

I'm trying to change an model using models/plugins/... but this file isn't executed. Exists any rule for names? I used the same rule that you in the file https://github.com/owen2345/camaleon-post-order-plugin/blob/master/app/models/plugins/post_reorder/post_reorder.rb

Any ideas?

**Comment by owen2345** [comment]
I am sorry Raul, you need to put in:
custom_models.rb

Check this:
http://camaleon.tuzitio.com/plugins.html

**Comment by raulanatol** [comment]
It's equals that the old plugins structure?

In the new structure (gems) after execute rails g camaleon_cms:gem_plugin plugin_name a file named plugin_name.rb is created with this comment:

```
# here your default models customization
# Site.class_eval do
#   has_many :user_tag, class_name: "Plugins::UserTag::Models::UserTag"
# end
```

It's confused

Thx!
Regards!

**Comment by owen2345** [comment]
I am sorry, I forget to remove that.
That way sometimes work well, but the other way "custom_models.rb" works well.

**Comment by raulanatol** [comment]
'custom_models.rb' works fine!

Thx!

**Comment by raulanatol** [comment]
Sorry again @owen2345!

custom_models.rb works fine but models don't work.
I need to create a new models:
 - I created the file plugins/user_tag/app/models/plugins/user_tag/user_tag.rb
```
class Plugins::UserTag::Models::UserTag < ActiveRecord::Base
  attr_accessible :name, :description
end

```
But this file is never executed.

**Comment by owen2345** [comment]
Raul, 
I am sorry, please remove "::Models"
```
class Plugins::UserTag::Models::UserTag 
```  into 
```
class Plugins::UserTag::UserTag
```
This mode of plugins need some testings yet

**Comment by raulanatol** [comment]
@owen2345 no problem! ;)

thx!
