### ISSUE TITLE
Hooks for post types from plugins?

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#127]
Is there any way to use hooks within plugins so themes can override the layout?

**Comment by owen2345** [comment]
yes, it is the same that themes.
define your hooks in config.json

**Comment by cmckni3** [comment]
What do you mean?

I really just want my plugin to use the `on_render_post_type` hook. Do I just setup some calls in my plugin's frontend controller?

**Comment by owen2345** [comment]
add "on_render_post_type" in your config.json, sample:
1:
```
hooks:{
"on_render_post_type": ["my_hook_function_name"]
}
```
2: create method in your helper
```
def my_hook_function_name(args)
  puts "----#{args.inspect}"
end
```
3: Visit any post_type on frontend to see your message

**Comment by owen2345** [comment]
Don't forget to restart your server after change any config.json file

**Comment by cmckni3** [comment]
I figured out what I needed to do. Needed to call `hooks_run` from my controller.

**Comment by owen2345** [comment]
Put this code anywhere of your code (controller, view)
```
hook_params = {greeting: "Hello World"}
hooks_run("name_of_your_hook", hook_params)
puts hook_params[:name]
```
This hook can be listened by plugins or themes or system adding the hook_key in config.json
```
hooks: {
name_of_your_hook: ["my_hook_helper"]
}
```
In my helper.rb
```
def my_hook_helper(args)
  args[:greeting] = "Hello Owen"
end
```
------
That hook will print:
"Hello Owen" if your plugin or theme is active else will print "Hello World"

**Comment by cmckni3** [comment]
Thanks but I figured that out earlier
