### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#129]
Do custom post types receive a "content" field automatically?

**Comment by owen2345** [comment]
for post_types the content is the description added on post_type form.

**Comment by cmckni3** [comment]
Do I have to do `<%= f.textarea :description %>` in the admin?

**Comment by owen2345** [comment]
The description can be edited in admin->settings->post type.
Screenshot:
![2015-09-29_1612](https://cloud.githubusercontent.com/assets/1148415/10176646/0633c256-66c4-11e5-90d4-0993d3b4ad52.png)

**Comment by cmckni3** [comment]
I'm not talking about that. I'm talking about when creating a new instance of a certain post type

**Comment by owen2345** [comment]
mmm I am sorry, in which section you are trying to do that?

**Comment by cmckni3** [comment]
I'm just wondering if a custom post type created from a plugin gets a field for content like it does in Wordpress.

I am ok with adding my own field and using tinymce.
