### ISSUE TITLE
Deploy on Heroku fails: "No such file"

### ISSUE THREAD

**Issue by Tvinky** [owen2345/camaleon-cms#132]
Hi,

I have some problems deploying Camaleon CMS on Heroku using this button in readme. It is failing on Heroku step: `Run scripts & scale dynos`.

From error details it looks like script can't find Gemfile or something like that: `Errno::ENOENT: No such file or directory - /app/vendor/bundle/ruby/2.0.0/gems/camaleon_cms-1.0.4/lib/Gemfile`

Here is [full error log](https://gist.github.com/Tvinky/ed6dc6bb615dc67d6f76)

**Comment by owen2345** [comment]
Please check 
"Migrating from 0.2.x or earlier?" on https://github.com/owen2345/camaleon-cms
you need to upgrade.

**Comment by Tvinky** [comment]
Haven't checked this part of documentation because I was just deploying it on Heroku with provided button - no updating/migration. Probably after newest these changes this Heroku `script` part is not updated or something like that. I will try to investigate this also, when I will have some free time.

**Comment by owen2345** [comment]
great! anyway today I will review also.

**Comment by cmckni3** [comment]
The sample project wasn't updated from 0.2.1. Pull Request incoming

**Comment by cmckni3** [comment]
Should be fixed from this [PR](owen2345/camaleon-CMS-Sample#4)

**Comment by Tvinky** [comment]
Yes, now I was able to deploy on Heroku. Thanks!

**Comment by cmckni3** [comment]
No problem.

It should also be faster on heroku because I switched it to puma instead of webrick.
