### ISSUE TITLE
Admin section breaks if changing slug of main site

### ISSUE THREAD

**Issue by mdkirby** [owen2345/camaleon-cms#134]
On version 1.0.3

If you change the slug for the main site, all pages on the admin section stop working due to ```h.current_site``` becoming ```nil```

I attempted changing the slug back in the rails console, and directly in the "term_taxonomy" table, but it did not fix the problem - not sure if that is due to caching, or if the slug is also stored somewhere else.

To reproduce, change the slug here:
http://localhost:3000/admin/settings/sites/1/edit

Then the following call will fail (and this is in the header, so all pages in admin section won't load)
```
def the_role
    object.get_role(h.current_site).name.titleize
end
```

Top of stack trace below:
```
NoMethodError - undefined method `name' for nil:NilClass:
  camaleon_cms (1.0.3) app/decorators/user_decorator.rb:25:in `the_role'
  camaleon_cms (1.0.3) app/views/layouts/admin/_header.html.erb:29:in `___sers_msiemers__rvm_gems_ruby_______camaleon_cms_gems_camaleon_cms_______app_views_layouts_admin__header_html_erb__2059493650570200624_70293944407300'
  actionview (4.2.4) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.4) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:143:in `render'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.4) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.4) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.4) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  camaleon_cms (1.0.3) app/views/layouts/admin.html.erb:39:in `___sers_msiemers__rvm_gems_ruby_______camaleon_cms_gems_camaleon_cms_______app_views_layouts_admin_html_erb___4375474354717447789_70293973369220'
```

**Comment by owen2345** [comment]
Checking...

**Comment by cmckni3** [comment]
The code in the Site model looks incomplete. Should really get rid of `PluginsRoutes#set_system_info`.

N.B. Writing to files isn't supported on Heroku.

**Comment by owen2345** [comment]
Ohhh!! that is right.

**Comment by owen2345** [comment]
In next versions I could move those configurations into database.

**Comment by cmckni3** [comment]
I like the idea of storing them in the database with the exception of `base_domain`. 

That's a big pain point in Wordpress. It stores all URLs in the database and contains tons of branching logic to looking in 2-3 places for a piece of configuration.

**Comment by mdkirby** [comment]
Any update on this? I have a staging deployment with a lot of data and we need to change one of the site slugs/urls - but I don't want to bring down the admin section, or start over with a new db.

I have taken a look at the code referenced by cmcknl3, and looked at that method [here](https://github.com/owen2345/camaleon-cms/blob/762411010404c9f0dec3de94cdcebacd6f70f9b7/lib/plugin_routes.rb#L98), but I don't have a full understanding of what needs to change to allow a url change to the base domain (and others)

**Comment by owen2345** [comment]
Do this:
- in your config/system.json change the base_domain for your new domain and restart server.
Please let me know if it works for you.

**Comment by mdkirby** [comment]
Thanks Owen - I'm trying this out locally first (with different port numbers for the 'sites'). I haven't had any luck yet.

It may be that I'm trying to use an ENV variable for the config, but it worked when I restarted the server with the BASE_DOMAIN set to 'localhost:3000'

https://github.com/mdkirby/camaleon-cms/pull/1/files

**Comment by mdkirby** [comment]
So, I haven't gotten it to work locally. I switched my local app back to a non-erb system.json - I tried switching the main site to localhost:3001 and even back to localhost:3000 and neither one will work.

I am coordinating the slug/url in 3 places - 
The entry in the db by updating it in the rails console `Site.find(1).update(slug: 'localhost:3000')`
The config/system.json: `"base_domain": "localhost:3000"`
The running local server `rails s -p 3000`

Anywhere else you could think of? The error is happening in the same place as before (see stacktrace in original post).

Strangely, in better errors, this happens:
```
>> h.current_site
!! #<NoMethodError: undefined method `original_url' for nil:NilClass>
``` 
But `h` is defined as a `Draper::HelperProxy`

For reference, here is my system.json:
```
{
  "base_domain": "localhost:3000", // primary domain
  "share_sessions": true, // (boolean) share user sessions between subdomains of base_domain (only for users_share_sites = true)
  "default_user_role": "client", // default user role for all new users
  "users_share_sites": true //(boolean) true: permit to share users between sites, false: All users are assigned for a unique site.
}

// Note: after any change in this file, you need to restart your server to apply changes.
```

**Comment by mdkirby** [comment]
I don't know if this is causing this particular issue, but in [this code](https://github.com/owen2345/camaleon-cms/blob/762411010404c9f0dec3de94cdcebacd6f70f9b7/app/helpers/site_helper.rb#L21) the call `site = Site.first.decorate rescue nil` looks like it is assuming `Site.first` is equivalent to 'Site.find(1)` or even `Site.order(:created_at).first but it is not, in fact, I am getting my Site with the `id: 21` when I call `Site.first` in the console, the SQL executed is:
```SELECT  "term_taxonomy".* FROM "term_taxonomy" WHERE "term_taxonomy"."taxonomy" = $1 ORDER BY "term_taxonomy"."term_group" DESC LIMIT 1```

**Comment by owen2345** [comment]
please add me on skype to resolve the problem:
owen-2345

**Comment by mdkirby** [comment]
I can take a shot at coding and refactoring the `current_site` method.
https://github.com/owen2345/camaleon-cms/blob/762411010404c9f0dec3de94cdcebacd6f70f9b7/app/helpers/site_helper.rb#L11

It looks like this is creating a case where current_site can return nil - it seems like we never want that to happen. Do you have tests for this method, or a spec that I could try to meet?

Also, I added you on Skype, just message me on there with a good time to chat.

Thanks!

**Comment by mdkirby** [comment]
I've got a PR for this https://github.com/owen2345/camaleon-cms/pull/201

It has worked when I test it locally without problems. The only thing is, the setting is system.json doesn't seem to matter. As long as I have a server running on the port that I specify in the main site's slug, then everything appears to be working.
