### ISSUE TITLE
Theme assets not found after precompiling

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#137]
The frontend of the site isn't using the correct path to the theme assets. It should use the path `/public/assets/themes/[theme-name]/assets/css` but it only get `/public/assets/css`

I set `serve_static_files` to `true` and `assets.compile` to `false`. For now, I enabled compilation and disabled serving static files but this needs to be investigated.

**Comment by owen2345** [comment]
Chris, where is this error?

**Comment by cmckni3** [comment]
I setup a site for use in production. I'll put an example on heroku.

**Comment by cmckni3** [comment]
I'm deploying a sample app to heroku right now.

**Comment by cmckni3** [comment]
Application source code: https://github.com/cmckni3/camaleon-assets-bug
Heroku: https://evening-island-6589.herokuapp.com/

**Comment by flaranda** [comment]
Similar problem here.

**Comment by owen2345** [comment]
Today I will review...

**Comment by cmckni3** [comment]
I believe I figured out part of my problem. I'm going to confirm the fix in another app. PR coming soon as well.

**Comment by cmckni3** [comment]
:+1: Looks good on my end. Just had to change the stylesheet link in my theme to `css/main.css`.

**Comment by owen2345** [comment]
great!

**Comment by cmckni3** [comment]
Precompilation just finished on my other app and everything is working great with serving assets through nginx. So glad to resolve this issue. :+1:

@flaranda Check your theme to make sure you have the extension when referencing the main stylesheet `stylesheet_link_tag theme_asset_path("css/main.css")`

**Comment by flaranda** [comment]
Great! Thanks @cmckni3 :)

**Comment by cmckni3** [comment]
No problem @flaranda
