### ISSUE TITLE
Commands in bin point to ruby.exe

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#14]
I have to run `rake update:bin` to run the application on OS X. I think they shebang line should be changed back to `#!/usr/bin/env ruby` and Windows users should compensate in their Ruby installation.

**Comment by cmckni3** [comment]
Alternatively, we can ignore the `bin` folder.

**Comment by owen2345** [comment]
yes, it sounds good.
With gem version that problem will not exist more:
https://github.com/owen2345/camaleon-cms-gem
I am still testing...

**Comment by cmckni3** [comment]
Awesome.

Is this repo going to be a demo of using the gem?

Are changes going to be backported to the gem?

**Comment by owen2345** [comment]
1: yes!
2: yes!

**Comment by cmckni3** [comment]
:+1:
