### ISSUE TITLE
Move system.json configuration into environment variables

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#141]

**Comment by owen2345** [comment]
do you want to put those settings in 
config/environments/production.rb
config/environments/development.rb
?

**Comment by cmckni3** [comment]
No, `ENV` so they are easily changed.

**Comment by cmckni3** [comment]
In development, they are typically read from `.env` using `foreman` or `heroku local`

**Comment by cmckni3** [comment]
I started work on it [here](https://github.com/cmckni3/camaleon-cms/commit/781261b310b8311768de5acccd37069ba62a459b)

I think we can move everything but `base_domain` to the database.

**Comment by cmckni3** [comment]
`base_domain` might need to be renamed as well. It's ambiguous.

**Comment by owen2345** [comment]
yeah, maybe into primary_domain.

**Comment by cmckni3** [comment]
Exactly!
