### ISSUE TITLE
Contact Form Plugin - custom layout

### ISSUE THREAD

**Issue by colinblaise** [owen2345/camaleon-cms#142]
The contact form plugin doesn't really allow for custom styles.  Would it be possible to assign a layout/template to a contact form? Similar to that of pages and posts.

For example I want to use bootstrap grids to layout my form.

.col-md-6
      .form-group
        label First Name
        ...
.col-md-6
      .form-group
        label Last Name
        ...

**Comment by owen2345** [comment]
For now, it does not support html customization editor, for next version I will add that option.
Check here to see how to customize your form from your theme:
http://camaleon.tuzitio.com/store/plugins/4
