### ISSUE TITLE
Custom fields readonly

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#144]
HI!

It's possible do a custom field readonly?

I'm working in a mailchimp plugin and I need to disable editing of specific custom fields.

Regards.

![mailchimp_edit_user](https://cloud.githubusercontent.com/assets/2389019/10302143/76d7a314-6c01-11e5-9e0c-442a376bdbf2.png)

**Comment by owen2345** [comment]
Done!
you can pass attributes disabled: true or readonly: true similar to required: true

**Comment by raulanatol** [comment]
Good!  
Thanks
