### ISSUE TITLE
RSS incorrect controller action

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#145]
It seems like the rss route is hooked up to the wrong controller action. It is currently returning the homepage's html as if it is rss/xml.

**Comment by owen2345** [comment]
please check here:
http://camaleon.tuzitio.com/rss.rss
It is returning all public post contents.
you can customize this by creating views/index.rss.builder in your theme.
Also you can create rss for your categories like:
http://camaleon.tuzitio.com/category/137-uncategorized.html into http://camaleon.tuzitio.com/category/137-uncategorized.rss
=> views/category.rss.builder and receive all variables of html version

**Comment by cmckni3** [comment]
It's not doing that in the current version.

It returns html for me

**Comment by owen2345** [comment]
something is wrong, I tried in a new project and it works fine.

**Comment by cmckni3** [comment]
Hmm, it works on 1.0.4 on my heroku app. I'm trying 1.0.5 on it right now.

**Comment by cmckni3** [comment]
On my site, it seems like it might be because I have custom templates and `render` needs to be call with `layout: false`

**Comment by cmckni3** [comment]
The RSS feed just outputs the homepage but the sitemap outputs the sitemap and is wrapped with my default layout.

**Comment by cmckni3** [comment]
See #149

**Comment by cmckni3** [comment]
I really think the [RSS route](https://github.com/owen2345/camaleon-cms/blob/master/config/routes/frontend.rb#L26) needs to go to a different action

**Comment by owen2345** [comment]
Done!
