### ISSUE TITLE
Override custom post types in sitemaps

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#157]
I have post types coming from a plugin that are automatically added to the sitemap but I have a custom URL for them on the frontend.

How do I remove the ones that were automatically generated?

**Comment by owen2345** [comment]
mmm good question, maybe I need to send in the hook.

**Comment by owen2345** [comment]
I added filters in array format for the hook "on_render_sitemap":
```
skip_post_ids: [], skip_posttype_ids: [], skip_cat_ids: [], skip_tag_ids: []
```
In these arrays you can add the id's of your objects to skip.
