### ISSUE TITLE
Custom permalink structure

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#158]
Need to be able to nest posts/pages/posts within a category under certain paths. See diagram below.

- About Us
  - Contact Information
  - Driving Directions

**Comment by owen2345** [comment]
Way 1: You need to create custom routes in your routes file and use that in your views.
Way 2: You can overwrite the method of the post_decorator.rb#the_url() and return your custom url.

Don't forget:
Your custom routes (routes.rb) need to point for frontend#post and pass the slug of your content.

**Comment by cmckni3** [comment]
I'm not sure that will be really sustainable for me. It works for 1 section but I have 5 sections. I don't want to have a case statement in the theme for each section. I believe it's going to fall apart on the user administration side as well.

**Comment by cmckni3** [comment]
Let's use the example below.

- IT Consulting
  - Support & Consulting (page)
  - Software Training (page)
- Web Development
  - Website Portfolio (page)
  - Web Development (page)
- Managed Hosting
  - Hosting Environment (page)
- Products
  - Product A (page)
- About Us
  - Why Choose Us (page)
  - News (category)

**Comment by cmckni3** [comment]
It seems like taxonomies aren't fully implemented in camaleon.

- IT Consulting (page)
  - Support & Consulting (page under IT Consulting)
  - Software Training (page under Software Training)
- Web Development (page)
  - Website Portfolio (page under Web Development)
  - Web Development (page under Web Development)
- Managed Hosting (page)
  - Hosting Environment (page under Managed Hosting)
- Products (page)
  - Product A (page)
- About Us (page)
  - Why Choose Us (page under About Us)
  - News (category, selected within nav menu builder and put under About Us)

This might take some work changing the nav menu builder as well. I might have led into this issue with #102

**Comment by cmckni3** [comment]
@owen2345 Thoughts?

**Comment by owen2345** [comment]
hey @cmckni3 
I created the new version Camaleon 2x in which I added this feature.
Check the screenshot.

Please let me know if it is ok for you.

![screen shot 2015-11-17 at 9 31 55 pm](https://cloud.githubusercontent.com/assets/1148415/11230150/acddbbb4-8d72-11e5-9c6c-98c31f98898e.png)

**Comment by owen2345** [comment]
Temporal repo: https://github.com/owen2345/camaleon-cms/tree/moduler

**Comment by owen2345** [comment]
@cmckni3 maybe this is what you looking for. (page hierarchy support)
https://github.com/owen2345/camaleon-cms/issues/275

**Comment by cmckni3** [comment]
@owen2345 That's exactly what I'm looking for. I guess my description of what I needed wasn't that great. Closing in favor of #275.
