### ISSUE TITLE
Cache problems

### ISSUE THREAD

**Issue by fbonomi** [owen2345/camaleon-cms#159]
Hi, I am new on camaleon cms.

I have installed today for some tests. I've created a new post type called "Product". I've created a product with two custom field that I want to print in view. I've found the post.html.erb file used for print information but i have noticed that there are many cache problems. If I edit the file I can't see the modification. I've turned of the plugin "Front Cache" but I still have problems. To see my modifications, I have to launch "rm -rf tmp/cache" everytime.

Is there a pratical solution for that? 

Usually In development stages the cache shouldn't be active.

Thank you
Federico

**Comment by owen2345** [comment]
Hello,
I will review today...

**Comment by cmckni3** [comment]
@fbonomi Do you know if it's actually content caching or is it a problem with your model not being reloaded?

I commonly have the issue that database fields aren't reloaded when a plugin is activated. I have to restart the rails server otherwise I get undefined method errors.

**Comment by cmckni3** [comment]
I find myself restarting the rails server for certain as well.

**Comment by owen2345** [comment]
I modified the plugin to clean cache after restart server and every post/patch requests.
Also, there is a method to clean cache from anywhere: "front_cache_clean()"
