### ISSUE TITLE
Build nav menu for plugins

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#160]
![2015-09-29_15-59-50](https://cloud.githubusercontent.com/assets/735717/10178045/20ceb7ac-66c3-11e5-80bd-155a51312fa3.png)

@owen2345 How do I allow frontend routes from plugins that are post types to be added to a menu?

Looks like [this code](https://github.com/owen2345/camaleon-cms/blob/master/app/views/admin/appearances/nav_menus/index.html.erb#L48) would have to change or I would have to add pages from within the plugin.

Adding pages from within the plugin seems really hacky.

**Comment by owen2345** [comment]
Chris,

I added a new hook "nav_menu_custom" to include custom menus in the menus list:
This hook receive {custom_menus: {}, menu: @nav_menu}.
Sample:
```
def my_custom_menu_hook(args)
  args[:custom_menus][:my_menu] = {link: "my link here", title: "Title for my url"}
end
```
This will add  a new menu group "Custom Menus" in the menus list, in which your menus will be shown.
