### ISSUE TITLE
Expose camaleon view helpers to ActionController::Base.helpers

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#161]
Trying to use `theme_asset_path` where I would normally use `asset_path`. Get no method error.

**Comment by owen2345** [comment]
Chris,
Where are you using this?
I am using in my template like this:

![screen shot 2015-10-10 at 7 41 58 am](https://cloud.githubusercontent.com/assets/1148415/10410976/6ebc9436-6f22-11e5-96bf-66051905d6fa.png)
and it works well.

**Comment by cmckni3** [comment]
I'm trying to use it from within a Carrierwave uploader. I get NoMethodError. I tried the Rails 3 way using `ActionController::Base.helpers` and get NoMethodError as well.

**Comment by owen2345** [comment]
Include the helper:
```
include ThemeHelper
theme_asset_path("js/admin.js")
```
It works for me.

**Comment by cmckni3** [comment]
Is the theme helper not namespaced under `Camaleon`?

**Comment by owen2345** [comment]
No, I am thinking to create the version 2.0 adding the namespace, sample:
models: camaleon/user.rb  => 
```
Class Camaleon::User 
end
```

helpers:
```
module CamaleonThemeHelper
end
```

controllers 
...

This will permit to anyone to integrate a rails app into Camaleon CMS without problems to overwrite methods or models.

**Comment by cmckni3** [comment]
Cool.

I would use the nested syntax though.

```ruby
module Camaleon
  class User
  end
end
