### ISSUE TITLE
Document to setup multiple domain with application

### ISSUE THREAD

**Issue by shyammohankanojia** [owen2345/camaleon-cms#167]
Can you give a link to Document to setup multiple domain with application on production.
How the domain redirection works?
Please explain if you get time, i want to host blogs of my application with multi domain
like blog.codecrux.com, blog.exploreout.in, blog.goos.in etc.

**Comment by charlesgwilson** [comment]
Although I’m not the author, in an effort to help him out I will see if I can answer this to some degree.

First steps are the same for a single site installation; pick a domain or subdomain you want to be the default site for Camaleon and install (I'm using the latest version, not sure if that matters) – for this example we will use blog.codecrux.com as our default site. It’s important to remember which site is the default site as it’s this site’s admin you will go to later to add the additional sites.  Make sure your other domains/subdomains are pointed to the same webroot as this domain/subdomain so they all share the same Camaleon install.

After installation is complete, log in to the Admin at blog.codecrux.com/admin.  Upon successful login, you should find “Sites” located under “Settings” in the side nav. *NOTE:* You can only find this by logging into the default site’s admin.  Navigate to “Sites” and click “Add Site”.  For the slug type in one of the other domains/subdomains, for example, blog.exploreout.in, give it a name and click Submit. You can now log in to the admin at blog.exploreout.in/admin and edit that sites content.

Hope this helps and good luck!

**Comment by owen2345** [comment]
Good answer Charles!
Additionally don't forget to configure your domain configuration, sample this is my configuration for camaleon:

Main Site:
```
server {
      listen 80;
      server_name tuzitio.com;
      root /var/www/tuzitio2/public;   # <--- be sure to point to 'public'!
      passenger_enabled on;

      rails_app_spawner_idle_time 0; # rufus scheduler both lines
      passenger_min_instances 1;

      client_max_body_size 200M;
}
```

Children Sites:
```
server {
      listen 80;
      server_name *.tuzitio.com;
      root /var/www/tuzitio2/public;   # <--- be sure to point to 'public'!
      passenger_enabled on;
      client_max_body_size 200M;
}
```

Note: If you have several domains and not subdomain, you need to register as a main domain with the same root directory.

I am sorry, I was busy with some improvements!
Thank you for your interest in Camaleon CMS.
