### ISSUE TITLE
Theme assets not being precompiled

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#168]
Not sure if this is https://github.com/owen2345/camaleon-cms/issues/137

Unlike there I would describe the bug as follows: I am trying to create a new theme `mytheme` in `app/apps/themes/mytheme`.
The main css file is being referenced in the resulting page using the path `/themes/av/assets/css/main`. CSS files in `app/apps/themes/mytheme/assets/css/` are not being precompiled at all.
Example: http://avs-berlin.herokuapp.com/

**Comment by momolog** [comment]
Could the reason be, that 
https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/assets.rb#L22
is commented out?

**Comment by owen2345** [comment]
Chris has fixed the problem #137 please review again if that is fix for you too.

**Comment by cmckni3** [comment]
It does seem like this is a different problem. The main css file on the heroku app load for me.

**Comment by momolog** [comment]
It was probably a mixture of #137 and personal confusion. Works for me now.

**Comment by cmckni3** [comment]
Sweet. :+1:
