### ISSUE TITLE
Example don't work

### ISSUE THREAD

**Issue by kaiomagalhaes** [owen2345/camaleon-cms#172]
I went to the site to see if I could use this CMS, I saw a option to use an example, a password and a login were give and as soon as I tried them I see this error: 

http://www.clipular.com/c/6724992308871168.png?k=ciWLa9-lENJ9u5GvasLYqd0OGJQ

**Comment by owen2345** [comment]
Hey Cristian, 

I tried to reproduce the error several times, but without success.
Please can you try again or send me the url in which you get that error?


Regards,

**Comment by kaiomagalhaes** [comment]
Hey,

       Right now it is not happening... =/

**Comment by owen2345** [comment]
great!
Enjoy! and I hope that Camaleon CMS likes you.
Any comment is welcome!

**Comment by cmckni3** [comment]
Can this be closed?

**Comment by kaiomagalhaes** [comment]
I think so
