### ISSUE TITLE
Add footer text field

### ISSUE THREAD

**Issue by aradius** [owen2345/camaleon-cms#185]
Hi
I'm trying to add in the main_helper.rb a custom footer 
I try :
  def truc_on_install_theme(theme)
    unless theme.get_field_groups.where(slug: "fields").any?
      group = theme.add_field_group({name: "Main Settings", slug: "fields", description: ""})
      group.add_field({"name"=>"Background color", "slug"=>"bg_color"},{field_key: "colorpicker"})
      group.add_field({"name"=>"Links color", "slug"=>"links_color"},{field_key: "colorpicker"})
      group.add_field({"name"=>"Background image", "slug"=>"bg"},{field_key: "image"})
      group.add_field({"name"=>"Footer text", "slug"=>"theme_custom_footer_text"},{field_key: "editor", translate: true})
    end
    theme.set_meta("installed_at", Time.current.to_s) # save a custom value
  end

But without success. Hooks are still mysterious to me.

**Comment by aradius** [comment]
Ok I just erased previous custom fields in the admin and I reselected the theme. And the footer appeared!

**Comment by cmckni3** [comment]
Yeah, the unless statement was skipping that code if you had previously activated the theme with that field group name.

Can this be closed?

/ping @owen2345
