### ISSUE TITLE
custom routing system

### ISSUE THREAD

**Issue by shishov** [owen2345/camaleon-cms#188]
Hello!
I have a few questions on URL structure can you help me?

1) i have the following structure
/root 
-/color/
--/red/ID-uniq-text.html 
--/green/ID-uniq-text.html
-/pen/
--/big/ID-uniq-text.html
--/small/ID-uniq-text.html
Now if I create a category then receive a URL
/category/ID-color.html or /category/ID-green.html
although from a logical point of view it is not the root elements, and i need get
/color/green/ID-uniq-text.html
How can I do that?

2) the item has a URl ID-unique-text.html, but it turns out that there
One unique item ID-'some letter' and an infinite number of such clones
60-color.html
60-color.htm
60-color
60-dfjhjdfh
no matter what the user writes after ID- it still returns the content as much as possible to fix it?

for example in wordpress custom taxonomy 
http://wordpress.stackexchange.com/questions/39500/how-to-create-a-permalink-structure-with-custom-taxonomies-and-custom-post-types

**Comment by owen2345** [comment]
Hello Anton,
This functionality will be added in the next version that will be published this sunday.
Regards,

**Comment by shishov** [comment]
Ok, thanks!
