### ISSUE TITLE
Permalink link not support utf-8 character

### ISSUE THREAD

**Issue by labolado** [owen2345/camaleon-cms#194]
Permalink link not support utf-8 character

**Comment by owen2345** [comment]
Hi @labolado could you please give a sample?

**Comment by kjj6198** [comment]
When  typing utf-8 character, it comes out this. Even though I've changed the language setting to Chinese,
this still happen. How can I resolve that?
```html
<meta name="description" content="westudent ?????????????????????????????" />
<meta name="keywords" content="??, ??, westudent, sudo, ??" />
<!-- the question mark is utf-8 charset !>
```

**Comment by dusu** [comment]
When setting post_type name as utf-8 character, it's generate a wrong visit link with an empty post_type name, like this: `http://localhost:3000/group/2-`

**Comment by owen2345** [comment]
Fixed! please use github version to review.

**Comment by dusu** [comment]
Great~
