### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chabgood** [owen2345/camaleon-cms#207]
In my existing app when I ran the generator I get this error:

rails generate camaleon_cms:install
      create  config/system.json
      create  lib/plugin_routes.rb
Could not find "apps" in any of your source paths. Your current source paths are:
/Users/chabgood/projects/me/registeryourhorse/lib/templates/camaleon_cms/install
/Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/camaleon_cms-2.0.0/lib/generators/camaleon_cms/install_template

**Comment by calvindcw** [comment]
Same issue here:

create  config/system.json
create  lib/plugin_routes.rb
Could not find "apps" in any of your source paths. Your current source paths are: 
/Library/Ruby/Gems/2.0.0/gems/camaleon_cms-2.0.1/lib/generators/camaleon_cms/install_template

**Comment by owen2345** [comment]
For now please use:
```
gem "camaleon_cms", github: 'owen2345/camaleon-cms', branch: "moduler" # version 2
# If you are using Camaleon CMS 1x, you can use this patch to use this new version
gem "migration1x", github: 'owen2345/camaleoncms_1xmigration'
```
tomorrow I will re build the gem with the new changes

**Comment by calvindcw** [comment]
Seems to work, thanks!

**Comment by Arcolye** [comment]
Same problem here, even in a fresh rails app

**Comment by owen2345** [comment]
Fixed here:
https://github.com/owen2345/camaleon-cms/issues/236
