### ISSUE TITLE
Posts feature field

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#220]
Hi @owen2345!

I think that a possible enhancement might be include a field (featured) in each post to mark featured posts.
I have created a custom field (featured) but it's very difficult to filter for this field in the: "All Items" views table.
Besides I have created an api method (GET api/v1/posts/featured.json) that fetches all posts with featured = true and it's necessary have this field to execute it.

What do you think?

Regards!

**Comment by owen2345** [comment]
@raulanatol I think that the idea is great!
Let me analyze for tomorrow.
Regards,

**Comment by raulanatol** [comment]
Nice @owen2345.
Maybe could be similar like ecommerce feature field 
[data field='ecommerce_featured' object='post' id='3']

Even we could to unify this feature.
Regards.

**Comment by owen2345** [comment]
you are right
