### ISSUE TITLE
Bug after update v2 ActionView::Template::Error (undefined local variable or method `root_url'

### ISSUE THREAD

**Issue by guillaumechaumet** [owen2345/camaleon-cms#223]
After update to version 2, my theme is broken.
ActionView::Template::Error (undefined local variable or method `root_url' for #<#<Class:0x0000000548cbf0>:0x007ffc4c986db8>):
    15:                 </span>
    16:                 <span class="categories-links">
    17:                     <%= raw get_taxonomy(post.the_categories.decorate, 'category tag') %>
    18:                 </span>
    19:                 <span class="tags-links">
    20:                     <%= raw get_taxonomy(post.the_tags.decorate, 'tag') %>
    21:                 </span>
  app/apps/themes/altratheme/views/layouts/index.html.erb:18:in `_app_apps_themes_altratheme_views_layouts_index_html_erb__3576703936127473287_70360795643920'
I achieved to change the theme and it's working.
The dashboard became also ugly.

**Comment by raulanatol** [comment]
Hi @guillaumechaumet!

In v2 **root_url** is removed. Please use **cama_root_url** instead of **root_url**.

Regards
