### ISSUE TITLE
Error when creating a custom field group

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#227]
on branch `moduler`

when creating a new field group like so:

![admin panel custom fields new](https://cloud.githubusercontent.com/assets/71108/11369074/70322ee8-92bd-11e5-8ab7-eba752981b63.jpg)

I am getting this error:
```
NameError in CamaleonCms::Admin::Settings::CustomFieldsController#create
undefined local variable or method `post_data' for #<CamaleonCms::Admin::Settings::CustomFieldsController:0x007fcadef6dff0>

Extracted source (around line #54):
# create a new custom field group
  def create
    @field_group = current_site.custom_field_groups.new(post_data)
    if @field_group.save
      @field_group.add_fields(params[:fields], params[:field_options])
      @field_group.set_option('caption', post_data[:caption])
```

![action controller_ exception caught-2](https://cloud.githubusercontent.com/assets/71108/11369144/cd0b6846-92bd-11e5-8a79-f9e6708d5483.jpg)

**Comment by pulkit21** [comment]
@momolog This issue has been fixed pull the latest code from moduler branch.

**Comment by owen2345** [comment]
Please try again:
https://github.com/owen2345/camaleon-cms/commit/03d41a71facf8d2a762961167ad05d8e3e7871eb

**Comment by momolog** [comment]
ok, thanks.
