### ISSUE TITLE
Specs not running

### ISSUE THREAD

**Issue by yortz** [owen2345/camaleon-cms#228]
Looks like it's not possibile to run specs on `moduler` branch (the only one with some features specs added). It seems that it doesn't find the `login_success` method. I think it'd be useful to make rspec work and to add some guidelines especially on how to integrate rspec for the FE of a `camaleon` install so that people using camaleon could have better understading on what is going on under the hood and have at least some basic tests (unit & integration) that they can use with some real rails application.

**Comment by owen2345** [comment]
For now please ignore the test folder, because I am trying to integrate my small tests in the gem but I don't know where to put the rspec configurations.

**Comment by yortz** [comment]
Thanks for your quick reply, so basically are you going to drop rspec support in favour of test unit or some other suite? I think that the issue with the missing `login_success` method can be easily fixed (guess we need to wrap common.rb into a module and include it when rspec runs - like you did in [wait_for_ajax](https://github.com/owen2345/camaleon-cms/blob/moduler/spec/support/wait_for_ajax.rb#L34)

Fact is that even after fixing this type of issue it's not clear how and what to require, since there are several custom initializers in the `config` folder of the gem itself and feature specs always complain about missing something either related to rails (e.g activerecord) or camaleon itself.

Also, at this point when do you think are you going to release those tests? At least a basic (working) setup of a test suite on camaleon itself would be enough to let other devs (like me) help you debug and add other features :smile: 

Also, are you going to provide some sort of guidelines (or tests) on how to integrate a test suite on a rails app that is using camaleon? Becasue I think that would also be useful.

I think that at this point it would be better to completely remove `rspec` from the `moduler` branch because that could be misleading, or at least it was for me: I've deliberately started working with V2 because I thought I could have some test support :sob: 

Keep me posted ... :smile:

**Comment by cmckni3** [comment]
I think a lot of refactoring needs to happen in order to make a test suite happen.
