### ISSUE TITLE
image custom field

### ISSUE THREAD

**Issue by guillaumechaumet** [owen2345/camaleon-cms#229]
I tried to insert a specific image by page. I want to find a clean solution of the following type:
```
  <a id="bg1" class="bg" href="<%= cama_root_path %>"><%= image_tag current_site.bg, class: "img-responsive" %></a>
```

This solution doesn't work with a custom field "bg".

Any idea?

**Comment by guillaumechaumet** [comment]
edit: I added markdown triple backticks

**Comment by owen2345** [comment]
you need to use like this:
```
current_site.the_field('my_key')
```
more here: http://camaleon.tuzitio.com:8080/documentation/category/40760-decorators/site-1
