### ISSUE TITLE
Heroku app.json

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#23]
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by williamrussellajb** [comment]
Using the Heroku Button on the gitup link ... it attempts to create the site, however, heroku is throwing an error on the app.json.

When I used the dev branch it was fine.

**Comment by owen2345** [comment]
Fixed!
