### ISSUE TITLE
Cannot go to General Setting page

### ISSUE THREAD

**Issue by tantv** [owen2345/camaleon-cms#230]
http://localhost:3000/admin/settings/site`

gives

![settings](https://cloud.githubusercontent.com/assets/4393818/11418744/5e099316-9455-11e5-80d6-6b65a5351779.png)

Why is that?

**Comment by owen2345** [comment]
Fixed, please check again.
It was a windows problem.

**Comment by tantv** [comment]
Hi @owen2345 ,

I follow all step (http://camaleon.tuzitio.com/installation.html) again but it also happened.
What was I wrong here?

**Comment by owen2345** [comment]
Please check this:
http://camaleon.tuzitio.com:8080/documentation/category/40757-developer-docs/installation-1

**Comment by tantv** [comment]
It worked, thanks @owen2345
