### ISSUE TITLE
theme generator not working

### ISSUE THREAD

**Issue by tantv** [owen2345/camaleon-cms#231]
rails g ctheme myTheme

the result is

![error-generator](https://cloud.githubusercontent.com/assets/4393818/11418871/663966e6-9456-11e5-8e85-81e1f7f213a9.png).

I'm using Rails 4.2.5

**Comment by owen2345** [comment]
for version 2, try this:
http://camaleon.tuzitio.com:8080/documentation/category/40756-uncategorized/themes-2

**Comment by iregina** [comment]
Had this same issue.

**Comment by iregina** [comment]
@owen2345 I think you meant to include this link: http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/themes-2

**Comment by owen2345** [comment]
Oops, yes it is!
Thanks @iregina
