### ISSUE TITLE
cannot stop intro popups

### ISSUE THREAD

**Issue by masciugo** [owen2345/camaleon-cms#234]
Whenever I try to use the admin frontend the intro help pops up and either I skip or see all of them it pops up again when I click on any link of the sidebar. Am I missing anything?

**Comment by theil** [comment]
Why is it that I still get this issue on v2.3.6? is it a regression? I have tried on 3 differnet envs and I get the same issue, but it suddenly disappeared on two of my envs (dev and staging) but not on prod.

**Comment by owen2345** [comment]
@theil I test many times without success:
- check this video for local testing:
http://www.screencast.com/t/skxnsPJj1
- also I tested in camaleon server: 
http://camaleon.tuzitio.com/plugins/demo_manage/
Could you please see if there is a problem saving for this in your logs?
![screen shot 2016-11-23 at 12 29 02](https://cloud.githubusercontent.com/assets/1148415/20569901/0a5e8ef6-b178-11e6-8b7c-56424a968b27.png)

Regards,

**Comment by theil** [comment]
Owen thanks for the replay, actually it was our fault. The ajax call was being sent to the wrong server because of nginx. Anyway keep on the good work, and once again thanks.
