### ISSUE TITLE
loading of S3 assets in admin media index page takes too long

### ISSUE THREAD

**Issue by yortz** [owen2345/camaleon-cms#235]
Hi, I've just noticed that after using for several days the now working `moduler` branch with added native S3 integration as documented in this closed issue

https://github.com/owen2345/camaleon-cms/issues/210

when browsing the admin media index page the retrieval from S3 is too slow (it's kinda running like London traffic).

I've been playing with the methods in the `UploaderHelper` and I've actually find out that this closure is the affected line of code that is actually clogging images retrieval from S3.

https://github.com/owen2345/camaleon-cms/blob/moduler/app/helpers/camaleon_cms/uploader_helper.rb#L185

I am saying this since if I just try to instantiate a new `@fog_connection` I authenticate and I just fetch the files the retrieval procedure is blazing fast, so this pointed me to think that this got something to do with camaleon itself and particularly with the resident logic that has been used to display assets on the media index page.

Since there is no test and no documentation for this part, I was wondering if you can take a look at this issue when you got time because this way S3 integration is working, but it's just **NOT** production ready :cry: 

Thanks in advance.

**Comment by yortz** [comment]
@owen2345  Still about this matter, could you please shed some light on `@tree[:files]` ???

https://github.com/owen2345/camaleon-cms/blob/bc204d858b6e02425e93ad62ea58790cd586b582/app/views/camaleon_cms/admin/media/_files_list.html.erb#L1

This is used in the partial for the file retrieval part but it's not clear to me how and why it is used there???

By reviewing the slow running method I've understand you are trying to add references from S3 from the `@fog_connection` to some sort of hash ? So is that used on the admin media index page to display the file list???

Could you also provide the final hash structure that you are trying to build and pass to the view to build the partial so I can understand how to try to replicate that hash (is that used to be passed as json somewhere????) and see if I can tweak that method?

Thanks in advance!

**Comment by owen2345** [comment]
Hi @yortz 
the @tree[:files] line is filtering the file format (images, audio, video, ...)
It is creating a json with file/folder structure, sample:
```
root folder
  {
      folders: {
      child_folder1:{
          folders: {}, 
          files: []
      }
    }, files: [
        {name: '', file: '', size:' ', url: ''}
    ], 
     path: ""
  }
```
Every request only use this json to get inner folders and inner files for current path
Regards,

**Comment by yortz** [comment]
Thanks for your support on this, I actually came up with some simpler/faster solution for S3 file retrieval

```
 @fog_connection_bucket_dir.files.select do |file|
    File.dirname(file.key).include?(@fog_connection_hook_res[:thumb_folder_name])
  end.group_by {|s| s.key.scan /^\d{1}\/.*\// }
```

This seems to be enough to get the files object from S3. I am now working on the views trying to change the `files_list.html.erb partial` that displays images and folder structure on the media index page. As I told you that method takes too long to respond; now the hard part would be to recreate the json structure to feed the js to render the file browser on that page :cry:

**Comment by owen2345** [comment]
Great!

**Comment by momolog** [comment]
https://github.com/owen2345/camaleon-cms/pull/241
