### ISSUE TITLE
Could not find "apps" in any of your source paths

### ISSUE THREAD

**Issue by gabskoro** [owen2345/camaleon-cms#236]
After running `rails generate camaleon_cms:install` I'm getting the following error

```ruby
rails generate camaleon_cms:install
  create  config/system.json
  create  lib/plugin_routes.rb

Could not find "apps" in any of your source paths. Your current source paths are:
/Users/gabrijel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/camaleon_cms-2.0.2/lib/generators/camaleon_cms/install_template
```

Does it have anything to do with your `plugin_routes.rb` file
```
def self.apps_dir
  dir =  "#{File.dirname(__FILE__)}".split("/")
  dir.pop
  dir.join("/")+ '/app/apps' <-- this one?
end
```

**Comment by Arcolye** [comment]
Yeah this is a big one. Anyone trying out Camaleon for the first time right now will be unable to get started.

**Comment by owen2345** [comment]
I am sorry friends, It was my error with ctrl+z keyword.
Please: 
```
bundle update
```
Regards,

**Comment by Arcolye** [comment]
With the 2.0.3 update, there IS an /app/apps directory now. But still getting this error anyway:
```
$ rails g camaleon_cms:install
   identical  config/system.json
   identical  lib/plugin_routes.rb
Could not find "apps" in any of your source paths. Your current source paths are: 
/Users/(...)/.rvm/gems/ruby-2.2.1/gems/camaleon_cms-2.0.3/lib/generators/camaleon_cms/install_template
```

**Comment by doole** [comment]
I'm having the same issue with 2.0.3 clean install (app/apps directory exists).

**Comment by nopicnicc** [comment]
Same problem for me with 2.0.4:

    $ rails generate camaleon_cms:install
    identical  config/system.json
    identical  lib/plugin_routes.rb
    Could not find "apps" in any of your source paths. Your current source paths are: 
    /Users/niklas/.rvm/gems/ruby-2.2.3/gems/camaleon_cms-    2.0.4/lib/generators/camaleon_cms/install_template

**Comment by gabskoro** [comment]
Confirming that the error still exists.

**Comment by owen2345** [comment]
Hi friends,
Please let me know if the error persist.
The problem was that gem builder doesn't recognize .keep files.
Regards,

**Comment by nopicnicc** [comment]
Thank you very much!

Seems to be working.

**Comment by gabskoro** [comment]
It works, tnx :)

Can you please explain what do you mean with: "gem builder doesn't recognize .keep files."

**Comment by owen2345** [comment]
To publish a gem, I need to build and then publish in ruby gems. But apparently that my folder "apps" with ".keep" files was not saved in ruby gems "it was the problem".

**Comment by owen2345** [comment]
Please, don't forget to share the website by social networks.
Regards,

**Comment by bydenix** [comment]
hi Mr owen2345,
  I am getting the following error. please help. I install it for the first time
![image](https://user-images.githubusercontent.com/33016532/31983709-1a205ad4-b967-11e7-9c2e-32162587fce3.png)

**Comment by gabskoro** [comment]
I would say that rails 5.1+ is still not supported, downgrade to 4.1+ and try again.

**Comment by bydenix** [comment]
I have reinstalled but the same again

![image](https://user-images.githubusercontent.com/33016532/31991018-5c4d2852-b97f-11e7-8320-1c337afead55.png)

**Comment by owen2345** [comment]
Hi guys,
please check installation steps here:
https://github.com/owen2345/camaleon-cms#installation
The command line error is "could not find camaleon......install" which is because you didn't install camaleon cms gem.
Regards!

**Comment by bydenix** [comment]
I could not get it to work :( I tried everything

![image](https://user-images.githubusercontent.com/33016532/32127420-6b50869e-bb7f-11e7-9032-3212b825c2b4.png)

**Comment by rubyonrailsdeveloper** [comment]
hello owen2345! how are you?

**Comment by rubyonrailsdeveloper** [comment]
I am going to install your cms template on my project but I can't do it..
I am using ruby-2.5.1 and rails 5.0.6 now..
Please help....
![1](https://user-images.githubusercontent.com/28003174/43925467-d42cd564-9c16-11e8-97e4-112d8c344aa9.png)
