### ISSUE TITLE
Bug and weird behaivor of the create/update/recover/publish button on post edit/creation section

### ISSUE THREAD

**Issue by mmeyerAlitmetrik** [owen2345/camaleon-cms#239]
This button does not have a constant use depending on the status of the post it will update/publish/recover/create.

This generates a really weird UX since depending on what you are doing you have to use the small button or the big green button.

Also when you try to recover a pending version it will recover the version but also set the status to published.

Steps to reproduce:

- Create a new post and save it as pending
- go back to the pending post and save a draft of it
- go to the draft version and recover that version

Result:
The post its recovered and it has the published status

Expected result:
The post its recovered and it has the pending status

**Comment by owen2345** [comment]
done!
please test using:
```
gem "camaleon_cms", github: 'owen2345/camaleon-cms'
```
