### ISSUE TITLE
TypeError in FrontendController#index

### ISSUE THREAD

**Issue by DagnisSlogis** [owen2345/camaleon-cms#244]
After creating/editing posts I got error in FrontendController#index

no implicit conversion of Time into String
in line 361 " d = Date._parse(date, comp)"

def parse(date, now=self.now)
      comp = !block_given?
      d = Date._parse(date, comp)
      year = d[:year]
      year = yield(year) if year && !comp
      make_time(date, year, d[:mon], d[:mday], d[:hour], d[:min], d[:sec], d[:sec_fraction], d[:zone], now)

**Comment by DagnisSlogis** [comment]
Updated gem and it seems there have been a fix for this.

**Comment by owen2345** [comment]
Great! Anyway I am going to review this weekend.
