### ISSUE TITLE
ActionView::MissingTemplate in CamaleonCms::Admin::Settings#site

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#248]
Missing partial camaleon_cms/admin/settings/admin/settings/custom_fields/_render, camaleon_cms/admin/admin/settings/custom_fields/_render, camaleon_cms/camaleon/admin/settings/custom_fields/_render, application/admin/settings/custom_fields/_render, /admin/settings/custom_fields/_render with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}.

**Comment by owen2345** [comment]
hey @lmany where did you found this error?
the correct code should be:
```
<%= render partial: "camaleon_cms/admin/settings/custom_fields/render", locals: {record: current_theme, field_groups: current_theme.get_field_groups, fields_name: "theme_fields"} %>
```

**Comment by lmany** [comment]
Hello thank you for your answer. I have this issue in the left menu admin when I clicked to "Settings>General sites". I used gem "camaleon_cms", github: 'owen2345/camaleon-cms', branch: "moduler" # version 2

**Comment by owen2345** [comment]
what OS are you using? maybe windows?

**Comment by lmany** [comment]
Using Mac Os X. Maybe something wrong in my apps/themes/my_theme/config.json ?

**Comment by lmany** [comment]
If i have to create _render.html.erb to respond to <%= render partial: "admin/settings/custom_fields/render", locals: {record: current_theme, field_groups: current_theme.get_field_groups, fields_name: "theme_fields"} %>?

**Comment by owen2345** [comment]
ohhh yeah,
the problem is in your my_theme/views/admin/settings.html.erb
please change:
```
admin/settings/custom_fields/render
```
into (added prefix "camaleon_cms" in version 2):
```
"camaleon_cms/admin/settings/custom_fields/render"
```

**Comment by lmany** [comment]
THANK YOU VERY MUCH!!!!!!!
