### ISSUE TITLE
Reintroduced: Admin section breaks if changing slug of main site

### ISSUE THREAD

**Issue by mdkirby** [owen2345/camaleon-cms#249]
A code change has reintroduced the bug in issue #134 

I haven't re-coded the fix, but if you look at the commit that fixed it before, it should be easy to incorporate: 
https://github.com/mdkirby/camaleon-cms/commit/fdb5566c25a50c2ec6bf6dc271d65f116ac53493

**Comment by mdkirby** [comment]
Additionally, if the way that `Site.main_site` is defined is DRY'ed up, then it can open up the possibility of changing the main site - I don't know how it would effect the rest of the app, but something like this might make the most sense (after adding a `primary` column or something similar to the term taxonomy table):
```
class Site < TermTaxonomy
...
  def self.main_site
    @main_site ||= Site.where(primary: true).order(:created_at).first || Site.order(:created_at).first
  end
...
```

**Comment by owen2345** [comment]
Are you using the v2 or v1?

**Comment by mdkirby** [comment]
We are using v1 and hoping to upgrade to v2.

It looks like when the change was made to namespace things, the code was reverted. For example:
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/site_helper.rb#L20

Anywhere that `CamaleonCms::Site.first` is called, assuming you will get the 'main_site' will create problems (at least with postgres) because the Site that is returned by the call to `first` can (and will) change as the database records are updated.

Defining the `main_site` in the model and having the helpers and views rely on that will give consistent results.

**Comment by keithlayne** [comment]
@owen2345  The PR that you merged into master from @mdkirby needs to be backported to the v1 branch, and a new gem release should be made.  This shouldn't take any real work.  Any other bugfixes on the master branch that apply to v1 should be backported too.

**Comment by mdkirby** [comment]
Are there plans to incorporate this fix into v1 and v2? Until this is fixed, we are having to maintain our own fork of camaleon, otherwise, making an update to the main site will "brick" the entire app. The front ends still work, but the admin section for every site becomes inaccessible.

**Comment by owen2345** [comment]
@mdkirby , @keithlayne 
I will work in this problem this weekend.
I think that correct way is to create method:
```
class CamaleonCms::Site ..
  def self.main_site
    @main_site ||= CamaleonCms::Site.reorder(id: :ASC)
  end
end
```
which easily can be overwritten to use custom site as a main_site:
```
CamaleonCms::Site.class_eval do
  def self.main_site
    @main_site ||= CamaleonCms::Site.where(slug: 'my_slug').first    
  end
end
```

Please let me know if it is ok for you.

**Comment by mdkirby** [comment]
@owen2345 - Yeah, the most important part is that the `main_site` is defined in just one place that can be overwritten. The bigger challenge is finding all the other code where a call to `Site.first` or something similar (e.g. `get_sites.first`) is being made.
https://github.com/owen2345/camaleon-cms/search?utf8=%E2%9C%93&q=Site.first

**Comment by owen2345** [comment]
v2 done!
please use master branch to review and let me know if it works well for you.
Regards!

**Comment by mazharoddin** [comment]
Hi, I am not sure if its similar problem or not but, some time newly created site becoming default site,  due to of this newly created site owner becoming super admin for entire site and he is able to access all new sites which were created.
Moreover earlier main site is not able to modify or remove newly created site because now it become default site.

Randomly I am seeing this issue and I could able to re-create it by updating slug info for default site using rails console.
````
irb(main):017:0> site = CamaleonCms::Site.first
irb(main):017:0> site.update(slug: "cms.net")
irb(main):017:0> site.save
````
By using above commands I am able to recreate the issue. I am using camaleon_cms 2.1.1 version.

**Comment by owen2345** [comment]
Fixed!
