### ISSUE TITLE
re-adding footer to default theme?

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#25]
From the admin dashboard.. if you delete the footer in the custom fields, and later try to re-add it. It will no longer show up in the general site > themes area. 

Footer appears to be permanently deleted

**Comment by williamrussellajb** [comment]
Sorry it was late last night, let me re-phrase.

I deleted the footer and can't re-add it using the custom theme.

Steps to reproduce:
1. Open admin site and navigate to Custom Fields
2. Delete the footer field
3. Refresh the main site and validate the footer was removed.
4. Navigate back to the admin > Custom Fields
5. Click add new field group
6. Add new "Editor" fields
7.  Name Column Left
8.  slug footer_left
9. Do this for center/right
10. On the left side, name the "Details Custom Field Group"to "Footer"
11. Choose where to display

Expected Result:
If I select where to display as "themes" I'm expecting to see my "Footer" in
General Site > Theme Settings > Footer



Not sure if I'm using it wrong. 
I'm still new to rails and learning from your open source project. 

Thanks!

**Comment by ikis-sysdecom** [comment]
We are checking  this problem.
thanks by the report.

**Comment by ikis-sysdecom** [comment]
One tip , that can help you , 
You can recover the footer by default if you change the theme to other and later return to theme by default. then the custom field is create again.("This is part of the theme").

The "footer implement"  you can look  in the layout of theme.(app/apps/themes/camaleon_first/view/layouts/index.html.rb).

You can edit content the footer in admin->settings->general site->theme setting(We go to move this view sorry ).
in the bottom appear the editor for modify the footer
