### ISSUE TITLE
Deployment to heroku : BreadcrumbsOnRails detected it won't be overridden. 

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#251]
Hi,
When i deployed to heroku i have this error message.
"BreadcrumbsOnRails detected it won't be overridden. To use methods from this gem you need to call them using bootstrap prefix i.e. add_bootstrap_breadcrumb and render_bootstrap_breadcrumbs."

Can you help?

**Comment by owen2345** [comment]
I tried several times and I can not reproduce the problem, sample here:
https://camaleon-cms-rails.herokuapp.com/
