### ISSUE TITLE
How skip User model?

### ISSUE THREAD

**Issue by apradillap** [owen2345/camaleon-cms#252]
<addr> PG::DuplicateTable: ERROR:  relation "users" already exists
: CREATE TABLE "users" ("id" serial primary key, "username" character varying, "role" character varying DEFAULT 'client', "email" character varying, "slug" character varying, "password_digest" character varying, "auth_token" character varying, "password_reset_token" character varying, "parent_id" integer, "password_reset_sent_at" timestamp, "last_login_at" timestamp, "created_at" timestamp, "updated_at" timestamp, "site_id" integer DEFAULT -1)  

Is it possible skip an existing model?

**Comment by owen2345** [comment]
you can do it overwriting the class in a initializer, see a sample to overwrite a class here:
http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/customize-post-type-routes.html

So, you need to overwrite this class:
https://github.com/owen2345/camaleon-cms/blob/master/app/models/camaleon_cms/user.rb#L9

like:
```
CamaleonCms::UniqValidatorUser.class_eval do
  def validate(record)
    # here my custom validation for user
  end
end
```

**Comment by cmckni3** [comment]
@apradillap Had this problem recently after attempting to upgrade camaleon.

The `schema_migrations` table in production only had the most recent timestamp. I had to fix it by adding the schema timestamps that were missing from `schema_migrations`.

**Comment by owen2345** [comment]
You can use db_prefix for table names, to do this, modify this in config/system.json
```
db_prefix: 'my_prefix'
```
