### ISSUE TITLE
show the default theme?

### ISSUE THREAD

**Issue by ztvMark** [owen2345/camaleon-cms#255]
as I can show the original default theme?
http://camaleon.tuzitio.com/media/132/custom.theme.for.specific.site.png

not on my camaleon_cms folders

______
Como puedo hacer que aparesca la carpeta camaleon_cms?
http://camaleon.tuzitio.com/media/132/custom.theme.for.specific.site.png

**Comment by owen2345** [comment]
Hi @ztvMark the camaleon_cms folder is this theme (it is a paid theme):
http://camaleon.tuzitio.com/store/themes/camaleon_cms
