### ISSUE TITLE
None Favicon

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#257]
Camaleon will display the Camaleon favicon when we don't have the favicon. Is there a way to disable the favicon when we don't have it? 

I try to implement a plug in but i can override method the_head. How can I override the the helper from in  my plug in ?

**Comment by owen2345** [comment]
Hi @Uysim 
I changed a little the cms to ease customization:
now, you can do it by two ways:
1. plugin:
you can use this hook:
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/frontend/seo_helper.rb#L87

2. argument
the_head({icon: nil})

**Comment by Uysim** [comment]
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/frontend/seo_helper.rb#L52

I see this line you still get icon from the current site. So do you think the the_head({icon: nil}) still work

**Comment by owen2345** [comment]
yes, 
the_head({icon: nil}) will overwrite the default icon with nil

**Comment by Uysim** [comment]
@owen2345 
I try to do the_head({icon: nil}) as you tell me but the default icon still display.
Can you look at https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/frontend/seo_helper.rb#L52 again?

Because I see you sill get icon from current_site.the_icon without and condition or option params in cama_build_seo method.

**Comment by Uysim** [comment]
It work now thank you

**Comment by Uysim** [comment]
@owen2345 Can you deploy this to ruby gem ?

**Comment by owen2345** [comment]
done: 2.1.0
