### ISSUE TITLE
Can not load plugin assets

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#258]
I just create a plugin. I load plugin js by plugin_asset_path('js/main.js'). It can not my javascript. I try to run rake assets:precompile but I can not see my plugin in assets plugin folder. 

And also I think the document is strange to say that : 
<script src=“<%= plugin_asset_path(”js/admin.js“) %>”></script> => /assets/plugins/my_plugin/assets/css/main-54505620f.css
I should path to javascript not css

**Comment by owen2345** [comment]
@Uysim I am sorry, it was for the previous version v1.
I updated the docs:
```
<script src="<%= plugin_asset_path("admin.js") %>"></script> => /assets/plugins/my_plugin/admin-54505620f.js  
<script src="<%= plugin_asset_path("admin.js", 'my_plugin') %>"></script> => /assets/plugins/my_plugin/admin-54505620f.js
```

**Comment by Uysim** [comment]
Thank you
