### ISSUE TITLE
undefined method `translate' 

### ISSUE THREAD

**Issue by eshaiju** [owen2345/camaleon-cms#26]
![translation_error](https://cloud.githubusercontent.com/assets/2918256/9302451/3c8d9328-44f4-11e5-8224-25946fb69122.png)

NoMethodError (undefined method `translate' for 333:Fixnum):
  app/decorators/application_decorator.rb:18:in `the_keywords'
  app/decorators/application_decorator.rb:49:in `the_seo'
  app/helpers/frontend/seo_helper.rb:11:in `init_seo'
  app/controllers/frontend_controller.rb:136:in `render_post'
  app/controllers/frontend_controller.rb:105:in `post'

  Rendered /home/shaiju/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.2ms)
  Rendered /home/shaiju/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.2ms)
  Rendered /home/shaiju/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /home/shaiju/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (29.2ms)

**Comment by owen2345** [comment]
fixed!
