### ISSUE TITLE
Contents menu icon personalize

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#260]
Hi @owen2345!

Exist any way to customize the icon of the content types into the admin content menu?

![current](https://cloud.githubusercontent.com/assets/2389019/12021354/e725b9cc-ad7d-11e5-844e-67fe28d6590a.png)

Change to:
![result](https://cloud.githubusercontent.com/assets/2389019/12021396/58c0f1dc-ad7e-11e5-89fc-3e17906d02af.png)

Maybe can be customized using the content groups form. Anything like this:

![form](https://cloud.githubusercontent.com/assets/2389019/12021454/d20e237a-ad7e-11e5-91d6-6650e8be52da.png)

Regards!

**Comment by owen2345** [comment]
Hi @raulanatol 
let me add this option.

**Comment by owen2345** [comment]
ready!

**Comment by raulanatol** [comment]
Works perfect!!

Thxs!
