### ISSUE TITLE
asset-theme-url incorrect path

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#263]
In scss I use asset-theme-url('images/1.jpg') I generate a url for me
localhost:3000/assets/themes/four_heart/assets//images/1.jpg

It is two / in front of the image with cause error in the production. 

Please have a look at 

https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/sass.rb#L47

The get_theme_prefix method return string which end with '/'

and

https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/sass.rb#L26

The asset_theme_url concate string "#{get_theme_prefix}/#{path.value}" which have middle '/' that cause this double / to be generate.

**Comment by owen2345** [comment]
@Uysim fixed!
please try again.

**Comment by owen2345** [comment]
Sample:
```
body{
  background-image: asset-theme-url("images/image.png");
  background-image: url(asset-theme-path("images/image.png"));
}
```

**Comment by Uysim** [comment]
Thank

**Comment by Uysim** [comment]
@owen2345 Can you help deploy this to ruby gem?

**Comment by owen2345** [comment]
done: 2.1.0
