### ISSUE TITLE
Multi languages with Contents Route Format => content/:post_type_title/:slug in Content Group

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#264]
Edit Post Type : When I'm changing the value of name other language and save, no problem at all.
My Contents Route Format in the panel visitor (Settings, stil in the edit post_type form) is setting to /:post_type_title/:slug.

Now in the public view, when i want to view the content, i have this error
 
Error
No route matches {:action=>"post", :controller=>"camaleon_cms/frontend", :locale=>:fr, :post_type_id=>"39", :post_type_title=>"liste-des-exposants", :slug=>"credit-foncier-du-cameroun", :title=>"liste-des-exposants"} missing required keys: [:post_type_title]

:post_type_title=>"liste-des-exposants" is my new name in french language.

But if Contents Route Format is setting to /:slug , there is no problem

Thks

**Comment by owen2345** [comment]
fixed!
please test using:
```
gem 'camaleon_cms', github: 'owen2345/camaleon-cms'
```
Next weekend I will publish the new gem version

**Comment by lmany** [comment]
Thank you

**Comment by lmany** [comment]
Hello,

Please could you help me on how to use and create shortcode ?

Thank you for your help

2015-12-31 12:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:

> fixed!
> please test using:
>
> gem 'camaleon_cms', github: 'owen2345/camaleon-cms'
>
> Next weekend I will publish the new gem version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/264#issuecomment-168174800>
> .
>



-- 
Léo MANY

**Comment by owen2345** [comment]
@lmany  I created this video:
https://youtu.be/jIp0w5BtpHI
please let me know if it is enough.

**Comment by lmany** [comment]
Owen,

Thank you very much it's was great!!

2016-01-06 2:34 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:

> @lmany <https://github.com/lmany> I created this video:
> https://youtu.be/jIp0w5BtpHI
> please let me know if it is enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/264#issuecomment-169190870>
> .
>



-- 
Léo MANY
