### ISSUE TITLE
smtp email settings and notifications

### ISSUE THREAD

**Issue by papadiddydoo** [owen2345/camaleon-cms#265]
I am unable to get the email settings and notifications to work.  I have configured gmail's smtp settings using smtp.gmail.com and port 587.  I have used the same username and password in other rails apps so i know the combination is correct.  The only error message I see is "Gmail needs permission Check Here" which I have already granted. And I don't see any errors in the error logs file.  

I am using the latest stable version of both ruby and rails.   ruby2.3.0 and rails 4.2.5.  Any help is greatly appreciated.  Much Thanks!

**Comment by owen2345** [comment]
Fixed the problem!

**Comment by truthSeekr** [comment]
are there notifications ?

**Comment by kirykr** [comment]
@owen2345 this might be the new error message 
```
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
``
