### ISSUE TITLE
undefined method `init_seo' 

### ISSUE THREAD

**Issue by CBlaize** [owen2345/camaleon-cms#266]
undefined method `init_seo' for #<Plugins::About::FrontController:0x007fcbab952440>

Upgraded from 1.x to 2.0.5.  Still working out some breaking changes.  

respond_to do |format|
   format.html do
      init_seo(current_site)
 ...

**Comment by owen2345** [comment]
@CBlaize  init_seo was deprecated, please use one of these:
http://www.rubydoc.info/github/owen2345/camaleon-cms/master/CamaleonCms/Frontend/SeoHelper
