### ISSUE TITLE
Tags on posts?

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#268]
Hello, 
I'm trying to create a data-filter for my categories/posts

I wanted to use "tags" as the id for grouping, or category.

     category = current_site.the_category(@category.the_slug) %>
        <% category.the_posts.decorate.each do |post| %>
        <div class="card"  data-filter=".<%= post.the_tag %>"> 

Im not sure where or how to grab the tags that are on a post.
Thanks!

**Comment by owen2345** [comment]
Hi @williamrussellajb 
the tags are like categories:
```
  has_many :categories, class_name: "CamaleonCms::Category", through: :term_relationships, :source => :term_taxonomies
  has_many :post_tags, class_name: "CamaleonCms::PostTag", through: :term_relationships, :source => :term_taxonomies
```
you can do it like this (filter all post's of a category by specific post tag slug):
```
my_category.the_posts.joins("LEFT JOIN 'term_relationships' as 'tag_rel' ON 'posts'.'id' = tag_rel.'objectid'  LEFT JOIN 'term_taxonomy' as 'tags' on tags.id = tag_rel.term_taxonomy_id").where(tags:{slug: 'mytag2'})
```
