### ISSUE TITLE
How to enable amazon S3 storage for all subdomains

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#270]
Hi,
Please let me know how to enable to amazon S3 storage for all subdomains, currently I enabled S3 storage on main site, but still subdomains are using local storage, so I wanted all subdomains also use same S3 storage as main site so that there is no need to configure subdomains manually , please let me know how I can do that.

**Comment by owen2345** [comment]
you can use the hook "on_uploader" or overwrite this method by your initializer.
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/uploader_helper.rb#L132

**Comment by mazharoddin** [comment]
Thank you, I will try to explore more, but  it would be great if you can provide some sudo/real code to start with, Thanks

**Comment by owen2345** [comment]
Sample using a hook (create a plugin):
add the hook in your my_plugin/config/camaleon_plugin.json
```
"hooks": {
    ....
    "on_uploader": [
      "my_plugin_my_method_name"
    ]
    ...
```

add this method in your plugin helper (my_plugin/app/helpers/plugins/my_plugin/main_helper.rb):
```
def my_plugin_my_method_name(args)
  main_site = CamaleonCms::Site.main_site
  args[:connection] = Fog::Storage.new({ :aws_access_key_id =>main_site.get_option("filesystem_s3_access_key"), :provider   => 'AWS', aws_secret_access_key: main_site.get_option("filesystem_s3_secret_key"), :region  => main_site.get_option("filesystem_region") })
  args[:bucket_name] = main_site.get_option("filesystem_s3_bucket_name")
end
```

**Comment by mazharoddin** [comment]
Thanks a lot, I will try and update you. Thank you.

**Comment by mazharoddin** [comment]
Hi,
I added system hook and created helper method as you suggested, now its working fine for all my subdomains.
However its taking time to load image upload window when I click on upload image, I believe its due to the fact that its trying to load all already existing images from S3, but it may create problem if there are several images.
Any way once again thanks for the solution.

**Comment by owen2345** [comment]
great!
about the slow problem I will improve in next versions.
PD: please don't forget to share camaleon by social networks.

**Comment by mazharoddin** [comment]
Sure, I will do that, its great CMS..

**Comment by mazharoddin** [comment]
Closing this issue because now I am able to use S3 for all subdomains as mentioned above. Thanks

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
With latest stable master branch, I am unable to use S3 for all subdomains though I added below helper method in "ApplicationHelper" file.
```
 def aws_s3_for_all_subdomains(args)
    main_site = CamaleonCms::Site.main_site
    args[:connection] = Fog::Storage.new({ :aws_access_key_id =>main_site.get_option("filesystem_s3_access_key"), :provider   => 'AWS', aws_secret_access_key: main_site.get_option("filesystem_s3_secret_key"), :region  => main_site.get_option("filesystem_region") })
    args[:bucket_name] = main_site.get_option("filesystem_s3_bucket_name")
  end
````
I also modified system.json file as below
````

"on_uploader": [
      "aws_s3_for_all_subdomains"
    ]
  }
````
As far I remember this was working fine earlier, but not sure from when it's broken.

**Comment by owen2345** [comment]
Hi @mazharoddin ,
I am sorry, but I removed the fog dependency for many problems with file permissions and cache, the easy way to do the same is by overwriting the following method:
https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L74
Regards,

**Comment by b264** [comment]
You could subclass it maybe instead of overwriting it?
```class YourUploader < CamaleonCmsAwsUploader```

**Comment by owen2345** [comment]
Like this:
```
CamaleonCmsAwsUploader.class_eval do
  def bucket
  # here overwrite the current function
  end
end
```

**Comment by mazharoddin** [comment]
np @owen2345, I am able to upload images to s3 and cloudfront using AWS uploaded, but still sub domains are not able to use main site S3 bucket details.
I modified earlier application helper as below.
````
module ApplicationHelper
  def aws_s3_for_all_subdomains(args)
    main_site = CamaleonCms::Site.main_site
    args[:connection] = Aws.config.update({ region: main_site.get_option("filesystem_region"),credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"),main_site.get_option("filesystem_s3_secret_key"))})
     s3 = Aws::S3::Resource.new
    args[:bucket_name] = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
  end
end
````
Please let me know if any changes are required. Thanks

**Comment by mazharoddin** [comment]
Hi @owen2345 , 

Can you please help me writing this helper method, due to this issue sub sites are using local space, but I wanted them to use main site s3 and cloudfront IDs.

**Comment by owen2345** [comment]
Hi @mazharoddin 
you need to overwrite this method:
```
CamaleonCmsAwsUploader.class_eval do
  def bucket
    @bucket ||= lambda{
      main_site = Cama::Site.main_site
      config = Aws.config.update({ region: main_site.get_option("filesystem_region", 'us-west-2'), credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"), main_site.get_option("filesystem_s3_secret_key")) })
      s3 = Aws::S3::Resource.new
      bucket = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
    }.call
  end
end
```

**Comment by mazharoddin** [comment]
Thanks @owen2345

**Comment by mazharoddin** [comment]
Hi @owen2345,

While testing this change I found that settings are not getting saved, I am unable to upload new logo or change media settings etc with latest code. 
I am using  camaleon_cms 2.2.1 from git://github.com/owen2345/camaleon-cms.git.
Can you please check the issue.

**Comment by mazharoddin** [comment]
@owen2345, I am unable to save S3/cloudfront settings as mentioned above, when i click save button I get confirmation mentioning site is updated, but settings are not getting saved.
<img width="203" alt="screen shot 2016-08-15 at 11 50 39 am" src="https://cloud.githubusercontent.com/assets/6102465/17657139/88594e6a-62de-11e6-85ca-db68389da04c.png">
<img width="265" alt="screen shot 2016-08-15 at 11 50 32 am" src="https://cloud.githubusercontent.com/assets/6102465/17657141/8c55d466-62de-11e6-9ff9-369f9bd8a5fe.png">

**Comment by owen2345** [comment]
Fixed, please use 2.3.x because that version includes a typing error.
Regards,

**Comment by mazharoddin** [comment]
Ok, Thanks @owen2345 , I will update once I test it.

**Comment by mazharoddin** [comment]
@owen2345 , now main site settings are getting successfully, Thank you!!.

But still I am unable to use main site S3 and cloudfront urls with other subdomains, I tried to override "CamaleonCmsAwsUploader" class using below code, I tried several time but its not working.

I created config/initializers/camaleon_cms.rb  file and added below code as you suggested.

```
CamaleonCmsUploader::CamaleonCmsAwsUploader.class_eval do
  # initialize a bucket with AWS configurations
  # return: (AWS Bucket object)
  def bucket
    @bucket ||= lambda{
      main_site = Cama::Site.main_site

      config = Aws.config.update({ region: main_site.get_option("filesystem_region", 'ap-southeast-1'), credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"), main_site.get_option("filesystem_s3_secret_key")) })
      s3 = Aws::S3::Resource.new
      bucket = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
    }.call
  end
end
```
Sorry for re-opening same issue again.

**Comment by owen2345** [comment]
Hi @mazharoddin,
could you please tell me what is the problem?
is there any error in the console? or is not calling to your custom method?
Regards,

**Comment by mazharoddin** [comment]
hi @owen2345 ,
There are no errors in console, i believe its not calling my custom method..one more thing, earlier I used to load "aws_s3_for_all_subdomains" using on_uploader hook, but currently I am not using this hook since I am overriding  "CamaleonCmsAwsUploader" class in initialize. 

So looks like subdomain not loading bucket config without selecting "s3" storage option in subdomain settings here.
![screen shot 2016-08-24 at 3 36 40 pm](https://cloud.githubusercontent.com/assets/6102465/17926858/9ef39f8e-6a10-11e6-924d-a4d5a8997599.png)

**Comment by mazharoddin** [comment]
hi @owen2345 ,
Can you please let me know how i can use old code in 2.3.3, atlease I will try to replace earlier working code, due to this issue I am not loading any images on subdomains, because I wanted all subdomains use s3 storage instead of local storage..Thanks

**Comment by owen2345** [comment]
Hi @mazharoddin 
I re added the hook to customize file uploader from hooks:
```
args={ server: 'local/aws', thumb: {w: 100, h: 100}, aws_settings: {region: 'us-west-2', access_key: 'xxx', secret_key: 'yyy', bucket: 'test'}}; hooks_run("on_uploader", args)
```
Please let me know if this works for you.
Regards,

**Comment by mazharoddin** [comment]
Let me try it, thank you @owen2345

**Comment by mazharoddin** [comment]
Hi @owen2345, can you please let me know how to test this change..

**Comment by owen2345** [comment]
create a hook
- add in config.json
```
" hooks": {
"on_uploader": ["my_helper"]
}
```
- in my helper.rb
```
def my_helper(args)
  args[:server] = 'aws'
  args[:aws_settings] = {region: 'us-west-2', access_key: 'xxx', secret_key: 'yyy', bucket: 'test'}
end
```
restart server and all file conections will use this setting

**Comment by mazharoddin** [comment]
Thanks @owen2345 ,
After some testing, I could able to use S3 for subdomains with below code.
```
 def aws_s3_for_all_subdomains(args)
    main_site = CamaleonCms::Site.main_site
    args[:aws_settings] = Aws.config.update({ region: main_site.get_option("filesystem_region"),credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"),main_site.get_option("filesystem_s3_secret_key"))})
    s3 = Aws::S3::Resource.new
    args[:bucket] = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))

  end
```
But I will change as you suggested..Thanks a lot

**Comment by owen2345** [comment]
great!
be careful with "aws_settings" , it receives a hash

**Comment by mazharoddin** [comment]
ohh Ok, Sure, but some reason I am unable to upload images to S3 for subdomain with your suggested helper...I am testing further ...I am trying to test cloudfront aswell... I will update you once I test S3 and cloudfront with subdomains...thank you ...

**Comment by mazharoddin** [comment]
Hi @owen2345,
I tested various combinations, but only below code is working.
```
 def aws_s3_for_all_subdomains(args)
    args[:server] = 's3'
    main_site = CamaleonCms::Site.main_site
    args[:aws_settings] = Aws.config.update({ region: main_site.get_option("filesystem_region"),credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"),main_site.get_option("filesystem_s3_secret_key"))})
    s3 = Aws::S3::Resource.new
    args[:bucket] = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
  end
```
Also note that for reason only `args[:server] = 's3'` is working instead of `args[:server] = 'aws'`

Onemore thing I am unable to use main site cloudfront url for subdomains, without that subdomains will use lot of bandwidth of S3, moreover images will load very slowly, can you please add cloudfront support aswell...thank you..

**Comment by owen2345** [comment]
it is strange your definition because this is function which is using your configuration:
https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L76
Also I added the fix for cloudfront customization

**Comment by mazharoddin** [comment]
Not sure how, but its working :) ..ok let me test the cloudfront part ..thanks..one more thing, I am seeing performance issue while main site user is trying to delete a image and if subdomain user trying delete/add new image, site completely becoming unusable for some time.
I will further test and update you..Thanks for the cloudfront fix...

**Comment by mazharoddin** [comment]
Hi @owen2345,
Cloudfront hook is not working, if I enabled cloud front in main site and if I didn't change earlier helper hook then I am getting below error if I try to access subdomain media folder.
```
undefined method `objects' for nil:NilClass Did you mean? object_id
    objects = {}
    objects['/'] = {files: {}, folders: {}}
    bucket.objects.each do |file|
      cache_item(file_parse(file), objects)
    end
    @current_site.set_meta(cache_key, objects)
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-cms-5d1e0b205798/app/uploaders/camaleon_cms_aws_uploader.rb:6:in `browser_files'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-cms-5d1e0b205798/app/uploaders/camaleon_cms_uploader.rb:23:in `objects'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-cms-5d1e0b205798/app/controllers/camaleon_cms/admin/media_controller.rb:84:in `init_media_vars'
```
I am getting below error if added cloud_front option to helper function.
```
invalid configuration option `:cloud_front'
    main_site = CamaleonCms::Site.main_site
    args[:aws_settings] = Aws.config.update({ region: main_site.get_option("filesystem_region"),cloud_front: main_site.get_option("filesystem_s3_cloudfront"), credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"),main_site.get_option("filesystem_s3_secret_key"))})
    s3 = Aws::S3::Resource.new
    args[:bucket] = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
  end

app/helpers/application_helper.rb:6:in `new'
app/helpers/application_helper.rb:6:in `aws_s3_for_all_subdomains'
```
I also tried changing helper as below.
```
def aws_s3_for_all_subdomains(args)
    args[:server] = 's3'
    main_site = CamaleonCms::Site.main_site
    args[:aws_settings] = Aws.config.update({ region: main_site.get_option("filesystem_region"), credentials: Aws::Credentials.new(main_site.get_option("filesystem_s3_access_key"),main_site.get_option("filesystem_s3_secret_key"))})
    s3 = Aws::S3::Resource.new
    args[:bucket] = s3.bucket(main_site.get_option("filesystem_s3_bucket_name"))
    args[:cloud_front] = main_site.get_option("filesystem_s3_cloudfront")
  end
```

**Comment by mazharoddin** [comment]
Hi @owen2345, 
if possible can you please have a look into this issue once. Thanks.

**Comment by owen2345** [comment]
Hi @mazharoddin,
sorry for my delay, I found the problem (there was || instead a ,).
Fixed and tested with:
```
def my_helper(args)
    args[:server] = 'aws'
    args[:aws_settings] = {region: 'us-west-2',
                           access_key: '0909090909',
                           secret_key: '01010101010101010100101100',
                           bucket: 'my_bucket',
                           cloud_front: 'https://d199wmwx3434.cloudfront.net'}
  end
```
Note: this hook should be register in your system.json to be executed for all sites.
Note2: Don't forget to "clear cache" in media browser
Test it using git version.
Regards,

**Comment by mazharoddin** [comment]
np @owen2345 , its working now, thank you so much...

One problem observed is if I change filesystem setting from local to aws and go back to local then all files are getting deleted, though I wont be using local storage, but it may create problem for users who uses local storage, so thought to report it.
 I can open seperate issue if required. Thanks.

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
Sorry to report it, but I am seeing one more issue related to S3 after deploying fix to staging server.
```
F, [2016-09-03T12:23:41.101755 #9510] FATAL -- : NoMethodError (undefined method `objects' for nil:NilClass
Did you mean?  object_id):
F, [2016-09-03T12:23:41.102293 #9510] FATAL -- :   
F, [2016-09-03T12:23:41.103130 #9510] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_aws_uploader.rb:15:in `browser_files'
F, [2016-09-03T12:23:41.103636 #9510] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:23:in `objects'
F, [2016-09-03T12:23:41.104067 #9510] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/controllers/camaleon_cms/admin/media_controller.rb:87:in `init_media_vars'
F, [2016-09-03T12:23:41.104454 #9510] FATAL -- : activesupport (5.0.0) lib/active_support/callbacks.rb:382:in `block in make_lambda'
```
Due to this issue I am getting 500 error if I try to access media folder on subdomain.

**Comment by mazharoddin** [comment]
Looks like there is some issue with cache, I am getting below error on my local setup aswell.
```
        "thumb" => '',
        'type' => is_dir ? '' : (s3_file.content_type rescue (MIME::Types.type_for(key).first.content_type rescue "")),
        'created_at' => is_dir ? '' : s3_file.last_modified,
        'dimension' => ''
    }.with_indifferent_access
    res["thumb"] = version_path(res['url']) if res['format'] == 'image' && File.extname(res['name']).downcase != '.gif'

/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_aws_uploader.rb:37:in `file_parse'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `block in cache_item'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `each'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `each_with_index'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `cache_item'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_aws_uploader.rb:16:in `block in browser_files'
```

**Comment by owen2345** [comment]
I think that the problem for "if I try to access media folder on subdomain" is because your hook is not calling for sub domains, put your hook in system.json and the function in applicatio helper.

**Comment by owen2345** [comment]
About the cache error, after you changed the file storage settings, you need to clear cache to re scan the files.

**Comment by mazharoddin** [comment]
Hi,
No I put the the hook in system.json and in application helper aswell
yes, I tried clearing the cache, dropping the database and recreating etc, but I am seeing same issue.

**Comment by owen2345** [comment]
@mazharoddin, Check my image, I don't have any error:
![screen shot 2016-09-03 at 15 29 18](https://cloud.githubusercontent.com/assets/1148415/18227223/36ea20f6-71eb-11e6-908c-6fd0924ada15.png)
Tried many times without any error.
Regards,

**Comment by mazharoddin** [comment]
ohh ok, sure I will try again, but it was not working for me even on newly created site aswell.

**Comment by mazharoddin** [comment]
hi @owen2345 , for some reason its not fully working for me, it worked for some time if I restart the server by changing filesystem back to local and back to S3, but  if I create new subdomain then I am seeing same issue again.
This time i got slightly different error.
```
F, [2016-09-04T15:11:50.167707 #6669] FATAL -- : NoMethodError (undefined method `last_modified' for "/production/database/production_backup/2016.01.14.08.47.44":String):
F, [2016-09-04T15:11:50.168159 #6669] FATAL -- :   
F, [2016-09-04T15:11:50.168415 #6669] FATAL -- : /home/deployer/apps/shop
/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_aws_uploader.rb:37:in `file_parse'
F, [2016-09-04T15:11:50.168773 #6669] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `block in cache_item'
F, [2016-09-04T15:11:50.169290 #6669] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `each'
F, [2016-09-04T15:11:50.169534 #6669] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `each_with_index'
F, [2016-09-04T15:11:50.170201 #6669] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_uploader.rb:59:in `cache_item'
F, [2016-09-04T15:11:50.171297 #6669] FATAL -- : /home/deployer/apps/shop/shared/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-34f309c45780/app/uploaders/camaleon_cms_aws_uploader.rb:16:in `block in browser_files'
F, [2016-09-04T15:11:50.172310 #6669] FATAL -- : aws-sdk-resources (2.5.8) lib/aws-sdk-resources/batch.rb:75:in `each'
```
I think this error occurs if we had some previous S3 images and later that subdomain settings were changed to use local. Now if I  change back to S3 then I am hitting above issue.

**Comment by owen2345** [comment]
@mazharoddin could you please send me a video or steps detailed to reproduce the problem?
PD: I tried many times to reproduce the problem but without success.
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345

**Comment by mazharoddin** [comment]
Hi @owen2345,
Please find below for the video with error while accessing media, which I could able to create on clean repository.
https://sendvid.com/yn94ko1b#
<img width="999" alt="screen shot 2016-09-06 at 10 12 14 pm" src="https://cloud.githubusercontent.com/assets/6102465/18282611/7c887aa4-747f-11e6-8c02-cb1b23da573e.png">

I checked in the changes to below repository. Thanks.
https://github.com/mazharoddin/camaleon_cms_debug

**Comment by mazharoddin** [comment]
Hi @owen2345, 
Please let me know if you could able to find out the issue.

**Comment by owen2345** [comment]
Hi @mazharoddin,
Sorry for the delay but I was too busy these days, the problem was because you have a file within multiple subfolders in AWS, like:
/foder1/folder2/folder3/my_file.jpg
I fixed the problem. please let me if it works well for you too.
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345 np, I will test and let you know ..thanks a lot.

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
Now I am not seeing that issue, Thanks for the fix, but now all subdomains  showing same images across the site, so all subdomains are showing root domian + other subdomains images ...so it creating privacy problem :(

**Comment by owen2345** [comment]
Hi @mazharoddin,
For now the AWS Uploader is waiting one bucket for each sub site.
Regards,

**Comment by mazharoddin** [comment]
ohh ok, but in hook we are specifying bucket name, since we wanted  these settings to applicable for all subdomain, so they are going to applicable for all sites, so we don't have any option to specify bucket name for each sub site. 

Pls do let me know we can specify bucket name for each subdomain, if its not possible, then the idea of sharing AWS settings across subdomain may not be useful, because each subdomain is different and they are owned by different users, so we may need to find a way use same bucket and store files by creating separate directory for each subdomain, or creating bucket for each subdomain during subdomain creation. what do you feel?.

```
args[:aws_settings] = {  region:     ENV["AWS_REGION"],
                             access_key: ENV["AWS_ACCESS_KEY_ID"],·
                             secret_key: ENV["AWS_SECRET_ACCESS_KEY"],·
                             bucket:     ENV["S3_BUCKET_NAME"],·
```

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
During my testing I observed that few subdomains have only images which I uploaded from subdomain have, but other subdomains are showing all images from the bucket, both are sharing same s3 config, so not sure why only few showing images to that specific subdomain uploaded images.

**Comment by owen2345** [comment]
Please try cleaning cache in media section to fetch again the files from aws.

**Comment by mazharoddin** [comment]
yeah I tried, but still it was showing all images for that subdomain,  I will do one thing, I will try create new bucket and try to assign it and test..thanks.

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
I tried with other bucket, but I am seeing same issue with new bucket aswell, bucket images are shown across the site, and any one can add or delete images from the bucket..since we are overriding S3 settings using hook, I am unable to add buckets specif to subdoman and there is a limitation with bucket names at S3 ..

**Comment by mazharoddin** [comment]
Hi @owen2345,
If possible can you please provide some sudo code on using single bucket across the subdomains, but restricting access to its own subdomain photos/ directories, I will try to implement it if possible.

**Comment by owen2345** [comment]
Hi @mazharoddin 
I added the support to manage your situation, sample:
```
def uploader_hook_for_aws(args)
  args[:aws_settings]['inner_folder'] = 'my_folder'
end
```
Please test using git version.
Regards,

**Comment by mazharoddin** [comment]
hi @own2345, 
wow really great, thanks, I will try it, but looks like the folder will be shared across all subdomains? but each subdomain images shoud't be visible to other subdomain since camaleon_cms is multi site...so will check if that works are not ..thank you so much for looking into it.

**Comment by mazharoddin** [comment]
@owen2345 , I tried to add new hook as you suggested, but its not working. Can you please check if you merged this code as I am unable to find any commit related to this.
Is its possible to create a folder whenever we create a subdomain and restrict access to that folder for that subdomain and later save all files related to that subdomain only in that folder. 
That way I think we can have different subdomain files in same bucket. What do you feel.

**Comment by owen2345** [comment]
Hi @mazharoddin ,
I am so sorry, my changed was not pushed to the master branch because there were conflicts.
Please try again:
https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L23
Regards,

**Comment by mazharoddin** [comment]
Sure, Thanks @owen2345

**Comment by mazharoddin** [comment]
Hi @owen2345,
Now images are uploaded to specified folder, but since we are overriding aws configuration using application helper, its applicable to all entire site, so now still all subdomains are able to access the images from 'my_folder', so still the actual issue persists, I think you can fix this issue by creating folders for each subdomain and restricting access to that folder based on subdomain...

**Comment by owen2345** [comment]
@mazharoddin did you put a custom name for each site? like:
```
{"inner_folder" => "my_folder_#{current_site.id}"}
```
By this way you are assigning an unique folder for each site.
Regards,

**Comment by mazharoddin** [comment]
Yeah @owen2345, now its working as expected, thanks a lot for the fix. I will close this issue after some more testing.

**Comment by choyno** [comment]
THANK YOU FOR THIS CHANGES
