### ISSUE TITLE
Translation doesn't work when setting menues

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#271]
Hi,
I created menues in  2 languages (fr, en) in external link.
The updated is ok, but when i launch frontend it doesn't work, or sometimes it's working for some menues but for all. No error, the translation doesn't work. 
Using camaleon_cms 2.0.5 from git://github.com/owen2345/camaleon-cms.git (at master)

Thank you

**Comment by owen2345** [comment]
It works well for me:
![screen shot 2016-01-07 at 6 15 16 am](https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png)
Video: http://screencast.com/t/LWWMt77m

**Comment by lmany** [comment]
Hello,

Thanks for all,

Question : How to change current language ?



2016-01-07 11:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:

> It works well for me:
> [image: screen shot 2016-01-07 at 6 15 16 am]
> <https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png>
> Video: http://screencast.com/t/LWWMt77m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/271#issuecomment-169620081>
> .
>



-- 
Léo MANY

**Comment by lmany** [comment]
Hello,

I have a big problem for deploying on heroku from my local website

The problem happens when i use my own theme. I want to use my own theme.

How can I solved this?





2016-01-10 12:59 GMT+01:00 Léo Many <leomany22@gmail.com>:

> Hello,
>
> Thanks for all,
>
> Question : How to change current language ?
>
>
>
> 2016-01-07 11:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:
>
>> It works well for me:
>> [image: screen shot 2016-01-07 at 6 15 16 am]
>> <https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png>
>> Video: http://screencast.com/t/LWWMt77m
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/owen2345/camaleon-cms/issues/271#issuecomment-169620081>
>> .
>>
>
>
>
> --
> Léo MANY
>



-- 
Léo MANY

**Comment by lmany** [comment]
Hello,

Its OK, due to version of git which have securty case

*/Users/many/.heroku/client/lib/heroku/jsplugin.rb:88: warning: Insecure
world writable dir /usr/local in PATH, mode 040777*

*Your version of git is 1.9.3. Which has serious security vulnerabilities.*

*More information here:
https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x
<https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x>*

Thks

2016-01-11 2:19 GMT+01:00 Léo Many <leomany22@gmail.com>:

> Hello,
>
> I have a big problem for deploying on heroku from my local website
>
> The problem happens when i use my own theme. I want to use my own theme.
>
> How can I solved this?
>
>
>
>
>
> 2016-01-10 12:59 GMT+01:00 Léo Many <leomany22@gmail.com>:
>
>> Hello,
>>
>> Thanks for all,
>>
>> Question : How to change current language ?
>>
>>
>>
>> 2016-01-07 11:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:
>>
>>> It works well for me:
>>> [image: screen shot 2016-01-07 at 6 15 16 am]
>>> <https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png>
>>> Video: http://screencast.com/t/LWWMt77m
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/owen2345/camaleon-cms/issues/271#issuecomment-169620081>
>>> .
>>>
>>
>>
>>
>> --
>> Léo MANY
>>
>
>
>
> --
> Léo MANY
>



-- 
Léo MANY

**Comment by owen2345** [comment]
great!
please let me know if you have more problems in heroku.
regards!

**Comment by lmany** [comment]
Hello,

Please let me know how to use other template then post_type.html.erb
template to render a post_type.

For example for page, i can use a template template_something.html.erb
rather than page.html.erb

Thanks

2016-01-07 11:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:

> It works well for me:
> [image: screen shot 2016-01-07 at 6 15 16 am]
> <https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png>
> Video: http://screencast.com/t/LWWMt77m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/271#issuecomment-169620081>
> .
>



-- 
Léo MANY

**Comment by lmany** [comment]
Hello,

It's OK for me.

Thanks

2016-02-12 12:03 GMT+01:00 Léo Many <leomany22@gmail.com>:

> Hello,
>
> Please let me know how to use other template then post_type.html.erb
> template to render a post_type.
>
> For example for page, i can use a template template_something.html.erb
> rather than page.html.erb
>
> Thanks
>
> 2016-01-07 11:18 GMT+01:00 Owen Peredo Diaz <notifications@github.com>:
>
>> It works well for me:
>> [image: screen shot 2016-01-07 at 6 15 16 am]
>> <https://cloud.githubusercontent.com/assets/1148415/12168070/6afea06c-b506-11e5-8d0a-5d44732357d8.png>
>> Video: http://screencast.com/t/LWWMt77m
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/owen2345/camaleon-cms/issues/271#issuecomment-169620081>
>> .
>>
>
>
>
> --
> Léo MANY
>



-- 
Léo MANY
