### ISSUE TITLE
NoMethodError in CamaleonCms::Admin::SessionsController#login_post

### ISSUE THREAD

**Issue by CBlaize** [owen2345/camaleon-cms#274]
undefined method `is_valid_email?' for #<CamaleonCms>

```ruby
     else
        match = match_attribute_method?(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end
```

I receive this error when attempting to login to the backend.

**Comment by owen2345** [comment]
please do:
rake db:migrate

**Comment by CBlaize** [comment]
Ah I see now.  The latest migration was supposed to add these columns in.  I must've messed something up because I have the correct versions in the schema_migrations table. And I can successfully run rake db:migrate.  However, the columns aren't added.

**Comment by owen2345** [comment]
this is the migration:
https://github.com/owen2345/camaleon-cms/blob/master/db/migrate/20151212095328_add_confirm_token_to_users.rb

**Comment by CBlaize** [comment]
I fixed it.

**Comment by owen2345** [comment]
great!
