### ISSUE TITLE
Custom Routes

### ISSUE THREAD

**Issue by CBlaize** [owen2345/camaleon-cms#275]
What made you decide to include the ID in the route?  Personally, I think it looks messy.

I was looking for something like this: 
/:category:title/:slug

http://localhost:3000/services/service.html looks much cleaner than,
http://localhost:3000/category/64-services/service.html

**Comment by owen2345** [comment]
Hi @CBlaize 
because that format is already reserved for:
```
"post_of_posttype" => "/:post_type_title/:slug  (Sample: http://localhost.com/services/myservice.html)"
```

please let me know if you have more ideas to add.

Below all current formats:
```
"post_of_post_type" => "/group/:post_type_id-:title/:slug  (Sample: http://localhost.com/group/17-services/myservice.html)",
      "post_of_category" => "/category/:category_id-:title/:slug  (Sample: http://localhost.com/category/17-services/myservice.html)",
      "post_of_category_post_type" => "/:post_type_title/category/:category_id-:title/:slug  (Sample: http://localhost.com/services/category/17-services/myservice.html)",
      "post_of_posttype" => "/:post_type_title/:slug  (Sample: http://localhost.com/services/myservice.html)",
      "post" => "/:slug  (Sample: http://localhost.com/myservice.html)"
```

**Comment by CBlaize** [comment]
All I really want is to specify a parent page.

![parent-pages](https://cloud.githubusercontent.com/assets/6540262/12158119/945493d2-b49c-11e5-8c80-152a0891a74f.png)

**Comment by owen2345** [comment]
This functionality is not done yet. In future versions will be added.

**Comment by CBlaize** [comment]
Awesome! Sounds good.

**Comment by owen2345** [comment]
@CBlaize done!
Please use master branch.
![camaleon-page-hierarchy-options](https://cloud.githubusercontent.com/assets/1148415/12377309/b6b628e0-bcef-11e5-8343-b417d8ceb208.png)
![camaleon-page-hierarchy](https://cloud.githubusercontent.com/assets/1148415/12377310/b6b7c90c-bcef-11e5-8f4c-2e8f0a21cc94.png)
![camaleon-page-hierarchy-setting](https://cloud.githubusercontent.com/assets/1148415/12377311/b6bba518-bcef-11e5-9972-d64b431ceea7.png)

**Comment by CBlaize** [comment]
Thanks!
