### ISSUE TITLE
Shortcode don't have post's content

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#277]
I can not find any where to get content of the post by shortcode. Do you have that option?

**Comment by owen2345** [comment]
If you do:
```
my_post.the_content()
```
this already getting the translation for current language and executing theshortcodes.

If you would like to execute a shortcode in code, you can do it:
```
do_shortcode(my_string_with_shortcodes, params = {})
```

I created this video:
https://youtu.be/jIp0w5BtpHI
please let me know if it is enough.
