### ISSUE TITLE
Theme views aren't added to the view path

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#278]
Receiving a missing template error when overriding templates inside of theme hooks. Had to use path to the theme for it to work.

```
themes/my_theme/views/my_template.erb
```

**Comment by owen2345** [comment]
@cmckni3 
how and where are calling this?

**Comment by CBlaize** [comment]
@owen2345 Same issue.

```ruby
app/apps/themes/theme/main_helper.rb

def theme_on_render_post(params)
    if params[:layout] == 'index'
      params[:layout] = 'themes/theme/views/layouts/1-column'
    end
end
```

I have to specify 'themes/theme/views/' because Theme views were missing from the view path - v2.1.0

**Comment by owen2345** [comment]
@cmckni3 
Please see my test in the screenshots:
![screen shot 2016-01-06 at 8 27 27 pm](https://cloud.githubusercontent.com/assets/1148415/12158862/31152d32-b4b4-11e5-940b-26b5fa11027c.png)

![screen shot 2016-01-06 at 8 28 18 pm](https://cloud.githubusercontent.com/assets/1148415/12158861/31108e12-b4b4-11e5-8cb7-5ee1b133d50f.png)

**Comment by cmckni3** [comment]
Appears to be fixed
