### ISSUE TITLE
undefined method `the_thumb_url' error if I click on user created tag

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#279]
Hi,
I am getting undefined method `the_thumb_url' error if I click on user created tag on article/product post.
Here is the exception.
````
undefined method `the_thumb_url' for #<CamaleonCms::PostTagDecorator:0x007fbc485b46e8>

    # Delegates missing instance methods to the source object.
    def method_missing(method, *args, &block)
      return super unless delegatable?(method)

      self.class.delegate method
      send(method, *args, &block)

draper (1.4.0) lib/draper/automatic_delegation.rb:7:in `method_missing'
camaleon_cms (2.1.0) app/helpers/camaleon_cms/frontend/seo_helper.rb:24:in `cama_the_seo'
camaleon_cms (2.1.0) app/helpers/camaleon_cms/frontend/site_helper.rb:71:in `the_head'
camaleon_cms (2.1.0) app/apps/themes/camaleon_first/views/layouts/index.html.erb:14:in 
````
I am using camaleon_cms version 2.1

**Comment by owen2345** [comment]
Hi,
PostTag doesn't support for thumbs, if you need thumbs or other attributes you can use the custom fields for PostTags.
![screen shot 2016-01-07 at 5 36 28 am](https://cloud.githubusercontent.com/assets/1148415/12167235/5d0f5e2e-b501-11e5-995e-06895b321366.png)
![screen shot 2016-01-07 at 5 35 51 am](https://cloud.githubusercontent.com/assets/1148415/12167236/5d1198c4-b501-11e5-8c55-848e26946399.png)

**Comment by mazharoddin** [comment]
No, I am not using postTag for thumbs, I just created a post and added tag to that post,  i am getting above exception if I click on tag.

**Comment by owen2345** [comment]
fixed!

**Comment by mazharoddin** [comment]
Thank you :)

**Comment by mazharoddin** [comment]
Working with latest code, hence closing this issue. Thanks for the fix.
