### ISSUE TITLE
How to let users create subdomains 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#281]
Hi,
Can you please let me know how to let users create subdomains by providing email address and subdomain name, that way I feel subdomain sites creation will be easy for main site owner and he can manage them easily from admin page if required.
I believe you are already doing this using demo plugin, can you please share code if its possible.

**Comment by owen2345** [comment]
Hi @mazharoddin 
I created a plugin to receive the request and then create the demo, please check the screenshot of the code:
![screen shot 2016-01-07 at 12 56 54 pm](https://cloud.githubusercontent.com/assets/1148415/12176529/2527c4f0-b53e-11e5-8dda-d5317bfaca4c.png)

**Comment by mazharoddin** [comment]
Thank you...

**Comment by mazharoddin** [comment]
I could able to let users create subdomains by providing slug and name by using your plugin code, thanks for sharing it.
