### ISSUE TITLE
Just FYI, your documentation site is down`

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#282]
The documentation site is down with an application error, just FYI.

**Comment by mazharoddin** [comment]
Hi, I am able to access the documentation site without any issue. 
http://camaleon.tuzitio.com/group/40747-documentation.html

**Comment by owen2345** [comment]
thanks for the info.

**Comment by williamrussellajb** [comment]
Thanks @mazharoddin , It's working for me too now. -- closing.
