### ISSUE TITLE
Allow users to create categories on post creation page

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#283]
Hi, 
I feel its better to allow users to create categories on post creation page before submitting the post if they didn't add category using category, otherwise its bit confusing to go back to category menu if user forgot to add the category, so it would be great if you can provide category create option using Ajax before submitting  post.
<img width="246" alt="screen shot 2016-01-08 at 22 06 09" src="https://cloud.githubusercontent.com/assets/6102465/12203319/52f1b438-b654-11e5-9f56-8766fb80e76d.png">

**Comment by owen2345** [comment]
great! I will work for it.

**Comment by mazharoddin** [comment]
Thank you :)

**Comment by owen2345** [comment]
done!
please review using the master branch.

**Comment by mazharoddin** [comment]
Hi, 
Its working, thank you.
<img width="277" alt="screen shot 2016-01-11 at 12 15 15" src="https://cloud.githubusercontent.com/assets/6102465/12228131/25a1030c-b85d-11e5-95d1-1561dd814023.png">
