### ISSUE TITLE
Can't apply font to custom theme

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [owen2345/camaleon-cms#284]
Hello.

When I generate my custom theme, camaleon-cms will create `index.html.erb` file in layouts folder. Then in this file I add this in `<head>` part:

        
      <link href='http://fonts.googleapis.com/css?family=Exo+2&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

When I do this in simple HTML page it works. However, when I apply this link into layout file, it ignores it and still uses default fonts.

How to apply custom fonts?

**Comment by owen2345** [comment]
Hi @SuperMasterBlasterLaser 
have you solved this problem?

**Comment by SuperMasterBlasterLaser** [comment]
Yes, I have created custom `css` file and added this line of code:

      * {
           font-family: 'Exo 2', sans-serif;
         }

It will apply to all html elements this font
