### ISSUE TITLE
New user role for basic info, theme setting and Contact Response

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#285]
I want user to be able to access the Basic infomation, Theme Setting and Contact Response but still restrict user from the settings section. How do I suppose to do that?

**Comment by owen2345** [comment]
Hi @Uysim actually it is not possible.

**Comment by Uysim** [comment]
@owen2345 it is possible I already do that.

**Comment by owen2345** [comment]
great!

**Comment by Uysim** [comment]
I hope you have add user permission for this before close it
