### ISSUE TITLE
Internal Server Error while trying to upload image on post

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#287]
Hi,
I am getting Internal Server Error while trying to upload image for one of the post, it was working fine earlier, but today I pulled latest changes from camaleon_cms repository, not sure if latest changes are cuasing problem, but now I am getting this error if I try to upload image.
Here is the exception.
````
D, [2016-01-11T13:25:12.085797 #24624] DEBUG -- :    (0.7ms)  COMMIT
I, [2016-01-11T13:25:12.087198 #24624]  INFO -- : Completed 500 Internal Server Error in 734ms (ActiveRecord: 4.5ms)
F, [2016-01-11T13:25:12.089136 #24624] FATAL -- : 
NoMethodError (undefined method `upload_directory_name' for #<CamaleonCms::SiteDecorator:0x0055af8fe8b1a8>):
  draper (1.4.0) lib/draper/automatic_delegation.rb:7:in `method_missing'
  /bundler/gems/camaleon-cms-d87fcb569efe/app/helpers/camaleon_cms/uploader_helper.rb:168:in `cama_media_find_folder'
  /bundler/gems/camaleon-cms-d87fcb569efe/app/controllers/camaleon_cms/admin/media_controller.rb:80:in `init_media_vars'
  activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `block in halting'
````

**Comment by mazharoddin** [comment]
This issue occurring due to my local changes, modified relevant code. Hence closing the issue. Thanks.

**Comment by owen2345** [comment]
yes, someone suggested to have a place where to change the upload directory name:
use site.slug instead of site.id like actually.
regards,

**Comment by mazharoddin** [comment]
Sure, I will change as you suggested if required, but for now I am using as it is. Thanks.
