### ISSUE TITLE
Allow users to use disqus comments

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#288]
Hi,
I feel it would be good if we allow users to choose disqus comments for posts or other content types on their subdomains, because disqus allows easy moderation and its very much useful in social engagement.
Thanks.

**Comment by owen2345** [comment]
it is easy!
you can do it by adding the disqus shortcode in your desired template like this (my_theme/views/single.html.erb):
```
<div class="blog">
    <div class="container">
        <!-- Left Section Start -->
        <%= render partial: 'partials/breadcrumb', locals: {breadcrumb: @post.the_breadcrumb } %>
        <div class="row">
            <div class="col-md-12">
                <h3><%= @post.the_title %><%= @post.the_edit_link %></h3>
                <div class="post-detail"><%= raw @post.the_content %></div>
                <div id="disqus_thread"></div>
                <script>
                     var disqus_config = function () {
                     this.page.url = "<%= @post.the_url %>"; // Replace PAGE_URL with your page's canonical URL variable
                     this.page.identifier = "<%= @post.id %>"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                     };
                    (function() { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = '//camaleon-cms.disqus.com/embed.js';

                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
                <a href="http://example.com/bar.html#disqus_thread">Link</a>
                <script id="dsq-count-scr" src="//camaleon-cms.disqus.com/count.js" async></script>
            </div>
        </div>
    </div>
</div>
```

**Comment by mazharoddin** [comment]
Hi,
Thanks for the code, but actually I meant providing  configuration option to set the disqus short name and other disqus attributes using site settings menu or using plugin.
Yes, we can edit the template file to use disqus, but if suppose users on subdomain wanted to use their disqus code then they can't do that because,  we  are already setting disqus code using template, so it will be available sitewide for that post type, but subdomain users may wanted to use their own disqus shortcode on their subdomain. So it would be good if you can provide some option to set their own disqus shortname using general settings or create a plugin to enable disqus on their subdomain. 
This can be considered as low priority work item, but I feel it would be helpful for subdomain users. Thanks

**Comment by owen2345** [comment]
I will create a small plugin for this, please send me the common requirements to do.

**Comment by mazharoddin** [comment]
Sure, I will do it, thanks for your support :+1:

**Comment by mazharoddin** [comment]
Hi Owen,
Find below for few requirements  I thought for disqus plugin,
1) Since we already have comments section in menu navigation, show disqus settings under that menu if user activates the plugin.
<img width="286" alt="screen shot 2016-01-14 at 11 09 55" src="https://cloud.githubusercontent.com/assets/6102465/12316664/60e32b8a-baaf-11e5-9c80-b2ccc668a993.png">
2) For now you can provide only basic options like setting up the disqus shortname.
3) Selecting which post type user wanted to enable discuss( post, product or custom post type etc).
Attaching drupal disqus settings page for reference.
<img width="435" alt="screen shot 2016-01-14 at 11 12 29" src="https://cloud.githubusercontent.com/assets/6102465/12316704/c81e7e30-baaf-11e5-83c4-254dfb8c6017.png">
4) Display disqus comments in comments section for end user.
![screenshot-1](https://cloud.githubusercontent.com/assets/6102465/12316831/f74707f8-bab0-11e5-9173-ca283b62bafa.png)

5) If time permits provide disqus moderation window along with usual comments in admin menu.
![screenshot-3](https://cloud.githubusercontent.com/assets/6102465/12316806/cc217e5a-bab0-11e5-8103-be1e05f70ed3.png)
6) These options should be good enough to start, I feel single sign-on or providing API details etc can be developed later.

**Comment by williamrussellajb** [comment]
I'd love this!

Im using facebook, but I'd rather have discuss.
