### ISSUE TITLE
Editor and Contributor user roles are cleared when adding a new Post Type

### ISSUE THREAD

**Issue by jheilema-nerdery** [owen2345/camaleon-cms#289]
If I add a new custom post type, and then visit the User Roles screen, the Editor and Contributor user role permissions are cleared *except* the new Post type.

![Screen shot of the contributor role after creating a new custom post type](https://www.dropbox.com/s/0mm958o0248n06q/Screenshot%202016-01-12%2010.52.12.png?raw=1)

The relevant portion of my Gemfile.lock:

    camaleon_cms (2.1.1)
      aws-sdk (~> 2)
      bcrypt
      breadcrumbs_on_rails
      cancancan (~> 1.10)
      draper (~> 1.3)
      fog (~> 1.34)
      font-awesome-rails
      meta-tags (~> 2.0)
      mini_magick
      mobu
      protected_attributes
      will_paginate
      will_paginate-bootstrap

**Comment by mazharoddin** [comment]
Yes, even I observed same behavior. Thanks.
<img width="765" alt="screen shot 2016-01-13 at 12 01 12" src="https://cloud.githubusercontent.com/assets/6102465/12286795/5f5f0f1c-b9ed-11e5-806a-c96e53ef3818.png">

**Comment by owen2345** [comment]
Fixed!
please try with master branch.

**Comment by mazharoddin** [comment]
I pulled latest changes, I am getting below error now if I try to access base domain.
````
undefined method `get_languages' for nil:NilClass

      else
        options[:locale] = I18n.locale if !options[:locale].present? && current_site.get_languages.size > 1
      end
      options[:locale] = nil if options[:locale].present? && current_site.get_languages.first.to_s == options[:locale].to_s
    end

/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-20aad238a3fb/app/helpers/camaleon_cms/frontend/application_helper.rb:33:in `cama_url_to_fixed'
draper (1.4.0) lib/draper/helper_proxy.rb:29:in `block in define_proxy'
/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-20aad238a3fb/app/decorators/camaleon_cms/site_decorator.rb:162:in `the_url'
/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-20aad238a3fb/app/helpers/camaleon_cms/site_helper.rb:30:in `cama_site_check_existence'

````
I was getting similar error with your earlier subdomain fix, but that time this used occur if I try to create second subdomain, but now site is inaccessible on main domain itself. Thanks

**Comment by owen2345** [comment]
https://github.com/owen2345/camaleon-cms/issues/286#issuecomment-171255381

**Comment by mazharoddin** [comment]
Yes issue #286 got fixed, but still issue #289 persists with latest changes. Thanks.

**Comment by jheilema-nerdery** [comment]
Thanks Owen, it works great now!

Also thanks for building this excellent product! You're doing a fabulous job!

**Comment by owen2345** [comment]
great, and thank you!
please don't forget to share by social networks and invite others, I am a little bad spreading.
