### ISSUE TITLE
Multiple Domain Needed

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#290]
I need multiple domain per site. Can you implement that ?

Thank before hand

**Comment by owen2345** [comment]
@Uysim 
Please try this:
- create an initializer in your project and add a method: cama_current_site_helper(args)
- args is a Hash{site, request}
- samples:
def cama_current_site_helper(args)
  args[:site] = Cama::Site.order(id: :asc).last.decorate
  # args[:site] = Cama::Site.find(10).last.decorate if args[:request].original_url.to_s.parse_domain == "my_domain.com"
  # args[:site] = Cama::Site.find_by_slug('my_domain_x').decorate if args[:request].original_url.to_s.parse_domain == "my_domain_xx"
end

**Comment by owen2345** [comment]
Note: use master branch please.

**Comment by rubyjedi** [comment]
This is a great tip, thanks! Definitely belongs in the Wiki. :-)
