### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#3]
How would a site running camaleon be upgraded to the latest release of camaleon?

It seems like it would a tedious task to upgrade a site to the latest release since camaleon isn't a Rails engine or gem.

**Comment by owen2345** [comment]
Hello Chris,
I am working to move into engine!

**Comment by cmckni3** [comment]
Awesome!

**Comment by owen2345** [comment]
95% converted into engine!

**Comment by cmckni3** [comment]
:+1:

**Comment by owen2345** [comment]
Gem version here:
https://github.com/owen2345/camaleon-cms-gem
It is in testing...
