### ISSUE TITLE
No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by aksilme** [owen2345/camaleon-cms#30]
Hi;

i'm getting this error just after putting site name
 No such file or directory @ rb_sysopen   camaleon-cms/app/apps/../../config/system.json

  # value: new value for attribute
  def self.system_info_set(key, val)
    ff = File.read(File.join(apps_dir, "..", '..', "config", "system.json"))
    File.open(File.join(apps_dir, "..", '..', "config", "system.json"), "w") do |f|
      f.write(ff.sub(/"#{key}": ?\"(.*)\"/, "\"#{key}\": \"#{val}\""))
    end

**Comment by owen2345** [comment]
fixed!
