### ISSUE TITLE
CMS demo is broken 

### ISSUE THREAD

**Issue by evandrojr** [owen2345/camaleon-cms#306]

**Comment by owen2345** [comment]
Could you please tell me what is the problem?

**Comment by evandrojr** [comment]
The link for Admin and frontend was not working. It gave me an incomplete URL. It is fine now. Thanks! Sorry for the simplified bug report.

**Comment by owen2345** [comment]
Don't worry, it is a memory problem of my server, because every day is created at least 100 demo sites (my server is small and cheaper hehe!).
