### ISSUE TITLE
nav-menu custom fields 500 error

### ISSUE THREAD

**Issue by CBlaize** [owen2345/camaleon-cms#307]
Hi,

I'm current running 2.1.1.  When I click the cog-icon next to a nav-menu item to edit the settings, a blue spinner shows up and stays.

```
GET http://localhost:3000/admin/appearances/nav_menus/form?menu_id=8&custom_fields=true 500 (Internal Server Error)
```

```
 FATAL -- :
ActionView::Template::Error (Missing partial camaleon_cms/admin/appearances/nav_menus/camaleon_cms/camaleon_cms/admin/settings/custom_fields/_render, camaleon_cms/admin/camaleon_cms/camaleon_cms/admin/settings/custom_fields/_render, camaleon_cms/camaleon/camaleon_cms/camaleon_cms/admin/settings/custom_fields/_render, application/camaleon_cms/camaleon_cms/admin/settings/custom_fields/_render, /camaleon_cms/camaleon_cms/admin/settings/custom_fields/_render with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :jbuilder]}.
```

![cama-1](https://cloud.githubusercontent.com/assets/6540262/12485969/23e1d64c-c026-11e5-97c9-b1d204aea531.png)

Was this functionality removed or do I just need to fix something that broke with the 2.0 update? Thanks!

**Comment by CBlaize** [comment]
Another bigger problem.  I created a custom field for a menu item that had a text field.  I edited my menu items.  Then, my custom field no longer exists.  I got back to settings -> custom fields, and my custom field is gone.

**Comment by owen2345** [comment]
partial fixed!
Please test using the github version.
TODO: translation support.

**Comment by owen2345** [comment]
Current master Branch solve all the problems
