### ISSUE TITLE
Changing theme reverting back footer info

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#309]
Hi,
I am using camaleon_first theme as default theme, I updated footer content after activating the theme,  but if I am changing theme to some other theme and reverting back to camaleon_first theme reverting footer content to initial content(default content). 
Due to this the information I updated in footer getting removed every time if I switch  theme.

**Comment by owen2345** [comment]
Hi @mazharoddin 
yes it is, because the old theme is cleaning its custom information that is not necessary for other themes and avoid garbage.
You can change this in the method executed after theme inactive

Regards,

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
Thanks for the answer, however I feel its better to keep old theme info some where stored, otherwise its would difficult for user to update it whenever he changes the theme.

**Comment by owen2345** [comment]
Hi @mazharoddin 
I think the better solution should add an extra button (update | upgrade or reload) which call in a method of theme to add extra functionality. Remember: each installation of theme create several posttypes, settings, menus, needed. So, this info can be duplicated.
What do you think?

**Comment by mazharoddin** [comment]
Hi @owen2345,
Yeah, your solution sounds good, but I feel it would be better we keep each theme configuration specific to that theme, that way each theme can be activated or de-activated as needed, and theme specific data can be retained, so that user no need to re-enter that info again and again. 
I feel its better we create separate menu to customize themes similar to wordpress, otherwise managing theme specific options and data will become tough if we add more themes.
![screen shot 2016-02-09 at 17 46 55](https://cloud.githubusercontent.com/assets/6102465/12916015/2f816ef2-cf55-11e5-87e3-ffedeeb9dac7.png)

**Comment by owen2345** [comment]
you are right!
working in it!

**Comment by mazharoddin** [comment]
Thank you...

**Comment by mazharoddin** [comment]
Hi @owen2345, 
please let me know if you got chance to work on this..it may be helpful feature..

**Comment by owen2345** [comment]
This is possible by:
- Comment the line where you are destroying the theme after uninstall
Note: By default camaleon doesn't destroy the theme after uninstall, you need to add like this in your hook for uninstall:
```
theme.destroy
```

**Comment by mazharoddin** [comment]
Ok, Thanks.
Also did you got chance to work on adding customization menu to themes, so that themes can be customized.
