### ISSUE TITLE
Opening category page gives page not found error

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [owen2345/camaleon-cms#311]
Hello.

I have created category and called it `Блог` and it has slug named `blog`. Then I have created Post which belongs to this category. I have included this category to Menu.

When I click on `Блог` link in my menu it says to me that page does not exist. Why? I thought it will be showing all posts which belong to this category.

**Comment by owen2345** [comment]
Hi @SuperMasterBlasterLaser 
could you please send your db.sqlite to see the error?
I cannot reproduce the error.

Regards,

**Comment by SuperMasterBlasterLaser** [comment]
I have sent database to your Gmail

**Comment by SuperMasterBlasterLaser** [comment]
When I try to open page of this category, It creates that kind of link:

      http://localhost:3000/category/34-

**Comment by SuperMasterBlasterLaser** [comment]
This is still happening. Adding category to menu and then I try to open it, it gives page not found page.

**Comment by dusu** [comment]
I have the same question, I'm sure that your category name must be non-ASCII characters,if you change it to ASCII characters, it works fine.

**Comment by SuperMasterBlasterLaser** [comment]
@dusu But `slug` is ASCII. When I write `Блог` it creates `blog` slug. However, when I try to open category itself it tries to open it wih this link:

       http://localhost:3000/category/34-

I think it is trying to open category by id. But route is wrong.

**Comment by dusu** [comment]
@SuperMasterBlasterLaser I tried to type name or slug after `/category/34-` manually and visit it, it worked. It seems like it going wrong only when it trying to generate the url, also it use name not slug to generate the url.

**Comment by SuperMasterBlasterLaser** [comment]
@dusu the problem is on generating url in templates. I hope there will be fixes.

**Comment by dusu** [comment]
@SuperMasterBlasterLaser me too.

**Comment by owen2345** [comment]
Fixed! the problem was the_title.parameterize which return empty for non ascii chars.
To test, please use git version.

**Comment by SuperMasterBlasterLaser** [comment]
@owen2345  :+1:
