### ISSUE TITLE
Media manager: can't delete items

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#312]
Using camaleon-cms revision 73888bdd249c42b082f36acc5eb815793f43e31e (latest).
Media is configured to use S3.

When anywhere but in the root media folder, there is no way to delete images (or folders), hovering over the items just shows the name badge but no trash can like it should:

![admin panel dashboard media](https://cloud.githubusercontent.com/assets/71108/12552457/3381fca4-c372-11e5-9189-2d602e3f21f2.png)

**Comment by owen2345** [comment]
@momolog Fixed!

**Comment by momolog** [comment]
Indeed. Thanks!
