### ISSUE TITLE
Media manager "shadow" items

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#313]
Using camaleon-cms revision 73888bdd249c42b082f36acc5eb815793f43e31e (latest).
Media is configured to use S3.

When creating folders, the media manager shows an additional item with the folder name that can't be deleted (see https://github.com/owen2345/camaleon-cms/issues/312) and is pretty confusing:

![admin panel dashboard media-1](https://cloud.githubusercontent.com/assets/71108/12552531/b27b9484-c372-11e5-8af5-fd63f84ccd74.png)

I presume this is created as a place holder when the "folder" is initially created because of the way S3 works. It should be deleted when the folder actually contains items, because these items will implicitly carry the folder information.

**Comment by owen2345** [comment]
fixed!

**Comment by momolog** [comment]
Nice!
