### ISSUE TITLE
Commit "changed datetimepickerr" breaks creating posts. ref =>55dfe78906c59df3cb873a8e684f14cfef1b9a56

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#315]
commit changed datetimepicker breaks the form for creating/updating posts.

With the latest commit (or after dateTimePicker) navigate to:
http://localhost:3000/admin/post_type/60/posts/new

Notice, all custom attributes, and "content" are broken. 
You'll be unable to create a new post since it will complain that the slug is missing.

let me know if you need screenshots

**Comment by owen2345** [comment]
@williamrussellajb 
sorry for my error, I fixed the problem. Please let me know if you have more errors.
Regards,
