### ISSUE TITLE
File format not allowed

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#317]
using revision 118cb7a159894651dd0397439c06d183c64f65a4
and S3 as storage.

when trying to upload normal media files like jpgs we now consistently get the error "File format not allowed ()":

![screen](https://cloud.githubusercontent.com/assets/71108/12599559/30ea201c-c493-11e5-98cd-f2c4e8a7400a.png)

**Comment by owen2345** [comment]
Hi @momolog 
I will review this weekend, I am waiting for a new aws test account.
Regards,

**Comment by owen2345** [comment]
fixed!
I forget to add .present? in a sentence.

**Comment by momolog** [comment]
Thanks a lot.
