### ISSUE TITLE
Add Custom field

### ISSUE THREAD

**Issue by Seaborg** [owen2345/camaleon-cms#319]
Hi, Just started using Camaleon-CMS so far I like it but there's very little documentation, i.e. how can I add a custom field?

**Comment by CBlaize** [comment]
In the backend.  Go to Settings -> Custom Fields.  

I've found some issues with Custom Fields for the Menu.  I'm working on getting those fixed.

**Comment by Seaborg** [comment]
Thanks. Haven't reached to menus just yet, but I need to create a Custom Group of Fields 
Multiple Links with Labels so I can have a list, current url field doesn't have a Label.

tried to open helper like so:
CamaleonCms::Admin::CustomFieldsHelper.class_eval do
  def cf_get_items
    items = {}

    items[:link] = {
      key: 'link',
      label: 'Link',
      options: {
        required: true,
        multiple: true,
        translate: true,
        default_value: true,
        show_frontend: true
      },
      extra_fields:[
        {
          type: 'url',
          key: 'url',
          label: 'Link Url',
        }
      ]
    }

and then created a view in:
/app/views/camaleon_cms/admin/settings/custom_fields/fields/_link.html.erb

but not sure what's preferred way, don't want to have a bug after the future Camaleon upgrades. It would be super useful if you could create a groups of given fields, i.e. group of URL + TEXT BOX + TEXT AREA, I appreciate your work.

**Comment by owen2345** [comment]
Fixed custom field problems for menus! now all fields works well for menus and also added a new function for advanced menus:
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/frontend/nav_menu_helper.rb#L119
