### ISSUE TITLE
"Slug can't be blank" when creating page

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#323]
Using camaleon_cms bfd9b6c9fe2ab3def3747c4d1574555f8b545509 (latest).

When creating a new page, I consistently get the error "Slug can't be blank":

![dhbdiaaa](https://cloud.githubusercontent.com/assets/71108/12765112/48284ac8-c9fd-11e5-8b95-3f6543bfcac1.png)

At the same time the permalink edit field is gone completely:

![ebbcfcge](https://cloud.githubusercontent.com/assets/71108/12765126/61311a68-c9fd-11e5-85a3-395fe8960bb3.png)

This is how it used to look: 

![mail-anhang](https://cloud.githubusercontent.com/assets/71108/12765136/6fb036dc-c9fd-11e5-8a77-6bc08abe764a.png)

I assume the permalink is the slug for pages so these two things are related.

**Comment by owen2345** [comment]
Fixed!
I am sorry, it was my error.

**Comment by momolog** [comment]
Thanks! Unfortunately I am getting a different slug error now:

```
1 Error so their data has not been saved:
Requires different slug:
```

<img width="1592" alt="admin panel projekt new" src="https://cloud.githubusercontent.com/assets/71108/12866348/3f7eaa40-cccb-11e5-9840-4893affe53e8.png">

**Comment by owen2345** [comment]
@momolog 
please try to edit your slug, maybe it is already in use.
Check my video testing.
http://screencast.com/t/VembrlT2

**Comment by momolog** [comment]
Nope:
<img width="1644" alt="admin panel projekt new-1" src="https://cloud.githubusercontent.com/assets/71108/12868181/4ef408f4-cd01-11e5-951a-ea08ae3d089f.png">
I am on aa5e7ffab6d0231652484fcde8c71a07cff5db98

**Comment by momolog** [comment]
Any news on this? I cannot save any new page due to this error, even if I specify completely random unique slugs.

**Comment by momolog** [comment]
Alright. This just means, that I did not provide unique slugs **in all available languages**.
I would still argue strongly that the error message is misleading and insufficient.

Should I open a new ticket for this?

**Comment by owen2345** [comment]
Hi @momolog 
is not possible to have the same slug in all pages for any language, because the url's come like this:
```
http://localhost/my-slug.html
```
and my-slug must be unique to avoid problems with other pages.
and about your screenshot, please contact me this weekend by skype to review the error, because I can not reproduce the problem in my local or create a repository with the error.

Regards,

**Comment by momolog** [comment]
@owen2345 actually I experienced the URLs to look like this:
```
http://localhost/my-de-slug.html     # default language (de), no locale in URL
http://localhost/en/my-en-slug.html     # english
http://localhost/en/my-fr-slug.html     # french
```
which makes perfect sense.
But if I fail to **provide** the english and/or french title (and therefore slug), I get the above shown error.
It makes sense to get an error, because then the slug for this page is `''`  in the two languages.

It's just the *error message* that is very confusing. It is generated in `app/models/camaleon_cms/post.rb:18`

**Comment by owen2345** [comment]
@momolog 
I fixed the problem, those fields are required.

**Comment by owen2345** [comment]
I think you have a javascript error, please review your console log
