### ISSUE TITLE
Feature: Role management limited to site

### ISSUE THREAD

**Issue by Austio** [owen2345/camaleon-cms#325]
Have a situation where it would be beneficial to have permissions scoped to a site.  If there is support for this I would be happy to make the code contribution. 

Basic would be you would have a global admin, and then all of the other roles would be able to be limited to specific sites.   Someone would be able to be the admin of just one site but would have no knowledge of the others.  

May have missed this when i was source diving, so if it already exists let me know

**Comment by owen2345** [comment]
Hi @Austio 
Please do ti!
Actually it doesn't exist, only the administrator of main site can create sub sites, create roles, etc..
