### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by Seaborg** [owen2345/camaleon-cms#329]
Hi,

I believe this must've been brought up but I couldn't find it nor figure out how to do it.
How can I read the values from custom fields. Just created Custom Fields Group like so:
with the slug: _custom-home-page

site is multilingual and now I'd like to pull data from the Content Home Page, i.e.
[data field='welcome-text' object='post' id='3']

I've tried:
<%= post.get_field("welcome-text'") %>
with no luck, site is multilingual, can you please provide me with sample and how to pull data from
custom fields? Also how can do I render data for different languages?

**Comment by owen2345** [comment]
please check this video:
https://youtu.be/PVyXMX2WI6Y

**Comment by Seaborg** [comment]
Thanks Owen, that's very helpful. I think it would make sense to put that somewhere in documentation if it's not already there. Great job BTW. I can see massive potential in your CMS.

**Comment by owen2345** [comment]
Unfortunately I don't have time to create the documentation these days.
But, Please share the CMS and the vide by social networks.
