### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#330]
In the search content if I put ' into the search bar for example "year's" the website fail.

![error](https://cloud.githubusercontent.com/assets/2389019/12946717/6343a6f8-cfee-11e5-917a-dead2cc10415.png)

![request](https://cloud.githubusercontent.com/assets/2389019/12946723/6b4d6730-cfee-11e5-8f2c-d698603f5e58.png)

I think that the problem is here: https://github.com/owen2345/camaleon-cms/blob/master/app/controllers/camaleon_cms/admin/posts_controller.rb#L37

Maybe with gsub changing the word year's to year\'s...

Regards.

**Comment by owen2345** [comment]
Fixed!

**Comment by raulanatol** [comment]
Works fine!
Thx!

I have created https://github.com/owen2345/camaleon-cms/pull/333 to remove a test log ;)
