### ISSUE TITLE
Please Deploy to ruby gem frequently

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#335]
I hope you can deploy to ruby gem frequently. It allow me to  get the last version of your gem

**Comment by cmckni3** [comment]
Yeah this would be very helpful. Seems like project development is slowing down though.

**Comment by owen2345** [comment]
I am sorry friends, I am too busy these days January until March, because I am solving personal problems.
These days I  will review all the project and if it is ok, I will generate the new version.
