### ISSUE TITLE
Method_missing sender

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#336]
Hi!

I got the error method_missing
Exiting gems/actionmailer-4.2.4/lib/action_mailer/base.rb:569:in `method_missing': undefined method `sender' for CamaleonCms::HtmlMailer:Class (NoMethodError)
	from gems/camaleon_cms-2.1.1.3/app/helpers/camaleon_cms/email_helper.rb:16:in `block in send_email'

I think that is a problem using Threads and hooks.
If I change the value of the line: 
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/email_helper.rb#L13 and I put the abort_on_exception=false the emails is sent correctly.

Regards.

**Comment by owen2345** [comment]
Hi @raulanatol 
yes, it is the problem.
I was thinking to move the hook to helper from mailer class.
what do you think?

**Comment by raulanatol** [comment]
Yes it's a good idea.
