### ISSUE TITLE
How can I have grid editor

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#340]
I see in your gallery you have grid editor. How can I have that grid editor

**Comment by owen2345** [comment]
@Uysim 
it is a paid plugin, the link to buy the plugin is here:
http://camaleon.tuzitio.com/store/plugins/camaleon_editor

**Comment by mazharoddin** [comment]
@owen2345 ,
If possible can you please record your screen while using this editor, it would be helpful to understand this plugin usage.

**Comment by mazharoddin** [comment]
I played with this plugin in demo site, its nice...I missed to read  this in plugin installation instructions.
