### ISSUE TITLE
Excessive memory consumption problem

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#343]
Hi!

I've discovered that when I have a lot of images on S3 If a go to .../admin/media the usage increase a lot. Even can to block the server down.

![memory_usage](https://cloud.githubusercontent.com/assets/2389019/13296561/0e38170a-db26-11e5-8813-445b13afb003.png)

Regards.

**Comment by raulanatol** [comment]
Hi @owen2345

I've created a new branch (https://github.com/raulanatol/camaleon-cms/tree/s3_memory_leak) to work in this bug.

I've created a cache system to limit the number of requests to S3. This help to reduce the memory consumption. 

This not is the final solution but it's a first step.

Regards.

**Comment by owen2345** [comment]
@raulanatol That is a serious problem.
I was thinking to manage this by database and adding a button to retrieve the files structure and not every time.

**Comment by raulanatol** [comment]
@owen2345 
I'm working in a cache system to improve this.
This week I will create a new PR.
Regards.
