### ISSUE TITLE
Feature Request: AWS s3 media upload

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#35]
Is there any plan to make AWS s3 sync for media files?

**Comment by owen2345** [comment]
Yes, We have planned to create a plugin for cloud files!

**Comment by raulanatol** [comment]
Nice!. Already you have something in mind.

I've been looking: https://github.com/whs/elFinder-driver and I was thinking edit the file app/controllers/admin/media_controller.rb. Besides adding the configuration of the module (parameters API_KEY, Bucket...) in the admin panel.

Any ideas?

**Comment by owen2345** [comment]
Great!
For now, not yet. But the library can be a good option!
Idea:
- Create a plugin

http://camaleon.tuzitio.com/plugins.html
- Add routes_main.txt with content:
```
get "/admin/elfinder" => "plugins/contact_form/admin#elfinder"  # this will overwrite the current route and 
use your method in your controller of your plugin.
```
- Add method elfinder in your controller with the custom code.

That's all.

**Comment by raulanatol** [comment]
Ok! I will try to do it.

Thanks!
