### ISSUE TITLE
Multiple Custom Field with same value

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#353]
Hi!

With this data (multiple custom field)
![before](https://cloud.githubusercontent.com/assets/2389019/13423410/a2635cb2-df92-11e5-9512-c28a63b462bf.png)

After save this is the result:
![after](https://cloud.githubusercontent.com/assets/2389019/13423414/a78b0834-df92-11e5-982b-01d3566e519a.png)

I think that the problem is here: 
https://github.com/owen2345/camaleon-cms/blob/master/app/models/concerns/camaleon_cms/custom_fields_read.rb#L178 because **the where** always return the first "a dog" and the id of the second "a dog" it will never enter into the **ids_saved**.

Regards.

**Comment by CBlaize** [comment]
+1

**Comment by owen2345** [comment]
Fixed!
