### ISSUE TITLE
How to let users create subdomains using omniauth

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#354]
Hi @owen2345 
Can you please let me know how to let users create subdomains by using their social profiles, i.e. I wanted to allow users to create subdomain using their facebook or twitter ID, this would  help users providing less information during registration, so that user can quickly start using the site.

**Comment by owen2345** [comment]
After social login do this:
```
site = Cama::Site.create(name: 'user name', slug: 'facebook-id').decorate
redirect_to site.the_url()
```

**Comment by mazharoddin** [comment]
Let me try, Thank you @owen2345
