### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by zedtux** [owen2345/camaleon-cms#355]
More and more Docker is used to "just try" a software, or to really run an app.

It would be really interesting to have a Docker image with all features working out-of-the-box. Someone who would like to tries Camaleon CMS would do the following:

```
$ docker run -p 3000:3000 owen2345/camaleon-cms
```

Or something like that, and then he would have to point his web browser to the running app.

**Comment by owen2345** [comment]
Hi @zedtux thanks for your suggestion, I will review docker because I didn't use until now.

**Comment by zedtux** [comment]
I can prepare something for you if you'd like to.

**Comment by owen2345** [comment]
yeah, it would help me a lot!

**Comment by zedtux** [comment]
Alright, let's do it ! :)

**Comment by raulanatol** [comment]
:+1:

**Comment by zedtux** [comment]
As this repos is a gem, I'm doing a new repo with a Rails app and the gem.

**Comment by zedtux** [comment]
I'm stuck on the following:

```
/usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:511:in `table_structure': Could not find table 'term_taxonomy' (ActiveRecord::StatementInvalid)
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:385:in `columns'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/attributes.rb:93:in `columns'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/attributes.rb:98:in `columns_hash'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:73:in `descends_from_active_record?'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:79:in `finder_needs_type_condition?'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/core.rb:256:in `relation'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/scoping/named.rb:33:in `default_scoped'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/scoping/named.rb:28:in `all'
	from /usr/local/bundle/gems/camaleon_cms-2.1.1/app/apps/plugins/front_cache/config/initializer.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
```

when I'm running the `rails generate camaleon_cms:install`.

**Comment by owen2345** [comment]
Hi @zedtux 
it is strange, I tried several times and it works well:
Gemfile:
```
gem "camaleon_cms", github: 'owen2345/camaleon-cms'
```
Results:
![screen shot 2016-03-12 at 8 21 12 am](https://cloud.githubusercontent.com/assets/1148415/13722927/9588ade8-e82b-11e5-9ad1-aca79f478eaa.png)

**Comment by zedtux** [comment]
I'm wondering if this is not related to the database I'm using ... (sqlite3)
I will try it with MySQL or PostgreSQL.

**Comment by owen2345** [comment]
I tested with the sqlite3 too.

**Comment by owen2345** [comment]
fast solution:
comment all lines from here:
```
/usr/local/bundle/gems/camaleon_cms-2.1.1/app/apps/plugins/front_cache/config/initializer.rb
```

**Comment by owen2345** [comment]
after install revert the changes.

**Comment by zedtux** [comment]
Okay, I'll do so. Should I open an issue somewhere else ?

**Comment by owen2345** [comment]
yes, please open on this github.
