### ISSUE TITLE
Camaleon store sources ?

### ISSUE THREAD

**Issue by zedtux** [owen2345/camaleon-cms#356]
Where are the sources of the store ? I want to fix the issue with the theme screenshots.

**Comment by owen2345** [comment]
@zedtux I am sorry, the plugin I saved in a private repository because it is managing a little payment process for paid plugins/themes

**Comment by zedtux** [comment]
Alright. So you should remove the `min-height` on the screenshot.

**Comment by zedtux** [comment]
There is no chance you move the critical code part in an engine in a private repo and open the reste of the store ?
I know it's a bit of work but it would allow us to improve the store for you.

**Comment by owen2345** [comment]
you are right, I will do it for next week please.

**Comment by zedtux** [comment]
Sure :+1:

**Comment by zedtux** [comment]
I'm no more using this project so I close the issue.
