### ISSUE TITLE
Subscribe form 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#357]
Hi @owen2345,
Please let me know if subscribe form plugin is available for camaleon-cms, or is there any plans to add it.
Without subscribe form its difficult to collect user email address for blog posts etc.
https://wordpress.org/plugins/email-subscribers/
https://wordpress.org/plugins/mailchimp-subscribe-sm/

**Comment by owen2345** [comment]
I created this, but needs some documentation:
https://github.com/owen2345/cama_subscriber

**Comment by mazharoddin** [comment]
Thanks @owen2345 , i will test and add documentation if time permits...
