### ISSUE TITLE
Sending mail on Heroku

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#360]
Some idea on this?
It's working fine on dev environment, but not in development.
 /app/vendor/bundle/ruby/2.0.0/gems/camaleon_cms-2.1.1/app/helpers/camaleon_cms/camaleon_helper.rb:21:in `block in sendmail': uninitialized constant CamaleonCms::CamaleonHelper::HtmlMailer (NameError)

**Comment by owen2345** [comment]
@lmany 
Are you using the git version?

**Comment by lmany** [comment]
@owen2345 
No I'm working in local, and deploying to heroku. Can tel me about a procfile in this case?

**Comment by lmany** [comment]
Is someone can help?

**Comment by bvogel** [comment]
I get the same error in my dev environment... (I use a completely vanilla gemset and followed the installation howto).

**Comment by owen2345** [comment]
yes, please use 2.1.1.4 it contains the fix and now you can use delayers like sidekiq, ...

**Comment by lmany** [comment]
Hello Owen,

It's nice to read you again.

This version is on github ?

I'am using the contact_form plugin, and the mailer is used into it, so how
can i configure and use sidekiq in that configuration ?

Thank you for all.

2016-04-13 18:06 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> yes, please use 2.1.1.4 it contains the fix and now you can use delayers
> like sidekiq, ...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209525469>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
Thank you!, I am again with Camaleon CMS.
use in your gemfile like this:
```
gem "camaleon_cms",  '2.1.1.4'
```
to use sidekiq, use like a normal rails app without any special configuration

**Comment by lmany** [comment]
Thanks,

But it's still not  to working.

the gem camaleon_cms is OK.

My procfile file.
----------------------
web: bundle exec rails server -p $PORT
worker: bundle exec sidekiq -c 5 -v

Thanks for your answer

2016-04-13 19:56 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> Thank you!, I am again with Camaleon CMS.
> use in your gemfile like this:
>
> gem "camaleon_cms",  '2.1.1.4'
>
> to use sidekiq, use like a normal rails app without any special
> configuration
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209567132>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
mmm it should works well, I am using:
```
sidekiq -C config/sidekiq.yml
```
where yml:
![screen shot 2016-04-13 at 3 34 43 pm](https://cloud.githubusercontent.com/assets/1148415/14506752/62976d40-018d-11e6-9831-b1cfe525367a.png)

**Comment by lmany** [comment]
Sorry,

It's great, working now.

Thank you very much.

Where can i downloaded the code, cause i didn't saw this on github,

the higher v is V2.1.1.3 on github

Thanks again

2016-04-13 21:36 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> mmm it should works well, I am using:
>
> sidekiq -C config/sidekiq.yml
>
> where yml:
> [image: screen shot 2016-04-13 at 3 34 43 pm]
> <https://cloud.githubusercontent.com/assets/1148415/14506752/62976d40-018d-11e6-9831-b1cfe525367a.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209614600>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
After a stable version, I published a new version in:
https://rubygems.org/gems/camaleon_cms
and also I created a new tag on github.

**Comment by lmany** [comment]
Sorry but i didn't found the new tags to download


2016-04-13 22:30 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> After a stable version, I published a new version in:
> https://rubygems.org/gems/camaleon_cms
> and also I created a new tag on github.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209634798>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
here:
![screen shot 2016-04-13 at 6 21 05 pm](https://cloud.githubusercontent.com/assets/1148415/14511304/87ee6762-01a4-11e6-8cbe-bdd85ac4f266.png)

**Comment by lmany** [comment]
OK,

But no v2.1.1.4

[image: Images intégrées 1]

2016-04-14 0:22 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> here:
> [image: screen shot 2016-04-13 at 6 21 05 pm]
> <https://cloud.githubusercontent.com/assets/1148415/14511304/87ee6762-01a4-11e6-8cbe-bdd85ac4f266.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209672891>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
I am sorry, it was my error typing...

**Comment by lmany** [comment]
Ok, so is there v2.1.1.4 ?

2016-04-14 0:53 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> I am sorry, it was my error typing...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209681786>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
yes, there is!

**Comment by lmany** [comment]
Hi Owen

I have this issue

First i have this menu where i'm working on it.

[image: Images intégrées 1]

If i select other menu, i loose the hierarchy.

[image: Images intégrées 2]
This appears when i use v2.1.1.4

2016-04-14 1:39 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> yes, there is!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-209691304>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
ooops, I can not see the screenshots

**Comment by lmany** [comment]
Thanks, see attachments

2016-04-15 20:19 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> ooops, I can not see the screenshots
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-210574042>
>



-- 
Léo MANY

**Comment by owen2345** [comment]
mm something is wrong, I can no see any screenshot, see my screen:
![screen shot 2016-04-16 at 8 00 06 am](https://cloud.githubusercontent.com/assets/1148415/14580832/48509aa6-03a9-11e6-83e8-c6af16352600.png)

**Comment by lmany** [comment]
I sent with attachements,
Ok
But The issue is simple.
I created menu1 with submenus. => ok.
I created orher menu2 => ok
Now, i want to select The menu1, when i did that i lost the submenus which were created under menu1

Envoyé de mon iPhone

**Comment by owen2345** [comment]
Fixed!
Please try again and confirm me if it works well for you too. (Master Branch)

**Comment by lmany** [comment]
Hello Owen,

It's great!!!!

It's ok for me

----------------------

Another question,

I try  to use country_select into add_manual_field  by using select_eval.
do have any idea ?

I want to use it into custom_field in purpose to a country to a post_type.

Thanks for your help.



2016-04-27 22:57 GMT+02:00 Owen Peredo Diaz <notifications@github.com>:

> Fixed!
> Please try again and confirm me if it works well for you too. (Master
> Branch)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owen2345/camaleon-cms/issues/360#issuecomment-215226843>
>



-- 
Léo MANY
