### ISSUE TITLE
Theming tutorial

### ISSUE THREAD

**Issue by zedtux** [owen2345/camaleon-cms#361]
It would be nice to have a tutorial explaining how themes are working and how to create a new one from scratch.

**Comment by owen2345** [comment]
Hi @zedtux 
I am sorry for this months, but I have almost solved my personal problems.
I will be able again from April to continue improving and creating the documentations.
Thanks for your interest in Camaleon Cms.

**Comment by zedtux** [comment]
You're welcome @owen2345. Camaleon is really great.

Question: What if I build a theme and I'd like to sell it ? Is it possible ?

**Comment by owen2345** [comment]
yes, it is possible!
For example, I have 3 paid themes here:
http://camaleon.tuzitio.com/store/themes which can be used in demo sites to see how it works.

Regards,

**Comment by zedtux** [comment]
I saw them, thank you. But what is the process in order to add a new one ? (I tried the buy button and see you're asking an email address in order to get the instructions)

**Comment by owen2345** [comment]
I am sorry, after I migrated to other server payment settings was wrong.
Now it is ok, thank you!

**Comment by zedtux** [comment]
How can I add my own theme in the store ? When I try to register I got the error message **You don't have authorization for this section.**

**Comment by owen2345** [comment]
You need to create your own account and after you can register your themes/plugins.

**Comment by owen2345** [comment]
Sorry, fixing the error....

**Comment by owen2345** [comment]
Fixed!

**Comment by zedtux** [comment]
Awesome ! Thank you I can continue now :)

**Comment by zedtux** [comment]
I'm in the theme form and I can see all the interesting fields excepted the one for the price. Is there an issue or is it done at another step ?

**Comment by owen2345** [comment]
The current publisher account only supports public/free themes or plugins, because the payment process needs to configure for every user/seller, like stripe, paypal or other payment process. For now you can use the paypal button in your description.

**Comment by zedtux** [comment]
Okay, thank you ! :)
