### ISSUE TITLE
How to rename post type menu

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#375]
Hi,
I created blog post type by using content group and I added blog post type to main menu,  it got added successfully but url path doesn't look nice, please let me know how I can  change url path for that menu item.
<img width="239" alt="screen shot 2016-04-02 at 20 34 04" src="https://cloud.githubusercontent.com/assets/6102465/14227106/928fd5e2-f912-11e5-8ed0-44b733d621b0.png">
Above blog post type created URL path as below
<img width="246" alt="screen shot 2016-04-02 at 20 36 43" src="https://cloud.githubusercontent.com/assets/6102465/14227109/b4227d68-f912-11e5-9895-967f460beafd.png">
But I wanted to rename it as vcap.me:3000/blog/ ..please let me know how I can do it.

**Comment by owen2345** [comment]
Hi @mazharoddin 
you can do it by edit content group:
![screen shot 2016-04-06 at 12 04 36 pm](https://cloud.githubusercontent.com/assets/1148415/14323746/c76dd82e-fbef-11e5-8faa-c75246d68318.png)

**Comment by owen2345** [comment]
I am sorry, for now it is not possible, because that structure is reservated for pages or posts, like 
http://localhost/my-page or http://localhost/my-page.html

**Comment by mazharoddin** [comment]
Thanks @owen2345, but it would be great if its possible to change the menu path for the post type, because actual URL generate by  post type is different than the menu item for that post type.
e.x below link has "/blog/" path, but I  try to access "http://www.vcap.me:3000/blog/" path, I am getting page not found error. 
http://www.vcap.me:3000/blog/apple-macbook-pro-mjlq2hna-15-inch-laptop-core-i716gb256gbintel-iris-pro

**Comment by owen2345** [comment]
Hey @mazharoddin 
Right now I added that support, please check if it works well for you.
https://github.com/owen2345/camaleon-cms/commit/c2853c39944894e9af1f1ff95fdd22824e10eefd

**Comment by mazharoddin** [comment]
Thanks @owen2345 , Now I could able to edit Post type menu item, but there are some issues and  I am getting 404 error randomly,  looks like it regressed other functionality, I will recreate and update this issue with screen shots.

**Comment by owen2345** [comment]
ok!, waiting for the screenshots....

**Comment by mazharoddin** [comment]
Hi @owen2345 , sorry for the delay, below error I am getting after I merged the new changes.
```
I, [2016-04-08T17:22:10.775424 #1634]  INFO -- : Completed 500 Internal Server Error in 223ms (ActiveRecord: 5.8ms)
F, [2016-04-08T17:22:10.777559 #1634] FATAL -- : 
ActionView::Template::Error (undefined method `cama_post_type_544_en_url' for #<#<Class:0x007f9d82994478>:0x007f9d819ea950>):
    33:                         <td><%= item.the_slug %></td>
    34:                         <td><%= item.count %></td>
    35:                         <td>
    36:                             <%= link_to raw('<i class="fa fa-eye"></i>'), item.the_url, class: "btn btn-primary btn-xs", title: "#{t('camaleon_cms.common.visit')}", target: '_blank' %>
    37:                             <%= link_to raw('<i class="fa fa-pencil"></i>'), {action: :edit, id: item.id }, class: "btn btn-default btn-xs cama_ajax_request", title: "#{t('camaleon_cms.admin.button.edit')}" %>
```
Got below exception while trying to access blog post  type menu at contents  menu after blog post type  is created using content group.
```
I, [2016-04-08T17:25:26.385031 #1634]  INFO -- :   Rendered /shared/bundle/ruby/2.2.0/bundler/gems/camaleon-cms-472675948a76/app/views/camaleon_cms/admin/posts/index.html.erb within /layouts/camaleon_cms/admin (201.1ms)
I, [2016-04-08T17:25:26.386021 #1634]  INFO -- : Completed 500 Internal Server Error in 320ms (ActiveRecord: 10.5ms)
F, [2016-04-08T17:25:26.392328 #1634] FATAL -- : 
ActionView::Template::Error (undefined method `cama_post_type_544_en_url' for #<#<Class:0x007f9d823ba1d8>:0x007f9d86591610>):
    3:         <div class="row">
    4:             <div class="col-md-12">
    5:                 <h4 class="pull-left"><%= t('camaleon_cms.admin.page_title.list_of') %> <%= @post_type.the_title.pluralize %>
    6:                     <b>(slug = <%= @post_type.the_slug %>)</b> <%= link_to("<i class='fa fa-eye'></i> #{t("camaleon_cms.common.visit")}".html_safe, @post_type.the_url, class: 'btn btn-xs', target: '_blank') %>
    7:                 </h4>
    8:                 <%= link_to raw("<i class='fa fa-plus'></i> #{t('camaleon_cms.admin.post_type.add')} #{@post_type.the_title}"), {action: :new}, class: "btn btn-primary pull-right cama_ajax_request" if can? :create_post, @post_type %>
    9:             </div>
```
One more issue observed is newly created blog type menu is getting deleted if I do refresh, again its getting created automatically, but again its getting deleted if I do refresh. But there is no exception in log files for this behavior.
<img width="318" alt="screen shot 2016-04-08 at 23 01 36" src="https://cloud.githubusercontent.com/assets/6102465/14392218/ec9ba014-fddd-11e5-92c0-4ba97dd2f915.png">
<img width="253" alt="screen shot 2016-04-08 at 23 01 45" src="https://cloud.githubusercontent.com/assets/6102465/14392219/ed86c7d8-fddd-11e5-9483-4fc016670753.png">

**Comment by owen2345** [comment]
Hey @mazharoddin 
could you please send me your DB or a sample DB with that problem?
I tried many times but without success.
Regards,

**Comment by mazharoddin** [comment]
Hi @owen2345,
Even I am unable recreate this issue completely after I cleaned up earlier database using rake db:drop.
Now I am observing page not found error only if I create blog post type on subdomain.

<img width="242" alt="screen shot 2016-04-09 at 20 11 57" src="https://cloud.githubusercontent.com/assets/6102465/14404277/6929d054-fe8f-11e5-8310-6eccc3c88014.png">

<img width="320" alt="screen shot 2016-04-09 at 20 12 07" src="https://cloud.githubusercontent.com/assets/6102465/14404278/6ac03db8-fe8f-11e5-848e-40dd449844f5.png">
<img width="324" alt="screen shot 2016-04-09 at 20 12 12" src="https://cloud.githubusercontent.com/assets/6102465/14404280/6c4c2cfa-fe8f-11e5-819d-377c6ecc3c0c.png">

Please find below file for DB dump.

[camaleon_cms.zip](https://github.com/owen2345/camaleon-cms/files/211296/camaleon_cms.zip)

Thanks.

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
I am getting below exception with above code change.
````
I, [2016-04-11T09:05:13.525787 #15511]  INFO -- : Completed 500 Internal Server Error in 38ms (ActiveRecord: 3.6ms)
F, [2016-04-11T09:05:13.527519 #15511] FATAL -- : 
NoMethodError (undefined method `count' for nil:NilClass):
 /2.2.0/bundler/gems/camaleon-cms-472675948a76/app/models/camaleon_cms/post_default.rb:33:in `find_by_slug'
  activerecord (4.2.5) lib/active_record/relation/delegation.rb:70:in `block in find_by_slug'

````

**Comment by owen2345** [comment]
hey @mazharoddin 
I fixed the problem! It was for subdomains without full domain name.

**Comment by mazharoddin** [comment]
Due to version issue, I am unable to verify the fix, I will let you know once I could able to verify...Thank You :)
