### ISSUE TITLE
will support markdown in future?

### ISSUE THREAD

**Issue by neversion** [owen2345/camaleon-cms#378]
Will camaleon support markdown in future, I think it's easer way for blogger to write.

**Comment by owen2345** [comment]
yes, I am thinking to include liquid gem.

**Comment by neversion** [comment]
Great, looking forward to it.
As I know, liquid gem is a template language, Has it got any connecting with markdown?

**Comment by owen2345** [comment]
mmm it is different, could you please send me a link or details about what kind of markup would you like to implement?

regards!

**Comment by neversion** [comment]
I hope we can write post just like write this comment in github. Type in markdown and can preview. 
> https://en.support.wordpress.com/markdown/

**Comment by owen2345** [comment]
It appears a good idea, I will apply the next month!
