### ISSUE TITLE
change search engine

### ISSUE THREAD

**Issue by bvogel** [owen2345/camaleon-cms#380]
this is more of a feature request or a question how to do it, but we would love to continue to use our current search engine over at findologic. How would one go about replacing the build-in search engine with findologic?

**Comment by owen2345** [comment]
You can use the "on_render_search" hook to do your custom search.
1: Add the hook in your config/system.json
```
{
  ...
  ...
  hooks:{
    "on_render_search": ["my_custom_search"]
  }
}
```
2: Add this method in your helper
```
def my_custom_search(args)
  args[:posts] = current_site.the_posts.where("LOWER(title) LIKE ? OR LOWER(content_filtered) LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
end
```
