### ISSUE TITLE
Compatibility with rails-composer

### ISSUE THREAD

**Issue by carukc** [owen2345/camaleon-cms#381]
Hello,  Will Camaleon work with sites that have been generated using rails-composer or is the theme / look and feel that's used independent of what rails-composer generates.

Apologies if this is a dumb question, I'm quite new to RoR and figuring this out as I go.

Thanks
Chris

**Comment by owen2345** [comment]
Hi @carukc 
Camaleon CMS manage the public content by themes, which permit you to create your views like a normal rails app.
If you are trying to add your custom controllers + routes + views +... try to ignore camaleon cms and work like in a normal rails app and use the helpers, models, ... of camaleon cms (if you need them)
Thanks for your interest in Camaleon CMS and let me know if you have any suggestion to improve Camaleon CMS. 
Regards,

**Comment by carukc** [comment]
I was more interested if the themes it generates were compatible but it looks like you handle themes within Camaleon itself.  It now includes most of the themes from http://startbootstrap.com/ but if I understand correctly I'm going to have to create my own version of the the one that I want.

I'll review the docs...

BTW... Congrats on this CMS.  It's really nicely put together... all the basics seem to be covered.

**Comment by owen2345** [comment]
I am sorry, this is not compatible with rails composer.
