### ISSUE TITLE
Basic install is generating a permission denied error

### ISSUE THREAD

**Issue by carukc** [owen2345/camaleon-cms#382]
I can easily change the permissions on the directory that's causing the problem but I'm not sure that it's the right thing to do.

When we try to run cms:install we get a mkdir error:

appliform@miniserver:~/htdocs/appliform-portal$ rails generate camaleon_cms:install
/home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /run/user/1000/spring-1011 (Errno::EACCES)
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/env.rb:40:in `tmp_path'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/env.rb:49:in `socket_path'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/env.rb:53:in `socket_name'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/run.rb:26:in `connect'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/run.rb:31:in `call'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/rails.rb:24:in `call'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/appliform/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/appliform/htdocs/appliform-portal/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

Should we be giving our dev user access to this directory?

Thanks
Chris

**Comment by carukc** [comment]
Strangely the logged in use is 1011 not 1000... something must be wrong with the session.  Checking

**Comment by owen2345** [comment]
mmm I think the problem is your folder permissions, because that commnd is simple (copy and create theme/plugin directories)

**Comment by carukc** [comment]
yea... thanks... but it should not have been using user ID 1000 so the login session is somehow confused.  I'm trying to figure that out now.

**Comment by carukc** [comment]
it's really bizarre... $uid is definitely 1011 for this user 1000 is another user but it's trying to create in:
 /run/user/**1000**/spring-**1011** 

it should be trying to create in:
 /run/user/**1011**/spring-**1011**

for some reason XDG_RUNTIME_DIR=/run/user/1000 ... how strange.

**Comment by carukc** [comment]
just FYI... it's something to do with 'sudo su - that-user'... it does not reset this env variable.  Logging in directly sets properly.

Good to know for future reference.

**Comment by owen2345** [comment]
thanks for sharing!
