### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by efleisc** [owen2345/camaleon-cms#383]
I have installed Camaleon into my existing project with no problems at all. however when I try to access it I get the following error message

CanCan::AuthorizationNotPerformed in CamaleonCms::Admin::InstallersController#index
This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.

Any idea of what I should do?

**Comment by owen2345** [comment]
Put like this in your initializer:
```
CamaleonCms::Admin::InstallersController.class_eval do
  skip_authorize_resource ....
end
```
By this way you can add or modify an existent class
