### ISSUE TITLE
Sub menues?

### ISSUE THREAD

**Issue by carukc** [owen2345/camaleon-cms#384]
I do not see a way to create sub menues in the admin interface.  Am I correct is thinking that this would be done using code?

Thanks
Chris

**Comment by owen2345** [comment]
It is a drag and drop sortable.
![screen shot 2016-04-16 at 8 03 59 am](https://cloud.githubusercontent.com/assets/1148415/14580844/ce26de10-03a9-11e6-91fc-a352bed270bc.png)

**Comment by carukc** [comment]
OK, Thanks... Just FYI.. this does not seem to work on Chrome.  FF and Edge seem fine though.

**Comment by owen2345** [comment]
Ooops I will check on monday!

**Comment by owen2345** [comment]
Fixed!

**Comment by carukc** [comment]
Great!  Thanks.

**Comment by nasim31** [comment]
Hi owen, Hi carukc,

Can you please help me on loading submenus ??
In my code only parent menus are showing. Submenus are not loading.
Code written :
<% cama_menu_parse_items(current_site.nav_menus.find_by_slug('main_menu').children).each do |item| %> <li class="<%= item[:current_item] ? 'active' : '' %>"><a class="<%= 'scroll' if item[:url].start_with?('#') %>" href="<%= item[:url] %>"><%= item[:label] %></a></li> <% end %>

Theme menu reference:
http://agency.dexignlab.com/xhtml/index.html

**Comment by owen2345** [comment]
http://camaleon.tuzitio.com/render-custom.html
