### ISSUE TITLE
Media folders can not be deleted with local storage

### ISSUE THREAD

**Issue by gcrofils** [owen2345/camaleon-cms#385]
In media, folders can not be deleted when stored on the local disk.
It works well on S3.

The bug is in `camaleon-cms/app/helpers/camaleon_cms/uploader_helper.rb`, [line 116](https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/uploader_helper.rb).

`@fog_connection_bucket_dir.files.head("#{current_site.upload_directory_name}/#{folder}/".gsub(/(\/){2,}/, "/")).destroy`

The object to destroy is a `Fog::Storage::Local::File` ([source](fog-local/lib/fog/storage/local/models/file))

Unfortunately this code tries to `::File.delete(path)` instead of `::File::rmdir` (remember, we are trying to delete a repository).
it raises an exception  `*** Errno::EPERM Exception: Operation not permitted @ unlink_internal`

**Comment by owen2345** [comment]
hey @gcrofils 
In current master branch, I removed fog dependency to use custom uploader (faster and clean).
Please try it!
