### ISSUE TITLE
Allow site admin to suspend a subdomain

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#386]
Hi,  I feel it would be great if we have option to suspend a subdomain site using admin window(admin/settings/sites/).
Suspended sites can show suspended message on their submdomain home page and if we required site owner can ask subdomain owners to take some actions to re-activate that subdomain...

**Comment by owen2345** [comment]
Done!

**Comment by mazharoddin** [comment]
Thanks @owen2345 :)
