### ISSUE TITLE
I would like to suggest changing the route name for the back end.

### ISSUE THREAD

**Issue by carukc** [owen2345/camaleon-cms#388]
Hi Owen,

We're making real progress on integrating the CMS.  Camaleon is really great.  It includes basic versions of everything one needs for a web front end.

I would like to suggest that you change the /admin route.

Since the intention is to use it for all guests that can log in and it seems only natural to put other integration code in there for non-administrative users... admin seems the wrong thing to call it...  only administrators will administrate there, other users will use it for accessing their profile page, perhaps forums, etc... we are using it for submission forms.

Perhaps something like /portal or /system or /users or /private ... which is more indicative of what it actually is... only a few users will actually use it to administrate.

We have a few other suggestions but will post them in their own threads.

Thanks
Chris

**Comment by owen2345** [comment]
Hi @carukc 
Done! 
you can do it by config/system.json:
```
"admin_path_name": "admin", // URL prefix for admin panel, for example to get http://localhost:3000/sekret/, this should be "sekret"
```

Note: The plugins to have this support will need to change their routes like this:
```
    scope PluginRoutes.system_info['admin_path_name'], as: 'admin' do    # for scope cases
```
Or this:
```
    namespace :admin, path: PluginRoutes.system_info["admin_path_name"] do     # for namespace cases
```

Regards!

**Comment by carukc** [comment]
Great!  Many Thanks!

Chris

**Comment by anteo** [comment]
> Note: The plugins to have this support will need to change their routes like this:

Should not this to be done in yours `PluginRoutes#load` and `PluginRoutes#load_themes` methods?

```
  elsif env == "admin" # admin
      res << "scope 'admin', as: 'admin' do \n"
      res << "namespace :plugins do \n"
      plugins.each do |plugin|
        res << "namespace '#{plugin["key"]}' do \n"
        res << "#{File.open(File.join(plugin["path"], "config", "routes_#{env}.txt")).read}\n" rescue ""
        res << "end\n"
      end
```

You need to change `scope 'admin', as: 'admin'` to `scope PluginRoutes.system_info['admin_path_name'], as: 'admin'`, because I can't do this in my own routes_admin.txt

If I add scope to routes_admin.txt, i get nested paths like `/admin/plugins/plugin_name/<admin_path_name>` instead of `/<admin_path_name>/plugins/plugin_name`

**Comment by owen2345** [comment]
@anteo 
You are right, but the change is for routes like this:
https://github.com/owen2345/camaleon-ecommerce/blob/master/config/routes.rb#L31

**Comment by anteo** [comment]
path to /admin is also hardcoded in _media_manager.js.coffee

**Comment by owen2345** [comment]
fixed!
