### ISSUE TITLE
We would like to suggest that external menu items also have visibility settings

### ISSUE THREAD

**Issue by carukc** [owen2345/camaleon-cms#389]
You can set the visibility of a page and if set the menu entry disappears for users that are not logged in.  This is really good!

We would like to suggest that you also have visibility setting for 'external' menu entries so that you can create links that only logged in users can see.

Keep up the great work!
Chris

**Comment by owen2345** [comment]
Done!
Use this plugin to see in action:
https://github.com/owen2345/cama_external_menu
Regards,
