### ISSUE TITLE
AssetsFilteredError clean installation using gem

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#39]
Hi! 

I installed the gem with a clean application and when I entered in /admin/plugins this happened.

```
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( plugins/contact_form/assets/docs/index.html )` to `config/initializers/assets.rb` and restart your server
```

I changed the gem file: config/initializers/assets.rb adding this line in the bottom:

```
Rails.application.config.assets.precompile += %w( plugins/*/assets/docs/* )
```

It's correct? Do you need a Pull Request?

Thx!

**Comment by owen2345** [comment]
Hello Raul,
I am working in the plugin and theme store, that information will be saved in that store and not in the plugin directory.
Thanks for your comment!
