### ISSUE TITLE
Not a issue but.. Looking for documentation and camaleon website is down

### ISSUE THREAD

**Issue by leahwchang** [owen2345/camaleon-cms#391]
Hi, I was looking for documentation to work on my project but it looks like camaleon site is down after the last commit about 2 hours ago.
<img width="1280" alt="screen shot 2016-04-27 at 8 06 22 pm" src="https://cloud.githubusercontent.com/assets/13529745/14871821/2b3014ec-0cb4-11e6-8294-358bc3966439.png">

**Comment by owen2345** [comment]
Fixed!
Problem reloading server, thank you!
