### ISSUE TITLE
NoMethodError in CamaleonCms::Frontend#index

### ISSUE THREAD

**Issue by ThinkTankShark** [owen2345/camaleon-cms#397]
Not loading the root page "/" or "/blog" (However the root page was defined) when there is no page created under admin.

The way around it is to login to admin first, create a page and then load the page again.

![screen shot 2016-05-14 at 4 43 19 pm](https://cloud.githubusercontent.com/assets/11286318/15271231/3e7eefb8-19f3-11e6-90e6-b44923fe2d88.png)

Would be great o have this fixed, since a lot of people use this engine along with their own website for blogging.

BTW best CRM available right now for rails.

**Comment by owen2345** [comment]
Hi @ThinkTankShark 
Thank you for the report, please give me all steps to reproduce the problem.
Regards,

**Comment by StephaneRob** [comment]
Hi @owen2345,
tried today (from scratch) and got this when try to load '/':

![screen shot 2016-05-21 at 21 09 45](https://cloud.githubusercontent.com/assets/4135765/15450432/a22b1930-1f9b-11e6-940f-28ad28e36283.png)

Need to load manually '/admin' first to init site.

rails 4.2.6
ruby 2.3.1
camaleon_cms 2.1.2.0
