### ISSUE TITLE
How to ensure only specified plugins and themse are available for subdomains

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#398]
Hi @owen2345 ,

How to ensure that only few specified themes are plugins are available to subdomain users, I created some themes and plugins at this location 'app/apps/plugins and app/apps/themse', but these plugins/themes are not yet tested fully, so I wanted to hide these plugins from subdomains, but available only to main domain so that I can test. 
Can you please let me know how I can do that. Thanks.

**Comment by owen2345** [comment]
Hi @mazharoddin 
you can use the "domain" setting in the config of your theme/plugin,
Sample:
```
"title": "Store",
  "version": "0.1.1",
  "domain": "camaleon",
  "key": "store",
```

Regards,

**Comment by mazharoddin** [comment]
Thanks a lot @owen2345 , this setting worked like charm :)
