### ISSUE TITLE
fix_ssl.rb conflicts

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#40]
Hi!

I'm working in a plugin (media_aws_s3) to permit upload all media to s3.
I created an elFinder gem to connect with S3 (not stable yet).
I'm testing the new gem like camaleon plugin and works fine but I have a problem with 
the fix_ssl.rb initializer, because when I make a request to S3 (using aws-sdk gem) this 
initializer use the certificate (lib/ca-bundle.crt) and the http connection response:
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

I changed this initializer:

```
 def use_ssl=(flag)
      self.verify_mode = OpenSSL::SSL::VERIFY_PEER
      self.original_use_ssl = flag

      if @address.to_s.include? "amazonaws.com"
        self.ca_file = nil
        self.ca_path = nil
        self.cert_store = nil
      else
        self.ca_file = Rails.root.join('lib/ca-bundle.crt').to_s
      end
    end
```

And it works but I think that isn't elegant.

Any idea?

**Comment by owen2345** [comment]
Thank you Raul!
We will review today...

**Comment by owen2345** [comment]
Fixed!

The custom method is only applied for facebook and not for all.

Regards,

**Comment by raulanatol** [comment]
Hi!

I have this problem:
```
NoMethodError (super: no superclass method `use_ssl=' for #<Net::HTTP xxx-s3-us-west-2.amazonaws.com:443 open=false>):
```

Only works for my if I change the super (https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/fix_ssl.rb#L15) for:

```
self.original_use_ssl = flag
```

Thx!

**Comment by owen2345** [comment]
ok, I have delivered a new version 0.1.7 with that fix and others

**Comment by owen2345** [comment]
Please, let me know if it is ok!

**Comment by raulanatol** [comment]
Works perfectly. Thx!
