### ISSUE TITLE
How to change title for posts

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#400]
Hi @owen2345,
Please let me know if is there any way to change title tag for posts, currently post title tag is generated from post title along with website name, its good enough for most of the websites, but I wanted to further customize title tag, so that post title tag is different from post title. This will be helpful from SEO point of view.
Also please let me know how to alter h1 tag for the post, currently post title is marked as 'h1' tag.

Currently title tag is generated as below, assuming my post title is how to use  Camaleon CMS.
```
<title> Camaleon | how to use  Camaleon CMS </title>
```
But I wanted to change as below
```
<title> Learn about Camaleon CMS and its capabilities | Best CMS Online - Camaleon CMS </title>
```
Please let me know how to do it.

**Comment by mazharoddin** [comment]
Hi @owen2345 , I feel its better to create a plugin to address SEO related issues, that way all SEO settings can be grouped together. Thanks

**Comment by owen2345** [comment]
Hi @mazharoddin,
actually you can do it by simple hook "seo":
```
r = { seo_data: s, object: options[:object] }
    hooks_run('seo', r)
```
which permit you to customize all SEO data

Regards,

**Comment by mazharoddin** [comment]
OK @owen2345 , Thanks.
