### ISSUE TITLE
uninitialized constant CamaleonCms::Admin::AdminController Error if I use cloudfront URL & while trying to delete Images

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#402]
Hi @owen2345,

I am getting "uninitialized constant CamaleonCms::Admin::AdminController" error if I use cloudfront URL in filesystem settings, I observed same error if I try to delete images in 'media' tab.
```
ActionController::RoutingError (uninitialized constant CamaleonCms::Admin::AdminController):
  activesupport (4.2.5) lib/active_support/inflector/methods.rb:263:in `const_get'
  activesupport (4.2.5) lib/active_support/inflector/methods.rb:263:in `block in constantize'
  activesupport (4.2.5) lib/active_support/inflector/methods.rb:259:in `each'

```

**Comment by owen2345** [comment]
@mazharoddin Please try again and confirm me if the problem persist with the version 2.2.0 because I tried many times and it works well for me.

Regards,

**Comment by mazharoddin** [comment]
yes @owen2345 ..I was getting this exception with latest version, let me re-create it.

**Comment by mazharoddin** [comment]
Hi @owen2345, yes I am able to recreate this issue with latest version aswell, you can  use https://github.com/mazharoddin/camaleon_cms_debug repository to recreate this issue

**Comment by owen2345** [comment]
@mazharoddin could you please send more details and screenshots to reproduce the error?
I can not reproduce the problem in your repo too.

**Comment by mazharoddin** [comment]
Sure @owen2345 , please find below for some screen shots, first I am enabling amazon s3 and cloudfront using settings, then later  I am  trying  to upload image using media, operation shows as completed, but after upload I am unable to access the image. If I click on image link I am getting "uninitialized constant CamaleonCms::Admin::AdminController" error.
<img width="1008" alt="screen shot 2016-06-18 at 20 49 36" src="https://cloud.githubusercontent.com/assets/6102465/16171834/70c49bde-3597-11e6-9b99-85b92369f27d.png">
<img width="298" alt="screen shot 2016-06-18 at 20 54 14" src="https://cloud.githubusercontent.com/assets/6102465/16171835/725d2574-3597-11e6-90e9-f8a31224e73a.png">
<img width="171" alt="screen shot 2016-06-18 at 20 55 36" src="https://cloud.githubusercontent.com/assets/6102465/16171837/75666352-3597-11e6-8373-78f697b7b821.png">
<img width="1271" alt="screen shot 2016-06-18 at 20 59 06" src="https://cloud.githubusercontent.com/assets/6102465/16171845/9cc1f47a-3597-11e6-8af5-f144dc95f86e.png">

**Comment by owen2345** [comment]
@mazharoddin 
I am so sorry, but I can not reproduce. Please contact me on skype "owen-2345" to review together.
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345, np. Thanks for debugging it. Let me check if there is something wrong with my S3/coudfront images.
Sure I will contact you on skype to review together.

**Comment by mazharoddin** [comment]
Hi @owen2345,
This issue was due to typo, I was using Cloudfront URL directly instead of appending "https://" to it.
 Now I am able to access photos using Cloudfront URI. Sorry for the confusion. Thanks.
