### ISSUE TITLE
How to override plugin views

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#405]
Hi @owen2345 ,

I am trying to create a theme for camaelon_ecommerce plugin, I wanted to override few plugin views so that I can display products differently. I tried to override plugin view pages by creating this directory (app/apps/themes/**shoppy**/views/plugins/ecommerce) in theme folder. 
This is working as expected for that theme, but due to this other themes(e.g. camaleon_first theme) also showing product pages differently, can you please let me know how I override plugin theme views so that changes are restricted to that particular theme.
I am trying to release it as opensource theme, so let me know if I can add it to themes store in camaleon.tuzitio.com website.

**Comment by owen2345** [comment]
@mazharoddin 
I am improving and fixing some details of current ecommerce gem to use it to manage themes and plugins store maybe with it your problem will be fixed.
I will finish in 2 days more.

**Comment by mazharoddin** [comment]
Sure @owen2345 , thanks..

**Comment by mazharoddin** [comment]
Hi @owen2345,
As I mentioned earlier, I created shoppy theme for camaleon-ecommerce plugin, theme can be downloaded from this repository https://github.com/mazharoddin/camaleon-cms-shoppy.
Feel free to include this theme as one of the camaleon-cms default theme.

**Comment by owen2345** [comment]
Good!
I uploaded my changes of ecommerce plugin, which contains improvements for frontend:
![screen shot 2016-06-06 at 10 09 12](https://cloud.githubusercontent.com/assets/1148415/15823006/31940e6c-2bcf-11e6-811a-40ad85affe2b.png)
Regards!

**Comment by mazharoddin** [comment]
Ok Great :)

**Comment by mazharoddin** [comment]
Hi @owen2345,
I am getting below error with latest changes.
````
undefined method `orders' for #<CamaleonCms::SiteDecorator:0x007f9fbc4d42f8>
 ````
      if can? :posts, pt
        items_i << {icon: "reorder", title: "<span>#{t('plugin.ecommerce.orders', default: 'Orders')} <small class='label label-primary'>#{current_site.orders.size}</small></span>", url: admin_plugins_ecommerce_orders_path}
````
vendor/plugins/camaleon-ecommerce/app/helpers/plugins/ecommerce/ecommerce_helper.rb:49:in `ecommerce_admin_before_load'
vendor/plugins/camaleon-cms/app/helpers/camaleon_cms/hooks_helper.rb:47:in `rescue in block in _do_hook'
vendor/plugins/camaleon-cms/app/helpers/camaleon_cms/hooks_helper.rb:41:in `block in _do_hook'
````
I also tried deleting and recreating the database.

**Comment by owen2345** [comment]
Hi @mazharoddin, I tried many times and it works well in my local, but which version of camaleon are you using?

**Comment by mazharoddin** [comment]
Hi @owen2345, I am using  camaleon_cms 2.1.2.1 version. Thanks

**Comment by owen2345** [comment]
could you please test with the master branch?

**Comment by mazharoddin** [comment]
Sure..

**Comment by mazharoddin** [comment]
@owen2345 , not sure why but I am getting same error with master branch aswell.
```
Using camaleon_ecommerce 1.0 (was 0.0.4) from git://github.com/owen2345/camaleon-ecommerce.git (at master)
Using camaleon_cms 2.1.2.0
```
```
 CACHE (0.0ms)  SELECT  "cama_metas".* FROM "cama_metas" WHERE "cama_metas"."objectid" = $1 AND "cama_metas"."object_class" = $2 AND "cama_metas"."key" = $3  ORDER BY "cama_metas"."id" ASC LIMIT 1  [["objectid", 13], ["object_class", "PostType"], ["key", "_default"]]
Completed 500 Internal Server Error in 40ms (ActiveRecord: 3.4ms)

NoMethodError (undefined method `orders' for #<CamaleonCms::SiteDecorator:0x007fa3ccf11630>):
  draper (1.4.0) lib/draper/automatic_delegation.rb:7:in `method_missing'
  /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-cbaded8ec875/app/helpers/plugins/ecommerce/ecommerce_helper.rb:49:in `ecommerce_admin_before_load'
````
I am getting this error if I am trying to access dashboard/trying to login etc.

**Comment by mazharoddin** [comment]
Hi @owen2345, please let me know if you were able to recreate this issue.

**Comment by owen2345** [comment]
@mazharoddin could you please share me a git project with this problem? yesterday I tried many times but without success.
Regards,

**Comment by mazharoddin** [comment]
hi @owen2345 , I could able to recreate this problem on a clean git repository.
Please find below for git repository details.
git@github.com:mazharoddin/camaleon_cms_debug.git
Thanks

**Comment by owen2345** [comment]
Hi @mazharoddin ,
I found and fixed the problem!
Thanks for the git repo.
Regards!

**Comment by mazharoddin** [comment]
Its great, thanks @owen2345 ..sure ..np

**Comment by mazharoddin** [comment]
Hi @owen2345, 
I am getting below error with latest changes.
```
 Showing /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-cbaded8ec875/app/views/plugins/ecommerce/partials/_cart_widget.html.erb where line #20 raised:

undefined method `*' for nil:NilClass
```
```

  def tax_total
    product_items.map{|item| product = item.product.decorate; (product.tax) * item.qty }.inject{|sum,x| sum + x } || 0
  end

  def weight_total

/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-cbaded8ec875/app/models/plugins/ecommerce/cart.rb:51:in `block in tax_total'
activerecord (4.2.6) lib/active_record/relation/delegation.rb:46:in `map'
activerecord (4.2.6) lib/active_record/relation/delegation.rb:46:in `map'
/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-cbaded8ec875/app/models/plugins/ecommerce/cart.rb:51:in `tax_total'
````

**Comment by owen2345** [comment]
@mazharoddin please update the gem, because it should be fixed with:
https://github.com/owen2345/camaleon-ecommerce/blob/master/app/decorators/plugins/ecommerce/product_decorator.rb#L38

**Comment by mazharoddin** [comment]
Yeah @owen2345 , its working with latest change, can you please increase version camaleon-ecommerce version, so that we can get the latest changes..thanks

**Comment by owen2345** [comment]
Done! create version 1.1 and created a new tag 1.1 too.
