### ISSUE TITLE
pt-BR problems

### ISSUE THREAD

**Issue by RafaelTCostella** [owen2345/camaleon-cms#407]
We found some problems in:

- Recovering bilingual texts with pt-BR as one of the options

- Recovering localed texts based on URL

- Some missing translations in admin panel

We hope that this PR helps :)

https://github.com/owen2345/camaleon-cms/pull/406

**Comment by owen2345** [comment]
Thanks very much @RafaelTCostella !

**Comment by RafaelTCostella** [comment]
cheers :beers:
