### ISSUE TITLE
 Sell digital goods using camaleon-ecommerce

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#410]
Hi @owen2345,
I feel it would be great if we can provide option to sell digital goods using camaleon-ecommerce, mainly digital art or photos etc. Is it is worth to add this option to ecommerce plugin?

**Comment by owen2345** [comment]
Hi @mazharoddin 
Please let me know what extra modifications should I add into current plugin?

**Comment by mazharoddin** [comment]
Sure @owen2345,
By keeping current camaleon-ecommerce implementation in mind, I thought about two approaches.

1) Providing extra option at product level as below.
![screen shot 2016-06-22 at 15 07 56](https://cloud.githubusercontent.com/assets/6102465/16264759/f679b364-3898-11e6-8b36-2a34eda23885.png)

In this approach we need to modify  'add new product page' so that it allows users to select a digital file/software or physical good etc .

If user selects digital file then load different product form using Ajax specific to digital file product, else  load current products form as is if user selects as physical good.
Though it may require changes to existing add new product form page, I feel this approach will be clean and we can add different product types later if required, e.g. later we can add product form specific to Art/Photos etc, main advantage will be each product type can have different product form.

2) In second approach we can provide on flag in our current product form with 'Is digital product?'
If user select digital product type then hide fields which are not related to digital download( Shipping weight etc) and skip customer details page in checkout process, provide the link or send a mail with link to customer on successful checkout.

In this approach we can directly use current product files upload form to upload photos/art/ebook  digital goods etc. 
![screen shot 2016-06-22 at 16 39 25](https://cloud.githubusercontent.com/assets/6102465/16264651/5e0f882e-3898-11e6-85bb-4e57afc3a0e3.png)

I think in either approach we need to change the checkout process some thing similar to below if user selects product type as digital.

![screen shot 2016-06-22 at 16 42 15](https://cloud.githubusercontent.com/assets/6102465/16264644/57b29016-3898-11e6-9194-cdb4b3461728.png)

Also we need to add one tab in ecommerce settings  similar to below.
![screen shot 2016-06-22 at 16 44 23](https://cloud.githubusercontent.com/assets/6102465/16264699/b7ce523c-3898-11e6-9a50-5ea207a8dec8.png)


If you think it require too many changes, may be we can hold this feature, may be later we can come up with different solution :)
