### ISSUE TITLE
Multi Image field

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#412]
Hi @owen2345,

Can you please add one more image field as multi image field in "Custom field group" so that we can upload multiple images.
With current image field we need to create new field to add new image, it is time consuming if we have multiple images, if you can add new multi image field then I will try to complete this plugin(https://github.com/mazharoddin/camaleon_cms_gallery) along with  views etc.
May be you can show drop box instead of below form for that new multi image field.
![screen shot 2016-06-24 at 16 41 52](https://cloud.githubusercontent.com/assets/6102465/16336395/ab3f7206-3a2a-11e6-96aa-8c446360e13e.png)

**Comment by owen2345** [comment]
@mazharoddin 
I think a better solution would be to permit select many files in the camaleon file browser and automatically add many image rows pre filled (simulate click 'add new field' button)
What do you think?

**Comment by mazharoddin** [comment]
Yes @owen2345, that would be clean solution to select multiple images, however creating too many rows for each image may not look good, it may fill out entire page if we try to add 50 or more images, even with pagination browsing multiple images it will be tough, because we can see only image link. 

Instead of showing 'add new field' rows for multiple images, you can try to show thumbnails, later if required you can allow user to move around the thumbnail and delete or edit thumbnail captions etc. but for now I feel showing thumbnails instead of image field with link make sense for more image, moreover if there are more images then it would be easy to paginate.
Pls let me know if  it make sense?

**Comment by owen2345** [comment]
@mazharoddin you are right!
For now I can suggest you to add your custom field, like this:
* Add your custom field option
```
def my_extra_custom_fields(args)
  args[:fields][:my_slider] = {
      key: 'my_slider',
      label: 'My Slider',
      render: theme_view('custom_field/my_slider.html.erb'),
      options: {
          required: true,
          multiple: true,
      },
      extra_fields:[
          {
              type: 'text_box',
              key: 'dimension',
              label: 'Dimensions',
              description: 'Crop images with dimension (widthxheight), sample:<br>400x300 | 400x | x300 | ?400x?500 | ?1400x (? => maximum, empty => auto)'
          }
      ]
  }
end
```
* Create your custom field render
```
<div class="group-input-fields-content" data-callback-render="render_my_custom_slider">
    <div class="form-group">
        <div class="input-group">
            <input data-dimension="<%= field.options[:dimension] %>" data-versions="<%= field.options[:versions] %>" data-thumb_size="<%= field.options[:thumb_size] %>" type="url" name="<%= field_name %>[<%= field.slug %>][values][][image]" class="data-error-place-parent image_field form-control <%= "required" if field.options[:required].to_s.to_bool %>"/>
            <span class="input-group-addon btn_upload" onclick="load_upload_image_field($(this).prev());"><i class="fa fa-upload"></i> <%= t('camaleon_cms.admin.button.upload_image')%> <%= "(#{field.get_option('dimension')})" if field.get_option('dimension').present? %></span>
        </div>
    </div>
    <div class="clearfix">
        <input placeholder="Title" type="text" name="<%= field_name %>[<%= field.slug %>][values][][title]" class="title_field translatable form-control required"/>
        <textarea placeholder="Description" name="<%= field_name %>[<%= field.slug %>][values][][descr]" class="descr_field form-control translatable required"></textarea>
    </div>
</div>
<script>
    function render_my_custom_slider(panel, values){
        values = $.parseJSON(values || '{}');
        panel.find('.descr_field').val(values['descr']);
        panel.find('.title_field').val(values['title']);
        panel.find('.image_field').val(values['image']);
        panel.find('.translatable').Translatable(ADMIN_TRANSLATIONS);
    }
</script>
```
Note: here you can use your custom field structure and custom javascripts where you can initialize drag and drop uploader.
* Use it
```
my_model.the_fields('key_of_the_field')
```

Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345, let me try. Thanks.
