### ISSUE TITLE
Not administrators users editing profile

### ISSUE THREAD

**Issue by RafaelTCostella** [owen2345/camaleon-cms#417]
Hey @owen2345!

I might have found a bug! When an user that does not have permission to edit another users tries to edit his password he gets an unauthorized message.

I found the bug that was around the method validate_role inside users_controller. The main problem is that it was just looking for url param [:id] to find the current user and the form was only sending the param user_id.

I thought in two solutions here:

1-) Add an id hidden input to the form
2-) Normalize the params in controller

I was in doubt which option choose, so I preferred option 2. Do you agree? I made the change in this [PR#416](https://github.com/owen2345/camaleon-cms/pull/416).

Finally, what do you think about adding [devise](https://github.com/plataformatec/devise) to authentication purposes?

**Comment by owen2345** [comment]
Hi @RafaelTCostella 
yes, it is a bug and the correct way to fix is 2.
About devise I am working in that solution, but it will take long time because all users structure is changing...
Regards,

**Comment by RafaelTCostella** [comment]
No problem @owen2345! If you want some help please do not hesitate in contact me! :smile: 

Cheers :beers:
