### ISSUE TITLE
Unable to upload media files.

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#418]
`1). Untitled.png (2.76 KB) 
ERROR: Internal Server Error`

**Comment by owen2345** [comment]
@prdpspkt 
I think the problems is imagemagick, please review the installation of imagemagick and if it is ok, please share me your full error of your console.
Regards,

**Comment by prdpspkt** [comment]
I have installed image-magick in windows as well as image_magick gem in project. Still this error is shown 
`MiniMagick::Error: ImageMagick/GraphicsMagick is not installed
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/configuration.rb:127:in `cli'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick.rb:38:in `graphicsmagick?'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:126:in `executable'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:110:in `command'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:504:in `mogrify'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:395:in `method_missing'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!'`

**Comment by owen2345** [comment]
Apparently the problem is with minimagick + imagemagick dependency and not of Camaleon CMS.
Here some ideas:
http://stackoverflow.com/questions/37331085/rails-error-on-windows-imagemagick-graphicsmagick-is-not-installed
Regards,
