### ISSUE TITLE
Cannot use shortcode

### ISSUE THREAD

**Issue by pannsamnang** [owen2345/camaleon-cms#432]
I cannot use shortcode after updated to lastest version.

**Comment by owen2345** [comment]
Hi @pannsamnang 
I reviewed shortcodes and works well for me, could you please share me a sample? or error logs?

**Comment by pannsamnang** [comment]
@owen2345 the shortcode cannot find the template.
![screenshot from 2016-07-28 09 16 48](https://cloud.githubusercontent.com/assets/16550513/17200117/aec3fa04-54ac-11e6-8126-9e4d559a5463.png)

**Comment by Uysim** [comment]
I think your short code still work. But short code partails show under the themes for plugin view not rails view

**Comment by owen2345** [comment]
Please use this format to be sure the path of the template:
```
theme_view('my_shortcodes/my_slider.html.erb')
```
or
```
plugin_view('my_shortcodes/my_slider.html.erb')
```
Regards,
