### ISSUE TITLE
Work with Devise?

### ISSUE THREAD

**Issue by alexbrinkman** [owen2345/camaleon-cms#434]
If I would like to use Devise for authentication, what level of effort am I looking at to get Devise and Camaleon to work nicely together?  Are there any examples or forks that are using Devise?

**Comment by owen2345** [comment]
This is in progress to change the current authentication process using devise and rails 5 support...
I estimate to finish the next week.
regards,

**Comment by alexbrinkman** [comment]
That is fantastic news.  Thanks for all your hard work!

**Comment by owen2345** [comment]
Yes, but I am having many problems with the multisite support.....

**Comment by alexbrinkman** [comment]
Ugg, well thanks for digging into that, we appreciate it.

**Comment by merongivian** [comment]
#103

**Comment by owen2345** [comment]
Hi @alexbrinkman 
I added this article, where you can see the steps to change authentication into devise:
http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/custom-login.html

Note: This doesn't work for multi-sites and for that reason I couldn't replace the authentication in Camaleon CMS.
Regards,

**Comment by phlcastro** [comment]
@owen2345 I used this [https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain](https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain) and worked like a charm
