### ISSUE TITLE
Reorder in menu does not work.

### ISSUE THREAD

**Issue by stahor** [owen2345/camaleon-cms#435]
Actually I don't see why it should work for there is no field to store order. I suggest using [acts_as_list plugin](https://github.com/rails/acts_as_list)
Should I make pull request?

**Comment by owen2345** [comment]
Hi @stahor 
I tested many times and reorder of menu items works well, could you please tell me more details about the error?
or create a pull request to have more details?
Regards,

**Comment by stahor** [comment]
My bad. I used old version =/
