### ISSUE TITLE
Camaleon App code

### ISSUE THREAD

**Issue by pmandha** [owen2345/camaleon-cms#436]
HI,

Is there a way/rake task to pull all the application code into the current folder. I see some errors and would like to fix them on the fly, but I have no other way but to change the gem code which I don't want to do.

Please provide some inputs here.

Eagerly waiting for response.
Praveen.

**Comment by owen2345** [comment]
There is a way, steps to do:
* Clone CMS in your local machine
* Put the folder within your project or anywhere you want
* Change Gemfile into
```
gem 'camaleon_cms', path: '/my/path/to/camaleon_gem'
```
Regards,

**Comment by pmandha** [comment]
wow thanks that was quick reply.

Thanks for hosting this project too, it definitely saved time for me. Appreciate you efforts.

**Comment by owen2345** [comment]
you're welcome!
If you see errors or bugs, please share me to add in the project, currently I am working hard to change the current login into devise.
Regards,
