### ISSUE TITLE
ActionController::RoutingError - Media routes fail when you use relative_url_root

### ISSUE THREAD

**Issue by jfgrissom** [owen2345/camaleon-cms#437]
Hi,

If you set the value for relative_url_root in system.json (for example to blog).
When you do media uploads the media path that the new image is tied to gets a routing error.

```
ActionController::RoutingError (No route matches [GET] "/blog/media/1/thumb/image.png"):
```

When you remove "blog" from the system.json relative_url_root the routing error goes away.

Also, if you leave the relative_url_root set but remove "blog" from the uri everything works too.
```
# Image works with this uri
/media/1/image/image.png
# Image does not work with this uri
/blog/media/1/image/image.png
```

Thanks,
Jay

**Comment by owen2345** [comment]
please test it using git version.
