### ISSUE TITLE
Draft posts can not be published

### ISSUE THREAD

**Issue by gcrofils** [owen2345/camaleon-cms#442]
## How an authorized user is supposed to publish a draft ? 

This test has been made with an admin user.

### 1. "Published" option is hidden when a post has a "draft" status.

See line 43 of [_sidebar.html.erb](https://github.com/owen2345/camaleon-cms/blob/master/app/views/camaleon_cms/admin/posts/_sidebar.html.erb)

```
<select id="post_status" name="post[status]" class="form-control select">
  <% if can? :publish_post, @post_type %>
    <option class="<%= 'hidden' if @post.draft? %>" value="published" <%= (@post[:status] == "published") ? "selected": "" %> ><%= t('camaleon_cms.admin.post_type.published')></option>
  <% end  %>
  <option value="pending" <%= (@post[:status] == "pending") ? "selected": "" %>><%= t('camaleon_cms.admin.table.pending')%></option>
  <option value="draft" <%= (@post[:status] == "draft") ? "selected": "" %>><%= t('camaleon_cms.admin.table.draft')%></option>
</select>
```

### 2. There is no other available button.

![publishdraft](https://cloud.githubusercontent.com/assets/93443/17431286/daee4834-5b2b-11e6-8266-004749f7f9ae.png)

**Comment by owen2345** [comment]
Fixed!
