### ISSUE TITLE
Feature Request: External Link should have target.

### ISSUE THREAD

**Issue by sanvuthy** [owen2345/camaleon-cms#444]
I think External Link should have option to set target. Just now I could not set target to '_blank'

**Comment by owen2345** [comment]
@sanvuthy you are right!

**Comment by sanvuthy** [comment]
+1

**Comment by owen2345** [comment]
Added!
Please test using git version.
Regards,

**Comment by sanvuthy** [comment]
I don't get it. Please advice me!

**Comment by owen2345** [comment]
This is a screenshot:
![screen shot 2016-09-05 at 09 11 39](https://cloud.githubusercontent.com/assets/1148415/18248858/cb6ab3b8-7348-11e6-996b-9cc3deabd0d2.png)
Please let me know if it is ok.

**Comment by sanvuthy** [comment]
Cool!
