### ISSUE TITLE
Forbidden attributes error

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#446]
It was working before and now doesn't work. it shows this error. Why ?
ActiveModel::ForbiddenAttributesError in CamaleonCms::Admin::SessionsController#login_post

` def sanitize_for_mass_assignment(attributes)
        if attributes.respond_to?(:permitted?)
          _**raise ActiveModel::ForbiddenAttributesError if !attributes.permitted?**_
          attributes.to_h
        else
          attributes `

activemodel (5.0.0) lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
activemodel (5.0.0) lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
activerecord (5.0.0) lib/active_record/core.rb:319:in `initialize'
activerecord (5.0.0) lib/active_record/inheritance.rb:65:in `new'
activerecord (5.0.0) lib/active_record/inheritance.rb:65:in `new'
activerecord (5.0.0) lib/active_record/relation.rb:125:in `block in new'
activerecord (5.0.0) lib/active_record/relation.rb:351:in `scoping'
activerecord (5.0.0) lib/active_record/relation.rb:125:in `new'
camaleon_cms (2.3.0) app/controllers/camaleon_cms/admin/sessions_controller.rb:45:in `login_post'

**Comment by prdpspkt** [comment]
When put email in login box this error appears. But using username works

**Comment by owen2345** [comment]
Fixed!
Tet using git version:
gem "camaleon_cms", github: 'owen2345/camaleon-cms'
