### ISSUE TITLE
Adding custom post type and custom field programmatically. 

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#447]
Camaleon CMS has no documentation for several things. I just make the decision to use it professionally. I want to do several things programmatically. Just wanted to add my post type and my custom fields to that post. Where and how I need to start ?

**Comment by owen2345** [comment]
Hi @prdpspkt 
here you can see many samples for post types, custom fields, posts, ...
https://gist.github.com/owen2345/c3217f0e6e5567b332f8dabbfbe634a6
