### ISSUE TITLE
Where to define current site? 

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#448]
When running in production mode. Console shows that 
`Please define the $current_site = CamaleonCms::Site.first.decorat`
but where and how to define.

**Comment by owen2345** [comment]
Please ignore, it is when you are installing or restarting the server or the access to the rails app was not by a url from where get the domain and look for the site for that domain.
For console access, you can define the $current_site to indicate which Site would you like to use.
