### ISSUE TITLE
rails generate camaleon_cms:install :error" Rais 5

### ISSUE THREAD

**Issue by windowsgit** [owen2345/camaleon-cms#452]
> Hello. I'am  started using camaleon cms with rails 5.0.0
> but at the begining I've already some issues.
> When:
`rails generate camaleon_cms:install`
>It show that error:
```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86)
/var/lib/gems/2.3.0/gems/breadcrumbs_on_rails-3.0.0/lib/breadcrumbs_on_rails/action_controller.rb:16:in `block in <module:ActionController>': undefined method `helper' for ...............................
```
can't continue forward, all needed gems are installed and bundle install work just fine;
Could you help me please..

**Comment by owen2345** [comment]
Fixed!

**Comment by windowsgit** [comment]
Not for rails 5.0.0, 
So i downgrad to rails 4.2.7 to work,

**Comment by owen2345** [comment]
sorry, the fix is still in the git branch and not published in a gem version, to see the fix please the git version:
gem "camaleon_cms", github: 'owen2345/camaleon-cms'

**Comment by windowsgit** [comment]
Thanx a lot owen2345, This works fine !!
