### ISSUE TITLE
How to create/change ecommerce plugin as multi vendor store

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#453]
Hi @owen2345, 
I wanted to create a multi vendor store using camaleon-ecommerce plugin, how easy it would be to modify existing ecommerce plugin to create multi-vendor store.
Here multi vendor store I mean, I would like to allow one of the subdomain(store) users to become as partners/vendors and they should be able to create products and track the orders etc. 
Store index/product listing page should show all products from multiple vendors.

Please let me know how I can achieve this using existing camaleon-ecommerce plugin, if I need to create new plugin provide some sudo code so that I can try. Thanks.

**Comment by owen2345** [comment]
@mazharoddin 
I think the solution is a in your theme where you will list all products from many stores like:
```
Cama::Post.where(post_type_id: Cama::PostType.where(slug: 'commerce').pluck(:id)).visible_frontend
```
Note: Stores are simple PostTypes with slug = commerce
Regards,

**Comment by mazharoddin** [comment]
hi @owen2345 ,

Thanks for the code, above code is useful to list all products from different subdomains(stores). 
But actually what I was looking for is having multiple stores in a subdomain(main store).
Here is what I mean.
```
store.camaleoncms.com ----> main store subdomain
```
Now inside this store subdomain, I wanted to have different vendors, i.e owner of this subdomain will have authority to make any registered user as vendor. 
```
store.camaleoncms.com/vendor1/ -->First vendor
store.camaleoncms.com/vendor2/ -->second vendor
```
So these vendors should be able to create products, list products individually and they should be able to see their orders etc, but one vendor should not be able to see/modify others product listing or orders etc, each vendor should have their separate admin interface. 
 
Please let me know how this can be achieved using new plugin/with existing one.

**Comment by owen2345** [comment]
Ahhh I understand, but the current ecommerce gem will not support that structure, because the ecommerce settings are related to the site and not to the ecommerce post-type.
What about like this:
- main-store.com
- vendor1.store.com
- vendor2.store.com
- vendor3.store.com
Each vendor site is a sub site of main-store.com but with a custom gem you can hide all non-used sections (settings, contents, appariences, ...) to have visible only ecommerce menu.
Regards,

**Comment by mazharoddin** [comment]
Sure, i that works too, please let me know details about that custom gem implementation,  but with this approach each vendor can see their own orders and main store  owner can see all orders and products right? 
Actually I tried to hide other sections by creating new user role(e.g partner), but this new user role user not able to access his own orders/other settings which are related to him.

**Comment by owen2345** [comment]
Yes, with a custom plugin you can see all products in your main store.
With your partner role should works well

**Comment by mazharoddin** [comment]
Thanks @owen2345.
