### ISSUE TITLE
Change history

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#459]
Is there a list of changes available somewhere?

We are on 2.1.2.6 now, looking to upgrade to the current stable version.

Thanks!

**Comment by owen2345** [comment]
Hey @p-decoraid 
I updated the changelog for camaleon cms:
http://camaleon.tuzitio.com/version-history.html
Regards,

**Comment by p-decoraid** [comment]
Thanks, this is great.
