### ISSUE TITLE
2.1.2.6 tag missing

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#460]
We are using gem version 2.1.2.6 and there does not appear to be a corresponding tag in this github repo.

A bunch of other releases seem to also be missing (e.g. anything between 2.1.2.1 and 2.1.2.5).

**Comment by p-decoraid** [comment]
This release is also not on rubygems.

**Comment by owen2345** [comment]
Hey @p-decoraid 
I reviewed all logs and 2.1.2.6 was never released, the last version for 2.1.x is 2.1.2.1 and after is 2.2.0.
Anyhow I published  this version 2.1.2.1 into ruby gems.
Regards,

**Comment by p-decoraid** [comment]
Okay thanks, that's interesting. I wonder where this 2.1.2.6 version came from then.
