### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#461]
* Site hangs every month or so and the application server needs to be restarted. The instances of the application are staying around.
* The application is using an excessive amount of memory after some time. It's currently using 4.2 GB of memory!

**Comment by owen2345** [comment]
Hi @cmckni3! 

What version are you using?
I am using 2.2.1 in camaleon site with 991 demonstration sites and it is using 2.4GB of memory.
Previous to 2.2.1 the helpers of current theme + helpers of installed plugins was loading on demand which was changed to avoid that kind of problems.

Regards,

![performace](https://cloud.githubusercontent.com/assets/1148415/17755607/df04077a-64a8-11e6-85f4-83c927b72b3c.png)

**Comment by cmckni3** [comment]
I'm running 2.1.2 but I don't want to update if it's going to break the entire site.

**Comment by owen2345** [comment]
Ufffff, then:
maybe you can add this change manually:
* Add this in the line 28
```
PluginRoutes.all_helpers.each{|h| include h.constantize }
```
* Comment the line 55.

   https://github.com/owen2345/camaleon-cms/blob/2.1.1/app/controllers/camaleon_cms/camaleon_controller.rb

By this way you can avoid to load helpers for every request.
Regards,

**Comment by cmckni3** [comment]
```
undefined method `all_helpers' for PluginRoutes:Class
```

**Comment by owen2345** [comment]
Here is the function:
https://github.com/owen2345/camaleon-cms/blob/master/lib/plugin_routes.rb#L183

**Comment by cmckni3** [comment]
Yeah I added it
