### ISSUE TITLE
How to create mobile app for Camaleon CMS and subdomains

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#462]
Hi @owen2345,
Can you please let me know how to create mobile for camaleon website and its subdomain. 
it would be great if you can suggest a way to access camaleon subdomain sites by creating a mobile app. Thanks.

**Comment by owen2345** [comment]
Hi @mazharoddin ,
I think you need to use the api mode of rails and using the helper method of camaleon cms:
current_site() which get the Site according to your domain/subdomain,...
Regards,

**Comment by mazharoddin** [comment]
Thanks @owen2345, yeah using API we can create an app, but just wondering is there any other way to create it.

**Comment by owen2345** [comment]
For now there is not other way, in the future I will create a small API plugin for camaleon ready to integrate with AngularJS.
Regards,

**Comment by mazharoddin** [comment]
ohh ok, Thanks @owen2345 ..
