### ISSUE TITLE
TinyMCE Templates

### ISSUE THREAD

**Issue by Dariusch** [owen2345/camaleon-cms#463]
Hello,
there is an active TinyMCE [template Plugin](https://www.tinymce.com/docs/plugins/template/#makingtemplates) for the editor, but nowhere to define a template.
https://github.com/owen2345/camaleon-cms/blob/master/app/assets/javascripts/camaleon_cms/admin/_data.js#L6
Shortcodes and Widgets are a nice thing but not very handy regarding a pure customizable css template like the one from tinyMCE

regards

**Comment by owen2345** [comment]
Hi @Dariusch ,
I added extra settings for tinymce which permit to customize all settings, sample:
```
tinymce_global_settings["settings"].push(oo);
function oo(custom_settings, def_settings){
    def_settings['plugins'] += ' my_plugin';
}
```
Please use git version for testing.
Regards,

**Comment by Dariusch** [comment]
Hi Owen, 
its nice to be able to add custom plugins but my question was rather, how I can define a template for the tinyMCE Editor to be inserted?
The Menu is Insert -> Insert Template and the flash message is "No templates defined."

**Comment by owen2345** [comment]
Hi @Dariusch 
you can do it like this:
https://www.tinymce.com/docs/plugins/template/
Add your templates into templates attribute, like:
```
function oo(custom_settings, def_settings){
    def_settings['templates'] = def_settings['templates'] || [];
    def_settings['templates'].push({title: 'Some title 1', description: 'Some desc 1', content: 'My content'});
}
```
Regards,

**Comment by Dariusch** [comment]
Hi Owen,
I still don't get where to use this function. TinyMCE is a JavaScript based Editor.
My Setup is a Rails App where the CMS is plugged in via the Gemfile, as described in your README.md.

**Comment by owen2345** [comment]
Hi @Dariusch,
use the hook "admin_before_load" to add your custom javascript:
```
def my_hook_function
  append_asset_libraries({“my_library”=>{js: [plugin_asset("js/my_custom_js")] } })
end
```
my_custom_js.js must contain like this:
```
tinymce_global_settings['settings'].push('my_custom_function');
// this function is called to customize the default params used for tinymce, where you will receive two args: 
//   custom_settings: extra settings sent by callers
//   def_settings: default settings defined for camaleon cms
function my_custom_function(custom_settings, def_settings){
    def_settings['templates'] = def_settings['templates'] || [];
    def_settings['templates'].push({title: 'Some title 1', description: 'Some desc 1', content: 'My content'});
}
```
Please let me know if this is clear.
Regards,

**Comment by Dariusch** [comment]
Hey Owen,
I found another little bug.
`tinymce_global_settings['settings'].push('my_custom_function');`
this should be
`tinymce_global_settings['settings'].push(my_custom_function);`
without the quotations it works as expected.
Maybe you can add this to the documentation some time.

thank you, Dariusch

**Comment by owen2345** [comment]
Hi @Dariusch,
you are right, sorry for my typing error.
Regards,

**Comment by CodeElegance** [comment]
Small note:
In the readme for the tinyMCE custom template plugin, it states:
`def my_theme_admin_before_load
    append_asset_libraries({"my_tinymce"=> { js: [theme_asset("my_tinymce_templates")]}})
end`
But this results in a file not found for the file.  It should be:
`def my_theme_admin_before_load
    append_asset_libraries({"my_tinymce"=> { js: [theme_asset("js/my_tinymce_templates")]}})
end`
('js/' before the file name)
However, I'm VERY new to the CMS (1 day), so that may not be the bet way to do it.

**Comment by owen2345** [comment]
I agree with you @CodeElegance!
Updated.
Thank you!
