### ISSUE TITLE
Checkbox and Checkboxes in Custom Fields not working proerly

### ISSUE THREAD

**Issue by Dariusch** [owen2345/camaleon-cms#464]
Hello,
there is an Issue with the CustomFields checkbox and checkboxes. 
When I add a checkbox to lets say a Post the value does not get properly saved.
When I add a group of checkboxes somehow only the last value gets saved.

regards Dariusch

**Comment by Dariusch** [comment]
https://github.com/owen2345/camaleon-cms/pull/465 is for multiple Checkboxes
Later today I will try to fix the single checkbox Issue

**Comment by owen2345** [comment]
Fixed the real problem, thanks for the report!

**Comment by Dariusch** [comment]
You are welcome.
Problem seems to be solved.
Thank you!
