### ISSUE TITLE
Setting Custom Homepage Via Theme Settings in Default Theme Not Working Correctly

### ISSUE THREAD

**Issue by DopplerRedshift** [owen2345/camaleon-cms#467]
Camaleon CMS: v2.3.0
Ruby: v2.3.1p112 revision 54768
Rails: v4.2.7

Recreating the Problem:  Using the default theme, I went to the _Theme Settings_ section and changed the _Home Page_ value to a new test page I had created.  This worked and the selected page loaded as the homepage.  However, changing it back to the default home page does not.  I've been debugging this issue and have some details about the database queries causing the improper page to display on the homepage:
- The database query that writes the new page id (slug) to be used for the home page when the user updates the theme settings works fine, as this query performed when the home page loads returns the proper value:

`SELECT cama_custom_fields_relationships.value FROM cama_custom_fields_relationships WHERE cama_custom_fields_relationships.objectid = 26 AND cama_custom_fields_relationships.object_class = 'Theme' AND cama_custom_fields_relationships.custom_field_slug = 'home_page' AND cama_custom_fields_relationships.group_number = 0  ORDER BY cama_custom_fields_relationships.term_order ASC`

This returns '2', which is the correct slug for the page I have set in the Theme Settings (this is the slug for the default page).
- However, the next query does not return the correct result:

`SELECT  cama_posts.* FROM cama_posts INNER JOIN cama_term_taxonomy ON cama_posts.taxonomy_id = cama_term_taxonomy.id WHERE cama_posts.post_class = 'Post' AND cama_term_taxonomy.taxonomy = 'post_type' AND cama_term_taxonomy.parent_id = 1 AND cama_posts.status = 'published' AND cama_posts.slug = '2' LIMIT 1`

This uses the correct post slug in the query, but returns `Empty set` - which it should not

As a result of the previous query returning `Empty set`, and I'm sure as a necessity to return at least one post, an additional query is made:

`SELECT  cama_posts.* FROM cama_posts INNER JOIN cama_term_taxonomy ON cama_posts.taxonomy_id = cama_term_taxonomy.id WHERE cama_posts.post_class = 'Post' AND cama_term_taxonomy.taxonomy = 'post_type' AND cama_term_taxonomy.parent_id = 1 AND (cama_term_taxonomy.slug = 'page') AND cama_posts.status = 'published'  ORDER BY cama_posts.post_order ASC, cama_posts.created_at DESC LIMIT 1`

This query returns the most recent post, which is the test page I made, and displays it as the home page instead of the selected page due to the `Empty set` return from above. Please look into this issue, and if you have any questions please let me know.  Thank you.

**Comment by owen2345** [comment]
Hi @DopplerRedshift ,
Please upgrade to 2.3.3 because that version has a typing error.
Regards,

**Comment by DopplerRedshift** [comment]
Actually, this problem persists even with the update.  It's still not displaying the correct homepage, and now I'm running Camaleon v2.3.3 - I've tried changing the homepage and re-saving to update the database, but it still won't display the welcome page as the homepage anymore. I've gone through the standard set of update commands to ensure I have the latest version of Camaleon:

1. I edited the Gemfile to update the version number for the `camaleon_cms` gem to be `'>=2.3.3'`
2. I then ran `bundle update` to update the installbase
3. Then I ran `rake db:migrate` to update the database
4. I restarted the web server (Apache/httpd)

It does indeed show the new version, but the problem persists.  Thanks!

**Comment by DopplerRedshift** [comment]
The problem seems to be with the `cama_posts.slug = '2'` call in the query of:

`SELECT  cama_posts.* FROM cama_posts INNER JOIN cama_term_taxonomy ON cama_posts.taxonomy_id = cama_term_taxonomy.id WHERE cama_posts.post_class = 'Post' AND cama_term_taxonomy.taxonomy = 'post_type' AND cama_term_taxonomy.parent_id = 1 AND cama_posts.status = 'published' AND cama_posts.slug = '2' LIMIT 1`

Since cama_posts.slug is a varchar(255) and contains the page names, not the id's, it will never return any results.  Changing the query to `cama_posts.id = '2'` fixes the problem and gives me the proper page.  Can you make this change to the CMS please?  Thanks Owen!

**Comment by owen2345** [comment]
@DopplerRedshift 
I tested the problem in 2.3.3 and it works well, please check the video and let me know if it the situation:
http://screencast.com/t/QiUTMTFz

**Comment by DopplerRedshift** [comment]
I can see in the screencast you provided that it works just fine on your system.  Oddly enough, it still doesn't work properly on mine.  I've created fresh installs, tried using sqlite and mysql (just for testing), and I still get this issue.  It's very odd that it's working on your system and not on mine.  Everything else appears to be functioning just fine.  Any ideas?

**Comment by owen2345** [comment]
@DopplerRedshift 
please contact me on skype to review the problem: owen-2345
