### ISSUE TITLE
adding gem to my plugin

### ISSUE THREAD

**Issue by killinit** [owen2345/camaleon-cms#468]
I have created API for Camaleon CMS.
Its a start but will develop it more.
now it is just a part of my base system.

I wanted to move it to a plugin and publish it for everybody.

Question:
How to add dependent gems to plugin?

or should I just add it to camaleon-cms gem?

**Comment by owen2345** [comment]
Hi @killinit ,
When you create a plugin for Camaleon cms the structure is like this (rails gem structure):
https://github.com/owen2345/cama_contact_form
Then, you can add your gem dependencies in my_plugin_name.gemspec
Regards,
