### ISSUE TITLE
Test suite does not run

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#470]
After doing #469 the tests still do not run:

<pre>
bundle exec rspec
bundler: failed to load command: rspec (/home/oleg/.rbenv/versions/2.3.1/bin/rspec)
LoadError: cannot load such file -- /home/oleg/apps/exp/camaleon-cms/config/environment
  /home/oleg/apps/exp/camaleon-cms/spec/rails_helper.rb:4:in `require'
  /home/oleg/apps/exp/camaleon-cms/spec/rails_helper.rb:4:in `<top (required)>'
  /home/oleg/apps/exp/camaleon-cms/spec/decorators/post_type_spec.rb:1:in `require'
  /home/oleg/apps/exp/camaleon-cms/spec/decorators/post_type_spec.rb:1:in `<top (required)>'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `load'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `each'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:100:in `setup'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:86:in `run'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
  /home/oleg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/exe/rspec:4:in `<top (required)>'
  /home/oleg/.rbenv/versions/2.3.1/bin/rspec:23:in `load'
  /home/oleg/.rbenv/versions/2.3.1/bin/rspec:23:in `<top (required)>'
</pre>

There is no config/environment.rb in this project, not sure what to do here.

**Comment by mazharoddin** [comment]
Not sure if you are trying to address some other issue, but I could able to run test suite using this  command 'rake camaleon_cms:rspec'.

Earlier I used to get Firefox connection error, but after degrading Firefox to version 20, now I am able to run all test cases using above command. There are failures, but most of the suite is working fine.

**Comment by p-decoraid** [comment]
@mazharoddin are you running that from camaleon-cms repository or from your own project that uses camaleon-cms?

**Comment by mazharoddin** [comment]
Hi @p-decoraid, I am running the specs from my own project which uses  camaleon-cms ...

**Comment by p-decoraid** [comment]
That is what I figured, thanks.
