### ISSUE TITLE
Assigning Custom Field Group to Users has no effects.

### ISSUE THREAD

**Issue by pbr-pl** [owen2345/camaleon-cms#477]
Assigning (by selecting "Where to display this group")  Custom Field Group to Users has no effects. When I assign this Custom Field Group to Post or Page I can see new fields when I edit/add Post or Page. Doing the same with Users has no effect

**Comment by owen2345** [comment]
Hi @pbr-pl 
I solved the problem, please test again using git version.
Regards,
