### ISSUE TITLE
Use only Admin portal of Camaleon with Rails 4 application

### ISSUE THREAD

**Issue by Bilkhaan** [owen2345/camaleon-cms#483]
Hi,

I have existing rails 4 application. I wanted to use a cms with it.

I have added camaleon gem and followed the steps mentioned in read me. I have noticed that it tries to use my root_url and i have root set already in to my home view. I am able to view my rails view but it breaks some functionality. The reason can be that camaleon is not quering my user model at all as you can see in attached screenshot.

<img width="1440" alt="screen shot 2016-09-02 at 3 25 45 am" src="https://cloud.githubusercontent.com/assets/13800703/18186578/f71d9edc-70bc-11e6-9b1f-e59e5bf0b1bb.png">

Another issue is that now i am unable to use current_user provided by devise. If i comment the root route in route file then root points to welcome view of camaleon. Although the Admin portal works fine.

Is there any way to use just the admin panel without disturbing the existing views and functionality.

**Comment by owen2345** [comment]
Hi @Bilkhaan,
I fixed the problem, please verify using git version.
Regards,
