### ISSUE TITLE
Rails console not running

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#485]
When I try to run rails console. I get this error.
I'm using rails 5
rails c
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/pradeep/cms/config/application.rb:7)
/var/lib/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:49:in `initialize': wrong number of arguments (given 0, expected 2) (ArgumentError)
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in `new'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in `block in controller'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:in `tap'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:in `controller'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:30:in `call'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/view_context.rb:49:in `build'
	from /var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/railtie.rb:63:in `block in <class:Railtie>'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `block in run_console_blocks'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each_registered_block'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `run_console_blocks'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `block in run_console_blocks'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `run_console_blocks'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:442:in `load_console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:34:in `initialize'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `new'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by owen2345** [comment]
Hi @prdpspkt,
I solved the problem by:
```
bundle udpate 
```
Please let me know if it works well for you too.
Regards,

**Comment by p-decoraid** [comment]
>>  /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

May want to fix that

**Comment by sahilchopra** [comment]
I am getting following error

.rvm/gems/ruby-2.3.0@cms/gems/actionpack-5.0.0.1/lib/action_controller/test_case.rb:49:in initialize': wrong number of arguments (given 0, expected 2) (ArgumentError) from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:innew'
from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in block in controller' from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:intap'
from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:in controller' from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:30:incall'

**Comment by owen2345** [comment]
Hi @sahilchopra,
I had the same problem and I fixed with bundle update and now it works well:

![screen shot 2016-09-12 at 09 21 31](https://cloud.githubusercontent.com/assets/1148415/18437311/57f92054-78ca-11e6-823c-4ac5f1e1dfa3.png)

please try again if the error persist please let me know your OS to reproduce the problem.
Regards,

**Comment by owen2345** [comment]
Add this in your Gemfile
gem 'draper', github: 'audionerd/draper', branch: 'rails5'
