### ISSUE TITLE
How can I Override FrontendController

### ISSUE THREAD

**Issue by huyngvu** [owen2345/camaleon-cms#492]
I tried with class_eval do but not have effect

**Comment by owen2345** [comment]
Hi @huyngvu,
I tried with this and it worked well:
```
# config/initializers/cama_custom.rb
Rails.application.config.to_prepare do
  CamaleonCms::FrontendController.class_eval do
    def index
      puts "@@@@@@@@@@@@@@@@@@@@@@"
      render 'my_custom_template'
    end
  end
end
```
Regards,

**Comment by huyngvu** [comment]
Hi @owen2345,

I have another solution for this case. I think help me easy to control the override of model / controller

`# config/initializers/override_configuration.rb`
`Dir.glob(File.join(Rails.root, 'app/**/*_decorator*.rb')) do |c|`
`  Rails.configuration.cache_classes ? require(c) : load(c)`
`end`

And now I can create the decorator for controller / model in app. 
For `example app/controllers/camaleon_cms/frontend_controller_decorator.rb`

Correct me if i'm wrong
Regards,

**Comment by owen2345** [comment]
@huyngvu yes, it is ok!, but I am not sure if it will work well. (could you please test it?)
All my customizations until now I did using the class_eval as my previous comment.

**Comment by huyngvu** [comment]
@owen2345 yes, i tested and it works.

Here is my `app/controllers/camaleon_cms/frontend_controller_decorator.rb`
`CamaleonCms::FrontendController.class_eval do`
`  def index`
`    byebug`
`    puts "@@@@@@@@@@@@@@@@@@@@@@"`
`    render 'my_custom_template'`
`  end`
`end`

**Comment by owen2345** [comment]
great!
