### ISSUE TITLE
Theme per Site

### ISSUE THREAD

**Issue by killinit** [owen2345/camaleon-cms#493]
Is it possible to add different Theme for different Site ?

**Comment by owen2345** [comment]
Yes, you can have many themes and each one can be installed in many sites or each theme for each site.
Regards,

**Comment by killinit** [comment]
ok Can You tell me how to set up it?
Should I change dashboards?

One more question can I set up user permissions to separate Site instance??

**Comment by owen2345** [comment]
About your question of permissions, you have a setting in your config/system.json
```
"users_share_sites": true, //(boolean, default true) true: permit to share users between sites, false: All users are assigned for an unique site.
```
About themes: For each site you can set the theme in admin->appearances -> themes -> select your theme (that's all)
Regards,
