### ISSUE TITLE
Default site_id is -1

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#499]
I ran into this in #498  - is there a reason why the default site_id is -1 and not null/nil?

**Comment by owen2345** [comment]
This is to support users shared between sites.
check this comment:
https://github.com/owen2345/camaleon-cms/pull/498#issuecomment-250519649

**Comment by p-decoraid** [comment]
I'm saying a null value should work as well as -1 and be in line with rails conventions.

**Comment by owen2345** [comment]
You are right! I will change for the next version.

**Comment by p-decoraid** [comment]
Thanks!
