### ISSUE TITLE
Dynamic URLs for pagination

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#505]
Hi @owen2345, 
please let me know how to remove/re-route dynamic URLs, which are generated from pagination. 
As per google dynamic URLs need to removed or re-routed to static URL, otherwise it will impact page and site rankings..so pls let me know how to route them as static URLs.
e.g.

```
http://example.com/sell?page=4 
http://example.com/sell?page=5
```

**Comment by owen2345** [comment]
Hi @mazharoddin 
where are generated this url's?

Regards,

**Comment by p-decoraid** [comment]
I don't think these urls have defined routes, hence the task would be to add such routes rather than change them. The urls are probably generated by will_paginate in the naive fashion of appending page=X param to the current params.

**Comment by mazharoddin** [comment]
hi @owen2345, these URLs are generated by one of my custom post type, I created one custom post type and added multiple posts, so that custom post type pagination generated these URLs.

**Comment by owen2345** [comment]
It is the pagination generated by will_paginate gem, if you don't want this, please edit the template as you want.
