### ISSUE TITLE
Localization TinyMCE

### ISSUE THREAD

**Issue by ramensoup** [owen2345/camaleon-cms#51]
Is it possible to locate TinyMCE with the language setting of Camaleon CMS ? When I change the language of the CMS, the language of TinyMCE doesn't change

**Comment by owen2345** [comment]
Done!
please bundle update to update the version.

**Comment by ramensoup** [comment]
Ok, thank you very much!
Il 03/09/2015 11:29, Owen Peredo Diaz
      ha scritto:
>Done!
>please bundle update to update the version.
>—
>Reply to this email directly or  view
          it on GitHub .
--
Stefano Pau<br>
Soc. Coop. welaika<br>
<a href="http://dev.welaika.com/">http://dev.welaika.com/</a>
