### ISSUE TITLE
Favicon Causes DNS issues. 

### ISSUE THREAD

**Issue by ajmyers01** [owen2345/camaleon-cms#510]
How are you hosting the Favicon for the chameleon favicon that site defaults to when no favicon is set ? 

It seems when you don't set a favicon it tries to use that default icon and messes with the DNS and seems to inject the hosted favicon host into the URLS inside the application. 

Example of Injection ![](https://dl.dropboxusercontent.com/spa/l2plmwrbl136qhn/-n6hu86t.png)

It seems that upon setting a favicon it eliminates the problem but I think this might be an issue with the core of the application. @owen2345

**Comment by owen2345** [comment]
@ajmyers01 
I tried to find the problem but without success, could you please give me steps to reproduce the problem?
