### ISSUE TITLE
Theme settings missing

### ISSUE THREAD

**Issue by killinit** [owen2345/camaleon-cms#513]
HI.
I have created new theme using:
rails g camaleon_cms:theme my_theme

Problem:
CamaleonCms::Site.first.get_theme.settings 
is nil ...

and I cannot get list of templates in post_type settings

**Comment by owen2345** [comment]
Hi @killinit ,
I tried to reproduce your problem but without success, see below for results:
![screen shot 2016-10-18 at 13 14 16](https://cloud.githubusercontent.com/assets/1148415/19488379/a051e38c-9534-11e6-92c5-50098978e0cb.png)
Maybe your theme is not installed.
Regards,
