### ISSUE TITLE
How to route subdomain to its own domain

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#514]
I am facing some issue while routing subdomain to its own domain, I updated the CNAME, but still if I access subdomain domain name, its taking to root domain name instead of subdomain domain name.
e.g.
I have a subdomain at blog.example.com, now I wanted to route blog.example.com to http:// blog.com, so I updated CNAME of blog.com as below.
```
www 	CNAME 	blog.example.com 	NA 	3603* 	3rd-party
```
but now if I access blog.example.com, I re-routed to http:// example.com  instead of http:// blog.com. 
Please let me know how to resolve this. Looks like some setting I am missing.

**Comment by owen2345** [comment]
@mazharoddin 
Please change the slug (domain) of your site in the DB, table name "cama_taxonomies".

**Comment by mazharoddin** [comment]
Thanks @owen2345 ..I will try it..

**Comment by mazharoddin** [comment]
Hi @owen2345,
I tried to change the slug as below, but still its not working.
```
=> UPDATE cama_term_taxonomy SET slug = 'demo.com' WHERE slug = 'demo';
UPDATE 1
```
I have a subdomain called demo.example.com and I updated CNMAE to route it to http://demo.com ..also updated db table as you suggested, but still if I access http://demo.example.com its routing to http://example.com instead of http://demo.com

**Comment by owen2345** [comment]
Please in your console enter this:
```
Cama::Site.all.pluck(:slug)
```
and let me know the results.

**Comment by mazharoddin** [comment]
Hi @owen2345,
Here is the o/p.
```
irb(main):001:0> Cama::Site.all.pluck(:slug)
   (0.8ms)  SELECT "cama_term_taxonomy"."slug" FROM "cama_term_taxonomy" WHERE "cama_term_taxonomy"."taxonomy" = $1 ORDER BY "cama_term_taxonomy"."term_group" DESC  [["taxonomy", :site]]
=> ["kisanly", "shopick", "shopper.com", "mazhar", "help", "demo.com", "indadent", "trendynhealthy", "aijaz"]
```
I wanted to route  http://trendynhealthy.shopper.com to http://trendynhealthy.com, thanks.

**Comment by mazharoddin** [comment]
Hi @owen2345,
Here is the o/p.
```
irb(main):001:0> Cama::Site.all.pluck(:slug)
   (0.8ms)  SELECT "cama_term_taxonomy"."slug" FROM "cama_term_taxonomy" WHERE "cama_term_taxonomy"."taxonomy" = $1 ORDER BY "cama_term_taxonomy"."term_group" DESC  [["taxonomy", :site]]
=> ["kisanly", "shopick", "shopper.com", "mazhar", "help", "demo.com", "indadent",  "aijaz"]
```
I wanted to route  http://shopick.shopper.com to http://shopick.com. Thanks.

**Comment by owen2345** [comment]
Please change "shopick" into "shopick.com" because without the extension it is working as a subdomain.

**Comment by mazharoddin** [comment]
Yes, I changed as you mentioned, but its routing to main domain(shopper.com) if I try to access http://shopick.com

**Comment by owen2345** [comment]
mmmm Please contact me on Skype to review more.
It is strange!

**Comment by mazharoddin** [comment]
Sure @owen2345
