### ISSUE TITLE
Creating a folder in image uploader should clear cache

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#517]
Currently when a folder is created in the image uploader it does not show up in the list of files/folders. After the cache is cleared manually, the new folder shows up. The current behavior makes one think folder creation failed when it in reality succeeded.

**Comment by p-decoraid** [comment]
I see that the added folder does appear when the parent folder has few elements in it. When creating subfolders in a folder with 1500+ files in it the subfolder does not appear without clearing the cache manually.

**Comment by owen2345** [comment]
Please try again, this should solved by https://github.com/owen2345/camaleon-cms/issues/519
