### ISSUE TITLE
Image uploader caching is not scalable

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#518]
Image uploader loads the entire bucket into the cache on any request. This means the time to open the uploader is proportional to the total size of the bucket, rather than to the size of folder being viewed/operated on.

**Comment by owen2345** [comment]
Hi @p-decoraid 
Camaleon CMS is caching the bucket data in the DB to optimize (The api doesn't permit to load data only for specific folder).

**Comment by p-decoraid** [comment]
> The api gem doesn't permit to load data only for specific folder

Sure it does...

**Comment by p-decoraid** [comment]
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_objects_v2-instance_method, pass the folder as prefix.

**Comment by owen2345** [comment]
@p-decoraid you are right.
Added the optimization!
