### ISSUE TITLE
Edit link visible when viewing post category while logged out

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#520]
![image](https://cloud.githubusercontent.com/assets/21235090/19451418/ccf428e0-9472-11e6-82a9-32829f5bddbf.png)

This edit link remains when logged out. It directs to the edit page for the category or post type (redirects to admin/login when user is not logged in).

This problem occurs on the following pages:

- mydomain.com/category/somecategory
- mydomain.com/post

**Comment by owen2345** [comment]
Hi @briank-musichouse 
Could you please show me the rails code of your title?
Regards,

**Comment by briank-musichouse** [comment]
I'm not sure which code you mean. This is happening with the default theme of a new Camaleon installation (folder=camaleon_first). As I understand it, themes in Camaleon from the default theme for views not present in the current theme folder, so these pages get their views from app/apps/themes/default/views/.

Assuming this is correct, here is category.html.erb:
`<article id="category-view" class="category_<%= @category.slug %>">
    <div class="panel panel-primary post_list no-line">
        <div class="panel-body">
            <div class="row">
                <% @posts.each_with_index do |post, index| %>
                    <%= raw "<div class='clearfix'></div>" if index%3 == 0 && index > 0 %>
                    <%= render partial: 'partials/post_list_item', locals: {post: post.decorate} %>
                <% end %>
            </div>
            <%= content_tag("div", raw(ct('no_contents_found', default: 'No contents found')), class: "alert alert-warning") if @posts.empty? %>
            <%= raw cama_do_pagination(@posts) %>
        </div>
    </div>
</article>
`

And here's post.html.erb:
`<article id="post" >
    <header class="entry-header">
        <% if @post.has_thumb? %>
            <div class="entry-thumbnail">
                <%= raw @post.the_thumb %>
            </div>
        <% end %>
        <h1 class="entry-title"><%= @post.the_title %></h1>
    </header>
    <div class="entry-content">
        <%= raw @post.the_content %>
    </div>
    <footer class="entry-meta">
        
        <% if @post.render_fields.present? %>
            <hr>
            <h4><%= ct("extra_attributes", default: 'Extra Attributes') %></h4>
            <%= raw @post.render_fields %>
        <% end %>
    </footer>
</article>
<%= render partial: 'partials/comments', locals: {post: @post} if @post.can_commented? %>`

**Comment by owen2345** [comment]
I reviewed your code and there is not exist the code to shoe the edit link, like:
```
<h1><%= @post.the_title %> <%= @post.the_edit_link %></h1>
```
Maybe you are using some plugin which is adding the edit link.
Regards,

**Comment by briank-musichouse** [comment]
I turned all plugins off, but nothing changed.

I think I may have found the problem. Both CategoryDecorator and PostTypesDecorator inherit from TermTaxonomyDecorator, which doesn't verify login in the_edit_link method. Can you take a look at camaleon-cms/app/decorators/camaleon_cms/term_taxonomy_decorator.rb:74 and see if that may be the problem?

Thanks for the fast response, I appreciate it!

**Comment by owen2345** [comment]
Added the restriction! Please try again.

**Comment by briank-musichouse** [comment]
That fixed it, thanks!
