### ISSUE TITLE
Request: async loading with cama_draw_custom_assets

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#521]
camaleon-cms/app/helpers/camaleon_cms/html_helper.rb:84

I would like to be able to load javascript assets asynchronously when appending them with the cama_draw_custom_assets method. It seems like this would be easy to do globally by modifying the line above, but allowing for async to be set optionally (globally or per asset) is probably better, and beyond me at this point.

**Comment by owen2345** [comment]
Hi @briank-musichouse 
I added a new hook "draw_custom_assets" to customize the print of the html.
Sample:
```
def my_hook(args)
  args[:js_html] = javascript_include_tag *args[:javascripts], async: true
end
```
Note: Please test using git version.
Regards,

**Comment by briank-musichouse** [comment]
That works, thank you!
