### ISSUE TITLE
Multi Site: How to assign users to specific sites only?

### ISSUE THREAD

**Issue by mayinx** [owen2345/camaleon-cms#525]
Hi there! 

I'm trying to setup a multi-site solution with camaleon-cms (great CMS by the way!) - the default-/main-site is edmeda.de - now I'd like to setup further sites - same via a key / subdomain (fubar.edmeda.de) others via a domain (my_domain.com)...  That seems to work great so far, but I got some troubles when it comes to user management: How do I create and assign users to specific sites only (it seems that every user I create can access each site)? And I'm missing a list view or something that shows the assigned users per Site ....   

Cheers 
Mayinx

**Comment by mazharoddin** [comment]
Hi @mayinx, 
Camaloen CMS allows you to share users across the sites or you can have each site has different users. This you can achieve using system.json file.
```
"users_share_sites": false, //(boolean) true: permit to share users between sites, false: All users are assigned for a unique site. (Only changed before installation)
```

**Comment by mayinx** [comment]
Ah - that worked - thanks a lot, mate! I didn't know about the config/system.json - would be great if this info could be added to the readme or a github-wiki-page ....

**Comment by mazharoddin** [comment]
Sure, np.

**Comment by mayinx** [comment]
Hi again,

I got another "multi site question" (not quite sure if I shall post it here or as a new "issue"?):

Camaleon CMS seems to create default user accounts (admin + client) per newly created site / subdomain - what is the best option / "the Camaleon-way" to hook into this process (programmatically)? To be precise: When a new site / subdomain is created I'd like to ...

a) ... create further user records (& change same attributes of the default user records)
b) ... create a default site structure (menus with pages & sub-pages / nested pages etc.)  
c) ... set a specific layout as default layout     

Cheers
Mayinx

**Comment by mazharoddin** [comment]
Hi, 
You can create helpers files to create user records and default site structure and hook them using system.json fin as below.
```
"hooks": {
  "on_uploader": [
      "aws_s3_for_all_subdomains"
    ]
  }
```
You can specify any theme as default theme by specifying in system.json file.
```
 "default_template": "shop", // default template name for new sites
```

**Comment by mayinx** [comment]
Cheers, mate - thanks to your hints, the [ "Camaleon- Create Theme"-videos](http://camaleon.tuzitio.com/documentation/category/40758-modules/themes-2.html) + this [gist](https://gist.github.com/owen2345/c3217f0e6e5567b332f8dabbfbe634a6) I was able to sort things out ... and I must say: Holy cow - Camaleon CMS is frackin' awesome - big kudos to the creator(s) / contributors! (why is Camaleon not listed in the [Ruby Toolbox among the top Rails-CMS](https://www.ruby-toolbox.com/categories/content_management_systems) where it definitely belongs?)

**Comment by mazharoddin** [comment]
Sure, np, yeah, looks like Owen didn't added to CMS list at ruby toolbox.

**Comment by owen2345** [comment]
yes, it is registered!
https://www.ruby-toolbox.com/gems/camaleon_cms
But I don't know how to update. hehe!

**Comment by mayinx** [comment]
Hi Owen - I'm not quite sure but it seems one has to ask the toolbox-guys specifically to add a gem to a certain category - which I did over here: [Add uncategorised gem to a existing category](http://help.ruby-toolbox.com/discussions/problems/11-add-uncategorised-gem-to-a-existing-category) - hopefully they will react ...

**Comment by owen2345** [comment]
cool, thank you very much!
