### ISSUE TITLE
Sprockets::Rails::Helper::AbsoluteAssetPathError in Admin::Sessions#login 

### ISSUE THREAD

**Issue by sarbazx** [owen2345/camaleon-cms#53]
getting this error when entering admin panel
![admin](https://cloud.githubusercontent.com/assets/5629946/9727309/2299421c-5630-11e5-92dc-b792cab4b9f1.png)

and also when entering Frontend panel.
![frontend](https://cloud.githubusercontent.com/assets/5629946/9727319/433d0774-5630-11e5-871e-5212d2d216c7.png)

**Comment by owen2345** [comment]
Hello Taskhyn,
please send me your:
- ruby version
- rails version
- SO and version
because I tried to reproduce that error but without success.

**Comment by owen2345** [comment]
Fixed!
