### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#530]
I got this message in my Rails 5 app:

DEPRECATION WARNING: Passing the separator argument as a positional parameter is deprecated and will soon be removed. Use `separator: '.'` instead. (called from upload_file at /gems/camaleon-cms-44d719d527dc/app/help
ers/camaleon_cms/uploader_helper.rb:41)

**Comment by owen2345** [comment]
Fixed!
