### ISSUE TITLE
S3 upload options

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#531]
I want to set cache-control headers for my S3 file uploads. There is an `on_uploader` hook that seems like it would be useful for this, only the arguments modified by the hook aren't passed through to the `add_file` method (unless I'm mistaken).

Basically, I want to get a `cache_control: 'public, max-age=1234567890'` argument into this line:
camaleon-cms/app/uploaders/camaleon_cms_aws_uploader.rb:56

**Comment by owen2345** [comment]
Added!
Sample: http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/custom-aws-params.html
Test using git version.

**Comment by briank-musichouse** [comment]
Thank you! It works perfectly, but there is an error in the documentation in the link above.

`args[:aws_file_upload_settings]` should be `args[:aws_settings][:aws_file_upload_settings]`

and

`args[:aws_file_read_settings]` should be `args[:aws_settings][:aws_file_read_settings]`

**Comment by owen2345** [comment]
you are right, updated!

**Comment by briank-musichouse** [comment]
I spoke too soon. Uploading works fine, but when I tried to delete the file I got a NoMethodError on `s3_file.cache_control` I haven't figured out how to fix it yet.

**Comment by owen2345** [comment]
I updated
http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/custom-aws-params.html
The problem was because the CMS is using the summary object for optimizations and to get the real object you need to use like this:
```
data[:cache_control] = (s3_file.is_a?(Aws::S3::ObjectSummary) ? s3_file.object : s3_file).cache_control
```

**Comment by briank-musichouse** [comment]
That did it, thanks!
