### ISSUE TITLE
Question about login

### ISSUE THREAD

**Issue by amr0th** [owen2345/camaleon-cms#532]
Hi,

I'm building a site with Camaleon (btw, great job) and I want to separate admin login from client login (I don't want clients to know what is the admin adress). How can I do this?

**Comment by owen2345** [comment]
Hi @amr0th,
Here I put a sample: http://camaleon.tuzitio.com/documentation/category/139779-examples/custom-frontend-login.html
Regards,

**Comment by amr0th** [comment]
Thanks @owen2345 :) Once again, Great job 👍

**Comment by vikagalkina** [comment]
Hi, I follow all steps from sample but get 404 on /login page. I use rails 5.1.3, camaleon_cms 2.4.3.12,  new project with default theme. Can you check please is yours sample still works?
