### ISSUE TITLE
Problem with setting post dates

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#534]
I'm migrating a blog from another platform to Camaleon, and I want to preserve the dates on posts. I've activated the Visibility Posts plugin, but the Published Date setting doesn't have the effect that I want. The posts I import show the date I imported them as the post date, rather than the date that I specify. The same applies to the list of Latest Articles, as they're ordered by the date created rather than the dates that I've set.

**Comment by owen2345** [comment]
Hi @briank-musichouse,
Visibility plugin "Published Date" is to indicate the date since this post will be visible for frontend visitors and not the created at date.
I created this plugin for that:
https://github.com/owen2345/camaleon_post_created_at
Please test it and let me know

**Comment by briank-musichouse** [comment]
That works great, thank you!
