### ISSUE TITLE
How to add leadpages to Camaleon

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#535]
Hi @owen2345,

Can you please let me know how to add Leadpages or other email opt-in landing page builders...I am trying to use contact form, but I feel Leadpages will increase opt-ins greatly.
I would like to offer some give aways to users if they subscribe to my blog, pls let me know how we can do that.

**Comment by owen2345** [comment]
Hi @mazharoddin 
I don't understand, could you please give me more details or an example?

**Comment by mazharoddin** [comment]
Sure, Leadpages are mainly useful for providing some give aways to users like free PDFs or XLs etc. 
Basically if they click the 'give away link' they will be prompted with subscribe option, if they subscribe they will allow to download that free PDF, in some cases if they subscribe they will be sent a confirmation mail along with the pdf download link. 
What I observed is it really helps in growing email subscribers. pls find below for few images.

![screen shot 2016-11-04 at 4 48 31 pm](https://cloud.githubusercontent.com/assets/6102465/20004888/e0f8f956-a2b4-11e6-8aa3-af480117d702.png)


If any user clicks on above link will be prompted with subscribe option.
![screen shot 2016-11-04 at 4 39 36 pm](https://cloud.githubusercontent.com/assets/6102465/20004889/e759cad2-a2b4-11e6-8511-06ee76aa046c.png)

Lead pages allows us to configure these subscribe options various way.

**Comment by owen2345** [comment]
ohhhh I understand, it is easy:
* for the admin panel you can show the private file browser with:
```
$.fn.upload_filemanager({
        formats: $input.data("formats") ? $input.data("formats") : "",
        selected: function (file, response) {
            console.log(file.url.split('?file=')[1].replace(/%2/g, '/'));
        },
        private: true
    });
```
* For the frontend you can create another url to download this file like:
```
send_file CamaleonCmsLocalUploader::private_file_path(params[:file], current_site)
```
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345, let me try it. Thanks
