### ISSUE TITLE
Timestamp of NavMenu and NavMenuItem not updated

### ISSUE THREAD

**Issue by Dariusch** [owen2345/camaleon-cms#539]
Hey Owen,
due to some latency issues we have built a fragment_cache for some view partials.

`cache [current_site.nav_menu_items.maximum(:updated_at).to_i, I18n.locale.to_s] do`

We have encountered a problem regarding the `updated_at` timestamp of `nav_menu_items`. Like when you reposition a `nav_menu_item` in `/admin/appearances/nav_menus` the nav item does not update this timestamp.
Same is applicable to to NavMenu.

Hoping for a fix soon.
LG Dariusch

**Comment by owen2345** [comment]
Fixed!
