### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#541]
Hi @owen2345,
I am getting 500 Internal Server Error with latest changes if I try to upload images using S3.
I am getting this error with your latest commit on image cropping.
```
Completed 500 Internal Server Error in 256ms (ActiveRecord: 10.2ms)


  
NoMethodError (undefined method `call' for nil:NilClass
Did you mean?  caller):
  
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/camaleon-cms-d390617ddfea/app/uploaders/camaleon_cms_aws_uploader.rb:66:in `add_file'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/camaleon-cms-d390617ddfea/app/helpers/camaleon_cms/uploader_helper.rb:61:in `upload_file'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/camaleon-cms-d390617ddfea/app/controllers/camaleon_cms/admin/media_controller.rb:83:in `upload
```
Here is my application helper file.
```
def aws_s3_for_all_subdomains(args)
    args[:server] = 's3'
    args[:aws_settings] = {  region:     ENV["AWS_REGION"],
                             access_key: ENV["AWS_ACCESS_KEY_ID"],·
                             secret_key: ENV["AWS_SECRET_ACCESS_KEY"],·
                             bucket:     ENV["S3_BUCKET_NAME"],·
                             cloud_front: 'https://d1dtr73lu3mys4.cloudfront.net'}
··········
   args[:aws_settings]['inner_folder'] = "#{current_site.name}"
  end
```

**Comment by owen2345** [comment]
Hi @mazharoddin 
I tested in my local but I can not see the error uploading, except the edit/resize image "cors error".
Could you please try again?
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345.. I will re-test. thanks.

**Comment by mazharoddin** [comment]
Hi @owen2345,
I re-tested with different setup, I am getting same error. Thanks.

**Comment by owen2345** [comment]
Please check again!

**Comment by mazharoddin** [comment]
Hi @owen2345,
I am able to upload images using S3 now, but now I am unable to edit them, shall I open new issue for this.
<img width="768" alt="screen shot 2016-11-26 at 7 43 58 pm" src="https://cloud.githubusercontent.com/assets/6102465/20640857/ea640f9a-b410-11e6-8cde-81869830d06d.png">

**Comment by owen2345** [comment]
@mazharoddin I had the same problem, but it was for my CORS configuration for S3 and Cloudfront: please try again and you will see an image and instructions to fix it.
Regards,

**Comment by mazharoddin** [comment]
ohh ok ..thanks.
