### ISSUE TITLE
RSS feed error

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#544]
I'm getting a MissingTemplate error whenever my app's RSS feed is requested. I can't find anything in the docs about setting up RSS, and the GitHub discussions all appear to be for the previous version. Even searching the code turns up results like `cama_rss_url`, which is called but doesn't appear to be defined anywhere.

Full error text:

> Missing template themes/my_site/views/rss, camaleon_cms/default_theme/rss with {:locale=>[:en], :formats=>[:xml], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
> * "/app/app/apps"
> * "/app/vendor/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-074c27287588/app/apps"
> * "/app/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/bundler/gems/camaleon-post-order-plugin-3c665b271660/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/bundler/gems/camaleon-google-analytic-plugin-812986e784b4/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/bundler/gems/camaleon_editor-2a8f638237b3/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/bundler/gems/camaleon-cms-074c27287588/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/gems/cama_contact_form-0.0.14/app/views"
> * "/app/vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/app/views"

**Comment by owen2345** [comment]
Fixed!
In previous versions you can use like:
http://localhost:3000/rss.rss and not http://localhost:3000/rss.xml

**Comment by briank-musichouse** [comment]
Thanks! I updated to the git version, and the errors appear to have stopped.
