### ISSUE TITLE
Integrate with an existing authentication system

### ISSUE THREAD

**Issue by georgebellos** [owen2345/camaleon-cms#545]
We want to use camaleon along with an existing rails 4 app that it has its own authentication system with devise and  let existing authenticated users with devise to use the cameleon admin panel.

Is it possible to disable - override the authentication system of camaleon?

**Comment by owen2345** [comment]
Hi @georgebellos 
Yes it is possible, please check this article:
http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/custom-login.html
Regards,
