### ISSUE TITLE
How to add review(5 star) widget

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#546]
Hi @owen2345,
can you please let me know how I can add review(5 star) widget to post type, I would like non logged in users also should be able to provide review by clicking on respective stars.

<img width="339" alt="screen shot 2016-12-03 at 9 59 33 pm" src="https://cloud.githubusercontent.com/assets/6102465/20860685/d27f71f6-b9a3-11e6-9957-d5c7476506ee.png">

**Comment by mazharoddin** [comment]
Hi @owen2345,
I came across wordpress plugin while searching about this, though it has several options, it has nice themes start with. I thought it may be useful if some one wanted to create review site using camaleon cms.
https://codecanyon.net/item/reviewer-wordpress-plugin/5532349

**Comment by aspirewit** [comment]
[Here](https://github.com/aspirewit/camaleon-cms-rating) is a simple rating implementation, so welcome to improve it.
