### ISSUE TITLE
Method overwrite warning when precompiling

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#549]
I've been getting this warning when precompiling my app:

`remote:        W, [2016-12-07T23:05:00.543365 #636]  WARN -- : Creating scope :featured.
Overwriting existing method CamaleonCms::Post.featured.
`

I'm running Rails 5 on Heroku, using the git version of Camaleon. This error popped up in the last few weeks, so it may be related to a recent update. Sorry I don't have a specific date when I first saw it.

**Comment by owen2345** [comment]
Sorry, I couldn't reproduce the issue, I think this is because you have already defined a method/scope in your custom models?

**Comment by briank-musichouse** [comment]
I haven't made any custom models. I don't know what I could have done to cause this, unless it's a gem compatibility issue.

**Comment by owen2345** [comment]
You are right, I found duplicated scopes. Fixed!
