### ISSUE TITLE
Multiple Language: Editor field of other language doesn't show container body to input data

### ISSUE THREAD

**Issue by SopharyMSH** [owen2345/camaleon-cms#552]
Hi owen2345, I suddenly cannot input data to all of the editors field of KH Language. 
Would you mind tell me how can I solve it?

![content error](https://cloud.githubusercontent.com/assets/20766439/21338208/9cb3c2ba-c6a6-11e6-87d3-b9a29af56d62.png)
![editor](https://cloud.githubusercontent.com/assets/20766439/21338209/9cb4d33a-c6a6-11e6-8426-f4cd80f753cf.png)

**Comment by owen2345** [comment]
Hi @SopharyMSH 
could you please debug the error? to see the error line and the url of the js file with the error.
The editor is stopped because there is an error in plugin.js

**Comment by SopharyMSH** [comment]
Hi @owen2345 
Would you mind guide me how can I debug that error?

**Comment by SopharyMSH** [comment]
![error](https://cloud.githubusercontent.com/assets/20766439/21631285/0a9da0ea-d26c-11e6-81a7-7d8ccceb1554.png)

**Comment by owen2345** [comment]
@SopharyMSH 
could you please send me the url or the content of plugin.js?
