### ISSUE TITLE
"Constrain proportions" can't be deselected in editor

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#554]
When I deselect "Constrain Proportions" on an image, the box unchecks. After I click Ok, the box is checked again though.

Camaleon 2.4 (git version), Rails 5

**Comment by owen2345** [comment]
@briank-musichouse 
could you please send me a screenshot?

**Comment by briank-musichouse** [comment]
<img width="830" alt="screen shot 2016-12-29 at 10 15 32 am" src="https://cloud.githubusercontent.com/assets/21235090/21548107/df029046-cdaf-11e6-86c5-c298b7cb3d9e.png">

**Comment by owen2345** [comment]
@briank-musichouse 
it is a Tinymce problem!

**Comment by owen2345** [comment]
@briank-musichouse 
it is a Tinymce problem!
