### ISSUE TITLE
Urgently BUG: Camaleon Version 2.1.1 does not upload file to S3

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#555]
Hi @owen2345,

Recently, the Camaleon CMS version 2.1.1 is not upload file to S3 but Capistrano has `rake assets:precomile` as normally without any errors, and the deployment was also successfully deployed. But when I view the file is show me `Error 403: Access Denied`, and when I check my S3 bucket, the file is no where to appear. Example: my image in `themes/theme_name/assets/images/logo.png` and I want to display the static logo at the bottom of the page. So, I use this method `= image_tag theme_asset_url('images/logo.png')` to display image. When I deployed, then I view the page, it shows me the URL of image in S3; Unfortunately, the image is `Error 403: Access Denied` and it is nowhere to shown in my S3 bucket.

## Noted: 

It is an old project, which It is already existed in Production. Before it is working fine, the problem just happen in these last several days.

**Comment by owen2345** [comment]
Hi @NySiya 
I am sorry, I don't understand your question.
Right now I tested with last version and it is working well.
Regards,

**Comment by jacobmaurer** [comment]
I ran into this as well (I think). You probably just need to modify your bucket's permissions to enable public write access. Something like this- https://havecamerawilltravel.com/photographer/how-allow-public-access-amazon-bucket should do it.

Cheers!

**Comment by NySiya** [comment]
@jacobmaurer, I have already checked my bucket, and its permission is enable already. But I still could not upload.
