### ISSUE TITLE
Sass style support

### ISSUE THREAD

**Issue by delphaber** [owen2345/camaleon-cms#56]
Hi :)

I've found a problem in production with `rake assets:precompile` using the `sass` syntax. This can be reproduced locally with https://github.com/delphaber/camaleon-test-sass and `rake assets:precompile`

```bash
$ rake assets:precompile
rake aborted!
Sass::SyntaxError: Undefined variable: "$red".
/Users/faber/Repos/blog/app/apps/themes/puppa/assets/css/_base.css.sass:2
-e:1:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

Sprockets tries to compile `_base.css.sass` but can't find the variable defined in `_colors.css.sass`.

I think this happens because `/config/initializers/assets.rb` tells sprockets to compile any `.css` (so, `.sass` too) separately. Sprocket should compile only `main.css.sass` which imports the other two files.

I tried to remove any `.css` related rule in `/config/initializers/assets.rb` and I was able to `rake assets:precompile` successfully.

Any clue? :)

**Comment by cmckni3** [comment]
This happens in vanilla Rails apps as well.

You need to add an `@import 'colors'` to your `_base.css.sass` file. Alternatively, you should look at a different way of [structuring your sass files](http://stackoverflow.com/questions/9138946/proper-scss-asset-structure-in-rails) (I would recommend switching to scss as well).

**Comment by owen2345** [comment]
I am working in a way to skip partial assets by adding a prefix (_), sample:
_colors.css.sass

It is still in testing...

Regards!

**Comment by cmckni3** [comment]
@owen2345 Yeah. That's probably a good idea as well because they might get compiled multiple times

**Comment by owen2345** [comment]
partial stylesheets must be prefixed with _
done!

**Comment by delphaber** [comment]
Thx

**Comment by cmckni3** [comment]
I'm still having issues.

```
Sass::SyntaxError: Undefined variable: "$alert-padding".
~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootstrap-sass-3.3.5.1/assets/stylesheets/bootstrap/_alerts.scss:10
```

**Comment by cmckni3** [comment]
`asset_theme_path` doesn't work in sass files for me either.

**Comment by owen2345** [comment]
asset_theme_path that not exist.
Right now I have committed the support for sass and scss files:
```
added asset functions for themes and plugins: 
# return them path (this prefix automatically the path with current theme location) 
# Sample: .container{ background: #ffffff url(asset_theme_path('img/patterns/pattern1.jpg')); }   
asset_theme_path(...) asset_plugin_path(...) 

 # return them path (this prefix automatically the path with current theme location) 
# Sample: .container{ background: #ffffff asset-theme-url('img/patterns/pattern1.jpg'); }   
asset_theme_url(...) asset_plugin_url(...)
```

**Comment by owen2345** [comment]
Please let me know if the partial sass files is working or send me and an example.

**Comment by cmckni3** [comment]
I tried using `asset-theme-url` and `url(asset_theme_path(...))` inside of sass.

Is that wrong? What's the actual syntax?

**Comment by cmckni3** [comment]
Ok, let me see if I still have the other app. Standby

**Comment by owen2345** [comment]
I am sorry, I forget to add the custom to the github.
Please try again.

**Comment by cmckni3** [comment]
Awesome, the helpers work now

**Comment by owen2345** [comment]
great!

**Comment by cmckni3** [comment]
Trying a precompile again

**Comment by cmckni3** [comment]
Same issue when precompiling

**Comment by owen2345** [comment]
let me see..

**Comment by cmckni3** [comment]
I'm trying a precompile on a rails app with just camaleon installed. Pretty sure it will do the same thing. I'll then push that repo up to GitHub.

**Comment by owen2345** [comment]
I have precompiled without problems. Please check attach file.

![screen shot 2015-09-29 at 11 38 03 am](https://cloud.githubusercontent.com/assets/1148415/10169123/b264df78-669d-11e5-9b4e-e51d57ee51db.png)

**Comment by cmckni3** [comment]
Ohhh it's an issue with the precompile settings and `bootstrap-sass`

**Comment by cmckni3** [comment]
Created an application to demonstrate it.

https://github.com/cmckni3/camaleon-sass-bug

**Comment by cmckni3** [comment]
Any ideas @owen2345?

**Comment by owen2345** [comment]
fixed, please try again. there was an error for file name validation

**Comment by cmckni3** [comment]
Fixed :+1:
