### ISSUE TITLE
Bootstrap Sass variable and Mixin are also undefined with Camaleon CMS version 2.4

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#560]
Not only custom variable even Bootstrap Sass variable and Bourbon Mixin also undefined. The structure of my asset is
<img width="229" alt="screen shot 2017-01-20 at 2 42 45 pm" src="https://cloud.githubusercontent.com/assets/12697539/22188798/f0da3c8e-e14a-11e6-9eff-34112fa3aeaf.png">

And This how I have imported
<img width="313" alt="screen shot 2017-01-20 at 2 44 41 pm" src="https://cloud.githubusercontent.com/assets/12697539/22188802/f7bbba3c-e14a-11e6-883b-17e62b51bcc2.png">

and This is how I used the variable:
<img width="686" alt="screen shot 2017-01-20 at 2 47 51 pm" src="https://cloud.githubusercontent.com/assets/12697539/22188817/075cf582-e14b-11e6-8090-ba05378208a3.png">

And When I rails s or do a rake assets:precompile it give me this error:
<img width="575" alt="screen shot 2017-01-20 at 2 46 24 pm" src="https://cloud.githubusercontent.com/assets/12697539/22188827/0fba648a-e14b-11e6-9023-6dc8a54e7b95.png">

Even I trying to used Camaleon CMS git version, it still the same.
Noted: I used this CMS with Rails 5

Kind Regards
 @NySiya

**Comment by haffla** [comment]
I don't think this is an camaleon-cms issue but I haven't found out what is causing it.
http://stackoverflow.com/questions/25310509/precompiling-scss-variable-is-undefined-rails-4

**Comment by owen2345** [comment]
@NySiya could you please try using the git version + checking the rails 5 installation steps? I think you have vs 5.1.
