### ISSUE TITLE
Assign a template to a content-group global page

### ISSUE THREAD

**Issue by Simon13px** [owen2345/camaleon-cms#561]
My structure is like this

Contentgroups
-- Page
---- Blog (pointing to /blog with the blog template)
---- Other pages
-- Blog-articles 
---- Article 1 (with the blog-article template)
---- Article 2

Is it possible to assign a template to the blog-articles content group ? As i tried it only applies to the articles inside the content group.

The problem is that my articles slug is /blog-articles/article-1, we would like it to be /blog/article-1.

Am i wrong or missing something in my structure ?

**Comment by owen2345** [comment]
Please check this small description
http://camaleon.tuzitio.com/documentation/category/139779-faqs/how-to-add-custom-routes-for-contents.html

**Comment by Simon13px** [comment]
I'll check it out, thanks a lot
