### ISSUE TITLE
Programatically enable custom field groups with multiple groups

### ISSUE THREAD

**Issue by jacobmaurer** [owen2345/camaleon-cms#562]
Hi there- there doesn't seem to be any way to programatically enable the 'support multiple groups' checkbox when doing something like:

`agent = theme.add_field_group({...})`

I tried adding `multiple: true` to both the first and second argument hashes, but the former throws an error and the latter has no effect, forcing me to enable the option manually after setting up the CMS. Am I perhaps missing something? If not, is this something you would consider adding support for? Allowing multiple values for *individual* fields is already supported in this way by adding `multiple: true` to the second argument hash.

Screenshot to show what exactly I'm referring to:

![multi-field-group](https://cloud.githubusercontent.com/assets/4667267/22451276/0b86dcb8-e722-11e6-9a51-391a42be04c5.png)

Cheers!

**Comment by owen2345** [comment]
Hi @jacobmaurer 
Please check this partial updated doc:
http://camaleon.tuzitio.com/documentation/category/40758-modules/custom-fields-1.html
Note: the attribute is (is_repeat: true)
Sorry for the delay, I was too busy.
Regards,

**Comment by jacobmaurer** [comment]
Thanks for the updated docs! All set here now- closing this issue.
