### ISSUE TITLE
Enable ability to programatically tie a custom field to a post type

### ISSUE THREAD

**Issue by jacobmaurer** [owen2345/camaleon-cms#564]
I couldn't find anything in the docs about this, nor could I find any examples of you doing it in your sample project. Is this doable? As-is, it seems I can create new field groups, fields, and post types, as well as add posts all programmatically, but I cannot tie a custom field to a post type and must instead do that manually in the CMS after set up.

Screenshot to show what I'm referring to- 

![field_group](https://cloud.githubusercontent.com/assets/4667267/22614999/4baa4bb0-ea40-11e6-956a-11de752f6fd6.png)

Thanks!

**Comment by owen2345** [comment]
Hi @jacobmaurer 
I updated a bit the doc page, please review again and let me know if it is enough.
http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/custom-fields-1.html
Regards,

**Comment by jacobmaurer** [comment]
Hi Owen! Thanks for the response and updated docs- much appreciated.

That did answer my question, but now I have a follow-up. I see now how to create a custom field group for a given post type, but how would one go about creating a custom field group tied to the 'site settings' (listed in the same dropdown in the CMS as the post types)? I've tried all sort of variants on `current_theme.settings.add_field_group({..})`, but nothing has worked so far.

Thanks again!

**Comment by owen2345** [comment]
@jacobmaurer what about this?
my_group = current_site.add_field_group({name: "My Group", slug: "my_group_key"}, '')

**Comment by jacobmaurer** [comment]
Aha! That did it. Thanks so much, cheers!
