### ISSUE TITLE
Colorpicker field type throws JS bugs in console and does not work

### ISSUE THREAD

**Issue by jacobmaurer** [owen2345/camaleon-cms#569]
Hi Owen,

I'm trying to add a colorpicker field. The picker renders in the admin panel, but I get a bug in the console-
![colorpickerbug](https://cloud.githubusercontent.com/assets/4667267/22874119/370e95c2-f179-11e6-8f12-583ea3ee60af.png)

I can manipulate the colorpicker on the front-end, but it won't actually let me choose a color. Any ideas?

**Comment by owen2345** [comment]
@jacobmaurer 
sorry, I couldn't reproduce the problem.
to use in frontend, I recommend you to use this plugin:
https://itsjavi.com/bootstrap-colorpicker/
PD: sorry for the delay, I was in vacation.
Regards,

**Comment by jacobmaurer** [comment]
OK no problem, thanks Owen.
