### ISSUE TITLE
Uploader integration

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#57]
Is there a way to use `elfinder` inside of a camaleon plugin?

**Comment by froilanq** [comment]
**Admin Panel use:**
```
$.fn.upload_elfinder({
	type:"all",  // options: all, image, audio, application/pdf, or mime type
	selected: function(files){
		// files: is files selected
	}, 
	mode: 'basic', // basic or full 
	tree: false, // view tree files
	multiple: true   // multiple or simple selected
})
```

**Frontend use:**

Includes:
option 1: load by *javascript_include_tag("elfinder_front.js")* in view or by manifest: *require elfinder_front.js*
option 2: load by *add_asset_library("elfinder_front")* in controller

 ```
open_elfinder({title: "Modal Title", type: "image", multiple: true}, function(files){
	// files: is files selected
});
```

**Comment by cmckni3** [comment]
Does this handle the file uploading as well?

**Comment by froilanq** [comment]
Only filters for file selection.
