### ISSUE TITLE
Is there a function like blogcard or linkcard?

### ISSUE THREAD

**Issue by minozo** [owen2345/camaleon-cms#570]
Is there some solution for blogcard or linkcard like this plugin below?

https://wordpress.org/plugins/pz-linkcard/

**Comment by owen2345** [comment]
You can create your custom shortcode to render like linkcard widget.
Sample:
[linkcard id='120']
See more about shortcodes here:
http://camaleon.tuzitio.com/documentation/category/40758-modules/shortcodes-4.html

**Comment by minozo** [comment]
thank you! :)
