### ISSUE TITLE
S3 errors

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#571]
I'm having some problems using S3. I've read through #541 but it doesn't help in my case, as I've already set the CORS policy on my bucket. The symptoms:

- I can upload images just fine.
- Deleting images works in the sense that the images are removed from S3, but the CMS loading graphic remains for a long time until eventually the browser shows a 503 error.
- The image editor doesn't work. I get a message about CORS and the console shows `XMLHttpRequest cannot load https://my_bucket/my_image.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://my_domain.com' is therefore not allowed access.` However, my S3 bucket already has the CORS policy set to allow all request types from my domain (see below).
- The symptoms are the same whether or not I enable Cloudfront.
- Before the image editor was made generally available throughout the CMS, I was able to use the cropper on avatar images. It seems that the update that made the image cropper/editor more available may have caused or revealed a conflict with my app.

My CORS rules (leaving out my domains):
```
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
```

Is there some kind of configuration within the app that's necessary for using the image editor? My current guess is that I have a request header problem, but since I've been unable to solve it I can't rule out other causes yet.

Rails 5.0.1/Puma/Heroku

**Comment by owen2345** [comment]
Hi @briank-musichouse ,
Check if cors configuration are defined well in S3 and Cloudfront (if you are using cloudfront)
Check this tutorial: http://blog.celingest.com/en/2014/10/02/tutorial-using-cors-with-cloudfront-and-s3/
I had problems too: first I forget to add cors for cloudfront, second: browser cache (I cleaned my cache)

Regards,

**Comment by briank-musichouse** [comment]
Yes, I created the issue because I already have CORS set up according to that tutorial and it still doesn't work.

I just tried clearing the browser cache with no change.

**Comment by briank-musichouse** [comment]
Update: I tried setting up S3 in development mode. This yielded different results than my production app.

- I could delete images without errors or delays.
- I could upload an image and use the editor.
- I still could not use the editor on a previously uploaded image.

**Comment by owen2345** [comment]
@briank-musichouse can you please test the cors by curl? sample:
```
curl -I -s -X GET -H "Origin: localhost:3000" http://d1yrjqwkmttvxm.cloudfront.net/test_image.jpg
```

**Comment by briank-musichouse** [comment]
```
HTTP/1.1 200 OK
Content-Length: 92102
Connection: keep-alive
Date: Tue, 21 Feb 2017 20:14:11 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Last-Modified: Tue, 07 Feb 2017 16:11:39 GMT
ETag: "f551d2c85e5031803e9a34e80e57498d"

Cache-Control: public, max-age=31536000
Accept-Ranges: bytes
Server: AmazonS3
Vary: Origin,Access-Control-Request-Headers,Access-Control-Request-Method
X-Cache: Miss from cloudfront
Via: 1.1 2ff66c3e8250d693b62131b62b019fc5.cloudfront.net (CloudFront)
X-Amz-Cf-Id: B0DMoCoLYlS3F_ptogQ_S-5yBcyUL3BCdIs-C5fANK05V0C2jUkRwg==
```

More info: When I click the edit button on an image, Chrome's Network panel shows five GET requests for the image URL. Not all of these requests contain an Origin header.

**Comment by owen2345** [comment]
"I still could not use the editor on a previously uploaded image"
Ohhh I understand, for new file uploads I added, {acl: 'public-read'} in this line:
https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L65
You need to update acl to old files:
http://stackoverflow.com/questions/40869996/change-s3-file-access-with-aws-sdk-2-and-ruby

**Comment by briank-musichouse** [comment]
I've identified one of the problems. The reason I was getting different results in different environments was because I had custom AWS upload settings enabled as documented here: http://camaleon.tuzitio.com/documentation/category/139779-faqs/custom-aws-params.html

I disabled that method, and now the production environment functions the same as the development environment. Is that documentation out-of-date?

There are still other problems, as well. The new summary:

- If I upload a new image, I can edit it.
- If I upload an image, then clear my browser cache, I can no longer edit it.
- I can't edit previously uploaded images. I did make them all public from the S3 console. Most of them were uploaded after the code change mentioned above anyway.
- As stated above, clicking the edit button on an image results in five GET requests, two of which don't have an `Origin` header. I suspect this is the problem, since a request without an `Origin` header will not result in a response with an `Access-Control-Allow-Origin` header, but I don't know what to do about it.

**Comment by briank-musichouse** [comment]
Update on the custom AWS settings. the `:aws_file_upload_settings` part works fine, it was the `:aws_file_read_settings` that was causing me problems.

**Comment by briank-musichouse** [comment]
Update: The cropper appears to work only if I disable the cache (not just clear it). The issue I have seems to be what's described [here](https://github.com/fengyuanchen/cropper/issues/148) but the fix of setting `checkCrossOrigin = false` didn't work for me. The cache-busting code all appears to be intact in the version of cropper bundled with Camaleon, but it's not helping.

I still don't know why this appears to be an issue for me when others have no problem. I also don't know why everything works fine in Firefox (just discovered that today), but not Chrome or Safari (all Mac versions). What I do know is that in those browsers, the XHR request for the cached image file has an origin problem.

At this point, I would take this issue to the cropper repository, but it appears the version bundled with Camaleon has been modified a bit, or at least uses specific settings, and also may not be the current version.

Does this new info give you any ideas?

**Comment by briank-musichouse** [comment]
Ok, I think I finally got it fixed. I had to configure Cloudfront to send an origin header with every request, rather than whitelisting the origin header as instructed in the documentation.

Since this turned out to be an issue with the browser cache, I suspect that the reason I've had issues when others have not may be related to my custom S3 upload settings, since they include a cache-control header. If files are uploaded without a cache header, the browser cache is not an issue. I tested this theory by removing the cache-control header in S3 and I was able to edit the image.

**Comment by owen2345** [comment]
Great!

**Comment by superchell** [comment]
I have the same problem, but the Сloudfront on the project is not used. Tell me how else can I solve this?

**Comment by owen2345** [comment]
@superchell please try using the github version and let me know if it works well for you too

**Comment by wingbui** [comment]
I have the same problem, please tell details how you fix it, thanks @brian-kephart

**Comment by brian-kephart** [comment]
The `suppress_content_type` stuff in the code below is because I had issues with the way S3 serves SVG images by default. If you don't use SVG, you can leave out every line of code that references `content_type`.
```js
// app/apps/themes/my_theme/config/config.json

{
  "hooks": {
    "uploader_aws_before_upload": ["suppress_content_type"],
    "on_uploader": ["aws_options"]
  }
}
```

```ruby
# app/apps/themes/my_theme/main_helper.rb

def suppress_content_type(args)
  @suppress_content_type = true unless args[:key].match? /\.svgz?\z/
end

def aws_options(args)
  args[:aws_settings][:aws_file_upload_settings] = lambda { |settings|
    @suppress_content_type ||= false
    settings[:cache_control] = 'public, max-age=31536000'
    settings[:content_type]  = params.dig('file_upload')&.content_type unless @suppress_content_type
    settings
  }
end
```

The other thing I had to do was set a custom header in my CloudFront origin settings.
<img width="811" alt="Screen Shot 2020-07-22 at 10 37 02 PM" src="https://user-images.githubusercontent.com/21235090/88250025-e55f0c80-cc6b-11ea-81ca-661cb7518928.png">

Hope it helps!
