### ISSUE TITLE
Request Update Feature

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#572]
Hi @owen2345, 

I really want to have `translate` option on Custom Fields for `Url field` and `Select field`, and I think it would be great to have it. In your [Custom Field doc](http://camaleon.tuzitio.com/documentation/category/40761-functions/custom-fields-3.html), I see that `Textbox field` has `translate` option `items[:text_box] = {
        key: 'text_box',
        label: t('camaleon_cms.admin.custom_field.fields.text_box'),
        options: {
            required: true,
            multiple: true,
            translate: true,
            default_value: true,
            show_frontend: true
        }
    }` but in `Url field` and `Select field` do not have. I face this problem I use camaleon with multiple available languages translation.

Kind regards,

**Comment by owen2345** [comment]
Hi @NySiya 
I added the support, please test it using git version.
Regards,
