### ISSUE TITLE
Feature request: title tag for User profiles

### ISSUE THREAD

**Issue by briank-musichouse** [owen2345/camaleon-cms#575]
Right now my User profiles use the site title as the page title. To avoid duplicate page titles I would like the profile page titles to have a title similar to `title: "#{current_site.the_title} | #{@user.the_name}"`

I believe the relevant method is here:
https://github.com/owen2345/camaleon-cms/blob/6fa26c8dbe7d95098623ef397b06028cb2075582/app/helpers/camaleon_cms/frontend/seo_helper.rb#L5

**Comment by owen2345** [comment]
Solved!
Thanks for reporting!
