### ISSUE TITLE
Can a custom post type be child of another custom post ?

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#576]
Simply, I want to achieve this. As categories can have multiple children categories or sub category, I want to have multiple post type for a post type. So that following thing can happen.

Post Type: Hospital(hospital) -> Child-Post-Type -> About (about-hospital)

Post-Type: Medical(medical)->Child-Post-Type-> About(about-medical)

Here two About post-types are not related.

Now when I add Hospital and visit its page. There I can add about post.
So when I open hospital page it looks like a site of hospital containing about, contact us links.

Myself I can achieve but from user perspective it is hard or time consuming. Is there is simple step I can achieve it.

Thanks

**Comment by owen2345** [comment]
For now it is not possible, but you can achieve extending by plugins.
I added custom fields for categories and post types, maybe this is ok for you.
Regards,

**Comment by prdpspkt** [comment]
I don't much about how camaleon_plugin works. I find most of the feature of it stunning and better than WordPress. So I wanted to use it in a project but. I'm not an experienced developer and have no much time to work on. I'm very sorry to say that. Actually I want to make a site where user can make a page like in Facebook and add about us, contact us page so that when any other person visits it. It feels like good website. If small changes can make it possible I will try. But don't know where to start. You can help me with a simple example with possibilities in comments in file. Thank You
