### ISSUE TITLE
How to loop through custom fields content

### ISSUE THREAD

**Issue by mwanikigeorge** [owen2345/camaleon-cms#578]
Hi
Am making a theme for in camaleon 2.4 and i have some slider content 

![cama](https://cloud.githubusercontent.com/assets/16100625/23740698/d96818bc-04b5-11e7-85c5-0feeea52d2b8.JPG)

and i would like to display these content in the front end, how do i go about it

**Comment by owen2345** [comment]
Sample here:
https://gist.github.com/owen2345/fdec8eb47db6db91a76c05827bc64c5b

**Comment by haffla** [comment]
Please close issues if they are resolved
