### ISSUE TITLE
Asset Undefined And Testing Repo

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#579]
Hello @owen2345 

Please, checkout this [repo](https://github.com/NySiya/undefined-mixin) for the problem. The problem has happened not only variable is undefined but also mixin. For the first time, when I run rails s, it worked fine, but after I restart server for several times, it gave me that errors.

Kind Regards,

**Comment by owen2345** [comment]
Problem solved in Camaleon CMS (Thanks a lot for the report).
To complete the fix in your git, please rename test_again.scss into _test_again.scss
Note: theme/plugin asset files must be prefixed with "_" to skip precompilation as single file.
Regards,
