### ISSUE TITLE
Display the featured image

### ISSUE THREAD

**Issue by mwanikigeorge** [owen2345/camaleon-cms#580]
How do i display the post featured image instead of adding a custom field for image in a post.

**Comment by pbr-pl** [comment]
example from my app:
'<%= image_tag(post.decorate.the_thumb_url || theme_asset_path('images/photos/default.jpg'), width: 330, class: 'setborder') %>'
in general @post.decorate.the_thumb_url

**Comment by mwanikigeorge** [comment]
thanks
