### ISSUE TITLE
Missing pagination in admin user list

### ISSUE THREAD

**Issue by pbr-pl** [owen2345/camaleon-cms#581]
Pagination is missing on admin users list. This happens because the controller passes @users "decorated" instead of raw
My solution is to pass raw @users - users_controller.rb:8 should looks like:
`@users = current_site.users.paginate(:page => params[:page], :per_page => current_site.admin_per_page)`
and decorate it in the view - admin/users/index.html.erb:30
`<% @users.decorate.each do |f| %>`

**Comment by owen2345** [comment]
You are right @pbr-pl 
I added the fix into github version

**Comment by pbr-pl** [comment]
OK thx. Fixed
