### ISSUE TITLE
real estate website functionality

### ISSUE THREAD

**Issue by etewiah** [owen2345/camaleon-cms#582]
Hi @owen2345 , thanks for creating such an awesome CMS!

I am working on a website builder for property listings which is also open source:

https://github.com/etewiah/property_web_builder

It has all the core functionality needed for a real estate website but it would be nice to add some extra CMS functionality.  In the spirit of open source, I would prefer to work with an existing solution rather than re-invent the wheel.

I am not entirely sure what the best way would be to combine my project with yours.  Do you have some documentation about how I might be able to implement a project like PropertyWebBuilder as a plugin?

It will probably be quite difficult to go through all the options here so if you are interested and have a few minutes to spare perhaps we could discuss this via skype.  

Cheers,

Ed

**Comment by owen2345** [comment]
Hi @etewiah please contact me on skype to review together!
Regards.

**Comment by etewiah** [comment]
Great, thanks.  I've sent you a contact request on skype.

**Comment by anhpham2710** [comment]
how is it going guys? I also need the plugins like Property_web_builder in Camaleon-cms

**Comment by etewiah** [comment]
In the end I decided to use Comfortable Mexican Sofa as it was easier.  @anhpham2710 , you can find that in the cms-pages branch:
https://github.com/etewiah/property_web_builder/tree/cms-pages
I hope to finish work on that branch next week so I can merge it into the master branch.
