### ISSUE TITLE
How to filter featured posts from a specific category

### ISSUE THREAD

**Issue by mwanikigeorge** [owen2345/camaleon-cms#583]
i have a video content group and would like to display posts hits category, with one post being featured, how do i achieve this? thanks

**Comment by owen2345** [comment]
Hi, you can do it like this:
```
my_category.posts.featured
```
Regards,

**Comment by mwanikigeorge** [comment]
thanks

**Comment by mwanikigeorge** [comment]
This what i was looking for 
<% if post.is_feature %>
