### ISSUE TITLE
json pagination problem

### ISSUE THREAD

**Issue by killinit** [owen2345/camaleon-cms#584]
I have found a bug.

I have content_group called "participants"

I have 21 pages in "participants"

in general setting i have option "Quantity of items to be listed on frontend" set up to 10

when i try to get ...(domain).../participants.json

I got error 
problem was on pagination settings
the url for next_page was impossible to create

I have omitted a problem changing Quantity of items to be listed on frontend to 100

Rendered /usr/local/rvm/gems/ruby-2.3.1@camaleon/gems/camaleon_cms-2.4.2/app/views/camaleon_cms/default_theme/partials/_cama_posts_entries.json.jbuilder (26.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.1@camaleon/gems/camaleon_cms-2.4.2/app/views/camaleon_cms/default_theme/post_type.json.jbuilder (66.8ms)
Completed 500 Internal Server Error in 270ms (ActiveRecord: 15.1ms)

ActionView::Template::Error (Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.):
    2: json.per_page posts.per_page
    3: json.total_entries posts.total_entries
    4: json.previous_page url_for(params.merge(page: posts.previous_page)) if posts.previous_page.present?
    5: json.next_page url_for(params.merge(page: posts.next_page)) if posts.next_page.present?
    6: json.entries posts.decorate do |post|
    7:   json.partial! partial: 'partials/cama_post_entry', locals:{ post: post }
    8: end

actionpack (5.0.1) lib/action_dispatch/routing/url_for.rb:176:in `url_for'
actionview (5.0.1) lib/action_view/routing_url_for.rb:96:in `url_for'
camaleon_cms (2.4.2) app/views/camaleon_cms/default_theme/partials/_cama_posts_entries.json.jbuilder:5:in `__usr_local_rvm_gems_ruby_______camaleon_gems_camaleon_cms_______app_views_camaleon_cms_default_theme_partials__cama_posts_entries_json_jbuilder___3652968212135170244_69974380473240'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.0.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
jbuilder (2.6.1) lib/jbuilder/jbuilder_template.rb:127:in `_render_partial'
jbuilder (2.6.1) lib/jbuilder/jbuilder_template.rb:121:in `_render_partial_with_options'
jbuilder (2.6.1) lib/jbuilder/jbuilder_template.rb:214:in `_render_explicit_partial'
jbuilder (2.6.1) lib/jbuilder/jbuilder_template.rb:21:in `partial!'
camaleon_cms (2.4.2) app/views/camaleon_cms/default_theme/post_type.json.jbuilder:4:in `block in __usr_local_rvm_gems_ruby_______camaleon_gems_camaleon_cms_______app_views_camaleon_cms_default_theme_post_type_json_jbuilder__1596179320828063274_69974381390920'
jbuilder (2.6.1) lib/jbuilder.rb:38:in `block in set!'
jbuilder (2.6.1) lib/jbuilder.rb:266:in `block in _merge_block'
jbuilder (2.6.1) lib/jbuilder.rb:305:in `_scope'
jbuilder (2.6.1) lib/jbuilder.rb:266:in `_merge_block'
jbuilder (2.6.1) lib/jbuilder.rb:38:in `set!'
jbuilder (2.6.1) lib/jbuilder/jbuilder_template.rb:99:in `set!'
jbuilder (2.6.1) lib/jbuilder.rb:66:in `method_missing'
camaleon_cms (2.4.2) app/views/camaleon_cms/default_theme/post_type.json.jbuilder:3:in `__usr_local_rvm_gems_ruby_______camaleon_gems_camaleon_cms_______app_views_camaleon_cms_default_theme_post_type_json_jbuilder__1596179320828063274_69974381390920'
actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.1) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
meta-tags (2.4.0) lib/meta_tags/controller_helper.rb:20:in `render'
camaleon_cms (2.4.2) app/controllers/camaleon_cms/frontend_controller.rb:57:in `post_type'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'

**Comment by owen2345** [comment]
Thanks for the report, I will fix until Friday please.

**Comment by owen2345** [comment]
Solved!
thanks for reporting.
Released new version (2.4.3.2) with the fix.
