### ISSUE TITLE
Probably typo in posts controller

### ISSUE THREAD

**Issue by MrTymur** [owen2345/camaleon-cms#586]
Probably typo on the line _187_ in posts controller **get_post_data** method. Сomparison instead of assignment.

> post_data[:status] **==** 'pending' if post_data[:status] == 'published' && cannot?(:publish_post, @post_type)

Or maybe I am wrong, please explain if so.

**Comment by owen2345** [comment]
@MrTymur you are right, fixed!

**Comment by MrTymur** [comment]
@owen2345 Thanks!
