### ISSUE TITLE
CamaleonCMS with Paper_trail

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#587]
Hi @owen2345,

I was just wondering if it is necessary to use `paper_trail` gem with camaleon, or, Camaleon already done with tracking user action in system?

Kind regards,

**Comment by owen2345** [comment]
@NySiya yes, it is necessary to add, because Camaleon doen't include tracking history.

**Comment by killinit** [comment]
Yes. Paper trail is very good idea for revisions !
Pehaps add options to use papertail for content groups?

04.04.2017 14:18 "Owen Peredo Diaz" <notifications@github.com> napisał(a):

**Comment by owen2345** [comment]
Yes, it would be great to create another plugin to track by content groups.

**Comment by NySiya** [comment]
@owen2345, Thank you so much for this. I would be glade if Camaleon include Paper_trail. :)
