### ISSUE TITLE
How to render several created in admin panel pages into onepager?

### ISSUE THREAD

**Issue by SophiaPetrova** [owen2345/camaleon-cms#588]
I need to combine several pages into one. I get the content of the current with @post.the_content in app/apps/themes/my_theme/views/page.html.erb but how to take the content of another page? Thanks!

PS: Using latest stable version '2.3.6'

**Comment by owen2345** [comment]
@SophiaPetrova in your template you are able to combine contents of multiple pages like:
```
%hr
= @current_post.the_content
%hr
= @page2.the_content
%hr
= @page3.the_content
```
Also, you can do it in your editor, like this:

<img width="1004" alt="screen shot 2017-04-04 at 11 58 58 am" src="https://cloud.githubusercontent.com/assets/1148415/24666376/2908496e-192e-11e7-83ab-0d2b1c16a757.png">
Check more details about data shortcode in your site: http://localhost.com/admin/settings/shortcodes

**Comment by SophiaPetrova** [comment]
Thanks for the fast reply, @owen2345! 

Still got one thing unclear. Are @page2 and @page3 titles or some keywords I need to set to the pages to use it like this (however I got the content using current_site.the_posts("page").where(id: 4).pluck(:content))?

Getting content in the editor worked after update of the version of the gem from 2.3.6 to 2.4.3.2.

Thanks very much and great work!

**Comment by owen2345** [comment]
@page2 and @page3 are sample variables which can be replace with:
```
page2 = current_site.the_post(20) # post with id = 20
page2 = current_site.the_post(21) # post with id = 21
```
Also, my_posts.pluck(:content) can be used but you will need to add the translation, like:
```
my_posts.pluck(:content).map{|content| content.translate }
```
Regards!
