### ISSUE TITLE
Strong Parameters

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#59]
Any plans to move away from using `protected_attributes` and using strong parameters instead of `attr_accessible` et. al.?

**Comment by owen2345** [comment]
Yes!, we have a plan to change that maybe in 3 months.
Actually I am working in a drag and drop editor "Please see attached".
![screen shot 2015-09-10 at 3 13 51 pm](https://cloud.githubusercontent.com/assets/1148415/9798281/f73ea02c-57cd-11e5-868e-a4482a18760e.png)

**Comment by cmckni3** [comment]
Sweet!

That drag and drop editor looks pretty neat as well.

**Comment by cmckni3** [comment]
Closing for now
