### ISSUE TITLE
how can I override default_url_options

### ISSUE THREAD

**Issue by wuboy0307** [owen2345/camaleon-cms#590]
in camaleon_cms/config/routes.rb

You already define default_url_options. However, I have to use https protocol in my production environment.

I try everything without luck, only thing I can do is override the routes.rb file.
```
    default_url_options :host => (CamaleonCms::Site.main_site.slug rescue ""), :protocol => Rails.application.config.force_ssl ? "https" : "http"
```

Is there any configuration I can set without override your routes file?

**Comment by owen2345** [comment]
@wuboy0307 sorry it was static.
I moved into PluginRoutes class which can be overwritten like this:
```
# config/initializers/custom_default_url_options.rb
PluginRoutes.class_eval do
  def self.default_url_options
    {host: 'owen.com', protocol: 'https'}
  end
end
```
Please try using github version for testing.
Regards!

**Comment by wuboy0307** [comment]
thanks, it works
