### ISSUE TITLE
What would be the best integration of a video hosting platform ?

### ISSUE THREAD

**Issue by gcrofils** [owen2345/camaleon-cms#592]
CameleonCMS is great platform. Nevertheless the video part is a bit lagging. 

So far, If I understand well: .mp4 can be uploaded in the media file manager. To play it back, is uses a simple html 5 video tag with known limits, including buffering.

![capture d ecran 2017-04-06 a 14 15 24](https://cloud.githubusercontent.com/assets/93443/24740500/1c927c3e-1ad4-11e7-9389-f058b7422443.png)

Not very nice if you ask me.

1) I would like to integrate upload to a video hosting platform such as Vzaar or Cloudinary.
These platforms process the videos to create -- for example -- different sizes.

2) Also I would like to integrate their player in posts.

3) Last but not least I d like to display a video as an alternative to featured picture.

What would be the best way to achieve this ?
I dont want to modify (too much or in the wrong way) the core code in order to have as less conflicts as possible with next releases of CamaleonCMS.

Thanks

**Comment by owen2345** [comment]
@gcrofils I can see the problem, you can do it by creating a plugin which manage the following:
- Permit to upload videos to a your video hosting
- Add a field meta['featured_video'] with a video uploader in the sidebar of post's form (use hook "post_form_sidebar_custom_html" [see here](https://github.com/owen2345/camaleon-cms/blob/master/app/views/camaleon_cms/admin/posts/_sidebar.html.erb#L150)
In this hook you can embed your custom html/script for your uploader which can assign the value into featured_video input
- If you want to add an alternative to media for videos, you can add a left menu "Video Media", like [here](https://github.com/owen2345/camaleon-ecommerce/blob/master/app/helpers/plugins/ecommerce/ecommerce_helper.rb#L20)
By this way your video uploader gem will work with next versions of the CMS.
Note: Plugin is equal to a rails gem with some files(controllers/helpers..) auto generated to inherit from Camaleon.

Regards!
