### ISSUE TITLE
Can I migrate existing pages from BrowserCMS to CamaleonCMS?

### ISSUE THREAD

**Issue by mkernsNCR** [owen2345/camaleon-cms#595]
I have a existing Rails Application and I am current using BrowserCMS. I want to start moving pages over from BrowserCMS to CamaleonCMS. I am having difficulties moving my existing pages from BrowserCMS to CamaleonCMS. Any suggestions would be greatly appreciated.

**Comment by mkernsNCR** [comment]
Hi @owen2345 I don't mean to be pushy but I am working on a project for my company and could really use your expertise on the subject of this issue.

**Comment by owen2345** [comment]
Hi@mkernsNCR,
please contact me on skype: owen-2345
Regards,

**Comment by mkernsNCR** [comment]
Thanks for your reply @owen2345! Would you be free for a Skype call around 3pm? My colleague will be joining us.

Regards!

**Comment by owen2345** [comment]
Yes, that is ok!

**Comment by mkernsNCR** [comment]
Perfect!
