### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BunlongOung** [owen2345/camaleon-cms#597]
Hi @owen2345,
I am working on a project that need to export post type records to excel or csv file, so can you kindly help me with that please. It would be a big help for me.

Thanks

**Comment by owen2345** [comment]
Hi @BunlongOung 
do you need to export this in front or admin panel?

**Comment by BunlongOung** [comment]
Hi @owen2345, 
I want this feature for admin panel.

Cheer

**Comment by NySiya** [comment]
Hello @owen2345,

How is this feature? Do you have any plugin of this feature? I want it, too.

Kind regards,

**Comment by brian-kephart** [comment]
@BunlongOung @NySiya have you seen [this?](https://github.com/owen2345/camaleon_export_import) It exports to JSON, not CSV, but you could use a separate converter, or fork the plugin and modify it.

**Comment by BunlongOung** [comment]
@brian-kephart Thanks!
