### ISSUE TITLE
How to get the contact form to actually send the emails

### ISSUE THREAD

**Issue by alexvco** [owen2345/camaleon-cms#598]
I tried to implement the contact form plugin and noticed that when a user clicks submit, it says message sent successfully however no real emails get sent. The message is saved and can be accessed from the admin section but how can we incorporate it with action mailer so that the message gets sent via email as well?

**Comment by owen2345** [comment]
Hi @alexvco 
You need to configure your email settings in admin -> settings -> general site -> email tab
Regards,

**Comment by alexvco** [comment]
Thanks @owen2345 

I appreciate it
