### ISSUE TITLE
Customize email template

### ISSUE THREAD

**Issue by alexvco** [owen2345/camaleon-cms#599]
Hi @owen2345 

Is there a way to customize the email template? I see in your code you have the following:

<h2><%= raw @subject  %></h2>
<div>
    <%= raw @html  %>
</div>

How and where would i be able to overwrite this?

I tried creating a camaleon_cms folder under my theme and making changes
(new/views/camaleon_cms/html_mailer/mailer.html.erb)

but that did not work...

**Comment by owen2345** [comment]
Hi @alexvco 
here you can see an example here:
https://github.com/owen2345/camaleon-cms/tree/master/app/apps/themes/camaleon_first/views
the template:
views/html_mailer/mailer.html.erb
the layout:
views/layouts/mailer.html.erb
Regards!

**Comment by alexvco** [comment]
I tried making changes to the files you mentionned, I am not seeing the changes when the email is sent....

<h4>Hello World</h4>

<%= raw @subject %>

<%= raw @html %>

I added "Hello World" in the beginning of the file(views/html_mailer/mailer.html.erb) but when the email is sent the hello world is not showing up...

**Comment by owen2345** [comment]
@alexvco 
sorry, it was my fault in the example.
Check again pls (updated example):
https://github.com/owen2345/camaleon-cms/tree/master/app/apps/themes/camaleon_first/views
Move layout within camaleon_cms folder and move template to views/ from html_mailer
Regards,

**Comment by alexvco** [comment]
@owen2345 

Thank you
