### ISSUE TITLE
Layout Support

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#6]
Is there any support for changing a page's layout from the admin? For example, what if I want an About page that uses a 1-column layout but I want all other pages to use a 2-column layout?

**Comment by owen2345** [comment]
yes, there is a support for templates:
You need to create a file in your views:
template_<my_template_name>.html.erb: this will be liested on content editor if it accept templates. To enable this, you need to edit your post_type settings and check template support (pages by default come enabled).

Here check themes structure:
http://camaleon.tuzitio.com/themes-1.html
