### ISSUE TITLE
Frontend routes issue

### ISSUE THREAD

**Issue by aspirewit** [owen2345/camaleon-cms#600]
1. The route labels defaults to English words, but when user using non English language, there will be no route to match, such as `cama_search_path`
2. In the segment constraints, non ascii characters needs decoding

related issue: #558

**Comment by owen2345** [comment]
@aspirewit can you please research for it? these days I am busy.
Regards!

**Comment by aspirewit** [comment]
@owen2345 Ok, I will give priority to adding the frontend routing related test cases.

**Comment by NelcifranMagalhaes** [comment]
Here the same error, when i change the language for Portugues Brazil, but when i change back for English, works.

**Comment by yfractal** [comment]
@NelcifranMagalhaes  
I think this should be fixed in this [pull request](https://github.com/owen2345/camaleon-cms/pull/611) .
We have used the code for a while, you may give it a try.

cc @aspirewit

**Comment by owen2345** [comment]
Please someone share me the error or how can I reproduce it?

**Comment by owen2345** [comment]
Merged!
Please test it and confirm me that it works well to release a new version.
Regards!

**Comment by NelcifranMagalhaes** [comment]
![printda tela de erro](https://cloud.githubusercontent.com/assets/22278938/25481928/df8199bc-2b25-11e7-9353-3db8975b3ff2.png)

**Comment by owen2345** [comment]
@NelcifranMagalhaes what language are you using?

**Comment by NelcifranMagalhaes** [comment]
for the error to occur , just change the language for Portuguese-Brazil in admin.

**Comment by aspirewit** [comment]
@NelcifranMagalhaes Please using `gem 'camaleon_cms', github: 'owen2345/camaleon-cms'`, and try again.

**Comment by owen2345** [comment]
Apparently it was solved in the current version of github. this weekend I will release the new version after some additional tests.
