### ISSUE TITLE
Contact Form Item not translate to chinese

### ISSUE THREAD

**Issue by lanzhiheng** [owen2345/camaleon-cms#606]
![image](https://cloud.githubusercontent.com/assets/8858472/25211155/650c3814-25b6-11e7-99a0-831a4acf2961.png)

**Comment by owen2345** [comment]
@lanzhiheng I am sorry, contact form only includes spanish and english translations.
You can use this to translate to other languages:
https://github.com/owen2345/cama_contact_form/blob/master/config/locales/es.yml
Regards!

**Comment by lanzhiheng** [comment]
@owen2345 OK 。I try to fix it
