### ISSUE TITLE
Feature Request: Memcached/Redis support

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#609]
I'm running on Heroku, which restarts my app from a slug every day (this is not configurable). This means that:

1. Since the Front Cache plugin uses the local filesystem, the cache files do not exist when the app is restarted.
2. Even if the local files were retained, the cache would be unnecessarily cleared because the plugin clears the cache on restart.
3. If I ever use more than one Heroku dyno, the cache would not be shared between them.

Support for a distributed caching system would solve all of this, and would be much appreciated!

**Comment by owen2345** [comment]
You are right @briank-musichouse I will add in the next version.
Regards!
