### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by aspirewit** [owen2345/camaleon-cms#612]
After changing the frontend languages, sometimes the page will appear the following problems. If I clear the cookies, the page can be displayed. Maybe data stored in sessions is not refreshed.

```
Template is missing
Missing template layouts/index with {:locale=>[:es, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}
```

**Comment by owen2345** [comment]
@aspirewit could you please create a git project with the problem or give more details to reproduce the problem? I tried to reproduce bu I can not see the error.
Regards!
