### ISSUE TITLE
User Roles Disabled

### ISSUE THREAD

**Issue by alexvco** [owen2345/camaleon-cms#613]
Hi @owen2345 

Everything in the User roles is disabled...
I cant change anything neither for the admin(all boxes checked) nor the client(all boxes unchecked)

<img width="1169" alt="1_screen shot 2017-04-24 at 4 44 39 pm" src="https://cloud.githubusercontent.com/assets/16466494/25357901/974f64ae-290d-11e7-97d7-c02c792557f4.png">
<img width="1169" alt="2_screen shot 2017-04-24 at 4 45 54 pm" src="https://cloud.githubusercontent.com/assets/16466494/25357916/aa1b7c3a-290d-11e7-92e5-77d741bebd4d.png">

Would appreciate your help

**Comment by yfractal** [comment]
@alexbrinkman does this  relate to https://github.com/owen2345/camaleon-cms/pull/607 ?

We think user should not be able change himself/herself roles. 
As a admin, for example 'Dev Keen', he can change client's roles, but he can't change himself roles.

**Comment by alexvco** [comment]
@yfractal 

No it seems as though everything is disabled...Dev Keen is an admin user and cannot edit/modify other admins nor clients...

**Comment by alexvco** [comment]
UPDATE:

The default client and admin roles are still disabled, however i found a way around it.
I created a new role and was able to check and uncheck the fields needed.

**Comment by owen2345** [comment]
Those roles are disabled, you need to create another custom roles to edit.
