### ISSUE TITLE
How to display different versions/dimensions of an image 

### ISSUE THREAD

**Issue by mwanikigeorge** [owen2345/camaleon-cms#614]

**Comment by owen2345** [comment]
Please use this:
https://github.com/owen2345/camaleon-cms/blob/master/lib/ext/string.rb#L124

**Comment by haffla** [comment]
Oh man this should be documented! I've written my own little function to fetch thumbs and other image versions. Anyway  :thumbsup:

**Comment by mwanikigeorge** [comment]
I agree this CMS is awesome but the documentation is too technical

**Comment by mwanikigeorge** [comment]
Thanks for the support @owen2345

**Comment by blaszczakphoto** [comment]
For specific version:
```
CamaleonCms::Post.find(44).get_meta(:thumb).cama_parse_image_version("800x")
```

For thumb:
```
CamaleonCms::Post.find(44).get_meta(:thumb).cama_parse_image_version
```
