### ISSUE TITLE
TinyMCE error after upgrading to 2.4.3.2

### ISSUE THREAD

**Issue by jcarlosgarcia** [owen2345/camaleon-cms#617]
Hi, 
We've upgraded progressively from 2.1.1.4 to 2.2.1, 2.3.6 and finally 2.4.3.2 and found a problem with TinyMCE in the admin interface. The editor was working on 2.1.1.4 but raises the same error on 2.2.1, 2.3.6 and 2.4.3.2 after the upgrade. Here's a screenshot of a post which indeed has the contet field filled in.

![camaleoncms_2 4 3 2](https://cloud.githubusercontent.com/assets/1229221/25492740/408d1288-2b74-11e7-9009-7e44de80ffab.jpg)

Any ideas?

Thanks,
JC

**Comment by owen2345** [comment]
Hi @jcarlosgarcia 
I tried to reproduce the problem but without success, in the screenshot I can see errors in tinymce. can you try bundle update? if not, contact me on skype owen-2345.
Regards!

**Comment by jcarlosgarcia** [comment]
Thank you very much @owen2345. Will contact you via Skype.

Best!

**Comment by jcarlosgarcia** [comment]
Closing this issue as it was a problem with the tinymce-rails gem
