### ISSUE TITLE
remove pluralize for some locales

### ISSUE THREAD

**Issue by wuboy0307** [owen2345/camaleon-cms#618]
https://github.com/owen2345/camaleon-cms/blob/6f5271cc4297559a8de3439a5b0b309919d0b436/app/views/camaleon_cms/admin/categories/index.html.erb#L15
https://github.com/owen2345/camaleon-cms/blob/6f5271cc4297559a8de3439a5b0b309919d0b436/app/views/camaleon_cms/admin/categories/index.html.erb#L42
https://github.com/owen2345/camaleon-cms/blob/6f5271cc4297559a8de3439a5b0b309919d0b436/app/views/camaleon_cms/admin/post_tags/index.html.erb#L6
https://github.com/owen2345/camaleon-cms/blob/6f5271cc4297559a8de3439a5b0b309919d0b436/app/views/camaleon_cms/admin/post_tags/index.html.erb#L40

I am from Taiwan. We use traditional Chinese, which doesn't have to pluralize or singularize string. CamaleonCMS will now append unnecessary "s" after my category name.
<img width="573" alt="2017-04-28 9 58 45" src="https://cloud.githubusercontent.com/assets/2128976/25511455/8a698c94-2bf9-11e7-9eb8-44d96f0111ce.png">

Maybe you should change it to @post_type.decorate.the_title.pluralize(nil, **current_locale**) ?

**Comment by owen2345** [comment]
@wuboy0307 I separated pluralizations into a helper CamaleonCms::CamaleonHelper.cama_pluralize_text then this method can be override and avoid pluralizations, like:
```
# config/initializers/pluralization.rb
CamaleonCms::CamaleonHelper.module_eval do
  cama_is_admin_request? && @cama_i18n_frontend == 'zn' ? text : text.try(:pluralize)
end
```

**Comment by wuboy0307** [comment]
The example should be:
```
CamaleonCms::CamaleonHelper.module_eval do
  def cama_pluralize_text(text)
    cama_is_admin_request? && @cama_i18n_frontend == 'zh-TW' ? text : text.try(:pluralize)
  end
end
```

But it works, thanks!
