### ISSUE TITLE
default slug from title.to_url

### ISSUE THREAD

**Issue by wuboy0307** [owen2345/camaleon-cms#619]
https://github.com/owen2345/camaleon-cms/blob/master/app/models/camaleon_cms/post_default.rb#L63
I am not sure why you commented out this line.

I am from Taiwan. We use traditional Chinese. 
jquery.slugify won't work for traditional Chinese, I must enter slug manually.

https://github.com/rsl/stringex
There's a helpful method to_url in stringex. It can convert a string to url, even for Chinese.
How about set slug to title.to_url if slug is blank?
```
  def before_validating
    self.slug = self.title.to_url if self.slug.blank?
  end
```

**Comment by owen2345** [comment]
@wuboy0307 it was disabled for multisite because post form on submit is sending this format:
<--en-->English<--es-->Spanish.

**Comment by wuboy0307** [comment]
Then we should deal with multisite string separation. For single site environment, it is still a good idea to generate slug like I proposed. Even for multisite environment, use to_url after local e string been split is still better. 

I know it's not quite easy for you to understand. But supports for non-ascii language  are important for me. Maybe you can do something  for this? Thanks.

**Comment by owen2345** [comment]
I now,
can you give a sample of your slug that you are using for? I tried to put this "測試" but it was converted into "%E6%B8%AC%E8%A9%A6".
Also let me know how should be the result.
Note: "string".to_url is not a function.
Regards!

**Comment by wuboy0307** [comment]
You must include https://github.com/rsl/stringex gem to get the to_url function.
"%E6%B8%AC%E8%A9%A6" is just the UTF-8 encoding format for "測試" 
(Chinese, Japan, Korea are encoded with 3 bytes per word)

"測試" .to_url will become "ce-shi", which is the spelling of these two words.
You can listen to it with google translation https://translate.google.com.tw/?hl=zh-TW/en/%E6%B8%AC%E8%A9%A6#zh-CN/en/%E6%B8%AC%E8%A9%A6

**Comment by owen2345** [comment]
Done!
Please use this plugin:
https://github.com/camaleon-cms/cama_non_ascii_slug

**Comment by wuboy0307** [comment]
Thanks, it works!
