### ISSUE TITLE
Customize frontend routes

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#62]
Is there any way to drop the `/plugin` part of a route exposed by a plugin?

Suppose I have a plugin called `About`. Can I have the frontend use `/about/something/list`?

**Comment by owen2345** [comment]
Yes, you can do it by routes_main.txt
Sample: 

scope "client", module: "plugins/tusqpones/client", as: "client" do
    resources "promotions", controller: "promotions", path: "promotions"  do

    end
end

This will accept your route and use your controllers like this:
http://localhost/client
http://localhost/client/promotions
http://localhost/client/promotions/....

Regards!

**Comment by cmckni3** [comment]
Thanks! I figured I could use the Rails routing parameters and methods.

On a sidenote, why do these files have a `.txt` extension instead of a`.rb`?

**Comment by owen2345** [comment]
Because ruby throws an error with:
"not exist method get for ...."
for this simple sample:
get "index" => :index

This is because it is not wrapped with any routes.draw

**Comment by cmckni3** [comment]
Is it not possible for camaleon plugins to use a routes.draw like Rails engines?

**Comment by owen2345** [comment]
Yes, I am thinking in that for new versions!

**Comment by cmckni3** [comment]
:+1:
