### ISSUE TITLE
SEO fields not translate to other languages

### ISSUE THREAD

**Issue by aspirewit** [owen2345/camaleon-cms#621]
Fixed in this PR https://github.com/owen2345/camaleon-cms-seo/pull/3, needs update `cama_meta_tag`'s version

![image](https://cloud.githubusercontent.com/assets/9118112/25646119/a1db5d7a-2fe7-11e7-9439-bb2046f1a107.png)

**Comment by owen2345** [comment]
Done!
Released cama_meta_tag 1.4.
