### ISSUE TITLE
Front Cache problem with Rails 5.1

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#624]
I started noticing this error on 4/27:
`ActionView::MissingTemplate: Missing template themes/music_house/views/camaleon_cms/404, camaleon_cms/default_theme/camaleon_cms/404, /camaleon_cms/404 with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, `

This appears to happen when requests are initiated for missing images or css.

**Comment by briank-musichouse** [comment]
I'm still getting this error regularly on asset 404s. Has anyone else experienced it?

**Comment by brian-kephart** [comment]
I attempted to upgrade from Rails 5.0.3 to Rails 5.1.1. Now this issue is occurring on some CMS content as well, not just assets, causing fatal errors when requesting pages.

`ActionView::MissingTemplate: Missing template themes/my_app/views/post, camaleon_cms/default_theme/post with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}.`

Top line of trace:
`File "/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.1/lib/action_view/path_set.rb", line 46, in find`

Running latest git version of Camaleon, Ruby 2.4.1.

**Comment by WMPayne** [comment]
I experienced trouble with Ruby 2.4 and Rails 5.1 with Camaleon as well. I've found it safe to work with 2.3.3 and Rails 5.0.3 though. Try making a new gemset and seeing if that helps the problem, I'm interested to hear if that changes anything because I need the most recent Rails versions as well.

**Comment by brian-kephart** [comment]
Both of these problems point me [here](https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/action_view.rb#L16).

This line calls the ActionView `find` method, which is what raises the exception. Neither of these files has changed since last year, though, so there's still some tracing to be done.

In the case of the asset 404s, the search correctly looks for `/camaleon_cms/404`, and it looks in `/camaleon-cms/app/views`. I have no idea why that causes an exception, since both are correct. I may not see this again since I just made a custom 404 page, and no one else has reported it.

In the case of the missing templates in Rails 5.1, I notice the message says there's a missing template called `/Post`. None of my pages use a template with this name, so it appears the wrong template is being searched. On top of that, the file `/camaleon_cms/default_theme/post` is genuinely [missing](https://github.com/owen2345/camaleon-cms/tree/master/app/views/camaleon_cms/default_theme).

**Comment by brian-kephart** [comment]
[I found something related to 404s](https://stackoverflow.com/questions/34688726/the-nothing-option-is-deprecated-and-will-be-removed-in-rails-5-1). It says the code used in [this line](https://github.com/owen2345/camaleon-cms/blob/master/app/controllers/camaleon_cms/frontend_controller.rb#L159) was deprecated in Rails 5 and removed in Rails 5.1.

**Comment by brian-kephart** [comment]
Regarding the Rails 5.1 template errors, I haven't found anything conclusive yet. I did notice, though, that `get_template` calls `get_meta`, which includes the method `with_indifferent_access`. This method has some [deprecations](https://blog.driftingruby.com/ruby-on-rails-5-1-0-deprecations/). I can't tell that any of them are related to the way this method is used in Camaleon, but can anyone verify?

**Comment by slopy** [comment]
Hi, 

Regarding Rails 5.1 I was actually able to run CMS with this patch. 
I've put this into initializers.
``` ruby
module HashWithIndifferentAccessParameter
  def with_indifferent_access
    ActiveSupport::HashWithIndifferentAccess.new(self)
  end
end

ActionController::Parameters.include Enumerable
ActionController::Parameters.include HashWithIndifferentAccessParameter

module AllowRedirectBackSymbol
  def redirect_to(options = {}, response_status = {})
    if options == :back
      return redirect_back(fallback_location: request.referer)
    end
    super
  end
end
CamaleonCms::FrontendController.include AllowRedirectBackSymbol
`
also 
``` ruby 
 require 'will_paginate/array'
```
I know that this is not the best approach to solve this but might give you some hint about Rails 5.1 issues.

Routes patch is related to 
http://edgeguides.rubyonrails.org/5_1_release_notes.html#direct-resolved-routes

**Comment by brian-kephart** [comment]
Thanks for that @slopy. I get what `HashWithIndifferentAccessParameter` does, but how do `AllowRedirectBackSymbol` and `require 'will_paginate/array'` apply to this problem? I couldn't understand the intent of the link you posted.

**Comment by brian-kephart** [comment]
It looks like `require 'will_paginate/array'` was added in #644.

**Comment by owen2345** [comment]
Hi Guys,
I couldn't see errors related to HashWithIndifferentAccessParameter.
Can someone give me the steps to reproduce it?
PD: I solved some conflicts for rails 5.1.1. (Github version until weekend to detect other errors)
Regards,

**Comment by brian-kephart** [comment]
@owen2345 the problem might not be `HashWithIndifferentAccess`. All of the instances I found of that method were applied to regular hashes, which is still valid. Looking into it I discovered that there's no deprecation with that method after all. The changes I was thinking of have to do with inheritance and classes, not with the method.

I'm still getting the error from my third post in this issue, even with your recent fixes. The only steps required to reproduce it in my app are to update to Rails 5.1, run the app in production, and click around the site. Generally, a few pages load fine before the error starts to occur. I wish I could be more precise, but the behavior is not completely consistent. I'm running latest Rails 5.1.1, Camaleon git version, and Ruby 2.4.1.

The other commenters have had problems too, but I'm curious whether they've had this specific problem. @WMPayne @slopy Have you seen this issue?

**Comment by brian-kephart** [comment]
Update: I tried a fresh Rails 5.1 app with Camaleon installed and I could not reproduce the issue. If no one else is getting these errors then it's probably specific to my app.

To re-sum up the problem, ActionView is looking for a template called post, which does not exist. Even if it did, that's not the correct template for anything in my app. This behavior does occurs on Rails 5.1.1, but not 5.0.3 and lower.

**Comment by brian-kephart** [comment]
It seems that something is causing my app to use templates from the default theme. As stated above, the `Post` template doesn't exist in the default theme within this repository, so an error is raised. After the error occurs, if I go to my index page, it renders the `Index` template from the default theme, not from my custom theme.

**Comment by brian-kephart** [comment]
Got it. Steps to reproduce:

1. Create Rails 5.1 app
2. Enable Front Cache plugin
3. Logout
4. Load a page twice

When a page is loaded from the plugin, the error occurs.
