### ISSUE TITLE
db:migrate StandardError Directly inheriting from ActiveRecord::Migration

### ISSUE THREAD

**Issue by rongworks** [owen2345/camaleon-cms#625]
Hi folks, I tried to install camaleonCMS on rails 5.1, but get this Error when trying to populate the db:

`rake db:migrate` fails 
after Migration `20160504155653 MoveFirstNameOfUsers` with:

`
StandardError: An error has occurred, this and all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
(...)
`
Full log:
[camaleon_migration_log.TXT](https://github.com/owen2345/camaleon-cms/files/982695/camaleon_migration_log.TXT)

This seems to be a problem with Migrations that don't follow the introduced scheme `ActiveRecord::Migration[x.x]`. But I can't find a workaround.

Any ideas? Thanks !

**Comment by owen2345** [comment]
Fixed, please bundle update for cama_contact_form.

**Comment by rongworks** [comment]
Great ! Thanks. 
db migration runs smoothly now.
