### ISSUE TITLE
Multilanguage & slugs

### ISSUE THREAD

**Issue by milleroff** [owen2345/camaleon-cms#627]
Hi,

I have a site based on Camaleon CMS v2.4.3 with multiple languages.
An article is available in each language by its slug as follows:
English version: http://example.com/article1_name
Russian version: http://example.com/ru/nazvanie_statji1

Now i'm using the following code to draw a language selection menu:

```ruby
def custom_draw_languages()
  lan = current_site.get_languages
  return if lan.size < 2

  res = ["<ul><li><a href='#'>#{I18n.locale.to_s}</a><ul>"]

  lan.each do |lang|
    next if I18n.locale.to_s == lang.to_s

    res << "<li> <a href='#{cama_url_to_fixed("url_for", {locale: lang})}'>#{lang}</a> </li>"
  end

  res << "</ul></li></ul>"
  res.join("")
end
```

I'm accessing the english version of the article http://example.com/article1_name, after that i want to open its russian version using the language menu selector. The problem is that it points to:
http://example.com/ru/article1_name
but it should point to:
http://example.com/ru/nazvanie_statji1

How can i draw the language menu so it outputs the correct slug ?

**Comment by owen2345** [comment]
@milleroff please test using this method:
https://github.com/owen2345/camaleon-cms/blob/master/app/decorators/camaleon_cms/site_decorator.rb#L115
to verify if it renders with the same error.

**Comment by milleroff** [comment]
Thanks for your answer, but it didn't help.

When using the original "draw_languages" function that you pointed to:

```ruby
<%= raw current_site.draw_languages('', true, '') %>
```

i get URLs like this: 
http://example.com/ru/article1_name?cama_set_language=ru

But as i mentioned in the first post, i need an URL with a translated slug:
http://example.com/ru/nazvanie_statji1

**Comment by josefsj3m** [comment]
Hello @owen2345 , I'm having the same problem. The cama_url_to_fixed method in the CamaleonCms :: SiteDecorator class does not consider the slug in the new language, is there any method that retrieves the language-based slug?

Thanks,

**Comment by superchell** [comment]
I have the same problem, have a solution?

**Comment by josefsj3m** [comment]
See #774
