### ISSUE TITLE
How iterate over multiple Class: CamaleonCms::CustomFieldGroup?

### ISSUE THREAD

**Issue by andrewkhouzam** [owen2345/camaleon-cms#629]
After Creating a custom content type called 'services', and adding custom Field Group that supports **multiple** field groups that have a title and description only the first element is added to the array retrieved from function "the_fields"

Is that a bug in the code, or there is another way to get the multiple Class: CamaleonCms::CustomFieldGroup?

**Comment by haffla** [comment]
I get a multiple field like with `@post.the_fields('custom_info')` and it gives me an array.
Is it working for you now?

**Comment by owen2345** [comment]
I added two more methods:
```
# the same function as get_fields_grouped(..) but this returns translated and shortcodes evaluated
the_fields_grouped(field_keys, is_json_format = false)

# the same function as get_fields_grouped(..) but this returns translated and shortcodes evaluated for a single field
the_field_grouped(field_key, is_json_format = false, is_multiple = false)
```
