### ISSUE TITLE
Have all videos open in a particular template like post open on post.html.erb

### ISSUE THREAD

**Issue by mwanikigeorge** [owen2345/camaleon-cms#630]
i have videos throughout the site and i would like them to open in a page with related videos like the way youtube does, how would i go about this?

thanks in advance

**Comment by brian-kephart** [comment]
@mwanikigeorge I did something similar in my site. Here's the general process:

Make videos a content type and give them their own default template in the theme's `/views` folder. Camaleon includes managing categories and tags for posts, so by giving each video categories and tags you can use the built-in methods to grab related videos.

To get an idea of how to do this, check out [this file](https://github.com/owen2345/camaleon-cms/blob/master/app/apps/themes/default/views/partials/_sidebar.html.erb). This is the sidebar for Camaleon's default theme, which shows blog posts related to the current post by categories. Notice in particular the method `the_related_posts`. This method will grab the video posts you want, which you can then display in the template view you create.
