### ISSUE TITLE
Bootstrap colors

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#64]
Bootstrap colors and styles are being overridden inside of `theme-default.scss`. You could actually change this in SASS to override the variables within `variables.css.scss` or `variables.css.sass`.

N.B. I believe the `.css` portion has been optional for awhile now.

**Comment by siakaramalegos** [comment]
+1

**Comment by owen2345** [comment]
I will change the admin template in the next versions.

**Comment by owen2345** [comment]
done!
