### ISSUE TITLE
copy migrations on first install instead of including path

### ISSUE THREAD

**Issue by wuboy0307** [owen2345/camaleon-cms#640]
In CamaleonCms::Engine file, you include the db/migrate path of camaleon_cms. It is convenient if I use camaleon_cms only. However, when I try to integrate other gems which also have some migration scripts to run, it is so painful because I can't reorganize the order of migrations. For example, if I want to integrate camaleon_cms with Spree, and share the same user table Spree::User. When I run db migration, camaleon_cms' migrations always run first and it always complains deleted_at doesn't exists (which it's true, camaleon_cms's migrations run  too early) since spree use "paranoia" gem to fake delete user and it need a deleted_at column. 

Please just follow the standard rails engine procedure, only copy your migration scripts to application's db/migrate folder on first install. So we can manage the order of migrations from different engines.

Update:
https://content.pivotal.io/blog/leave-your-migrations-in-your-rails-engines
I think it's quite convenient for most of users who only wanna use camaleon_cms as a blog system without integrating with other gems.
Maybe it's better you make this configurable so we can choose to run migration automatically or manually copy to application migration path.

**Comment by michaelkrupp** [comment]
+1

Getting the migrations to work properly was a major PITA for me.
Please do not "magically include" files and configuration from all over the place. This was especially problematic while integrating Camaleon and Devise with an existing model, as I have absolutely zero influence on the order of migrations in the cama namespace.

Most gems I know of stick to the `gem_name:install:*` pattern or ship custom generators for their migrations.

**Comment by wuboy0307** [comment]
A temporary ugly fix:

Just put this in your application initializer:
```
      app.config.paths["db/migrate"] = "db/migrate"
```

It will overrides all migrate path to be only "db/migrate". 
However, this issue should still need to be handled.

**Comment by owen2345** [comment]
I will change this for the next release! If anyone has already solved, pls do pull request to merge it.
Regards!!!

**Comment by Kartikvlog** [comment]
If anyone getting the issue while deploying camaleon somewhere so just override the camaleon controller and add `  config.assets.compile = true` in production.rb file and also use `color: rgba(0, 0, 0, 1);` in place of `color: rgba(0, 0, 0);` and then run `bundle exec rails assets:precompile` .
