### ISSUE TITLE
Bootstrap navbar in admin

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#65]
Are you opposed to using a bootstrap navbar in the admin area?

I see there are some bootstrap elements mixed with a custom header. I think this could be simplified by using bootstrap's navbar.

**Comment by owen2345** [comment]
No, But It was in the template.
I am thinking to change the current template for this in a new version:
http://www.condorthemes.com/flatdream/form-elements.html

**Comment by cmckni3** [comment]
That looks pretty neat

**Comment by cmckni3** [comment]
That's actually a paid theme

**Comment by cmckni3** [comment]
What do you think about https://www.almsaeedstudio.com/preview?

**Comment by owen2345** [comment]
yes, I bought that theme but I am not sure if I need to buy any other license to use in the CMS.

**Comment by owen2345** [comment]
I like https://www.almsaeedstudio.com/preview
it looks pretty well!
do you know if I need another license to use that in the CMS?

**Comment by cmckni3** [comment]
The link to the one I posted is open source on GitHub. Let me find the GitHub link.

The one you had posted would probably need a license that's expensive or not even possible. Would need a license to redistribute.

**Comment by cmckni3** [comment]
https://github.com/almasaeed2010/AdminLTE

That's the GitHub repo for the theme I posted.

**Comment by owen2345** [comment]
great! I will work in AdminLTE template!
thank you!

**Comment by cmckni3** [comment]
No problem :+1: 

Let me know if I can help

**Comment by cmckni3** [comment]
How is the work on the new admin interface coming?
