### ISSUE TITLE
undefined method `saved_change_to_attribute?' for #<CamaleonCms::Site:0x007ff468a826b8>

### ISSUE THREAD

**Issue by aidzas** [owen2345/camaleon-cms#651]
On clean install, Rails 5

**Comment by owen2345** [comment]
Please test again using github version and confirm me to deliver new version with the fix.
thank you!

**Comment by 209cameronism** [comment]
@owen2345 

Hello, I had the same problem also, but I used the github version and it works fine.

Thx

**Comment by michaelkrupp** [comment]
@owen2345 

`saved_change_to_attribute?` was introduced in [Rails 5.1]((https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81#diff-2bd7c52253c45ccc631ca0d1199d1201R144).

Your check in `config/initializers/active_record_extension.rb` breaks compatibility with Rails 5.0 for me.

**Comment by owen2345** [comment]
I changed into methods.include?
https://github.com/owen2345/camaleon-cms/blob/master/config/initializers/active_record_extension.rb#L89
