### ISSUE TITLE
Multiple Files Uploading

### ISSUE THREAD

**Issue by gcrofils** [owen2345/camaleon-cms#653]
When we upload several files, we have observed a weird behavior : some of them are not listed ("disappear") as shown in the video : 

[![cp_multiuploading](https://user-images.githubusercontent.com/93443/27079862-ff9fbd94-506b-11e7-9856-77599a084df8.jpg)](https://app.vzaar.com/videos/10507484)

(click to open the video in a new window)

**Comment by haffla** [comment]
CamaleonCms uses [this jquery plugin](http://hayageek.com/docs/jquery-upload-file.php). When uploading multiple files the plugin starts one request per file concurrently. So your webserver sees NR_OF_IMAGES requests at the same time. I could not track down exactly what goes wrong. There is a lot going on when uploading a file (database, imagemagick...). I'm going to look into it.
A temporary solution is to tell the plugin to upload the files sequentially. Then it works. Add these two lines 
```
sequential: true,
sequentialCount: 1,
```
[to the plugin's option parameter](https://github.com/owen2345/camaleon-cms/blob/master/app/assets/javascripts/camaleon_cms/admin/uploader/_media_manager.js.coffee#L101)

**Comment by haffla** [comment]
I just uploaded 18 files (running Cama locally). My whole laptop literally freezes and `top` shows all my cpus running at 100%. I get a 
`ActiveRecord::ConnectionTimeoutError - could not obtain a connection from the pool within 5.000 seconds (waited 20.077 seconds); all pooled connections were in use`

So I guess my proposed solution is the way to go. I'm going to do a pull request.

**Comment by haffla** [comment]
Can be closed now
