### ISSUE TITLE
Content group slug on multiple sites

### ISSUE THREAD

**Issue by phlcastro** [owen2345/camaleon-cms#655]
Hi,

I couldnt find any older issue regarding this problem. So Im not sure if is something Im missing here or if it is a real current limitation.
I have this multiple site installation and I would like to create a content group called "blog" on all of them.
The problem is that even being allowed to do it, when I try to use it dont work as expected: it only works for one site and all others dont.
Lets say I have 3 sites, all of them with a content group with slug 'blog'.

www.firstdomain.com/blog - doesnt work
www.seconddomain.com/blog - doesnt work
www.thirddomain.com/blog - works!!

If I change the thirddomain content group slug to something else, then www.seconddomain.com/blog works fine (but firstdomain still doesnt).

Is it something Im misconfigured or its a know bug?

Thanks in advance!

**Comment by haffla** [comment]
Can be closed then
