### ISSUE TITLE
[Question] Add fields to post category

### ISSUE THREAD

**Issue by paulitolinhares** [owen2345/camaleon-cms#656]
Hello, I'd like to know if it's possible to add a new field to the `Cama::Category`. I'd like to add a cover picture (somehow like it happens on posts).

**Comment by haffla** [comment]
It works the same way! Create your custom field group at `/admin/settings/custom_fields/new` and choose to display that group in the category section. Now this group will be shown in the edit section of your categories (`/admin/post_type/[POST_TYPE_ID]/categories/[CATEGORY_ID]/edit`).

Now you can access the fields with for example

`your_category.the_field('image')`

or multiple

`your_category.the_fields('images')`

**Comment by paulitolinhares** [comment]
It works! Thanks a lot
