### ISSUE TITLE
Import Script to Camaleon CMS Database

### ISSUE THREAD

**Issue by NySiya** [owen2345/camaleon-cms#659]
Hello @owen2345,

I am trying to write an import script to import my **Old database** to my **existing production database**. But now I face a problem in CamaleonCMS relationship on importing `cama_term_relationships`. I see a column named `ObjectId` but I don't know what it is used for and its relation with other columns.

Please, let me know as soon as possible.
Regards,

**Comment by owen2345** [comment]
objectid is the object owner id, sample: if your object_class = 'Post', then your objectid is the Id of your post.
Note: this field is only for field groups which belongs to Objects and not for fields of a field group.
Sorry for the delay answering but until next month I am offline.
Regards,

**Comment by NySiya** [comment]
@owen2345, Thank you so much 👍
