### ISSUE TITLE
Ukrainian Flag Image

### ISSUE THREAD

**Issue by Surakarus** [owen2345/camaleon-cms#664]
Could you please, add ukrainian flag image? Similar to [#302](https://github.com/owen2345/camaleon-cms/issues/302).
Thank you in advance.

**Comment by owen2345** [comment]
Done!

**Comment by Surakarus** [comment]
I believe, that flag pictures should be named after locales, not countries. Ukrainian locale abbreviation is "uk", so picture's name should be "uk.png". In current state flag doesn't appear. However, if I manually rename picture, it appears. Also, resolution of pictures of the existing flags is 24x24px, but resolution of picture of the ukrainian flag is 48x48px. Thank you for help, keep doing great work!
P.S. Here's suitable image ![uk](https://user-images.githubusercontent.com/18678026/28007887-e16a9da6-655d-11e7-8e57-083a76baf6be.png)
