### ISSUE TITLE
Changer order back office

### ISSUE THREAD

**Issue by floreasy** [owen2345/camaleon-cms#665]
Hi, how would it be possible to change the display order of the elements in the back office ? 

I tried to modify the post_controller and add an "order" method like this : 

` @posts = @posts.order(:slug)`

In this case I would order by slug name, but nothing really happen when I inspect the content, whatever I put inside ... 

Any ideas ? 

I would like to put a link on the top of each column ( ID, title, status etc ... ) and these link would sort them in the order. 

Thank you so much for you work.

**Comment by owen2345** [comment]
You need to use reorder to override the current ordering "created_at", sample:
@posts = @posts.reorder(title: :asc)

**Comment by floreasy** [comment]
Thank you very much, that is just what I needed ! 
Have a nice day
