### ISSUE TITLE
Loop on the multiple group custom fields on the FO

### ISSUE THREAD

**Issue by floreasy** [owen2345/camaleon-cms#668]
Hi,
Everything is in the title, I cannot succeed in getting the datas of a multiple custom fields group created in back office. I can get only the first one by using the_field('slugname') but thing is I have like 4 groups that I need to get datas and I could not find how to get them. 

Thank you !

**Comment by floreasy** [comment]
Actually I found in /app/view/camaleon_cms/default_theme/partials the file _render_custom_field.html.erb which looks like what I need. But when I try to use the variable "field" there s an error occuring. How could I access these datas ?
Thank you !

**Comment by floreasy** [comment]
I tried this : 
`@post.get_fields_grouped('_group-sous-menus-des-pages').inspect`
Where "_group-sous-menus-des-pages" is the slug of my custom group field but it returns an empty table . I really do not get it.

**Comment by floreasy** [comment]
[ UP ] I could get the datas "manually" using `@post.get_fields('slug-name',1)` where "1" is the second element in my multiple group. I would be really glad to get that into a proper loop ! 
Thank you

**Comment by brian-kephart** [comment]
@floreasy I haven't used the function you're asking about, but it looks like `get_fields_grouped` takes an array of strings, not a plain string. Try `@post.get_fields_grouped(['_group-sous-menus-des-pages']).inspect` and see if you get what you need.

**Comment by floreasy** [comment]
Thank you Brian for the answer. Actually, what you wrote did not work, but if I write the slug of the subfield, it does return an array of all the items / subfields. So, to close the subject, here's what you got to do if you want to loop on multiple fields : 
`@post.get_fields_grouped(['name-of-the-slug'])` -> will return you an array of all the values of the multiple custom fields.
