### ISSUE TITLE
show/hide custom fields based on another custom fields value

### ISSUE THREAD

**Issue by hazemtaha** [owen2345/camaleon-cms#671]
Is it possible to create custom fields that are dependant on another custom fields? I need to show/hide certain custom fields based on the value of another custom field, is it possible?

**Comment by owen2345** [comment]
@hazemtaha for now it is not possible, you need to add your custom javascript to control the custom fields.

**Comment by hazemtaha** [comment]
is there a way to override admin panel views?

**Comment by owen2345** [comment]
You can add :render attribute for custom fields using this hook "extra_custom_fields":
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/admin/custom_fields_helper.rb#L341
The attribute :render is the template path, if it is empty or not exist it will render
```
"camaleon_cms/admin/settings/custom_fields/fields/#{custom_field[:key]}"
```
Check here:
https://github.com/owen2345/camaleon-cms/blob/master/app/views/camaleon_cms/admin/settings/custom_fields/_render.html.erb#L34

Regards,
