### ISSUE TITLE
Validation with contact_form

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#679]
This is the message when i used camaleon_cms 2.4.3.12
----------------------------
ActiveRecord::RecordInvalid in CamaleonCms::Admin::InstallersController#save
Validation failed: Requires different slug

**Comment by lmany** [comment]
The steps for the issue 
1 - migration from camaleon_cms 2.4.3.6 to 2.4.3.12
2 - the main_helper.rb file on ....install_theme 
gr = current_theme.add_field_group({name: "Contact us", slug: "contact_us"})
3 - re install the app (admin/installer) and I had this issue.

**Comment by pbr-pl** [comment]
in main_helper.rb
```ruby
unless current_themetheme.get_field_groups.where(slug: "contact_us").any?
  gr = current_theme.add_field_group({name: "Contact us", slug: "contact_us"})
end
```
