### ISSUE TITLE
NoMethodError in CamaleonCms::Admin::SessionsController#login_post

### ISSUE THREAD

**Issue by dwarfi** [owen2345/camaleon-cms#684]
I've received this message while trying to log in to the backend. I've installed the CMS on an existing app.
![screenshot from 2017-09-09 20 22 28](https://user-images.githubusercontent.com/11318084/30243201-a8120c14-959c-11e7-867e-6ef8a9e18089.png)

**Comment by owen2345** [comment]
I think you are using your own user model, pls confirm that you followed this steps:
http://camaleon.tuzitio.com/documentation/category/139779-faqs/custom-login.html#custom_authentication_using_my_model
Also, if you have the same attributes with different names, add alias_attribute ...
Regards!!!
