### ISSUE TITLE
Error action save_comment

### ISSUE THREAD

**Issue by danilvoe** [owen2345/camaleon-cms#685]
Only get acquainted with CMS(Version 2.4.3.12). When you try to leave a comment, an error occurs, while the comment itself is created and can be seen in the confirmation section of comments.

![screenshot_299](https://user-images.githubusercontent.com/15100792/30260470-32320140-96d0-11e7-8b14-e27434340e94.jpg)

**Comment by owen2345** [comment]
Fixed!
