### ISSUE TITLE
Assets compilation failing working with webpack

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#688]
Added Camaleon to an ongoing rails project using webpack through the [webpacker gem](https://github.com/rails/webpacker) and now I'm having an issue with the assets compilation...
`ActionView::Template::Error (File to import not found or unreadable: ~foundation-sites/scss/foundation`

I've made a [repo](https://github.com/tostasqb/webpacker-camaleon) so that I could ask for your help in describing the problem. 

In _themes > new > assets > styles > sitewide > foundation.scss_ I'm importing the foundation node_module like before but now just doesn't work...

**Comment by owen2345** [comment]
Hi @tostasqb 
I solved your problem changing into:
```
@import 'foundation-sites/scss/foundation';
```
Regards!!!

**Comment by tostasqb** [comment]
Hi @owen2345, thanks for the input. it helped on runtime although it still gave me errors precompiling and on first starting the server. 

Anyhow I just discovered that using another folder (outside the theme) for assets helps. and precompiles as expected, so I guess I'll use that workaround as I will not be using another theme anyway. It may be related with mixing sprockets with the webpack compilation...

I suspect in other cases it would be useful a final solution using webpacker but I'll close this for now.
