### ISSUE TITLE
Inactive site with no page selected is inaccessible

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#690]
This is an unusual case for sure, but it's possible. If a site is set as inactive and no page is selected to show on the inactive site, the site becomes completely inaccessible.

Steps to reproduce:

1. Delete all 'Page' posts in a Camaleon site.
2. Set the site to 'Inactive'.
3. Attempt to access.

Result:
`ActiveRecord::RecordNotFound: Couldn't find CamaleonCms::Post without an ID`

Access restored with Rails console:
`CamaleonCms::Site.find_by_slug('www.mydomain.com').update(status: 'active')`

Code fails [here](https://github.com/owen2345/camaleon-cms/blob/c0bcc598cf798802973b1f4b0ecc8477ec1d6608/app/controllers/camaleon_cms/camaleon_controller.rb#L102).

**Comment by owen2345** [comment]
Added fix, pls review again!
