### ISSUE TITLE
Not working: users_share_sites = false

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#691]
`users_share_sites = false` doesn't seem to be working for me. Steps to reproduce:

1. Create a new app, add `camaleon-cms` (git version) to Gemfile, `bundle`
2. Add config/system.json with `users_share_sites = false`
3. `rails g camaleon_cms:install`
4. `rails db:migrate`
5. Configure config/initializers/camaleon_map_sites.rb (see below)
6. Deploy
7. Initialize site, login to Admin
8. Create additional site at www.mydomain.com/admin/settings/sites
9. Create a user - user appears in both sites, can login to both

config/initializers/camaleon_map_sites.rb:
```
Rails.application.config.to_prepare do
  CamaleonCms::SiteHelper.module_eval do
    def cama_current_site_helper(args)
      if !args[:site].present? && request.present?
        args[:site] =
        case request.original_url.to_s.parse_domain
        when 'site1.com'
          CamaleonCms::Site.find_by_slug('www.site1.com').decorate
        else
          CamaleonCms::Site.find_by_slug('www.site2.com').decorate          
        end
      end
    end
  end
end

```

**Comment by brian-kephart** [comment]
Checking users in Rails console, it appears that users are correctly assigned a site_id, but it doesn't appear to have any effect on their ability to login.

**Comment by brian-kephart** [comment]
Never mind, I fount a typo that send all of the above code to the `else` condition.

**Comment by owen2345** [comment]
Great!
