### ISSUE TITLE
Migration does not work

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#692]
I tried to install it on my existing app, but it did not generate any new migration files
I did:
    RAILS_ENV=development rake db:migrate:status VERBOSE=true

all is up and Camaleon migrations are not listed.

I tried:

    RAILS_ENV=development rake db:migrate VERBOSE=true

nothing happened.. I thought its ok, but when I run the app I got error:

> PG::UndefinedTable: ERROR: relation "cama_term_taxonomy" does not exist LINE 5: WHERE a.attrelid = '"cama_term_taxonomy"'::re... ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"cama_term_taxonomy"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

How can I do migrations properly ? I just followed common steps but no luck..

**Comment by owen2345** [comment]
Hi @hopewise 
please use this temporary fix:
https://github.com/owen2345/camaleon-cms/issues/640#issuecomment-307981355
working in the real fix because the above code is not copying migrations from plugins.

**Comment by hopewise** [comment]
Thanks, how would I make sure that when I run the migrations, it will use development db?

**Comment by hopewise** [comment]
I tried it, did not copy any migration file..

**Comment by owen2345** [comment]
I solved the problem and added to installation steps:
in your config/system.json add auto_include_migrations=false
and then generate migrations manually:
```
rake camaleon_cms:generate_migrations
```

**Comment by hopewise** [comment]
would this work on a pre-existing app?

**Comment by owen2345** [comment]
yes, with config => auto_include_migrations=false ignores the default auto include migrations, then you can copy/generate migrations and customize if you want and run migrations.

**Comment by hopewise** [comment]
I just followed steps and worked fine without any customization, however I could not visit any link of the CMS, I've opened a new issue for that,,

**Comment by owen2345** [comment]
great!
