### ISSUE TITLE
Tags for multiple post types

### ISSUE THREAD

**Issue by jpac-run** [owen2345/camaleon-cms#694]
Hello @owen2345 

Is there a way to make the tags global instead of having them repeated in each content type?

Example: I want to have the tag "abc" in a post of content type A and have that same tag in a post of content type B, without creating the same tag twice.

Thank you in advance ;)

**Comment by owen2345** [comment]
Check this
http://camaleon.tuzitio.com/documentation/category/139779-faqs/make-global-post-tags.html

**Comment by jpac-run** [comment]
Didn't notice this one on the FAQs.

Thank you @owen2345 ;)

**Comment by jpac-run** [comment]
Hello @owen2345 

Just added the code snippet to the project and now I can search for all tags but, when updating, it throws an exception:

ActiveRecord::StatementInvalid in CamaleonCms::Admin::PostsController#create

Mysql2::Error: Column 'name' in where clause is ambiguous: SELECT cama_term_taxonomy.id FROM `cama_term_taxonomy` LEFT OUTER JOIN `cama_term_taxonomy` `post_types_cama_term_taxonomy` ON `post_types_cama_term_taxonomy`.`id` = `cama_term_taxonomy`.`parent_id` AND `post_types_cama_term_taxonomy`.`taxonomy` = 'post_type' WHERE `cama_term_taxonomy`.`taxonomy` = 'post_tag' AND `cama_term_taxonomy`.`parent_id` IN (2, 7, 33, 39, 40, 41, 46, 59) AND (name not in ('test'))

Any advice?

Thanks!

**Comment by owen2345** [comment]
Pls review again the link:
http://camaleon.tuzitio.com/documentation/category/139779-faqs/make-global-post-tags.html
I released another version with hooks added into post tags.
Regards!!!

**Comment by jpac-run** [comment]
Hello @owen2345 

The fix works when you create a tag with the tag form. Although, when I create/update a post, it continues to throw the same exception. If you add this code into app/models/concern/camaleon_cms/categories_tags_for_posts.rb

    def update_tags(tags)
        rescue_extra_data
        tags = tags.split(",").strip
        post_tags = self.post_type.post_tags
        post_tags = post_tags.where("cama_term_taxonomy.name not in (?)", tags) if tags.present?
        self.term_relationships.where("term_taxonomy_id in (?)", post_tags.pluck("#{CamaleonCms::TermTaxonomy.table_name}.id")).destroy_all
        tags.each do |f|
          post_tag = self.post_type.post_tags.where({name: f}).first_or_create(slug: f.parameterize)
          self.term_relationships.where({term_taxonomy_id: post_tag.id}).first_or_create
        end
        update_counters("tags")
    end

the create/update works fine, but only if you use **existing** tags!

If you try to add a tag that does not exist, while adding tags to a post (in post form), it will throw another exception: 

ActiveModel::RangeError in CamaleonCms::Admin::PostsController#update
[2, 7, 33, 39, 40, 41, 46, 59] is out of range for ActiveModel::Type::Integer with limit 4 bytes

To avoid this, you must update the update_tags method like this:

    def update_tags(tags)
      rescue_extra_data
      tags = tags.split(",").strip
      post_tags = self.post_type.post_tags
      post_tags = post_tags.where("cama_term_taxonomy.name not in (?)", tags) if tags.present?
      self.term_relationships.where("term_taxonomy_id in (?)", post_tags.pluck("#{CamaleonCms::TermTaxonomy.table_name}.id")).destroy_all
      tags.each do |f|
        post_tag = self.post_type.post_tags.where({name: f}).first_or_create(parent_id: self.post_type.id, slug: f.parameterize)
        self.term_relationships.where({term_taxonomy_id: post_tag.id}).first_or_create
      end
      update_counters("tags")
    end

making the parent_id the same as the post_type (I'm using the same logic as the example for the hook method in the example you put on the FAQ)

Do you think this can be added in any other way on the Camaleon core code?

Thanks ;)

**Comment by owen2345** [comment]
Released a new version with the fix for hardcoded attributed.
Updated manual:
http://camaleon.tuzitio.com/documentation/category/139779-faqs/make-global-post-tags.html
