### ISSUE TITLE
Support with Gitter?

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#697]
Hi @owen2345, excellent work building this cms btw. 

This issue is related with support and sharing regarding camaleon-cms since I feel, as a recent user, the potential of the product but not really a very active community around it. 

My question would be regarding your thoughts about creating a slack channel to help build and gather the community around camaleon-cms and discuss simple questions (when possible of course) that arise with using it day-to-day.

**Comment by owen2345** [comment]
Hi @tostasqb 
I created this channel: camaleoncms.slack.com
Regards,

**Comment by floreasy** [comment]
Hey @owen2345  could you send invitations to the slack channel please ? 

Thanks a lot,

Flo

**Comment by tostasqb** [comment]
Maybe slack is not a good choice after all. Though this could be public easily but I guess not. Thinking towards Gitter (?)

**Comment by owen2345** [comment]
I prefer Gitter:
https://gitter.im/camaleoncms/Lobby

**Comment by tostasqb** [comment]
Excellent, closing.
