### ISSUE TITLE
ActiveModel::UnknownAttributeError in CamaleonCms::Admin::InstallersController#save

### ISSUE THREAD

**Issue by AliChegini** [owen2345/camaleon-cms#698]
Hi @owen2345 ,

I am trying to setup the project on mac and after inserting a name for the website I get this annoying error. The wired thing is that I did manage to make it work one time without e-commerce plugin but when I did a fresh setup and included e-commerce in gem file I can't get it to work again!!! I see the starting page to choose the name and this error.

PS: I have tried the whole process from the top 5 times in different folders and every time I deleted the old project.

Do you know how can I solve this issue ? It seems like the e-commerce plugin create this issue and I really need to use this plugin.

![screen shot 2017-09-30 at 14 50 44](https://user-images.githubusercontent.com/14887288/31045962-df31232a-a5ef-11e7-9357-dae7bbb305f6.png)

Regards,

**Comment by owen2345** [comment]
Are you integrating to existent project?

**Comment by AliChegini** [comment]
No, completely from the scratch. fresh and clean setup without existing project.

**Comment by owen2345** [comment]
I will review tomorrow.
Note: ecommerce plugin only works on rails 4 and not for rails 5.

**Comment by AliChegini** [comment]
Then that should the problem. My version is Rails 5.1.4
