### ISSUE TITLE
Redirect loop with existin devise model

### ISSUE THREAD

**Issue by dirkwink** [owen2345/camaleon-cms#699]
Hello everybody!

I try to use an existing devise model to login into Camaleon. I used this [FAQ page](http://camaleon.tuzitio.com/documentation/category/139779-faqs/custom-login.html#custom_authentication_using_my_model) to get it work. But everytime I enterd the (correct) login credentials the app redirects me to the root url instead the admin dashboard.

After a little search, i found this [code](https://github.com/camaleon-cms/devise-authentication/blob/master/app/controllers/application_controller.rb) on Github and added it to my app. This results in a redirect loop after I entered the credentials. The serverlog shows the redirect loop is between the two url's `/admin` & `/administrators/sign_in`:
```
Started GET "/admin" for 172.28.0.1 at 2017-09-30 14:38:24 +0000
Cannot render console from 172.28.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by CamaleonCms::AdminController#dashboard as HTML
CamaleonCms::Site Load (0.5ms)  SELECT  "ccmsterm_taxonomy".* FROM "ccmsterm_taxonomy" WHERE "ccmsterm_taxonomy"."taxonomy" = $1 ORDER BY "ccmsterm_taxonomy"."term_group" DESC LIMIT $2  [["taxonomy", "site"], ["LIMIT", 1]]
CamaleonCms::Meta Load (0.4ms)  SELECT  "ccmsmetas".* FROM "ccmsmetas" WHERE "ccmsmetas"."objectid" = $1 AND "ccmsmetas"."object_class" = $2 AND "ccmsmetas"."key" = $3 ORDER BY "ccmsmetas"."id" ASC LIMIT $4  [["objectid", 1], ["object_class", "Site"], ["key", "_default"], ["LIMIT", 1]]
Camaleon CMS - Hook "app_before_load" executed from dependency front_cache
Camaleon CMS - Hook "app_before_load" executed from dependency cama_contact_form
CAMA_ADMIN_LOGIN_PATH => /administrators/sign_in
Redirected to http://localhost:3000/administrators/sign_in
Filter chain halted as :cama_authenticate rendered or redirected
Completed 302 Found in 7ms (ActiveRecord: 0.9ms)

Started GET "/administrators/sign_in" for 172.28.0.1 at 2017-09-30 14:38:24 +0000
Cannot render console from 172.28.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::SessionsController#new as HTML
Administrator Load (0.5ms)  SELECT  "administrators".* FROM "administrators" WHERE "administrators"."id" = $1 ORDER BY "administrators"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/admin
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 3ms (ActiveRecord: 0.5ms)
```

After digging a bit deeper I figured out, that `cama_current_user` returns `nil` . So I suppose that Camaleon does not recognize the logged in administrator (?).

3 hours later I have no further ideas how to debug or track down this error. All I want is to enter the admin panel with my existing model.

Hopefully someone of you have some ideas and can help me!

**Comment by owen2345** [comment]
@Psych0D can you create a repo with the problem?

**Comment by Psych0D** [comment]
I try to provide it this week ok? I'm very busy right now. 

Are you familiar with docker? Because devise using a LDAP-Server for authentication in my scenario, and providing a docker container is much more easier as writing a whole installation instruction ;)

**Comment by owen2345** [comment]
ok!
