### ISSUE TITLE
Ecommerce plugin

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#70]
Hi!

When the project was changed to gem the ecommerce plugin was erased.
Last plugin update: https://github.com/owen2345/camaleon-cms/commit/99b04f78908db4c2337fd98666d633d605c83646

Are you going to remove this plugin?

I'm thinking to restore the plugin code. 
Any ideas?
Thanks!

**Comment by owen2345** [comment]
Hi Raul,
Plugins and themes were moved to:
http://camaleon.tuzitio.com/store/plugins
http://camaleon.tuzitio.com/store/themes
