### ISSUE TITLE
Using the existing app mainlayout?

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#701]
Suppose that I need to use my existing app's layout:

    app/views/layouts/application.html.haml

instead of the index in the theme, how would I do so? would you please provide the right hook settings in`system.json`  ? as this is common need for pre-existing apps.

**Comment by owen2345** [comment]
I added this doc:
http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/how-to.html

**Comment by hopewise** [comment]
thanks @owen2345 I will check that settings and respond feedback back to you

**Comment by hopewise** [comment]
I've tried it, here is the result I got:
while it should be something like that:
![screen shot 2017-10-10 at 7 07 59 am](https://user-images.githubusercontent.com/1061157/31368986-d968215e-ad89-11e7-9a87-4fd17e4ba7d9.png)

**Comment by owen2345** [comment]
I think it is almost ok. Please review your page template and your css.

**Comment by hopewise** [comment]
I've noticed that the content is not injected into the yield of my main template, if I try to visit a page that is not there, it would say "OOOPS, THE PAGE YOU ARE LOOKING FOR DOES NOT EXIST" which is fine, however, it will render the text of OOOPS behind my template, but not into the yield, please see the attachment:

![screen shot 2017-10-11 at 6 37 31 am](https://user-images.githubusercontent.com/1061157/31421283-33938838-ae4f-11e7-902f-06012b29aa3f.png)
