### ISSUE TITLE
NoMethodError in CamaleonCms::Admin::InstallersController#save

### ISSUE THREAD

**Issue by kiwinesian** [owen2345/camaleon-cms#702]
Hello,

I'm really new to ruby and I thought I'm giving this a go - moving away from Wordpress.
I've got all the requirements installed, running postgres, and local

I managed to get to the setup page, but then after clicking save, I got the following error page.

Any idea what might cause the issue?
I used the installation as per the instruction on GitHub.

<img width="1280" alt="screen shot 2017-10-11 at 11 08 12 am" src="https://user-images.githubusercontent.com/12476195/31458872-2fb3c260-ae76-11e7-8b53-76e725ac633f.png">

**Comment by owen2345** [comment]
This is a problem for Rails 5, please review the installation steps for rails 5:
https://github.com/owen2345/camaleon-cms#installation
# gem 'draper', '~> 3' # only for Rails 5

**Comment by stjokro** [comment]
aaahhh.. got it! 
My apologies for missing that particular commented line.

Spent almost 2 days trying this out actually, so I'm really thankful for your help! :)

Just finished setting up. Logged in into the admin page and got "invalid route" instead of the " Welcome to the admin panel of your site."
Re-logged in and finally got the expected welcome message.
Not sure if this is a bug or something?
PS: I didn't use the gem github - maybe its fixed on the github branch already?

**Comment by owen2345** [comment]
mmm it is strange, if you can reproduce again pls let me know to fix it!
Enjoy Camaleon CMS.

**Comment by stjokro** [comment]
I just tried to reproduce it - and I couldn't. :\
hmmm.. i will let you know if it happens again - probably will do quite a few more runs with different DB. :)
Thanks so much for your help! really appreciate it!
and looking fairly good in the Ruby world! :)

**Comment by stjokro** [comment]
Hello I'm back,

a little different issue I have when I run it under windows - couldn't get into the admin install page.
I used Rails 5 still with postgresql database.
I promised I have the gem 'draper' this time around.

Any idea what might cause the issue?


![failed](https://user-images.githubusercontent.com/12476195/31518992-c3832e74-af55-11e7-8860-b0d136ee254b.png)

**Comment by owen2345** [comment]
Your problem is related to "JavaScript runtime"
try adding this:
gem 'therubyracer'

**Comment by stjokro** [comment]
Hi Owen,

Thanks for the fast response!
I see that you have commented out the gem 'therubyrace'
I un-commented this line, do bundle install, and the rails s
unfortunately still resolved to the same issue.

Works fine under Mac though.. :S

**Comment by stjokro** [comment]
aaahhh I managed to get this to work by adding the following line to the Gemfile
`gem 'coffee-script-source', '1.8.0'`
and it **has** to be 1.8.0
I tried 1.9.0 and the latest 1.12.0 - both wouldn't work and resulted in the same error. 

This works on my Windows 10 x64; but still a bit of a struggle to get it to run on Windows 7 x86.
Will give an update if I find anything else. :)

**Comment by owen2345** [comment]
thanks for keeping me informed.
