### ISSUE TITLE
Can't see changes when assigning field group to User

### ISSUE THREAD

**Issue by vikagalkina** [owen2345/camaleon-cms#704]
Hello Owen! Have same issue as this https://github.com/owen2345/camaleon-cms/issues/477
Using Rails 5.1.4, camaleon cms version 2.4.4.5.
Please can you help with this?
![image](https://user-images.githubusercontent.com/8970482/31651280-b3b83eae-b323-11e7-88ec-ba466af2318f.png)
![image](https://user-images.githubusercontent.com/8970482/31651330-f3252bb0-b323-11e7-9d7a-c507a69c6f70.png)

And this is generated params when creating custom field:
`Started POST "/admin/settings/custom_fields" for 127.0.0.1 at 2017-10-17 10:17:57 +0300
Processing by CamaleonCms::Admin::Settings::CustomFieldsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"9Wdf8vdbWsyqNrOf0nmEllW4uqNee6bPqQ+F+9yOTCm3UCTEM8wHGNQUHvFoLWBr3+Hm/XzPvo8jZ1feXaAdhw==", "custom_field_group"=>{"name"=>"team", "is_repeat"=>"0", "description"=>"", "assign_group"=>"User,1", "caption"=>"Others Users"}, "fields"=>{"_1508224667_7054"=>{"id"=>"", "name"=>"team", "slug"=>"team", "description"=>""}}, "field_options"=>{"_1508224667_7054"=>{"field_key"=>"text_box", "label_eval"=>"", "panel_hidden"=>"", "default_value"=>"", "multiple"=>"0", "required"=>"0", "translate"=>"0"}}}`

**Comment by owen2345** [comment]
@vikagalkina right now I tested and it is working well:
- CMS: 2.4.4.5
- Rails: 5.1.4
- Ruby: ruby 2.3.0p0
- OS: Mac os
<img width="1180" alt="screen shot 2017-10-17 at 5 49 10 am" src="https://user-images.githubusercontent.com/1148415/31658535-44b5fdda-b2ff-11e7-8372-8d90ba943d78.png">
<img width="1203" alt="screen shot 2017-10-17 at 5 48 56 am" src="https://user-images.githubusercontent.com/1148415/31658536-44d47666-b2ff-11e7-84af-713a82a99d8e.png">
Did you see any error in console? or create a repo with the error then I can analyze it for the error.
Regards!

**Comment by vikagalkina** [comment]
I think i find the problem. I use my model CustomUser with Devise authentication as camaleon user. When custom field created it save this data with **object_class=User**
`SQL (0.5ms)  INSERT INTO "cama_custom_fields" ("object_class", "name", "slug", "objectid", "parent_id", "description") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["object_class", "User"], ["name", "mmm"], ["slug", "_group-team"], ["objectid", 1], ["parent_id", 1], ["description", ""]]
`
but when rendered form for new user it makes query for **object_class=CustomUser** 
`CamaleonCms::CustomFieldGroup Load (0.6ms)  SELECT "cama_custom_fields".* FROM "cama_custom_fields" WHERE ("cama_custom_fields"."object_class" != $1) AND "cama_custom_fields"."parent_id" = $2 AND "cama_custom_fields"."object_class" = $3 ORDER BY cama_custom_fields.field_order ASC  [["object_class", "_fields"], ["parent_id", 1], ["object_class", "CustomUser"]]
`

**Comment by owen2345** [comment]
You are right! I will review the next days, if you can fix it, pls send a PR with the fix.

**Comment by vikagalkina** [comment]
@owen2345 
This fix works for me

**Comment by owen2345** [comment]
yes, that is great
