### ISSUE TITLE
Disable create new sites?

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#708]
How would I prevent creating new sites when visiting the `admin_path_name`?

**Comment by owen2345** [comment]
Please overwrite this method "manage_sites?" on site model to return false.
Here a sample how to overwrite/extend a model.
http://camaleon.tuzitio.com/documentation/category/139779-faqs/how-to-extend-a-post-model.html

**Comment by hopewise** [comment]
thanks
