### ISSUE TITLE
Serve camaleon assets from cloudfront?

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#709]
I need to let Camaleon load its assets (ex: :fonts ) from a specific URL ( cloudfront distribution ) as I need to store camaleon assets into an S3 bucket that has `Access-Control-Allow-Origin`

Is there a way to configure Camaleon to load its assets from custom URL?

**Comment by owen2345** [comment]
Please review this:
https://github.com/owen2345/camaleon-cms/issues/280
