### ISSUE TITLE
How do I get the featured image URL?

### ISSUE THREAD

**Issue by rfestag** [owen2345/camaleon-cms#712]
I'm writing a custom template, and I cannot figure out how to get the Featured Image URL. On a more general note, it isn't clear when we can expect a value to be available directly from the decorator, from options, as a field, or a a meta. Is there a good way to discover what all is available on a given post?

**Comment by rfestag** [comment]
It turns out the property is "the_thumb_url". I'm leaving this open because it would be nice to know the answer to the second half of the question:  Is there a good way to discover what all is available on a given post?

**Comment by truthSeekr** [comment]
I follow your posts, I found also `the_thumb_url` but it seems that it only points me to the oryginal file.
