### ISSUE TITLE
Media gallery uses different path than actual path

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#714]
For images that are uploaded into bucket directly are not shown in the media dialog, however they are successfully listed,
I got this error for each image access:

    Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)

its because the path of image is changed when viewed in the media gallery:

the actual path:
https://cms.dcaclab.com/transformer-showcase-2.jpg
the media gallery used path (which is wrong ) :
https://cms.dcaclab.com/thumb/transformer-showcase-2-jpg.jpg

this issue for images that are uploaded into bucket directly (without Camaleon upload file)

**Comment by owen2345** [comment]
file thumb/... is generated automatically for all images uploaded by camaleon cms media manager, then it should exist.
