### ISSUE TITLE
Default user_model?

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#715]
I have not defined `user_model` in the `system.json`, and I have created a website, and changed the admin password..

What is the default `user_model` ? I am already using `User` model that is associated with devise for my existing project, would it be easy to let my created site use my project users and authenticate via devise? or do I have to start site creation all over from beginning?

**Comment by owen2345** [comment]
User_model is used for authentication also used for current_user in camaleon dashboard.
http://camaleon.tuzitio.com/documentation/category/139779-faqs/custom-login.html
By this way you can maintain your current user information and add required attributes of camaleon_cms  user model.
