### ISSUE TITLE
No such file or directory @ dir_initialize

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#720]
I've deployed my app to amazon elastic beanstalk env, however, if I try to visit the blog, I get this error:

     No such file or directory @ dir_initialize - /var/app/current/tmp/cache/

However, it work fine locally, any idea?

**Comment by owen2345** [comment]
Hi @hopewise is this the full error message?
I think the problem is with cache.

**Comment by hopewise** [comment]
yes, this is the full error message, I've fixed it by adding the directory manually at the tmp folder and deploy again to AWS, it worked! it seems that the app has no permission to create a directory at linux server of elastic beanstalk?

Any way, the solution was easy to do, thanks.
