### ISSUE TITLE
Media& content permissions?

### ISSUE THREAD

**Issue by hopewise** [owen2345/camaleon-cms#723]
If I need to hire someone to add content, how would I address the following concerns:

1. Deleting/ Editing previous content.
2. Deleting existing media images.

What's the advice to overcome those concerns?

**Comment by hopewise** [comment]
I've noticed that in the permission, there is only checkbox me media, but, how to prevent deleting media while allow adding media?

**Comment by hopewise** [comment]
Any suggestion here?

**Comment by owen2345** [comment]
@hopewise for now it is not possible to do it, I will add for the next versions.
