### ISSUE TITLE
Thumbnail is original image...

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#726]
After selecting a "Featured Image" on any post, the image shown on the cms is not the thumbnail, it's the original image...I would suspect this wouldn't be the normal behaviour since a user can upload an image of 30MB and that would be very odd to show on the page every time the user is editing it.

**Comment by tostasqb** [comment]
Example image shown here:
https://ibb.co/dzr9Sb

**Comment by truthSeekr** [comment]
Hey tostasqb ? Its already my observation, what is the answer to it ?

**Comment by tostasqb** [comment]
Hey. Left this here for a "not forget" list. Let me see if this has an easy fix. Stand by

**Comment by truthSeekr** [comment]
Hey, thanks for answer. I replied to your another question. 
I found that helper is just bad written, the thumbnail actually is created

**Comment by truthSeekr** [comment]
Its so hard to use it the way I want. I wanted to make 2 versions of the picture.
One thumbnail based on oryginal, and the BIG CROPPED VERSION but it actually makes thumb based on this cropped version...

**Comment by truthSeekr** [comment]
> Hey. Left this here for a "not forget" list. Let me see if this has an easy fix. Stand by

Any news ?:)

**Comment by tostasqb** [comment]
This thing could have a deep refactor. Explanation:
Every image has 2 initial versions, Original and Thumb. Saving a post with an image creates a meta record that refers to the Original but with the Thumb path. This means calling `object.get_meta("thumb")` will always returns the Original image...

For low immediate impact I'll try to change only the decorator `the_thumb_url` so it transforms the image url in a thumb.

More on this, the thumbnail is 100x100 which could be a little disappointing to see in the post. I think we should bump a little the thumbnail. I'll make some tests and get back on this.

**Comment by truthSeekr** [comment]
When I added "image" to custom_field with particular version "1920x1000" it also creates thumb for me ( additional unnecesery ). Like you said "2 initial version for every file", but sometimes we don't need thumbnail.

I think maybe we could just send by `the_thumb_url` an parameter with our version that we need. It only needs to append it to the name of returning image like
`post.the_thumb_url("1920x100")`.

**Comment by blaszczakphoto** [comment]
For getting specific version of thumb(image):
```
CamaleonCms::Post.find(44).get_meta(:thumb).cama_parse_image_version("800x")
```

For getting thumb:
```
CamaleonCms::Post.find(44).get_meta(:thumb).cama_parse_image_version
```
