### ISSUE TITLE
We're sorry, but something went wrong. If you are the application owner check the logs for more information.

### ISSUE THREAD

**Issue by nandangsopyan** [owen2345/camaleon-cms#728]
Hello,

I've fresh install camaleon cms, but after 'rails server -e production' showing error like this on browser : 

===========
We're sorry, but something went wrong. 
If you are the application owner check the logs for more information.
=======================

on console error like this : 

========
E, [2017-11-10T06:35:56.789740 #441] ERROR -- : [12095d91-f9b7-4f9d-8428-6ef65462db36] Camaleon CMS - Please define your current site: $current_site = CamaleonCms::Site.first.decorate or map your domains: http://camaleon.tuzitio.com/documentation/category/139779-examples/how.html
=======

This error only appear on Production mode, but on Development mode camaleon running well.

Please help how to resolve. 

Thank you very much.

**Comment by rfestag** [comment]
I ran into the same issue recently. I ended up basically copying my development database over. You have a few simple options:

1) If you are continuning to use sqlite, you can copy your db/development.sqlite3 file to db/production.sqlite3, and it will probably work (or, in your config/database.yml, point your production environment to your db/development.sqlite3 file)
2) If you are moving to a more production database (MySQL or Postgres), you'll need to manually dump/import from your development database (if it is also MySQL or Postgres), or find a way to export your sqlite database into a format that can be loaded into your target database. 

There may be an easier way to do this, but that's what I ended up doing. I swapped my development system over to Postgres, manually configured it, then dumped it and loaded it into my production database.

**Comment by mawarduri** [comment]
I will try it, thank you @rfestag

**Comment by owen2345** [comment]
Problem fixed guys! don't worry.

**Comment by mawarduri** [comment]
Thanks All, SOLVED!
