### ISSUE TITLE
Contact form throws error on submission

### ISSUE THREAD

**Issue by rfestag** [owen2345/camaleon-cms#729]
I added a contact form page to my application. Whenever I submit the form, I get the following error:

```
undefined method `back_url' for #<Plugins::CamaContactForm::FrontController:0x007f82147970a0>

actionpack (5.1.4) lib/action_dispatch/routing/polymorphic_routes.rb:249:in `handle_string_call'
actionpack (5.1.4) lib/action_dispatch/routing/url_for.rb:181:in `full_url_for'
actionpack (5.1.4) lib/action_dispatch/routing/url_for.rb:167:in `url_for'
actionpack (5.1.4) lib/action_controller/metal/redirecting.rb:105:in `_compute_redirect_to_location'
actionpack (5.1.4) lib/action_controller/metal/redirecting.rb:61:in `redirect_to'
actionpack (5.1.4) lib/action_controller/metal/flash.rb:57:in `redirect_to'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:64:in `block in redirect_to'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:63:in `redirect_to'
turbolinks (5.0.1) lib/turbolinks/redirection.rb:12:in `redirect_to'
cama_contact_form (0.0.24) app/controllers/plugins/cama_contact_form/front_controller.rb:23:in `save_form'
...
```
It looks like this happens after the e-mail is sent, because I'm seeing both the confirmation and the e-mail sent to my target account. 
On a related note, it would be nice if, in the configuration of the contact form, we could set the "from" address, rather than using the site default. This way different contact forms could have an appropriate "reply to".

**Comment by rfestag** [comment]
Looking more closely, the offending line appears to be [this](https://github.com/owen2345/cama_contact_form/blob/5a57e58d1a2ba0784d126043f30ec1688ffab6ad/app/controllers/plugins/cama_contact_form/front_controller.rb#L23)

I am using Turbolinks, so perhaps the `:back` URL doesn't work properly? Any thoughts on how to work around this?

**Comment by rfestag** [comment]
I found a resolution (using redirect_back instead of redirect_to when in Rails 5), and submitted a pull request to cama_contact_form: https://github.com/owen2345/cama_contact_form/pull/16.

**Comment by owen2345** [comment]
Released a new version with the fix!
