### ISSUE TITLE
the path to the media file breaks when the frontend and backend localizations do not match

### ISSUE THREAD

**Issue by superchell** [owen2345/camaleon-cms#733]
When I install English localization on the frontend by default and Russian localization (as an example) for the backend, the URL of the media file looks like "https://myspace.com/en/path_to_media". The same problem is present on other localizations.

**Comment by owen2345** [comment]
@superchell can you please share a screenshot?

**Comment by superchell** [comment]
@owen2345 l[anguages settings page](https://i.imgur.com/6zNvwZJ.png)  and [media page](https://i.imgur.com/RonK6Qy.png). Pictures URL  are broken and contains "en" - abbreviation of English localization

**Comment by owen2345** [comment]
I released a new version with the fix, please test it.

**Comment by superchell** [comment]
Everything works, thanks!
