### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#74]
Any plans on adding a test suite?

**Comment by benjaminwood** [comment]
:+1:

**Comment by owen2345** [comment]
Not yet, the next month I will do it.

**Comment by cmckni3** [comment]
This really needs to happen.

Things are broken on pretty much every released version.

**Comment by raulanatol** [comment]
+1 also we could use https://travis-ci.org/.

**Comment by owen2345** [comment]
I am sorry friends, I am too busy these days January until March, because I am solving personal problems.
If anyone can help with this, it could be good!
