### ISSUE TITLE
ActionController::InvalidCrossOriginRequest: Security warning

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#742]
I'm experiencing an issue similar to [this one](https://github.com/SCPR/SCPRv4/issues/267). That link covers all the details, but basically I get this error whenever a crawler tries to access any js file that doesn't exist on the server, instead of a 404. All these requests are being routed to `camaleon_cms/frontend#post` according to my error logger. Note that even though that link refers to the response code as 500, it is actually 422.

Their fix is [here](https://github.com/SCPR/outpost/commit/925b5a833c7d140f1eac4360aa2e930c568d2aee).

This began occurring when I stopped using a 404 redirect in my site settings and created a custom app/apps/themes/my_theme/views/camaleon_cms/404.html.

Ruby 2.4.2
Rails 5.1.4
Camaleon git version 2b64adee3d520e74905459f1d09b9e688a6e2ffd

**Comment by brian-kephart** [comment]
Correction: I found a couple of instances of this error before I changed my 404 page.

**Comment by owen2345** [comment]
The fix is correct, can you please make a pull request with the fix?

**Comment by brian-kephart** [comment]
I'm not having any luck. I'm unclear as to how to implement this in Camaleon, and using that code with minimal changes affects Camaleon's own error handling.
