### ISSUE TITLE
Bootstrap map missing

### ISSUE THREAD

**Issue by kobeumut** [owen2345/camaleon-cms#747]
Hi, 
i get an error on site and in admin panel, tinymce sometimes is freezing.
![ekran resmi 2018-01-05 08 52 26](https://user-images.githubusercontent.com/5182289/34597183-3efd4b74-f1f6-11e7-9a3c-d3aaa6e95ae1.png)

**Comment by WMPayne** [comment]
Could you post the main.css (or main.scss) file from your theme? Often, this is a result of not correctly using the asset pipeline in a production environment.

One potential workaround, and the one that I use, is to use the bootstrap-sass gem. In your gemfile: 
```ruby
gem 'bootstrap-sass', '~> 3.3.7'
```

Then, in main.scss
```sass
@import "font-awesome";
@import "bootstrap-sprockets";
@import "bootstrap";
@import "theme";
```

This strategy could also be used for Bootstrap 4, if you have the need for it.

**Comment by owen2345** [comment]
Hi @WMPayne 
This is the full code of the theme:
https://github.com/owen2345/camaleon-cms/tree/master/app/apps/themes/camaleon_first

**Comment by WMPayne** [comment]
Thanks for that. Totally forgot to check that he was using one of the included themes... I assumed he was using a custom one and didn't check the URL. My bad.
