### ISSUE TITLE
Post url not being created by slug

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#748]
Steps to replicate:

1. Create a content type, on Content Groups, with title Slideshows and slug `slideshow`. 
2. Set that content type route format to `post_of_posttype`
3. Create a post with `whatever` title and the url you will see is going to be something like `http://localhost:3009/slideshows/whatever`instead of `http://localhost:3009/slideshow/whatever`

The url that is being created is a slugification of the post type `title` instead of using the `slug` itself.

**Comment by rfestag** [comment]
I don't see a Contents Route Format of post_of_posttype. Where are you seeing that? The only ones I see imply that they should be using the title (such as /:post_type_title/:slug).
