### ISSUE TITLE
AWS Media doesn't scale

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#757]
Using AWS with a large number of files is unusable. Clear cache breaks as well as delete, and whole experience of going into folders, upload, create folder is very slow.

I've taken a look on the code and the main problem seems to rely on the `browser_files` method that stores a hash of all files in the S3 bucket on a single meta row...

I'm happy to help on refactoring this part but surely appreciate some help as well.

**Comment by owen2345** [comment]
Hi @tostasqb I was thinking in the same problem.
My idea was to move it in a database table like "cama_media".
Unfortunately for now I am still busy with a project.
Regards!

**Comment by tostasqb** [comment]
That's great to know. Also think that using a table would be the way to go. I'll be making some tests and be in touch.

**Comment by owen2345** [comment]
Finally it was moved to DB structure! Check vs 2.4.5.7.
