### ISSUE TITLE
Sprockets::FileNotFound in CamaleonCms::AdminController#dashboard

### ISSUE THREAD

**Issue by nasim31** [owen2345/camaleon-cms#763]
[Gemfile.txt](https://github.com/owen2345/camaleon-cms/files/1667631/Gemfile.txt)
Hi Owen,
I'm creating a new theme by following your video "Camaleon- Create Theme part 1"
## Console Error:
_Sprockets::FileNotFound (couldn't find file 'font-awesome.min.css' with type 'text/css'
Checked in these paths:_

I have attached my Gemfile for my application details.
Do you have any updated theme creation video with voice instruction that works for rails5 and bootstrap3.x... ??

Or do you have any written step by step documentation for theme creation ?

Thanks.

**Comment by owen2345** [comment]
Hi @nasim31 did you fix this problem?

**Comment by nasim31** [comment]
yes
