### ISSUE TITLE
Page not found not giving 404 status code

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#767]
The page not found is giving a 200 status code instead of a 404

**Comment by brian-kephart** [comment]
Are you setting the 404 page in your site settings? This happened to me as well when I set a 404 page in my site settings. To work around it I added `app/apps/themes/my_theme/views/camaleon_cms/404.html.erb` and disabled the redirect in site settings.

Basically, the default 404 behavior is correct, but selecting a 404 page in your site settings causes the CMS to treat it as a redirect. [See here](https://github.com/owen2345/camaleon-cms/blob/5876cb69e6282e5af73c0714f5911d7ee72aedb7/app/controllers/camaleon_cms/frontend_controller.rb#L206).

**Comment by tostasqb** [comment]
Thanks for the workaround @brian-kephart. Nice to know.

Still, being constructive, I don't think that setting a page not found on site settings (that I did) should change the status of the page. That is just the definition for witch page to use as "page not found"...should always give the correct status code.

Haven't tested any code solution here but I think one of two scenarios would be appropriate:

1. Change the line to add a status
`redirect_to page_404.the_url, status: :not_found`
2. Instead of redirecting, because it previously sends a 3XX code, just `render` the setting page if set by the user or the 404. Any of the two with the status `:not_found`

Setting the correct status code also avoids SEO and crawling problems from Google that currently catches "Soft 404" issues.
