### ISSUE TITLE
Cant create theme without sudo

### ISSUE THREAD

**Issue by DarkHostDH** [owen2345/camaleon-cms#771]
I tried to create new theme
```
$ rails g camaleon_cms:theme nwtheme
Running via Spring preloader in process 14726
/usr/lib/ruby/2.3.0/fileutils.rb:1366:in `mkdir': Permission denied @ dir_s_mkdir - /var/lib/gems/2.3.0/gems/camaleon_cms-2.4.5.3/lib/generators/camaleon_cms/theme_template/app_nwtheme (Errno::EACCES)
```
Should I have sudo permissions for this?

**Comment by owen2345** [comment]
You need permission to write in your current project because this command will create another folder + theme files

**Comment by truthSeekr** [comment]
I have same issue, 
i gave chmod hmod -R g+rwx Project
permission denied @ dir_s_mkdir - /home/radoslaw/.rvm/gems/ruby-2.5.0/gems/camaleon_cms-2.4.5.8/lib/generators/camaleon_cms/theme_template/app_my_theme (Errno::EACCES)

**Comment by owen2345** [comment]
Hallo!
Added the fix, please try using github version until delivery the new version.
Cheers!
