### ISSUE TITLE
Duplicate pages of posts

### ISSUE THREAD

**Issue by superchell** [owen2345/camaleon-cms#776]
Pages of posts have duplicates. For an example [http://camaleon.tuzitio.com/documentation/category/139779-faqs/how-to-add-custom-routes-for-contents.html](http://camaleon.tuzitio.com/documentation/category/139779-faqs/how-to-add-custom-routes-for-contents.html) and [http://camaleon.tuzitio.com/bla/bla/bla/how-to-add-custom-routes-for-contents.html](http://camaleon.tuzitio.com/bla/bla/bla/how-to-add-custom-routes-for-contents.html) will give the same content. But the path "blah/blah/bla" does not exist on the site. This is very critical for the SEO.

**Comment by josefsj3m** [comment]
There is the same problem with locale. If a page or post has more than one language it could be rendered in the wrong language, for instance, localhost:3000/pt-br/bem-vindo renders the portuguese,  localhost:3000/welcome renders the english page, that is ok. But, localhost:3000/pt-br/welcome also renders the page in portuguese which is wrong.

Looking trought the code I saw that the frontend_controller#post is not considering neither the locale nor the post_type_title, both are present in the route format.

Regards,

**Comment by brian-kephart** [comment]
I fixed the duplicates problem (SEO-wise) by using canonical tags in my layout. Something like this:
```erb
<link rel="canonical" href="<%= @post.the_url %>">
```

You could also include a redirect in a method called by the `on_render_post` hook.
```ruby
redirect_to @post.the_url unless request.url == @post.the_url
```

I saw in #777 that this probably can't be incorporated into the CMS, but it could be incorporated into an optional plugin. Maybe it could be added to the SEO plugin. There could be a checkbox in the post editor that says "Redirect to canonical URL".

I'm not sure what to do about the locale problem, though. I haven't used that feature.
