### ISSUE TITLE
Deploy on AWS ElasticBeanstalk

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#78]
Hi!

I'm working to deploy camaleon-cms on amazon Elastic Beanstalk.
I'm doing a little guide to do it. Exists any type of wiki, or file to include this guide?

**Comment by owen2345** [comment]
You can publish your plugin in camaleon plugin store:
http://camaleon.tuzitio.com/store/plugins
Note: You need to create an account to upload the plugin.

**Comment by raulanatol** [comment]
Sorry, but it's not a plugin. 
I was referring to a "how to deploy on AWS" tutorial.
It's only a checklist to deploy on AWS services.

**Comment by owen2345** [comment]
please send me the tutorial by email and I will publish in the site.

**Comment by raulanatol** [comment]
Ok!
