### ISSUE TITLE
wildcard ssl using nginx redirects page to localhost instead of main sub-domained site

### ISSUE THREAD

**Issue by serialbandicoot** [owen2345/camaleon-cms#780]
Hi,

I'm not sure if this issue is todo with the way I have my wildcard ssl set up with nginx, however. The permalink for the page is using the request_uri.

![screen shot 2018-02-19 at 17 33 32](https://user-images.githubusercontent.com/742312/36390550-5e73f714-159b-11e8-8580-288819f6876c.png)

As you can see the permalink it using localhost:4109, which is the underlying location, however in my nginx config I have. This is fine as the url sub_domain.mysite.com the redirects traffic to localhost:4109.

```
location / {
    proxy_pass http://localhost:4109;
  }
```

Is there anyway to get chameleon to use /my-post instead of trying to route the whole url?

**Comment by owen2345** [comment]
I think it can be changed from Rails configuration, because the current code to get the that uri is:
cama_post_url(locale: :en, slug: 'test', ...)
check here:
https://stackoverflow.com/questions/2660172/how-do-i-set-default-host-for-url-helpers-in-rails

**Comment by serialbandicoot** [comment]
Thanks for the support quick reply 👍 

![screen shot 2018-02-19 at 18 28 16](https://user-images.githubusercontent.com/742312/36392616-0b715b0c-15a4-11e8-9c48-f5c97b61066f.png)


Just one small problem, it retains the port 4109 - I've tried a few combinations passing in port of 80 or 443, however it seems to cause a redirect loop. Do you know if there is a way to exclude port?

awesome lib btw!.....

**Comment by owen2345** [comment]
there is a setting for port along with domain, sample: {domain: 'dd.com', port: '80'}

**Comment by serialbandicoot** [comment]
Well I'm quite confused it would seem that by providing port 80 / 443 or nil it end up in a redirect loop and is unable to login.

Any ideas what could be causing the re-direct loop?

**Comment by serialbandicoot** [comment]
So I've managed to do a trace and for some weird reason it hits the url fine. This is with port set to nil and previously I managed to create a page.

<img width="353" alt="screen shot 2018-02-19 at 19 40 38" src="https://user-images.githubusercontent.com/742312/36394625-14610196-15ad-11e8-9f21-1e446375879c.png">

However it then 302/301 until it resides on the root page set up for the cms.

**Comment by serialbandicoot** [comment]
I think I've figured out the issue. My nginx config wasn't setting the header and I quite possible had some caching going on with browser whilst trying out variations.

Anyway this was the server config.

```
server {
  server_name address.com;
  proxy_set_header Host $host;
  listen 443 ssl;
  location / {
    proxy_pass http://localhost:4109;
  }
```

And the this is the code in the _ApplicationController_

```
class << self
    def default_url_options
      Rails.application.config.action_controller.default_url_options
    end
  end

  def default_url_options
    if Rails.env.production?
      {:host => "address.com"}
    elsif Rails.env.staging?
      {:host => "staging.address.com", port: nil}
    else
      {}
    end
  end

}
```

Setting the port to nil, seemed to be a way of removing it from the permalink.
