### ISSUE TITLE
Intro Popups in the Admin Screen

### ISSUE THREAD

**Issue by serialbandicoot** [owen2345/camaleon-cms#781]
Hi @owen2345.

It seems that after having a few issues with wildcard ssl and nginx, I'm potentially getting the same issues as described here: https://github.com/owen2345/camaleon-cms/issues/234

Is there anyway of manually setting the popups to cease?

Thanks....

**Comment by WMPayne** [comment]
Try to force SSL in the production.rb configuration file. What often happens is that nginx will route to it without SSL, and then serve the static assets over http. When the ajax calls are made like this, they don't register that the popups should not continue.
