### ISSUE TITLE
Updating custom fields does not update parent

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#785]
I have a theme with custom fields added via the `:add_field_group` method. Similar to this:

```ruby
# app/apps/themes/my_theme/main_helper.rb
def my_theme_on_install_theme(theme)
  unless theme.get_field_groups.where(slug: "fields").any?
    group = theme.add_field_group({name: "Main Settings", slug: "fields", description: ""})
    group.add_field({"name"=>"Background color", "slug"=>"bg_color"},{field_key: "colorpicker"})
    group.add_field({"name"=>"Links color", "slug"=>"links_color"},{field_key: "colorpicker"})
    group.add_field({"name"=>"Background image", "slug"=>"bg"},{field_key: "image"})
  end
end
```

When I save fields in my theme settings, the `:updated_at` value of the theme does not change. This means that if I cache in my views with `current_theme` as the key, the cache does not bust when I update the theme settings. I can use `current_theme.custom_field_values`, but that adds a database query.

It seems like updating custom field values should change the parent object's `:updated_at` attribute, either by using the `:touch` method or some other callback.

Any thoughts?

**Comment by owen2345** [comment]
Fixed!

**Comment by brian-kephart** [comment]
Thanks, it works well!
