### ISSUE TITLE
Uploading image doesn't auto orient

### ISSUE THREAD

**Issue by airchen233** [owen2345/camaleon-cms#786]
Hi @owen2345 ,
When I upload an image(Width < Height) in the media tab, it came out a result that image rotate for 90 deg.
It seems like `MiniMagick::Image.open(file)` return an image which
`img[:width] = h_original` and `img[:height] = w_original`.
`MiniMagick::Image.open(file).auto_orient` may help.
Could you fix this? Thanks

**Comment by owen2345** [comment]
Hi @airchen233 I added a new hook where you can add the auto orient
Sample:
```
def my_hook_listen(args)
  args[:img]. auto_orient
end
```
NOTE: To test this please use github version.

**Comment by airchen233** [comment]
Hi @owen2345 ,
It seems the new hook lost in the latest commit `a4ce8b6` when conflict happened.
I tested commit `c478a35` but got a wired result.

Here is the image i use to test.
[image](https://power-spot-quest.s3.ap-northeast-1.amazonaws.com/668547105.jpg)

Waiting for your reply.Thanks

**Comment by owen2345** [comment]
Sorry, please try again!

**Comment by airchen233** [comment]
Hi @owen2345 ,
Thanks for your reply!

I tried the latest commit. 
Hook works well, but the result was not what i expected.

I think maybe i need auto_orient at the time MiniMagick open the image:
[https://github.com/minimagick/minimagick/issues/360](https://github.com/minimagick/minimagick/issues/360)

Thanks

**Comment by owen2345** [comment]
Hi @airchen233 
sorry, my example was not correct. Please try this one:
```
def my_hook_listen(args)
  args[:img] = args[:img].auto_orient
end
```
Cheers!

**Comment by airchen233** [comment]
Hi @owen2345 ,
I'm sorry but it didn't work...

**Comment by airchen233** [comment]
Hi @owen2345 ,
auto_orient only work at the time MiniMagick open the image, so I create a pull request to fix it.
Waiting for your reply. Thanks!

**Comment by owen2345** [comment]
@airchen233 Please check the message in the pull request and let me know if it works well for you too.

**Comment by airchen233** [comment]
Hi @owen2345 ,
I used the hooks you mentioned at the pull request, and they works!~
Thanks for your patient replys!
