### ISSUE TITLE
Redirect after subscription

### ISSUE THREAD

**Issue by BlazPerus** [owen2345/camaleon-cms#798]
Hey,

Not an issue but really can't make it work.

How would one go and redirect user after successful subscription after form submit ('cama_subscriber' gem?). 

Thanks!

**Comment by owen2345** [comment]
Hi @BlazPerus 
I added these hooks to customize it:
- cama_subscriber_error_subscription: {errors: error, redirect: cama_root_url, status: stat}
- cama_subscriber_after_subscription: {msg: msg, redirect: cama_root_url, status: stat}
Please try using those hooks.
Cheers!
