### ISSUE TITLE
Better support for migrations inside of plugins

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#80]
Any plans for some better support for migrations inside of plugins?

Basically, how are migrations handled when we add/update/remove fields to a plugin for a new version?

**Comment by owen2345** [comment]
You need to use the hook "on_upgrade", please check here:
http://camaleon.tuzitio.com/hooks.html

**Comment by cmckni3** [comment]
Interesting.

I would really prefer Rails/ActiveRecord to handle the checks though

**Comment by owen2345** [comment]
If you can do it, I would be grateful.

**Comment by cmckni3** [comment]
I can try to do it if I get around to it

**Comment by cmckni3** [comment]
Currently, fighting with migrations with being skipped as well because do a strict comparison of the version number.

I'm going to make a workaround.

**Comment by cmckni3** [comment]
@owen2345 Is there any way for me to update the documentation?

**Comment by owen2345** [comment]
please send me your email to create one accoutn
