### ISSUE TITLE
Plugin isolation

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#81]
I think plugins (really anything with a separate Gemfile) should be isolated so the gems in it don't conflict. For example, adding slim to a plugin and to the main Rails application causes bundler warnings.

**Comment by owen2345** [comment]
I am thinking in a way to manage plugins like a rails gem where the people only will need add the gem like this:
gem "camaleon-ecommerce"

**Comment by cmckni3** [comment]
Yeah, `camaleon-ecommerce` would be a Rails engine. That's how refinery plugins work too.

It's pretty neat how plugins work right now but the lack of isolation is also a disadvantage.

**Comment by owen2345** [comment]
correct, please let me know if you can create a way to manage that disadvantage.

**Comment by cmckni3** [comment]
Ok, I'll think about some possible solutions

**Comment by owen2345** [comment]
I added the support for plugins in gem version!
