### ISSUE TITLE
Support for old Ruby/Rails versions

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#813]
The documentation says Camaleon supports Ruby 1.9 and Rails 4.1, but that's not really the case right now.
- Some of the dependencies in the gemspec require Ruby 2.0, or even 2.2, so the current version of Camaleon can't be installed with Ruby 1.9.
- Running Rubocop reveals multiple cases of syntax in the code that is incompatible with Ruby 1.9.
- Rails 4.1 predates ActiveJob. Running the tests when using Rails 4.1 results in this error:
```bash
NoMethodError:
       undefined method `deliver_later' for #<Mail::Message:0x0000000a224e80>
     # ./app/helpers/camaleon_cms/email_helper.rb:29:in `cama_send_email'
     # ./app/helpers/camaleon_cms/email_helper.rb:17:in `send_email'
     # ./spec/helpers/email_helper_spec.rb:7:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:28:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:27:in `block (2 levels) in <top (required)>'
```

Rails 4.2+ works fine. Ruby 2.2+ works fine.

The versions of Ruby and Rails that aren't currently working with Camaleon have been unmaintained for multiple years now, so I favor dropping them from the documentation for future development. Otherwise, we should manage dependencies so these versions actually work.

**Comment by owen2345** [comment]
Hi @brian-kephart 
I agree with you, we can drop old versions and change ruby/rails minimum versions.
Cheers!

**Comment by brian-kephart** [comment]
Thanks for the fast reply! I’ll submit a PR. What about Ruby 2.2 and Rails 4.2? They are unmaintained as well, but not causing any build problems. Should we keep them or not?

**Comment by owen2345** [comment]
We can keep them, because if we change it we can affect existent projects.
