### ISSUE TITLE
Test fix prevents testing plugins

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#817]
[This line](https://github.com/owen2345/camaleon-cms/blob/master/app/views/layouts/camaleon_cms/admin.html.erb#L19) causes problems when I try to test my plugins. Since I'm running my plugin tests from a different repo, the file path doesn't render correctly and my tests throw an exception.

A comment in the rendered file says it's needed to work around a TinyMCE bug. I tried running the Camaleon test suite with that line commented out and it passed, so maybe the workaround is no longer needed.

If it's still needed, can we just place the necessary content in a conditional block in the view, instead of rendering it from a file?

**Comment by owen2345** [comment]
@brian-kephart you are right, can you please make a pull request with the change?
Regards!
