### ISSUE TITLE
Changing layouts

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#82]
Where exactly would a theme_layout call go for changing a specific post/page layout?

Would it go in `post_<post.id>.html.erb`/`page_<page.id>.html.erb`?

**Comment by owen2345** [comment]
You can customize your templates for pages, post_types, categories.
Sample: create a file "page.html.erb" => this is a template for each post of post_type with slug = "page", if this is not present this will render default template "single.html.erb"

Sample: create a file "page_10.html.erb" => this is a template for  post with id = "10"

Sample: create a file "post_types/page.html.erb" => this is a template for a post_type with slug = "page", if this is not present this will render default template "post_type.html.erb" 

Docs: http://camaleon.tuzitio.com/themes-1.html

If you want to customize the layout, you can do it by hooks, sample:
on_render_category
Check details here: http://camaleon.tuzitio.com/hooks.html

**Comment by cmckni3** [comment]
Is there a place in the UI to pick a template for a page/post?

**Comment by cmckni3** [comment]
Another main concern is that I want the theme to be able control the layout of plugin pages.
