### ISSUE TITLE
Route problem

### ISSUE THREAD

**Issue by ecojob** [owen2345/camaleon-cms#827]
Hello, 

I am trying to implement Camaleon on en existing project (rails 4.2.8). 

I do have in my system.json:
"relative_url_root": "blog-cama"
"admin_path_name": "cama_admin"

I am unable to get to http://localhost:3000/blog-cama
http://localhost:3000/en/reg/blog-cama does also not work.

could be related to my existing route which are in a scope:  
  scope "/:locale/:reg" do

Shall I add : gem 'draper' ? 

Do you have any clue what could be wrong ?  

Thank you and regards

**Comment by owen2345** [comment]
Hi @ecojob 
can you review your rake routes?

**Comment by ecojob** [comment]
This is my home path: 

home_path | GET | /:locale/:reg/home(.:format)

here are the camaleon related path  /:locale/:reg/ 

cama_admin_path GET /blog-cama/cama_admin(.:format) camaleon_cms/admin#dashboard
cama_admin_dashboard_path GET /blog-cama/cama_admin/dashboard(.:format) camaleon_cms/admin#dashboard
cama_admin_ajax_path  GET /blog-cama/cama_admin/ajax(.:format)  camaleon_cms/admin#ajax
cama_admin_search_path  GET /blog-cama/cama_admin/search(.:format)  camaleon_cms/admin#search
cama_admin_login_path GET /blog-cama/cama_admin/login(.:format) camaleon_cms/admin/sessions#login
POST  /blog-cama/cama_admin/login(.:format) camaleon_cms/admin/sessions#login_post
cama_admin_logout_path  GET /blog-cama/cama_admin/logout(.:format)  camaleon_cms/admin/sessions#logout
cama_admin_forgot_path  GET|POST|PATCH  /blog-cama/cama_admin/forgot(.:format)  camaleon_cms/admin/sessions#forgot
cama_admin_confirm_email_path GET|POST|PATH /blog-cama/cama_admin/confirm_email(.:format) camaleon_cms/admin/sessions#confirm_email
cama_admin_register_path  GET|POST|PATCH  /blog-cama/cama_admin/register(.:format)  camaleon_cms/admin/sessions#register
cama_admin_api_path GET|POST  /blog-cama/cama_admin/api/:method(.:format) camaleon_cms/admin#api
cama_admin_post_type_post_trash_path  GET /blog-cama/cama_admin/post_type/:post_type_id/posts/:post_id/trash(.:format)  camaleon_cms/admin/posts#trash
cama_admin_post_type_post_restore_path  GET /blog-cama/cama_admin/post_type/:post_type_id/posts/:post_id/restore(.:format)  camaleon_cms/admin/posts#restore
ajax_cama_admin_post_type_posts_path  GET|POST|PATCH  /blog-cama/cama_admin/post_type/:post_type_id/posts/ajax(.:format)  camaleon_cms/admin/posts#ajax
cama_admin_post_type_posts_path GET /blog-cama/cama_admin/post_type/:post_type_id/posts(.:format) camaleon_cms/admin/posts#index
POST  /blog-cama/cama_admin/post_type/:post_type_id/posts(.:format) camaleon_cms/admin/posts#create
new_cama_admin_post_type_post_path  GET /blog-cama/cama_admin/post_type/:post_type_id/posts/new(.:format) camaleon_cms/admin/posts#new
edit_cama_admin_post_type_post_path GET /blog-cama/cama_admin/post_type/:post_type_id/posts/:id/edit(.:format)  camaleon_cms/admin/posts#edit
cama_admin_post_type_post_path  GET /blog-cama/cama_admin/post_type/:post_type_id/posts/:id(.:format) camaleon_cms/admin/posts#show
PATCH /blog-cama/cama_admin/post_type/:post_type_id/posts/:id(.:format) camaleon_cms/admin/posts#update
PUT /blog-cama/cama_admin/post_type/:post_type_id/posts/:id(.:format) camaleon_cms/admin/posts#update
DELETE  /blog-cama/cama_admin/post_type/:post_type_id/posts/:id(.:format) camaleon_cms/admin/posts#destroy
list_cama_admin_post_type_categories_path GET /blog-cama/cama_admin/post_type/:post_type_id/categories/list(.:format) camaleon_cms/admin/categories#list
cama_admin_post_type_categories_path  GET /blog-cama/cama_admin/post_type/:post_type_id/categories(.:format)  camaleon_cms/admin/categories#index
POST  /blog-cama/cama_admin/post_type/:post_type_id/categories(.:format)  camaleon_cms/admin/categories#create
new_cama_admin_post_type_category_path  GET /blog-cama/cama_admin/post_type/:post_type_id/categories/new(.:format)  camaleon_cms/admin/categories#new
edit_cama_admin_post_type_category_path GET /blog-cama/cama_admin/post_type/:post_type_id/categories/:id/edit(.:format) camaleon_cms/admin/categories#edit
cama_admin_post_type_category_path  GET /blog-cama/cama_admin/post_type/:post_type_id/categories/:id(.:format)  camaleon_cms/admin/categories#show
PATCH /blog-cama/cama_admin/post_type/:post_type_id/categories/:id(.:format)  camaleon_cms/admin/categories#update
PUT /blog-cama/cama_admin/post_type/:post_type_id/categories/:id(.:format)  camaleon_cms/admin/categories#update
DELETE  /blog-cama/cama_admin/post_type/:post_type_id/categories/:id(.:format)  camaleon_cms/admin/categories#destroy
list_cama_admin_post_type_post_tags_path  GET /blog-cama/cama_admin/post_type/:post_type_id/post_tags/list(.:format)  camaleon_cms/admin/post_tags#list
cama_admin_post_type_post_tags_path GET /blog-cama/cama_admin/post_type/:post_type_id/post_tags(.:format) camaleon_cms/admin/post_tags#index
POST  /blog-cama/cama_admin/post_type/:post_type_id/post_tags(.:format) camaleon_cms/admin/post_tags#create
new_cama_admin_post_type_post_tag_path  GET /blog-cama/cama_admin/post_type/:post_type_id/post_tags/new(.:format) camaleon_cms/admin/post_tags#new
edit_cama_admin_post_type_post_tag_path GET /blog-cama/cama_admin/post_type/:post_type_id/post_tags/:id/edit(.:format)  camaleon_cms/admin/post_tags#edit
cama_admin_post_type_post_tag_path  GET /blog-cama/cama_admin/post_type/:post_type_id/post_tags/:id(.:format) camaleon_cms/admin/post_tags#show
PATCH /blog-cama/cama_admin/post_type/:post_type_id/post_tags/:id(.:format) camaleon_cms/admin/post_tags#update
PUT /blog-cama/cama_admin/post_type/:post_type_id/post_tags/:id(.:format) camaleon_cms/admin/post_tags#update
DELETE  /blog-cama/cama_admin/post_type/:post_type_id/post_tags/:id(.:format) camaleon_cms/admin/post_tags#destroy
cama_admin_post_type_drafts_path  GET /blog-cama/cama_admin/post_type/:post_type_id/drafts(.:format)  camaleon_cms/admin/posts/drafts#index
POST  /blog-cama/cama_admin/post_type/:post_type_id/drafts(.:format)  camaleon_cms/admin/posts/drafts#create
new_cama_admin_post_type_draft_path GET /blog-cama/cama_admin/post_type/:post_type_id/drafts/new(.:format)  camaleon_cms/admin/posts/drafts#new
edit_cama_admin_post_type_draft_path  GET /blog-cama/cama_admin/post_type/:post_type_id/drafts/:id/edit(.:format) camaleon_cms/admin/posts/drafts#edit
cama_admin_post_type_draft_path GET /blog-cama/cama_admin/post_type/:post_type_id/drafts/:id(.:format)  camaleon_cms/admin/posts/drafts#show
PATCH /blog-cama/cama_admin/post_type/:post_type_id/drafts/:id(.:format)  camaleon_cms/admin/posts/drafts#update
PUT /blog-cama/cama_admin/post_type/:post_type_id/drafts/:id(.:format)  camaleon_cms/admin/posts/drafts#update
DELETE  /blog-cama/cama_admin/post_type/:post_type_id/drafts/:id(.:format)  camaleon_cms/admin/posts/drafts#destroy
cama_admin_post_type_index_path GET /blog-cama/cama_admin/post_type(.:format) camaleon_cms/admin/post_type#index
POST  /blog-cama/cama_admin/post_type(.:format) camaleon_cms/admin/post_type#create
new_cama_admin_post_type_path GET /blog-cama/cama_admin/post_type/new(.:format) camaleon_cms/admin/post_type#new
edit_cama_admin_post_type_path  GET /blog-cama/cama_admin/post_type/:id/edit(.:format)  camaleon_cms/admin/post_type#edit
cama_admin_post_type_path GET /blog-cama/cama_admin/post_type/:id(.:format) camaleon_cms/admin/post_type#show
PATCH /blog-cama/cama_admin/post_type/:id(.:format) camaleon_cms/admin/post_type#update
PUT /blog-cama/cama_admin/post_type/:id(.:format) camaleon_cms/admin/post_type#update
DELETE  /blog-cama/cama_admin/post_type/:id(.:format) camaleon_cms/admin/post_type#destroy
cama_admin_post_type_taxonomy_posts_path  GET /blog-cama/cama_admin/post_type/:post_type_id/:taxonomy/:taxonomy_id/posts(.:format)  camaleon_cms/admin/posts#index
cama_admin_profile_path GET /blog-cama/cama_admin/profile(.:format) camaleon_cms/admin/users#profile
cama_admin_profile_edit_path  GET|POST|PATCH  /blog-cama/cama_admin/profile/edit(.:format)  camaleon_cms/admin/users#profile_edit
cama_admin_user_updated_ajax_path PATCH /blog-cama/cama_admin/users/:user_id/updated_ajax(.:format) camaleon_cms/admin/users#updated_ajax
impersonate_cama_admin_user_path  GET /blog-cama/cama_admin/users/:id/impersonate(.:format) camaleon_cms/admin/users#impersonate
cama_admin_users_path GET /blog-cama/cama_admin/users(.:format) camaleon_cms/admin/users#index
POST  /blog-cama/cama_admin/users(.:format) camaleon_cms/admin/users#create
new_cama_admin_user_path  GET /blog-cama/cama_admin/users/new(.:format) camaleon_cms/admin/users#new
edit_cama_admin_user_path GET /blog-cama/cama_admin/users/:id/edit(.:format)  camaleon_cms/admin/users#edit
cama_admin_user_path  GET /blog-cama/cama_admin/users/:id(.:format) camaleon_cms/admin/users#show
PATCH /blog-cama/cama_admin/users/:id(.:format) camaleon_cms/admin/users#update
PUT /blog-cama/cama_admin/users/:id(.:format) camaleon_cms/admin/users#update
DELETE  /blog-cama/cama_admin/users/:id(.:format) camaleon_cms/admin/users#destroy
cama_admin_user_roles_path  GET /blog-cama/cama_admin/user_roles(.:format)  camaleon_cms/admin/user_roles#index
POST  /blog-cama/cama_admin/user_roles(.:format)  camaleon_cms/admin/user_roles#create
new_cama_admin_user_role_path GET /blog-cama/cama_admin/user_roles/new(.:format)  camaleon_cms/admin/user_roles#new
edit_cama_admin_user_role_path  GET /blog-cama/cama_admin/user_roles/:id/edit(.:format) camaleon_cms/admin/user_roles#edit
cama_admin_user_role_path GET /blog-cama/cama_admin/user_roles/:id(.:format)  camaleon_cms/admin/user_roles#show
PATCH /blog-cama/cama_admin/user_roles/:id(.:format)  camaleon_cms/admin/user_roles#update
PUT /blog-cama/cama_admin/user_roles/:id(.:format)  camaleon_cms/admin/user_roles#update
DELETE  /blog-cama/cama_admin/user_roles/:id(.:format)  camaleon_cms/admin/user_roles#destroy
cama_admin_settings_post_types_path GET /blog-cama/cama_admin/settings/post_types(.:format) camaleon_cms/admin/settings/post_types#index
POST  /blog-cama/cama_admin/settings/post_types(.:format) camaleon_cms/admin/settings/post_types#create
new_cama_admin_settings_post_type_path  GET /blog-cama/cama_admin/settings/post_types/new(.:format) camaleon_cms/admin/settings/post_types#new
edit_cama_admin_settings_post_type_path GET /blog-cama/cama_admin/settings/post_types/:id/edit(.:format)  camaleon_cms/admin/settings/post_types#edit
cama_admin_settings_post_type_path  GET /blog-cama/cama_admin/settings/post_types/:id(.:format) camaleon_cms/admin/settings/post_types#show
PATCH /blog-cama/cama_admin/settings/post_types/:id(.:format) camaleon_cms/admin/settings/post_types#update
PUT /blog-cama/cama_admin/settings/post_types/:id(.:format) camaleon_cms/admin/settings/post_types#update
DELETE  /blog-cama/cama_admin/settings/post_types/:id(.:format) camaleon_cms/admin/settings/post_types#destroy
get_items_cama_admin_settings_custom_fields_path  POST  /blog-cama/cama_admin/settings/custom_fields/get_items/:key(.:format) camaleon_cms/admin/settings/custom_fields#get_items
reorder_cama_admin_settings_custom_fields_path  POST  /blog-cama/cama_admin/settings/custom_fields/reorder(.:format)  camaleon_cms/admin/settings/custom_fields#reorder
list_cama_admin_settings_custom_fields_path GET /blog-cama/cama_admin/settings/custom_fields/list(.:format) camaleon_cms/admin/settings/custom_fields#list
cama_admin_settings_custom_fields_path  GET /blog-cama/cama_admin/settings/custom_fields(.:format)  camaleon_cms/admin/settings/custom_fields#index
POST  /blog-cama/cama_admin/settings/custom_fields(.:format)  camaleon_cms/admin/settings/custom_fields#create
new_cama_admin_settings_custom_field_path GET /blog-cama/cama_admin/settings/custom_fields/new(.:format)  camaleon_cms/admin/settings/custom_fields#new
edit_cama_admin_settings_custom_field_path  GET /blog-cama/cama_admin/settings/custom_fields/:id/edit(.:format) camaleon_cms/admin/settings/custom_fields#edit
cama_admin_settings_custom_field_path GET /blog-cama/cama_admin/settings/custom_fields/:id(.:format)  camaleon_cms/admin/settings/custom_fields#show
PATCH /blog-cama/cama_admin/settings/custom_fields/:id(.:format)  camaleon_cms/admin/settings/custom_fields#update
PUT /blog-cama/cama_admin/settings/custom_fields/:id(.:format)  camaleon_cms/admin/settings/custom_fields#update
DELETE  /blog-cama/cama_admin/settings/custom_fields/:id(.:format)  camaleon_cms/admin/settings/custom_fields#destroy
cama_admin_settings_site_path GET /blog-cama/cama_admin/settings/site(.:format) camaleon_cms/admin/settings#site
cama_admin_settings_test_email_path GET /blog-cama/cama_admin/settings/test_email(.:format) camaleon_cms/admin/settings#test_email
cama_admin_settings_theme_path  GET /blog-cama/cama_admin/settings/theme(.:format)  camaleon_cms/admin/settings#theme
cama_admin_settings_save_theme_path POST  /blog-cama/cama_admin/settings/save_theme(.:format) camaleon_cms/admin/settings#save_theme
cama_admin_settings_languages_path  GET /blog-cama/cama_admin/settings/languages(.:format)  camaleon_cms/admin/settings#languages
cama_admin_settings_shortcodes_path GET /blog-cama/cama_admin/settings/shortcodes(.:format) camaleon_cms/admin/settings#shortcodes
POST  /blog-cama/cama_admin/settings/languages(.:format)  camaleon_cms/admin/settings#save_languages
cama_admin_settings_site_saved_path PATCH /blog-cama/cama_admin/settings/site_saved(.:format) camaleon_cms/admin/settings#site_saved
cama_admin_settings_sites_path  GET /blog-cama/cama_admin/settings/sites(.:format)  camaleon_cms/admin/settings/sites#index
POST  /blog-cama/cama_admin/settings/sites(.:format)  camaleon_cms/admin/settings/sites#create
new_cama_admin_settings_site_path GET /blog-cama/cama_admin/settings/sites/new(.:format)  camaleon_cms/admin/settings/sites#new
edit_cama_admin_settings_site_path  GET /blog-cama/cama_admin/settings/sites/:id/edit(.:format) camaleon_cms/admin/settings/sites#edit
GET /blog-cama/cama_admin/settings/sites/:id(.:format)  camaleon_cms/admin/settings/sites#show
PATCH /blog-cama/cama_admin/settings/sites/:id(.:format)  camaleon_cms/admin/settings/sites#update
PUT /blog-cama/cama_admin/settings/sites/:id(.:format)  camaleon_cms/admin/settings/sites#update
DELETE  /blog-cama/cama_admin/settings/sites/:id(.:format)  camaleon_cms/admin/settings/sites#destroy
cama_admin_comments_path  GET /blog-cama/cama_admin/comments(.:format)  camaleon_cms/admin/comments#list
cama_admin_post_comment_answer_path GET /blog-cama/cama_admin/posts/:post_id/comments/:comment_id/answer(.:format)  camaleon_cms/admin/comments#answer
cama_admin_post_comment_save_answer_path  POST  /blog-cama/cama_admin/posts/:post_id/comments/:comment_id/save_answer(.:format) camaleon_cms/admin/comments#save_answer
cama_admin_post_comment_toggle_status_path  GET /blog-cama/cama_admin/posts/:post_id/comments/:comment_id/toggle_status(.:format) camaleon_cms/admin/comments#toggle_status
cama_admin_post_comments_path GET /blog-cama/cama_admin/posts/:post_id/comments(.:format) camaleon_cms/admin/comments#index
POST  /blog-cama/cama_admin/posts/:post_id/comments(.:format) camaleon_cms/admin/comments#create
new_cama_admin_post_comment_path  GET /blog-cama/cama_admin/posts/:post_id/comments/new(.:format) camaleon_cms/admin/comments#new
edit_cama_admin_post_comment_path GET /blog-cama/cama_admin/posts/:post_id/comments/:id/edit(.:format)  camaleon_cms/admin/comments#edit
cama_admin_post_comment_path  GET /blog-cama/cama_admin/posts/:post_id/comments/:id(.:format) camaleon_cms/admin/comments#show
PATCH /blog-cama/cama_admin/posts/:post_id/comments/:id(.:format) camaleon_cms/admin/comments#update
PUT /blog-cama/cama_admin/posts/:post_id/comments/:id(.:format) camaleon_cms/admin/comments#update
DELETE  /blog-cama/cama_admin/posts/:post_id/comments/:id(.:format) camaleon_cms/admin/comments#destroy
cama_admin_appearances_widgets_path GET|DELETE  /blog-cama/cama_admin/appearances/widgets(.:format) camaleon_cms/admin/appearances#widgets
cama_admin_appearances_widgets_save_path  POST|PATCH  /blog-cama/cama_admin/appearances/widgets_save(.:format)  camaleon_cms/admin/appearances#widgets_save
cama_admin_appearances_widget_delete_path GET|PATCH /blog-cama/cama_admin/appearances/widget_delete(.:format) camaleon_cms/admin/appearances#widget_delete
cama_admin_appearances_render_form_path GET /blog-cama/cama_admin/appearances/render_form(.:format) camaleon_cms/admin/appearances#render_form
preview_cama_admin_appearances_themes_path  GET /blog-cama/cama_admin/appearances/themes/preview(.:format)  camaleon_cms/admin/appearances/themes#preview
load_data_cama_admin_appearances_themes_path  GET|POST|PATCH  /blog-cama/cama_admin/appearances/themes/load_data(.:format)  camaleon_cms/admin/appearances/themes#load_data
cama_admin_appearances_themes_path  GET /blog-cama/cama_admin/appearances/themes(.:format)  camaleon_cms/admin/appearances/themes#index
cama_admin_appearances_nav_menu_delete_menu_item_path GET /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/item_delete/:id(.:format)  camaleon_cms/admin/appearances/nav_menus#delete_menu_item
cama_admin_appearances_nav_menu_custom_settings_path  GET /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/custom_settings/:id(.:format)  camaleon_cms/admin/appearances/nav_menus#custom_settings
cama_admin_appearances_nav_menu_save_custom_settings_path POST  /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/save_custom_settings/:id(.:format) camaleon_cms/admin/appearances/nav_menus#save_custom_settings
cama_admin_appearances_nav_menu_edit_menu_item_path GET /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/edit_menu_item/:id(.:format) camaleon_cms/admin/appearances/nav_menus#edit_menu_item
cama_admin_appearances_nav_menu_update_menu_item_path POST  /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/update_menu_item/:id(.:format) camaleon_cms/admin/appearances/nav_menus#update_menu_item
cama_admin_appearances_nav_menu_add_items_path  POST  /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/add_items(.:format)  camaleon_cms/admin/appearances/nav_menus#add_items
cama_admin_appearances_nav_menu_reorder_items_path  POST  /blog-cama/cama_admin/appearances/nav_menus/:nav_menu_id/reorder_items(.:format)  camaleon_cms/admin/appearances/nav_menus#reorder_items
cama_admin_appearances_nav_menus_path GET /blog-cama/cama_admin/appearances/nav_menus(.:format) camaleon_cms/admin/appearances/nav_menus#index
POST  /blog-cama/cama_admin/appearances/nav_menus(.:format) camaleon_cms/admin/appearances/nav_menus#create
new_cama_admin_appearances_nav_menu_path  GET /blog-cama/cama_admin/appearances/nav_menus/new(.:format) camaleon_cms/admin/appearances/nav_menus#new
edit_cama_admin_appearances_nav_menu_path GET /blog-cama/cama_admin/appearances/nav_menus/:id/edit(.:format)  camaleon_cms/admin/appearances/nav_menus#edit
cama_admin_appearances_nav_menu_path  PATCH /blog-cama/cama_admin/appearances/nav_menus/:id(.:format) camaleon_cms/admin/appearances/nav_menus#update
PUT /blog-cama/cama_admin/appearances/nav_menus/:id(.:format) camaleon_cms/admin/appearances/nav_menus#update
DELETE  /blog-cama/cama_admin/appearances/nav_menus/:id(.:format) camaleon_cms/admin/appearances/nav_menus#destroy
cama_admin_appearances_nav_menus_menu_path  GET /blog-cama/cama_admin/appearances/nav_menus/menu(.:format)  camaleon_cms/admin/appearances/nav_menus#index
cama_admin_appearances_widgets_main_index_path  GET /blog-cama/cama_admin/appearances/widgets/main(.:format)  camaleon_cms/admin/appearances/widgets/main#index
POST  /blog-cama/cama_admin/appearances/widgets/main(.:format)  camaleon_cms/admin/appearances/widgets/main#create
new_cama_admin_appearances_widgets_main_path  GET /blog-cama/cama_admin/appearances/widgets/main/new(.:format)  camaleon_cms/admin/appearances/widgets/main#new
edit_cama_admin_appearances_widgets_main_path GET /blog-cama/cama_admin/appearances/widgets/main/:id/edit(.:format) camaleon_cms/admin/appearances/widgets/main#edit
cama_admin_appearances_widgets_main_path  PATCH /blog-cama/cama_admin/appearances/widgets/main/:id(.:format)  camaleon_cms/admin/appearances/widgets/main#update
PUT /blog-cama/cama_admin/appearances/widgets/main/:id(.:format)  camaleon_cms/admin/appearances/widgets/main#update
DELETE  /blog-cama/cama_admin/appearances/widgets/main/:id(.:format)  camaleon_cms/admin/appearances/widgets/main#destroy
cama_admin_appearances_widgets_sidebar_reorder_path POST  /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/reorder(.:format) camaleon_cms/admin/appearances/widgets/sidebar#reorder
cama_admin_appearances_widgets_sidebar_assign_index_path  POST  /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign(.:format)  camaleon_cms/admin/appearances/widgets/assign#create
new_cama_admin_appearances_widgets_sidebar_assign_path  GET /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign/new(.:format)  camaleon_cms/admin/appearances/widgets/assign#new
edit_cama_admin_appearances_widgets_sidebar_assign_path GET /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign/:id/edit(.:format) camaleon_cms/admin/appearances/widgets/assign#edit
cama_admin_appearances_widgets_sidebar_assign_path  PATCH /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign/:id(.:format)  camaleon_cms/admin/appearances/widgets/assign#update
PUT /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign/:id(.:format)  camaleon_cms/admin/appearances/widgets/assign#update
DELETE  /blog-cama/cama_admin/appearances/widgets/sidebar/:sidebar_id/assign/:id(.:format)  camaleon_cms/admin/appearances/widgets/assign#destroy
cama_admin_appearances_widgets_sidebar_index_path GET /blog-cama/cama_admin/appearances/widgets/sidebar(.:format) camaleon_cms/admin/appearances/widgets/sidebar#index
POST  /blog-cama/cama_admin/appearances/widgets/sidebar(.:format) camaleon_cms/admin/appearances/widgets/sidebar#create
new_cama_admin_appearances_widgets_sidebar_path GET /blog-cama/cama_admin/appearances/widgets/sidebar/new(.:format) camaleon_cms/admin/appearances/widgets/sidebar#new
edit_cama_admin_appearances_widgets_sidebar_path  GET /blog-cama/cama_admin/appearances/widgets/sidebar/:id/edit(.:format)  camaleon_cms/admin/appearances/widgets/sidebar#edit
cama_admin_appearances_widgets_sidebar_path PATCH /blog-cama/cama_admin/appearances/widgets/sidebar/:id(.:format) camaleon_cms/admin/appearances/widgets/sidebar#update
PUT /blog-cama/cama_admin/appearances/widgets/sidebar/:id(.:format) camaleon_cms/admin/appearances/widgets/sidebar#update
DELETE  /blog-cama/cama_admin/appearances/widgets/sidebar/:id(.:format) camaleon_cms/admin/appearances/widgets/sidebar#destroy
toggle_cama_admin_plugins_path  GET /blog-cama/cama_admin/plugins/toggle(.:format)  camaleon_cms/admin/plugins#toggle
cama_admin_plugin_upgrade_path  GET /blog-cama/cama_admin/plugins/:plugin_id/upgrade(.:format)  camaleon_cms/admin/plugins#upgrade
cama_admin_plugins_path GET /blog-cama/cama_admin/plugins(.:format) camaleon_cms/admin/plugins#index
cama_admin_plugin_path  DELETE  /blog-cama/cama_admin/plugins/:id(.:format) camaleon_cms/admin/plugins#destroy
save_cama_admin_installers_path POST  /blog-cama/cama_admin/installers/save(.:format) camaleon_cms/admin/installers#save
welcome_cama_admin_installers_path  GET /blog-cama/cama_admin/installers/welcome(.:format)  camaleon_cms/admin/installers#welcome
cama_admin_installers_path  GET /blog-cama/cama_admin/installers(.:format)  camaleon_cms/admin/installers#index
crop_cama_admin_media_path    /blog-cama/cama_admin/media/crop(.:format)  camaleon_cms/admin/media#crop
ajax_cama_admin_media_path  GET /blog-cama/cama_admin/media/ajax(.:format)  camaleon_cms/admin/media#ajax
download_private_file_cama_admin_media_path GET /blog-cama/cama_admin/media/download_private_file(.:format) camaleon_cms/admin/media#download_private_file
upload_cama_admin_media_path  POST  /blog-cama/cama_admin/media/upload(.:format)  camaleon_cms/admin/media#upload
actions_cama_admin_media_path POST  /blog-cama/cama_admin/media/actions(.:format) camaleon_cms/admin/media#actions
cama_admin_media_path GET /blog-cama/cama_admin/media(.:format) camaleon_cms/admin/media#index
GET /blog-cama/cama_admin/*path(.:format) camaleon_cms/admin/admin#render_error {:error_msg=>"Invalid route"}
cama_root_path  GET /blog-cama(/:locale)(.:format)  camaleon_cms/frontend#index {:locale=>//}
cama_index_path GET /blog-cama(/:locale)/index(.:format)  camaleon_cms/frontend#index {:locale=>//}
cama_post_type_path GET /blog-cama(/:locale)/:label/:post_type_id-:title(.:format)  camaleon_cms/frontend#post_type {:locale=>//}
cama_post_of_post_type_path GET /blog-cama(/:locale)/:label/:post_type_id-:title/:slug(.:format)  camaleon_cms/frontend#post {:locale=>//}
cama_category_path  GET /blog-cama(/:locale)/:label/:category_id-:title(.:format) camaleon_cms/frontend#category {:locale=>//}
cama_post_of_category_path  GET /blog-cama(/:locale)/:label_cat/:category_id-:title/:slug(.:format) camaleon_cms/frontend#post {:locale=>//}
cama_post_of_category_post_type_path  GET /blog-cama(/:locale)/:post_type_title/:label_cat/:category_id-:title/:slug(.:format)  camaleon_cms/frontend#post {:locale=>//}
cama_post_tag_path  GET /blog-cama(/:locale)/:label/:post_tag_id-:title(.:format) camaleon_cms/frontend#post_tag {:locale=>//}
cama_post_of_tag_path GET /blog-cama(/:locale)/:label/:post_tag_id-:title/:slug(.:format) camaleon_cms/frontend#post {:locale=>//}
cama_post_tag_simple_path GET /blog-cama(/:locale)/:label/:post_tag_slug(.:format)  camaleon_cms/frontend#post_tag {:locale=>//}
cama_profile_path GET /blog-cama(/:locale)/:label/:user_id-:user_name(.:format) camaleon_cms/frontend#profile {:label=>"profile", :locale=>//}
cama_search_path  GET /blog-cama(/:locale)/:label(.:format) camaleon_cms/frontend#search {:label=>"search", :locale=>//}
cama_post_of_posttype_path  GET /blog-cama(/:locale)/:post_type_title/:slug(.:format) camaleon_cms/frontend#post {:locale=>//}
cama_save_comment_path  POST  /blog-cama(/:locale)/save_comment/:post_id(.:format)  camaleon_cms/frontend#save_comment {:locale=>//}
cama_save_form_path POST  /blog-cama(/:locale)/save_form(.:format)  camaleon_cms/frontend#save_form {:locale=>//}
cama_sitemap_path GET /blog-cama(/:locale)/sitemap(.:format)  camaleon_cms/frontend#sitemap {:format=>:xml, :locale=>//}
cama_robots_path  GET /blog-cama(/:locale)/robots(.:format) camaleon_cms/frontend#robots {:format=>:txt, :locale=>//}
cama_rss_path GET /blog-cama(/:locale)/rss(.:format)  camaleon_cms/frontend#rss {:format=>"rss", :locale=>//}
cama_ajax_path  GET /blog-cama(/:locale)/ajax(.:format) camaleon_cms/frontend#ajax {:locale=>//}
cama_hierarchy_post_path  GET /blog-cama(/:locale)/:parent_title/*slug(.:format)  camaleon_cms/frontend#post {:format=>/html|rss|json/, :locale=>//}
cama_post_path  GET /blog-cama(/:locale)/:slug(.:format)

**Comment by owen2345** [comment]
Then the config is ok.
Admin uri: localhost:3000/blog-cama/cama_admin

**Comment by ecojob** [comment]
http://localhost:3000/blog-cama/cama_admin/
 leads to 
http://localhost:3000/blog-cama/cama_admin/home

with the following error:
I am getting 
This page isn’t working
localhost redirected you too many times.
ERR_TOO_MANY_REDIRECTS

**Comment by owen2345** [comment]
what about if you disable "admin_path_name": "cama_admin" and check if the problem persists.

**Comment by ecojob** [comment]
http://localhost:3000/blog-cama/uglyfruits/home 
redirects me to 
http://localhost:3000/blog-cama/reg/home

http://localhost:3000/blog-cama/admin
redirects me to 
http://localhost:3000/blog-cama/admin/home

Both are throwing the same error : 
This page isn’t working
localhost redirected you too many times.
RR_TOO_MANY_REDIRECTS

**Comment by owen2345** [comment]
mmm I think there is something that is redirecting to home, did you review it in a clean project?

**Comment by ecojob** [comment]
I could make it work on a new project. 
You are right, it seems we do have conflict with our routes. Where can I change camaleon's route ? 

Where do you define them as it is not in routes.rb ?
