### ISSUE TITLE
NameError in AdminController#dashboard

### ISSUE THREAD

**Issue by kinsomicrote** [owen2345/camaleon-cms#83]
![action controller exception caught 2015-09-17 09-10-57](https://cloud.githubusercontent.com/assets/6418930/9928183/46d47834-5d1c-11e5-900d-1fcfbf942ffc.png)

**Comment by owen2345** [comment]
hello,

please send me your ruby, rails version and in what situation was generated, because I tried to generate the problem but without success.

**Comment by kinsomicrote** [comment]
Rails 4.2.3
Ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]

It happened when I tried logging into the admin dashboard

**Comment by kinsomicrote** [comment]
Hello, were you able to verify it?

**Comment by owen2345** [comment]
I am sorry, all weekend I tried to reproduce the error but without success. Please add me on skype to review the problem.
my skype: owen-2345

regards,

**Comment by cmckni3** [comment]
I run into these errors when developing plugins. They are fixed by restarting the Rails server for me.

**Comment by kinsomicrote** [comment]
I'll do some traceback and see what happens, would get back to you on this.

**Comment by cmckni3** [comment]
Have you followed the migration section in the readme? I recently removed the code from `lib/plugin_routes.rb` that loaded the Gemfile from this project and moved them into the gemspec.

**Comment by kinsomicrote** [comment]
I just tried it out again and did not encounter the error. Issue closed!

**Comment by kinsomicrote** [comment]
Thanks.

**Comment by kinsomicrote** [comment]
@owen2345 what is your skype id? wanna talk to you about a pitch I have to write article on camaleon-cms. The id above does not seem to be correct.

**Comment by owen2345** [comment]
it is owen-2345
don't forget to add - between letters and numbers.

**Comment by kinsomicrote** [comment]
Sent. If that was not you, add me up: kinsomicrote

**Comment by cmckni3** [comment]
@owen2345 I found you on skype

**Comment by kinsomicrote** [comment]
@owen2345 Got it?
