### ISSUE TITLE
Problems loading the Documentation

### ISSUE THREAD

**Issue by sebastianGitDL** [owen2345/camaleon-cms#837]
Hello!!! This is not related to the gem, but I am getting an error when trying to access the documentation: [developer-docs](http://camaleon.tuzitio.com/category/40757-developer-docs.html)

![screen shot 2018-09-13 at 5 05 31 pm](https://user-images.githubusercontent.com/1608166/45513395-f1790980-b778-11e8-9cb8-cf2e9839c53b.png)

Thanks in advance for looking into this!

**Comment by dannio** [comment]
yeah his website went down. I was just trying this CMS out and ran into this too.

**Comment by owen2345** [comment]
Sorry guys, this weekend I will solve the problem! unfortunately the company who was providing the free hosting had problems with their services...
Cheers!

**Comment by sebastianGitDL** [comment]
No problem at all!! Glad to hear you are already on it. 

Thanks again for the help and the great CMS! 

Good luck!

**Comment by sebastianGitDL** [comment]
The site is up again! Thanks for working on this! Closing the issue
