### ISSUE TITLE
Shortcode yield content 

### ISSUE THREAD

**Issue by dannio** [owen2345/camaleon-cms#838]
Hi,

I'm not sure if this is possible or not as the documentation is down, but from what I can currently tell from looking at the code is that there's no options to yield the content like in wordpress right?

e.g

[container]
[image]
[/container]

**Comment by owen2345** [comment]
you can pass options through attributes, likes:
[container attr1='val attr 1' attr2="value attr 2"]
....
[/container]

Rendering your chortcode, check for variables "attributes" and "args".
Cheers!

**Comment by dannio** [comment]
Oh cool thanks a lot!
