### ISSUE TITLE
Mandrill plugin

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#84]
Hi! 

I'm working in a mandrill plugin.
Is there any way to override the html_mailer.rb? 
I'm thinking in a way to override it only if mandrill plugin is enabled.

Any ideas?

**Comment by owen2345** [comment]
Raul, 

I added a new hook to customize the emails called "email".
Docs here: http://camaleon.tuzitio.com/hooks.html
I will generate a new version of gem this weekend with this an other changes.
For testing you can download from github mailers/html_mailer.rb

Regards,

**Comment by raulanatol** [comment]
It sounds good.

Thanks!
