### ISSUE TITLE
Cloudflare + Heroku

### ISSUE THREAD

**Issue by stjokro** [owen2345/camaleon-cms#843]
Hello everyone,

This is more of a question instead of an issue.
Not sure if anyone is using Cloudflare for the CDN, but is happening is that camaleon CMS always ask to relogin very frequently to the admin panel - almost when I'm navigating between 1 menu to the other.

This issue doesn't exist if I access the apps directly from the heroku link - nor if I disable the Cloudflare (direct root domain access with no CDN).

My configuration is as follow:
1. Redirect from root domain to www.
2. Force HTTPS
3. SSL Certificate = Full
4. Cache level is standard
5. Updated the domain name in the admin panel to www.mysite.com

If anyone can share their configuration, that would be highly appreciated! :)
I can do a redirect of admin page to Heroku if needed, but would like to avoid this.

Thanks everyone in advanced!

**Comment by brian-kephart** [comment]
The authentication system [checks the IP address of the request](https://github.com/owen2345/camaleon-cms/blob/504cebf20a29439ae1a7338c2973ed564ea805ad/app/helpers/camaleon_cms/session_helper.rb#L127), and I suspect this is causing your problem. If the CDN has nodes all over the place, and you don't hit the same one on every request, and if the app sees the CDN proxy node's IP instead of your own, then it would force another login. I'm honestly not sure how to fix this, though.

**Comment by zener79** [comment]
Same issue here... 
@stjokro , how did you solved?

**Comment by stjokro** [comment]
didn't get to solve this @zener79 =\
i think @brian-kephart have a point - maybe try to not check IP address on request.

Let me know if you have any luck!

**Comment by zener79** [comment]
I think I will use a different subdomain not proxyed by Cloudflare (orange cloud turned off) for admin tasks for the moment.

**Comment by stjokro** [comment]
that's a good option!
what i did is that if i need to make admin tasks, ill just go directly on the heroku app link.

not the sweetest - but itll do its job for now. :)

btw, have you done a comparison between wordpress and camaleon CMS in terms of speed, resources, performance for an apple-to-apple website?

Thinking to migrate it to wordpress as i've never had such an issue with wordpress

**Comment by brian-kephart** [comment]
@owen2345 can the IP check be removed, or would that compromise security? I'm not sure what role that check plays.

**Comment by owen2345** [comment]
Hi @brian-kephart 
done: browser and ip verification removed (2.4.5.14)

**Comment by brian-kephart** [comment]
@stjokro did this solve your issue?
