### ISSUE TITLE
Update the Website

### ISSUE THREAD

**Issue by westonganger** [owen2345/camaleon-cms#848]
The website for this project needs some work so that it appears up to date.

A few major things:

- Change references of "Ruby on Rails 4.2" to simply just "Ruby on Rails" as this supports Rails 5 too which is much newer and important.
- Remove Last updated at date from the plugins store. It does not add anything to the store it just makes it look outdated. Some of the dates aren't even correct according to the repo update dates.
- Remove "Edit" links from Home page
- Github stars are incorrect as probably lots of other data
- Hide the blog links. If its not being updated or utilized then it should be hidden from the main page. Theres even a bitcoin post there that someone added which should be removed.

I would love to help out with this effort if there is a repo I can contribute to for the website.

I am also interested in helping maintain this project and its related plugin/theme eco-system if there is a need for my help.

**Comment by owen2345** [comment]
Hi @westonganger,
I agree what are you saying with. Please help me! For now I am too busy with my little baby.
I will give you access to edit the site content.
Cheers!

**Comment by westonganger** [comment]
I would also like to help out with triaging some of these open issues. Many seem outdated and are probably no longer relevant.

**Comment by owen2345** [comment]
Cool!
Please let me know your email to add you on Camaleon site and be able to edit site information.

**Comment by westonganger** [comment]
weston@westonganger.com

**Comment by owen2345** [comment]
Cool, I made your account as editor. Please use your current account and access to:
http://camaleon.tuzitio.com/admin/

**Comment by westonganger** [comment]
The only thing I am authorized to do is edit documentation. Can you increase my permissions?

**Comment by westonganger** [comment]
Okay the website is better updated now.

Next the plugin & theme store needs work. 
- I want to lower the barrier of entry for contributing to these stores. 
- My main gripe with it is that the images are required. If someone does not want to take the time to make images then they simply just wont upload it to the store.
- Also remove presence validations on any fields that are not absolutely necessary
- Also we need to remove the "Last Updated"

**Comment by westonganger** [comment]
Also if your willing to provide me contributor access to this repository I would like to do some issue closing and triaging.

**Comment by westonganger** [comment]
All outdated/invalid issues have now been closed.

Also #852 merged which lists all plugins and themes in the Readme.

**Comment by WMPayne** [comment]
Sorry to write in a closed issue, but I figured this was better than opening a new one.

I've been using Camaleon for a couple of years now, and over time, I've learned quite a lot about it. One of the biggest knocks against it is that the documentation can be insufficient... since I've been working with it a lot, would it be possible to get the ability to edit/improve the documentation at http://camaleon.tuzitio.com/docs.html ?

**Comment by owen2345** [comment]
Hey @WMPayne 
I would be grateful if you could do that.
Please let me know your email to add you as a content editor.
Cheers!
