### ISSUE TITLE
Camaleon CMS in Rails 5, adding a new post the form disappear when updating the category

### ISSUE THREAD

**Issue by choyno** [owen2345/camaleon-cms#859]
Hello anyone encounter this bug or weird behavior? i created a custom group/field everything was setup according to my required design but my problem is when i create a new post and select the category the custom fields disappear

Please see the video below 

https://screencast.com/t/ZRBabKAnZvGb

GEMS
camaleon_cms = 2.4.5.10
ruby = 2.5.1
rails = 5.2.1

THANK YOU and MORE POWER 👍

**Comment by choyno** [comment]
up

**Comment by owen2345** [comment]
Fixed 2.4.5.12! 
Thanks for reporting
