### ISSUE TITLE
Broken Preview Function for Draft Post

### ISSUE THREAD

**Issue by ericbeansmile** [owen2345/camaleon-cms#861]
Now the `render_post` checks if `@post.can_visit?` , but that method checks if `object.status == 'published'`. This doesn't allow to preview draft post since the post status is "draft" not "published". The change was introduced in https://github.com/owen2345/camaleon-cms/commit/782f73334dd045c66d660747141bdfd71bc1ea2c .

https://github.com/owen2345/camaleon-cms/blob/393288351730172ed4756574097efe9419ff2ab8/app/controllers/camaleon_cms/frontend_controller.rb#L166

https://github.com/owen2345/camaleon-cms/blob/393288351730172ed4756574097efe9419ff2ab8/app/decorators/camaleon_cms/post_decorator.rb#L193

**Comment by choyno** [comment]
have you found solution for this one?

**Comment by choyno** [comment]
im currently tracing the camaleon source code trying to fix how this draft post can viewable

**Comment by ericbeansmile** [comment]
@choyno You can look into the `draft_render` method in FrontendController. I made a change in that method like:

```ruby
    if args[:permitted] || can?(:update, post_draft)
      render_post(post_draft, false, nil, true) # add the last argument as flag of draft_render
```

and also override the `render_post` method to accept the draft_render flag arg:

```ruby
def render_post(post_or_slug_or_id, from_url = false, status = nil, draft_render = false)
  ...
   if !@post.present? || (!draft_render && !@post.can_visit?)
      if params[:format] == 'html' || !params[:format].present?
        page_not_found
  ...
end
```

This is not very elegant but allows draft preview.

**Comment by choyno** [comment]
@ericbeansmile  what rails version and rails version  you are using?

**Comment by ericbeansmile** [comment]
@choyno The visibility filter is used in many places. I'm not sure there would be any side effect if it allows draft post. Haven't dig too far.

**Comment by ericbeansmile** [comment]
Great!
