### ISSUE TITLE
SEO field is not saving for specific custom group

### ISSUE THREAD

**Issue by choyno** [owen2345/camaleon-cms#863]
SEO field is not saving for specific custom group

Version 2.4.5.12

please check the video

https://screencast.com/t/VlQF5CKd0K2j

**Comment by superchell** [comment]
this is fixed in [this PR](https://github.com/owen2345/camaleon-cms-seo/commit/6fba835d49ba9ec9fe245349b0e6a7ae7726730d). Apparently the old version of seo plugin is installed in the demo.

**Comment by choyno** [comment]
@superchell  im using Camaleon Version 2.4.5.12  in my local its the same and not saving
its not updated also?

**Comment by superchell** [comment]
@choyno try to install seo plugin manually
put in your gemfile `gem 'cama_meta_tag', github: 'owen2345/camaleon-cms-seo'`
and run `bundle install`

**Comment by choyno** [comment]
@superchell  thank you mate 

confirm fixed done (Y)
