### ISSUE TITLE
Front Cache Issue  with Rails 5.1

### ISSUE THREAD

**Issue by choyno** [owen2345/camaleon-cms#865]
Hello 
anyone  encounter this problem im Using 
Rails 5.2.1
Camaleon_cms Version 2.4.5.12

im using Load Balancer server for my Rails Application but when i activate and start using  the Front Cache all the post URLs  turn into IP address  

before activate
`sample.com/post_types/example_post_1`  

after activated

`117.x.x.1/post_types/example_post_1`  

this url changes cause timeout and its not good also to view the IP of the server

**Comment by choyno** [comment]
im using Front Cache of the camaleon only

**Comment by brian-kephart** [comment]
I can't see any reason why that's happening. What load balancer are you using? Is the code online?

**Comment by choyno** [comment]
every time i deploy using capistrano 
"cap production deploy" 

on the first load of the site all the url  change into the ec2 IP Address
ex. 117.x.x.1/post_types/example_post_1


so i need to disable first my front cache then after deploy i activated it again but there are times the cache still cache the IP Address


Thank you for replaying mate
