### ISSUE TITLE
undefined method `add_flash_types' for CamaleonCms::CamaleonController:Class

### ISSUE THREAD

**Issue by rafaelbpa** [owen2345/camaleon-cms#869]
Followed all the steps in the documentation, but when I try to access localhost:3000 I get this routing error:

**undefined method `add_flash_types' for CamaleonCms::CamaleonController:Class**

I'm using rails 5.2.0 and ruby 2.4.1

I am pasting the full stack trace below:

`/Users/rafael/.rvm/gems/ruby-2.4.1/bundler/gems/camaleon-cms-1cf112642af5/app/controllers/camaleon_cms/camaleon_controller.rb:2:in `<class:CamaleonController>'
/Users/rafael/.rvm/gems/ruby-2.4.1/bundler/gems/camaleon-cms-1cf112642af5/app/controllers/camaleon_cms/camaleon_controller.rb:1:in `<main>'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
activesupport (5.2.0) lib/active_support/dependencies.rb:468:in `block in load_file'
activesupport (5.2.0) lib/active_support/dependencies.rb:653:in `new_constants_in'
activesupport (5.2.0) lib/active_support/dependencies.rb:467:in `load_file'
activesupport (5.2.0) lib/active_support/dependencies.rb:365:in `block in require_or_load'
activesupport (5.2.0) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.2.0) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.0) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.0) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (5.2.0) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.2.0) lib/active_support/dependencies.rb:348:in `require_or_load'
activesupport (5.2.0) lib/active_support/dependencies.rb:502:in `load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
activesupport (5.2.0) lib/active_support/dependencies.rb:193:in `const_missing'
/Users/rafael/.rvm/gems/ruby-2.4.1/bundler/gems/camaleon-cms-1cf112642af5/app/controllers/camaleon_cms/frontend_controller.rb:1:in `<main>'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
activesupport (5.2.0) lib/active_support/dependencies.rb:468:in `block in load_file'
activesupport (5.2.0) lib/active_support/dependencies.rb:653:in `new_constants_in'
activesupport (5.2.0) lib/active_support/dependencies.rb:467:in `load_file'
activesupport (5.2.0) lib/active_support/dependencies.rb:365:in `block in require_or_load'
activesupport (5.2.0) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.2.0) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.0) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.0) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (5.2.0) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.2.0) lib/active_support/dependencies.rb:348:in `require_or_load'
activesupport (5.2.0) lib/active_support/dependencies.rb:502:in `load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
activesupport (5.2.0) lib/active_support/dependencies.rb:193:in `const_missing'
activesupport (5.2.0) lib/active_support/inflector/methods.rb:285:in `const_get'
activesupport (5.2.0) lib/active_support/inflector/methods.rb:285:in `block in constantize'
activesupport (5.2.0) lib/active_support/inflector/methods.rb:281:in `each'
activesupport (5.2.0) lib/active_support/inflector/methods.rb:281:in `inject'
activesupport (5.2.0) lib/active_support/inflector/methods.rb:281:in `constantize'
activesupport (5.2.0) lib/active_support/dependencies.rb:574:in `get'
activesupport (5.2.0) lib/active_support/dependencies.rb:605:in `constantize'
actionpack (5.2.0) lib/action_dispatch/http/request.rb:88:in `controller_class_for'
actionpack (5.2.0) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:46:in `controller'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by brian-kephart** [comment]
That's a Rails method, from the ActionController package. It's inherited in CamaleonController from ActionController::Base through ApplicationController.

Did you modify app/controllers/application_controller.rb? I don't see how else this could happen, unless you are monkey patching the classes I listed.
