### ISSUE TITLE
"the_avatar" showing as undefined.

### ISSUE THREAD

**Issue by nasim31** [owen2345/camaleon-cms#874]
Hi, owen2345!

Thank you for awesome CMS. And Thank you very much for Awesome video tutorial also.
But it's not working as you have shown in video part - 2.
I'm Getting this error ::
ActionView::Template::Error (undefined method `the_avatar' for #<CamaleonCms::PostCommentDecorator:0x00007f00e0b02df8>
Code written:
<% @post.the_comments.decorate.each do |comment|  %>
         <%= comment.the_avatar(theme_asset_url('images/testimonials/pic1.jpg')) %>
<%end%>
I have attached few lines of code for more reference.

[avatar-codes.txt](https://github.com/owen2345/camaleon-cms/files/2875639/avatar-codes.txt)

**Comment by nasim31** [comment]
> Hi, owen2345!
> 
> Thank you for awesome CMS. And Thank you very much for Awesome video tutorial also.
> But it's not working as you have shown in video part - 2.
> I'm Getting this error ::
> ActionView::Template::Error (undefined method `the_avatar' for #CamaleonCms::PostCommentDecorator:0x00007f00e0b02df8
> Code written:
> <% @post.the_comments.decorate.each do |comment| %>
> <%= comment.the_avatar(theme_asset_url('images/testimonials/pic1.jpg')) %>
> <%end%>
> I have attached few lines of code for more reference.
> 
> [avatar-codes.txt](https://github.com/owen2345/camaleon-cms/files/2875639/avatar-codes.txt)

is there problem with gem that I used or rails version ????
Please reply..

**Comment by superchell** [comment]
@nasim31 `the_avatar` method designed for User model only. Try `comment.comment_user.decorate.the_avatar`.

**Comment by nasim31** [comment]
Thanks man. Its working now.

**Comment by nasim31** [comment]
Hi superchell,
Can you please help me on loading submenus ??
only parent menus are showing. Submenus are not loading.
Code written : 
`<% cama_menu_parse_items(current_site.nav_menus.find_by_slug('main_menu').children).each do |item| %>
								<li class="<%= item[:current_item] ? 'active' : '' %>"><a class="<%= 'scroll' if item[:url].start_with?('#') %>" href="<%= item[:url] %>"><%= item[:label] %></a></li>
							<% end %>`

Theme menu reference:
http://agency.dexignlab.com/xhtml/index.html

**Comment by owen2345** [comment]
Hi @nasim31 
check this sample: http://camaleon.tuzitio.com/render-custom.html
