### ISSUE TITLE
Missing template themes/[themename]/views/single

### ISSUE THREAD

**Issue by tostasqb** [owen2345/camaleon-cms#875]
This happens specially on url's with extensions. Those files don't exist, but the app should not break anyway. 

Examples:
```
/blahblah.gif
/not-existent-folder-name/blah.gif
```

Error describes problems in 
```
/camaleon-cms-43bbaf0d8b50/config/initializers/action_view.rb:16:in `find'
/camaleon-cms-43bbaf0d8b50/app/controllers/camaleon_cms/frontend_controller.rb:202:in `render_post'
/camaleon-cms-43bbaf0d8b50/app/controllers/camaleon_cms/frontend_controller.rb:215:in `page_not_found'
/camaleon-cms-43bbaf0d8b50/app/controllers/camaleon_cms/frontend_controller.rb:167:in `render_post'
/camaleon-cms-43bbaf0d8b50/app/controllers/camaleon_cms/frontend_controller.rb:113:in `post'
```

**Comment by brian-kephart** [comment]
This should be fixed by #878.

**Comment by tostasqb** [comment]
In some level it has been resolved, I think It now depends on the level of deep folders. e.g.
`/a/b/image.png` still throws an error.

**Comment by brian-kephart** [comment]
I see the problem. If you have a custom 404 page, Camaleon will still attempt to render a response because of [this line](https://github.com/owen2345/camaleon-cms/blob/master/app/controllers/camaleon_cms/frontend_controller.rb#L215).

That line needs to be altered similarly to the approach in #878.
