### ISSUE TITLE
Plugin custom_models append new attribute to Users

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#88]
Hi!

I'm working in a plugin for integrate with Mailchimp but I need to append an extra parameter in the user's entity for save if the user is newsletter enabled or no.

I do this (custom_models.rb file)
```
User.class_eval do
  attr_accessible :newsletter_subscribed
end
```
But it's not possible access to this parameter. The class_eval method works fine because I created an extra method and it works fine.

Thx!

**Comment by cmckni3** [comment]
`attr_accessible` isn't going to give you a new attribute on the `User` model. You would have use `attr_writer`, `attr_reader`, or `attr_accessor` as appropriate. However, these won't be saved the to the database and will only be available while the Ruby object is in memory.

You would have to either create a migration to add a database-backed attribute or use custom fields. I suggest namespacing the attribute as well.

I wouldn't recommend adding a migration because it's going to create another column. I'm not sure whether custom fields exist for users though.

**Comment by raulanatol** [comment]
Hi Chris!

Thanks for your advice.
I will try to follow the 'generate_custom_field_products' method in the ecommerce plugin like a sample.
 
Regards!

**Comment by raulanatol** [comment]
Hi!

Is there any way to use *update_field_value* method (custom_fields_read.rb) the first time?
The first time after create an new user this method fail because the field is only created using *set_field_values* method.

Example of problem.
1. Create a field_groups for Users (slug: test_field_a)
2. Create a new user
3. In hook user_after_register execute:
```
user.update_field_value('test_field_a', 'new_value')
```
And no commit performed. Because the current_user.field_values not contains the *test_field_a* field.

I was working in an update_or_create_field method but I don't know the way to set a correct *custom_field_id*

Any ideas?

**Comment by cmckni3** [comment]
I believe you need to call `add_field` and that will set the initial value. Are you using something like the following?

```ruby
group = get_user_field_groups(Site.first).first
group.add_field({ slug: 'test_field_a', name: 'Something'}, {field_key: 'text_box'})
```

**Comment by raulanatol** [comment]
Hi Chris!

Yes I used it.
It's part of a new plugin for mailchimp this is piece of source:

```
def mailchimp_on_active(plugin)
   group = User.first.get_user_field_groups(current_site).where({slug: 'plugin_mailchimp_user_data'})
    unless group.present?
      new_group = group.create({name: 'Mailchimp user data', slug: 'plugin_mailchimp_user_data', description: 'Mailchimp newsletter user subscription data'})
      new_group.add_field({'name' => "t('plugin.mailchimp.user.newsletter_subscribed')", 'slug' => 'mailchimp_newsletter_subscribed'}, {field_key: 'checkbox', default_value: false})
      new_group.add_field({'name' => "t('plugin.mailchimp.user.newsletter_enabled_at')", 'slug' => 'mailchimp_newsletter_enabled_at'}, {field_key: 'date'})
    end
end
```

And using the user_after_register hook...

```
    if params[:user][:newsletter_enabled] == '1'
      user = plugin[:user]
      user.the_newsletter_subscribed(true)
      user.the_newsletter_enabled_at(Time.zone.now)
      #FIXME background mailchimp subscribe!
    end
```

And in the User custom model...

```
def the_newsletter_subscribed(value)
    self. update_field_value('mailchimp_newsletter_subscribed', value)
end
```

The problem is:
- update_field_value only works when exists the field value for this user. For example after edit the user profile and set any value in this field.

![edit_user](https://cloud.githubusercontent.com/assets/2389019/10038843/6ad982a0-61c3-11e5-9e63-96ae195ff9f0.png)

Thx!
