### ISSUE TITLE
Sub menus loading issue

### ISSUE THREAD

**Issue by nasim31** [owen2345/camaleon-cms#883]
Not able to parse the submenus.
Help please.

`<% cama_menu_parse_items(current_site.nav_menus.find_by_slug('main_menu').children).each do |item| %>
								<li class="<%= item[:current_item] ? 'active' : '' %>"><a class="<%= 'scroll' if item[:url].start_with?('#') %>" href="<%= item[:url] %>"><%= item[:label] %></a></li>
							<% end %>`

This line is only able to get parent menus. But sub menus are not loading.
working on this page.
http://agency.dexignlab.com/xhtml/index.html

**Comment by owen2345** [comment]
http://camaleon.tuzitio.com/render-custom.html

**Comment by nasim31** [comment]
Is there any option to put an icon instead of writing the name of the menus.
Ex. Placing a `<span class="ti-home"></span>` in place of writing "**Home**" ??
