### ISSUE TITLE
Cannot create site on Rails 6

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#884]
The CI passes all test on Rails 6, the gem installs, the migrations run, but I can't create a site.

Steps to reproduce:
- `rails _6.0.0beta3_ new testapp`
- `cd testapp`
- `rails s` (You're on Rails!)
- add `gem 'camaleon_cms'` and `gem 'draper'` to gemfile, run `bundle`
- `rails g camaleon_cms:install`
- `rake camaleon_cms:generate_migrations`
- `rails db:migrate`
- `rails s` (Camaleon CMS initialization screen)
- fill out the form. Result:
<img width="581" alt="Screen Shot 2019-03-23 at 6 53 59 PM" src="https://user-images.githubusercontent.com/21235090/54873116-d9c0b480-4d9d-11e9-8638-e3f47c2bd6fc.png">

The steps above work fine on Rails 5.2.

**Comment by owen2345** [comment]
I think it is concerning to belongs to is required in rails 6 which in this case for site does not exist parent and owner.
To support rails 6, we need to modify several things according to rails 6 changes (for now not supported yet).

**Comment by brian-kephart** [comment]
Do you know what `parent` and `owner` refer to? I can't even tell what this error is referring to.

**Comment by brian-kephart** [comment]
I tried to write a failing spec for this, but the spec has no problem creating a site.

The spec:
```ruby
describe "create the first Site", js: true do
  it "first Site" do
    CamaleonCms::Site.destroy_all
    visit "#{cama_root_relative_path}/admin/installers"
    expect(page).to have_css("#new_site")
    within '#new_site' do
      fill_in "site_slug", with: 'owen'
      fill_in "site_name", with: 'Owen sub site'
      click_button "Submit"
    end
    expect(page).to have_text('Your site was created successfully.')
  end
end
```
