### ISSUE TITLE
undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by awais4123** [owen2345/camaleon-cms#888]
I am using s3 to upload images and I am getting `nil class` and `undefined method` errors at numerous actions. 
When I try to reload the media I get `undefined method merge for nil:NilClass` and when I try to upload an image I get `nil can't be coerced into Float`. I was not getting this nil class error before. It just started to appear. 

Can you please help me with the errors? This is happening on the live website.

**Comment by superchell** [comment]
I fixed this issue #872. But unfortunely this PR was reverted.

**Comment by owen2345** [comment]
@superchell I had to revert because there were other errors cause of it. Could you please solve the problem and make the new PR?

**Comment by owen2345** [comment]
@awais4123 Fixed!
