### ISSUE TITLE
In Demo : Preview is not working

### ISSUE THREAD

**Issue by rakeshrajwar** [owen2345/camaleon-cms#889]
![11](https://user-images.githubusercontent.com/1665183/56005488-4fa9a300-5cee-11e9-9845-4746e813f437.png)

**Comment by texpert** [comment]
Working now, so closing - see the fresh screenshot below:

<img width="1680" alt="Screenshot 2022-12-15 at 00 37 00" src="https://user-images.githubusercontent.com/2990033/207730194-1fd215ec-7a6f-48af-83b4-139669cabca2.png">
