### ISSUE TITLE
uninitialized constant CamaleonCms::Admin::AdminController when config.eager_load = true

### ISSUE THREAD

**Issue by thmyrk** [owen2345/camaleon-cms#891]
In case when `config.eager_load = true` (for example in production environment), when moving to a not existing URL inside admin scope `/admin/not-existing-url-here`, instead of being redirected to a fallback page, I receive an error `uninitialized constant CamaleonCms::Admin::AdminController`. This is probably caused by https://github.com/owen2345/camaleon-cms/blob/master/config/routes/admin.rb#L144 .

Interestingly enough, when `eager_load = false` the problem doesn't occur.

**Comment by owen2345** [comment]
@thmyrk you are right. In the next days I will look for a fix. Looks a complex problem 😄

**Comment by brian-kephart** [comment]
Thanks @thmyrk for identifying this. I've gotten a few of these errors and didn't know what they were.

**Comment by brian-kephart** [comment]
As an update on this, I can reproduce this issue even when `config.eager_load = false`.

Just go to a non-existing URL in the admin scope, like http://localhost:3000/admin/nope.
