### ISSUE TITLE
config.eager_load = true causes boot failure in Rails 6

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#894]
I think this is an issue with the new Zeitwerk autoloader that is used in Rails 6, but it's something to be aware of. Full description and repro here: https://github.com/fxn/zeitwerk/issues/43

**Comment by fxn** [comment]
Problem is that as it is, the project structure does not comply with the requirements. [This file](https://github.com/owen2345/camaleon-cms-seo/blob/master/app/models/plugins/cama_meta_tag/cama_meta_tag.rb) in the engine does not define the corresponding constant.

On easy fix would be not to ship that file.
