### ISSUE TITLE
Attack Plugin Error Issue when acitvated

### ISSUE THREAD

**Issue by choyno** [owen2345/camaleon-cms#896]
hello im using 

Rails 5.1.6
Ruby 2.5.1
Camaleon  2.4.5.14
Dalli' 2.7.10

when i try to activate it i got an error in the post_type

ArgumentError in CamaleonCms::FrontendController#post_type
key cannot be blank

{
status: 500,
error: "Internal Server Error",
exception: "#<ArgumentError: key cannot be blank>",
traces: {
Application Trace: [ ],
Framework Trace: [
{
id: 0,
trace: "dalli (2.7.10) lib/dalli/client.rb:378:in `validate_key'"
},
{
id: 1,
trace: "dalli (2.7.10) lib/dalli/client.rb:365:in `perform'"
},
{
id: 2,
trace: "dalli (2.7.10) lib/dalli/client.rb:59:in `get'"
},
{
id: 3,
trace: "newrelic_rpm (5.2.0.345) lib/new_relic/agent/instrumentation/memcache.rb:49:in `block (3 levels) in instrument_methods'"
},
{
id: 4,
trace: "dalli (2.7.10) lib/active_support/cache/dalli_store.rb:306:in `block in read_entry'"
},
{
id: 5,
trace: "dalli (2.7.10) lib/dalli/client.rb:266:in `with'"
},
{
id: 6,
trace: "dalli (2.7.10) lib/active_support/cache/dalli_store.rb:87:in `with'"
},
{
id: 7,
trace: "dalli (2.7.10) lib/active_support/cache/dalli_store.rb:306:in `read_entry'"
},

But when i remove the disable the plugin camaleon works properly.

**Comment by choyno** [comment]
https://github.com/owen2345/camaleon-cms/issues/888
Fixed with the new release 2.4.6.1!

**Comment by owen2345** [comment]
@choyno could you pls tell me the steps to reproduce the error?
I tried with the last version 2.4.6.5 and I did not see the error.

**Comment by choyno** [comment]
@owen2345  thank you so much for your reply okay i tried on the available latest version i can only see 
camaleon tag version 2.4.6.1 still i got an error, sorry i forgot to mention i used camaleon Json type 

ex. 
sample.come/cms/post/sample-article.json 

**Step 1**
 Install Rails 5.1.6
            Ruby 2.5.1
            Camaleon 2.4.5.14 or Camaleon 2.4.6.1
**Step 2**
        i Create post type using json.jbuilder 
**Step 3**
       access the url with json format
**Step 4**
      upon checking the url i got that error
``` ArgumentError in CamaleonCms::FrontendController#post_type
key cannot be blank```
**Step 5**
     Tried to disable the Attack Plugin, now i can access the json format

sir where i can get the latest version 2.4.6.5 ?
