### ISSUE TITLE
Admin Dashboard is not showing icons related to font-awesome 

### ISSUE THREAD

**Issue by salmagomaa** [owen2345/camaleon-cms#906]
Once, I installed the gem, and tried to open the admin dashboard, all of the icons are missed.
I tried to add this line manually in 
`<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">` in camaleon_cms-2.4.6.5/app/views/layouts/camaleon_cms/admin.html.erb

So do you have any idea about fixing the issue? or should I open a PR to merge the fix I added?

**Comment by owen2345** [comment]
@salmagomaa it is strange, I tested the last version and it worked well for me.
Could you please review if your site is loading "http://localhost:3002/assets/fontawesome-webfont-....woff2" ?
Cheers!
