### ISSUE TITLE
 Routes exists but Rails throws a 404

### ISSUE THREAD

**Issue by suhailpattambi** [owen2345/camaleon-cms#908]
Followed below steps.

- added gem "camaleon_cms",  '>= 2.3.6'
- bundle install
- rails generate camaleon_cms:install
- "admin_path_name": "cms_admin" added this line in /config/system.json
- rake camaleon_cms:generate_migrations
- rake db:migrate
- rails server

getting 404 when trying /cms_admin, I can see the routes when running rake routes.

**Comment by owen2345** [comment]
Hi @suhailpattambi 
I tested right now and it is working well.
Check in your config file for ```relative_url_root``` to be empty which can affect the app path.
For: ```"admin_path_name": "cms_admin"```
- If relative_url_root is empty, then the url is localhost/cms_admin
- If relative_url_root='blog', then url is localhost/blog/cms_admin

Sorry for my late answer.
