### ISSUE TITLE
Camaleon website issues

### ISSUE THREAD

**Issue by brentkearney** [owen2345/camaleon-cms#909]
Sorry that this is not exactly for camaleon-cms project itself, but relates to it. I tried to report a problem with the [Camaleon website](http://camaleon.tuzitio.com), but the contact form at the bottom of the home page crashes the site. The problem I was reporting is that the [Read more](http://camaleon.tuzitio.com/about) link in the first paragraph of the home page links to a page that no longer exists.

**Comment by owen2345** [comment]
@brentkearney sorry for my late answer. If the problem persist, please add a screenshot and ways to reproduce it.
