### ISSUE TITLE
How to turn on auto-resizing of photos that are uploaded

### ISSUE THREAD

**Issue by truthSeekr** [owen2345/camaleon-cms#914]
I would like to turn on auto-resize of image when it is uploading. So when the image resoultions are bigger than 2000xSomething I would like to scale it to for example to 1600x and delete version 2000x

**Comment by owen2345** [comment]
Hi @truthSeekr 
there is a hook called "before_upload" which you can use to make anything before uploading:
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/uploader_helper.rb#L49
