### ISSUE TITLE
Recently Viewed Posts

### ISSUE THREAD

**Issue by awais4123** [owen2345/camaleon-cms#919]
I need to implement a feature to fetch the recently viewed posts. Is it possible to fetch the recently viewed posts?  Is there any column in the DB where we store the last visit date/time?

**Comment by owen2345** [comment]
@awais4123 there is not included in the cms.
You can add easily by:
- add a column in the posts table
- listen "on_render_post" hook to track the last visited time, which receives this data: ```{post: @post, post_type: @post_type, layout: layout_, render: r_file}```
Regards!
