### ISSUE TITLE
Deprecation warning: render file: should be given the absolute path to a file

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#922]
I'm getting these deprecation warnings when running my system tests.

```
DEPRECATION WARNING: render file: should be given the absolute path to a file (called from _eval_shortcode at /Users/briankephart/.rvm/gems/ruby-2.6.5/bundler/gems/camaleon-cms-34184ede4aad/app/helpers/camaleon_cms/short_code_helper.rb:162)
```
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/short_code_helper.rb#L162

**Comment by brian-kephart** [comment]
It appears this happens when calling `CamaleonCms::Post#the_content` or `CamaleonCms::Post#the_field`

**Comment by owen2345** [comment]
Hi @brian-kephart 
could u pls add ruby/ror version to reproduce the problem?
Thanks!

**Comment by brian-kephart** [comment]
Sorry about that. This is a deprecation notice in Rails 6.0. I've seen it using Ruby 2.6-2.7 and Rails 6.0.0-6.0.2.2, but Ruby version shouldn't matter as long as it's Rails 6.0.x. I returned to this issue because Rails 6.1 ought to be coming out in the next few months, and Rails 6.1 users should see errors from this.

I _think_ this happens due to calling
```ruby
shortcode_add 'some-shortcode', theme_view('partials/_some_partial'),  'shortcode description'
```

because the `theme_view` method does not return an absolute path. I haven't had a chance to test this theory, though. I'm pretty sure the theory is correct, but I'm not sure if this is the only cause of the deprecation notice or if other changes are necessary as well.

**Comment by brian-kephart** [comment]
I haven't had any success with this issue yet. The deprecation notice doesn't provide a trace, and all the lines it points to refer to TinyMCE fields, like `post.the_content` or `post.the_field('some_field')`. It is difficult to figure out the root cause because most of the rendering methods have some defaults, so I can't even tell whether the option passed to `render :file` comes from my application code or from Camaleon itself.

However, [this StackOverflow topic](https://stackoverflow.com/questions/57335007/use-of-absolute-path-in-rails-6) makes me think that Camaleon is using `render :file` when it should be `render :template`. @owen2345 any thoughts on this?
