### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#93]
A lot of the admin pages take a long time to load.

I notice some cached queries but a lot of the time is actually spent in the views.

I think it's something to investigate but it could just be the asset pipeline, etc while running in development mode.

**Comment by Austio** [comment]
https://github.com/MiniProfiler/rack-mini-profiler have you considered using this to baseline?

**Comment by owen2345** [comment]
mini-profiler seems good!
