### ISSUE TITLE
Uploader media in current release.

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#932]
Hi,
When i try to upload and image, i have the issue below.
I use current release.

Processing by CamaleonCms::Admin::MediaController#ajax as */*
  Parameters: {"media_formats"=>"image"}
  CamaleonCms::Site Load (0.4ms)  SELECT  "cama_term_taxonomy".* FROM "cama_term_taxonomy" WHERE "cama_term_taxonomy"."taxonomy" = $1 ORDER BY "cama_term_taxonomy"."term_group" DESC LIMIT $2  [["taxonomy", "site"], ["LIMIT", 1]]
  ↳ /Users/many/Documents/projets/camaleon-cms/app/helpers/camaleon_cms/site_helper.rb:8
  CamaleonCms::User Load (0.3ms)  SELECT  "cama_users".* FROM "cama_users" WHERE "cama_users"."auth_token" = $1 ORDER BY "cama_users"."role" ASC LIMIT $2  [["auth_token", "wtLIqLGrQuZqGylaiDiFNw"], ["LIMIT", 1]]
  ↳ /Users/many/Documents/projets/camaleon-cms/app/helpers/camaleon_cms/session_helper.rb:127
  CamaleonCms::Meta Load (0.2ms)  SELECT  "cama_metas".* FROM "cama_metas" WHERE "cama_metas"."objectid" = $1 AND "cama_metas"."object_class" = $2 AND "cama_metas"."key" = $3 ORDER BY "cama_metas"."id" ASC LIMIT $4  [["objectid", 1], ["object_class", "Site"], ["key", "_default"], ["LIMIT", 1]]
  ↳ /Users/many/Documents/projets/camaleon-cms/app/models/concerns/camaleon_cms/metas.rb:25
Camaleon CMS - Hook "app_before_load" executed from dependency front_cache
Camaleon CMS - Hook "app_before_load" executed from dependency cama_contact_form
  CamaleonCms::Meta Load (0.2ms)  SELECT  "cama_metas".* FROM "cama_metas" WHERE "cama_metas"."objectid" = $1 AND "cama_metas"."object_class" = $2 AND "cama_metas"."key" = $3 ORDER BY "cama_metas"."id" ASC LIMIT $4  [["objectid", 1], ["object_class", "Site"], ["key", "languages_site"], ["LIMIT", 1]]
  ↳ /Users/many/Documents/projets/camaleon-cms/app/models/concerns/camaleon_cms/metas.rb:25
Camaleon CMS - Hook "admin_before_load" executed from dependency front_cache
Camaleon CMS - Hook "admin_before_load" executed from dependency cama_contact_form
Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.7ms)

  
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "cama_media" does not exist
LINE 8:                WHERE a.attrelid = '"cama_media"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"cama_media"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
  
activerecord (5.2.4.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
activerecord (5.2.4.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (5.2.4.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (5.2.4.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
activerecord (5.2.4.1) lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/Users/many/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.2.4.1) lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activerecord (5.2.4.1) lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
activerecord (5.2.4.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
activerecord (5.2.4.1) lib/active_record/connection_adapters/postgresql_adapter.rb:757:in `column_definitions'
activerecord (5.2.4.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
activerecord (5.2.4.1) lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
activerecord (5.2.4.1) lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
activerecord (5.2.4.1) lib/active_record/model_schema.rb:466:in `load_schema!'
activerecord (5.2.4.1) lib/active_record/attributes.rb:234:in `load_schema!'
activerecord (5.2.4.1) lib/active_record/attribute_decorators.rb:51:in `load_schema!'
activerecord (5.2.4.1) lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/many/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.2.4.1) lib/active_record/model_schema.rb:456:in `load_schema'
activerecord (5.2.4.1) lib/active_record/model_schema.rb:336:in `columns_hash'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1070:in `arel_column'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1179:in `order_column'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1169:in `block (2 levels) in preprocess_order_args'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1164:in `each'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1164:in `map'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1164:in `block in preprocess_order_args'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1159:in `map!'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:1159:in `preprocess_order_args'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:297:in `order!'
activerecord (5.2.4.1) lib/active_record/relation/query_methods.rb:292:in `order'
/Users/many/Documents/projets/camaleon-cms/app/models/camaleon_cms/media.rb:10:in `block in <class:Media>'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:122:in `instance_exec'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:122:in `block (2 levels) in build_default_scope'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:120:in `each'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:120:in `inject'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:120:in `block in build_default_scope'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:144:in `evaluate_default_scope'
activerecord (5.2.4.1) lib/active_record/scoping/default.rb:119:in `build_default_scope'
activerecord (5.2.4.1) lib/active_record/scoping/named.rb:55:in `default_extensions'
activerecord (5.2.4.1) lib/active_record/associations/association.rb:139:in `extensions'
activerecord (5.2.4.1) lib/active_record/associations/collection_proxy.rb:37:in `initialize'
activerecord (5.2.4.1) lib/active_record/relation/delegation.rb:132:in `new'
activerecord (5.2.4.1) lib/active_record/relation/delegation.rb:132:in `create'
activerecord (5.2.4.1) lib/active_record/associations/collection_association.rb:35:in `reader'
activerecord (5.2.4.1) lib/active_record/associations/builder/association.rb:108:in `private_media'
draper (3.1.0) lib/draper/automatic_delegation.rb:12:in `method_missing'
/Users/many/Documents/projets/camaleon-cms/app/uploaders/camaleon_cms_uploader.rb:63:in `get_media_collection'
/Users/many/Documents/projets/camaleon-cms/app/uploaders/camaleon_cms_uploader.rb:24:in `objects'
/Users/many/Documents/projets/camaleon-cms/app/controllers/camaleon_cms/admin/media_controller.rb:105:in `init_media_vars'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.8) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.8) lib/rack/etag.rb:25:in `call'
rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.8) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.8) lib/rack/session/abstract/id.rb:259:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.8) lib/rack/method_override.rb:22:in `call'
rack (2.0.8) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/admin/settings/site" for 127.0.0.1 at 2019-12-29 14:11:36 +0100
Processing by CamaleonCms::Admin::SettingsController#site as HTML

**Comment by tostasqb** [comment]
Just a guess, did you make an update to camaleon's version lately? do you have a `cama_media` table? 

This is catching my eye...

```
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR: relation "cama_media" does not exist
LINE 8: WHERE a.attrelid = '"cama_media"'::regclass
```
