### ISSUE TITLE
There's not SEO documentation.

### ISSUE THREAD

**Issue by josephschito** [owen2345/camaleon-cms#935]
Where I can find SEO docs?

**Comment by owen2345** [comment]
Hi @josephschito 
there is a hook called "seo" which enables you to configure everything from here: https://github.com/kpumuk/meta-tags
Cheers!

**Comment by josephschito** [comment]
Thank you owen!

There's any way to customize the SEO section in Camaleon?
What I need is a Wordpress like seo editor (with Google preview).

**Comment by owen2345** [comment]
@josephschito unfortunately it is so basic in: admin -> settings -> general site -> seo settings
