### ISSUE TITLE
undefined local variable or method `cama_forgot_path'

### ISSUE THREAD

**Issue by truthSeekr** [owen2345/camaleon-cms#939]
When I tried to reset password for admin on local machine and copied link from console to browser I get:

undefined local variable or method `cama_forgot_path' for #<CamaleonCms::Admin::SessionsController:0x00007f3a9ad21d48> Did you mean? cama_root_path cama_robots_path cama_post_path cama_error_path

**Comment by owen2345** [comment]
Fixed!
