### ISSUE TITLE
Is `render inline:` intended here instead of `render html:`?

### ISSUE THREAD

**Issue by cantino** [owen2345/camaleon-cms#949]
By using `render inline:` you execute ERB, which would be a security issue if it could come from a user.

https://github.com/owen2345/camaleon-cms/blob/19369328a6d70859657c9bcae76747e9ca15ddfb/app/controllers/camaleon_cms/frontend_controller.rb#L104

**Comment by brian-kephart** [comment]
Sorry for the extremely late response. That input can only come from a hook defined by the programmer, so there's no out-of-the box way that it can execute user input, and there might be a legitimate reason someone wants ERB.
