### ISSUE TITLE
Post Type form is confusing

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#95]
When creating/editing a post type, the `options` section is really confusing.

What exactly does this section do? It seems like it enables these options for that post type. Maybe there should be some help text.

Also, shouldn't an option be permanently enabled? It seems that disabling an option would break plugins when the plugin requires an option to be enabled.

**Comment by owen2345** [comment]
That section needs text details to explain each setting.
To avoid the problem, maybe I can add an internal setting (Boolean "permit_edit_setting") to enable or disable the edition for settings.
This configuration could be used only by code.

**Comment by cmckni3** [comment]
I was going to suggest maybe having a `required` attribute when setting it up through code. Effectively the same thing but required is very generic.

Maybe call it `permit_editing`
