### ISSUE TITLE
{acl: 'public-read'} is hard-coded in CamaleonCmsAwsUploader, no way to change

### ISSUE THREAD

**Issue by texpert** [owen2345/camaleon-cms#955]
Here it is - https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L92

Sure I've worked it around by setting `public read` access to the bucket, but AWS is complaining of this and, indeed, this would be good to be configurable.

**Comment by owen2345** [comment]
Hi @texpert
You can customize it using the hook "on_uploader", sample:
```
def my_hook_listener(settings)
  settings[:aws_settings][:aws_file_upload_settings] = lambda { |file_settings| file_settings.merge({ .. custom_file_settings })  }
end
```

BTW: Sorry for the bad code, the project  is too too old.

**Comment by texpert** [comment]
Thanks a lot, @owen2345 , worked like a charm!!

However, I have just discovered, that downloading of private files is possible only via presigned URL. Not a word about it in AWS docs, until I went to their forums :(
