### ISSUE TITLE
 uninitialized constant Draper (NameError)

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#956]
Rails 5.2.4.2
Camaleon 2.5.2
May be code needs to be changed.

**Comment by owen2345** [comment]
Hi @prdpspkt 
did you add the following?
```# gem 'draper', '~> 3' # for Rails 5+```

**Comment by prdpspkt** [comment]
`gem 'drapper', '~> 4.0.1'` worked fine.
