### ISSUE TITLE
Webpacker support

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#966]
I am starting this issue in order to un-hijack #947.

With Webpacker now being the default JS compiler in Rails, it would be nice to support it properly. It seems as though some other contributors are interested in this as well. There are a lot of issues to work through, though. I would love to know what other people think of this idea, so I'm posting this issue for discussion, as well as my personal opinions about it.

I'm not so much concerned with assets for the admin side of things. Those can be included in compiled form, so it doesn't matter what build tool is used.

The frontend side of things is where I think Webpacker has potential, because that's where we see custom assets that need compilation. Having Babel for handling ES6+ features and tools like PostCSS and autoprefixer for cross-browser CSS is a big win for anyone customizing their theme. Right now, theme assets are compiled with Sprockets, but using them with Webpacker requires custom config or moving them out of the theme directory and into app/javascript/packs. I think the main goal of adding webpacker support to Camaleon should be to make theme assets compile correctly via webpack without any extra config by the user.

I am not a fan of the current Rails default of using Webpacker for JS and Sprockets for other assets.
1. I find Webpacker extremely helpful for compiling CSS because of the tools mentioned above.
2. The two-compiler setup is a poor fit for libraries like Bootstrap that have both JS and CSS components (in my opinion).
3. Reducing dependencies is a worthwhile goal. Even if Camaleon follows the Rails default of separate asset pipelines, it should at least be _possible_ to remove one of them. Of course, Camaleon already accomplishes this by not requiring Webpacker, but I'd like to get the benefits of Webpacker without needing to include Sprockets.

Again, these are my opinions. It doesn't matter what I think, it matters what the user community overall and @owen2345 as the creator/maintainer think, so please comment if you have an opinion about this!

**Comment by texpert** [comment]
I'd also be very glad to reduce dependencies, but we could keep them both (with opt-out possibility), for the start, see how it will work and watch the community feedback.

**Comment by tostasqb** [comment]
Adding webpacker and asset compilation for the frontend is not something problematic at this point. I covered this some time ago in the article below...

https://revs.runtime-revolution.com/bringing-rails-webpack-react-and-camaleon-cms-together-6cc52f1aa372

**Comment by brian-kephart** [comment]
@tostasqb thank you for your input. You are correct that it is possible to compile your frontend with webpacker. However, it does not work out of the box for the included themes, or for themes created by the developer that follow the established directory structure. Currently, using webpacker for frontend requires you to keep your theme assets in the app/javascript directory, away from all the other theme files. This is one of the two main problems I would like to solve, along with removing the dependency on sprockets.

**Comment by brian-kephart** [comment]
Recent comments by DHH indicate that Rails is leaning towards native ESM modules for future development, rather than bundling with Webpacker (or any other bundler). Since Webpacker no longer seems like a long-term replacement for the asset pipeline, I'm going to close this issue. I no longer think it's a good investment of time.

**Comment by texpert** [comment]
@brian-kephart , some questions still legit for maybe using a bundler:

- non-JS assets - import maps are not going to support these in the v1 standard. sprockets is still an option, but I don't know if there is a possibility to replace sass to dart-sass;

- bundling the engine assets - this is still unresolved. Webpacker gem on the way to 6.0 release has even temporarily removed the doc about using it with Rails engines, stating that they are first going to achieve a stable state for 6.0 to be released.

**Comment by brian-kephart** [comment]
@texpert  My motivation for opening this issue was twofold:
1. **Move from the "old way" (Sprockets) to the "new way" (Webpacker).** Basically, I wanted to keep up with changes in the Rails ecosystem. Now that the future of that ecosystem does not appear to be "Webpacker for everything by default," this motivation is no longer valid, which is why I closed the issue.
2. **Remove Sprockets dependency.** This is still valid. Webpacker users still need Sprockets to use Camaleon. Ideally this would not be the case, but I personally don't want to put the work in to change this unless Webpacker is going to be the default asset bundler for Rails for the forseeable future. Plus, as you said, there's not even a clear path forward here for migrating the engine assets to Webpacker. It seems like a lot of work for little benefit.

I'm not saying there are no benefits. I'm just saying this doesn't seem totally necessary to me anymore.
