### ISSUE TITLE
Warning delegation of draper-3.1.0 and activesupport-6.0.3.2

### ISSUE THREAD

**Issue by nnhansg** [owen2345/camaleon-cms#970]
Hi @owen2345 ,

I have created new project with gems as the following:
1. gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
2. gem "camaleon_cms",  '>= 2.5.3.1'
3. gem 'draper', '~> 3'

But when I run `rails s -p 3002`, it has some warnings:

![image](https://user-images.githubusercontent.com/8666770/90969728-1447f700-e526-11ea-8bdb-092cbf84f337.png)

Should we fix them?

Thanks.

**Comment by texpert** [comment]
@nnhansg , have you tried to bump Draper's version (first removing the version constraint, of course)?
