### ISSUE TITLE
Getting error with migration

### ISSUE THREAD

**Issue by benn82** [owen2345/camaleon-cms#974]
Hello,

I'm trying to implement Camaleon to my existing application.

I got this error when trying to run `rake db:migrate`

LoadError: cannot load such file -- ../app/models/exception_handler/exception.rb

Could someone help me, please?

Thank you

**Comment by texpert** [comment]
Hello!

I could see no such file in Camaleon. You better provide the full error trace.

**Comment by benn82** [comment]
@texpert Here you are.
This is the migration file generated from Camaleon

`# This migration comes from exception_handler (originally 0)
class CreateErrors < ActiveRecord::Migration[5.0]

  # => ATTRS
  require_relative "../../app/models/exception_handler/exception.rb"

  #########################################
  #########################################

    # => Defs
    @@table = ExceptionHandler.config.try(:db)

  #########################################

    # Up
    def up
      create_table @@table do |t|
        ExceptionHandler::ATTRS.each do |attr|
          t.text attr
        end
        t.timestamps
      end
    end

  #########################################

    # Down
    def down
      drop_table @@table, if_exists: true
    end

  #########################################
  #########################################

end
`

And here are the error:
`== 20201020172239 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs)
   -> 0.0057s
-- create_table(:active_storage_attachments)
   -> 0.0064s
== 20201020172239 CreateActiveStorageTables: migrated (0.0123s) ===============

rake aborted!
LoadError: cannot load such file -- /Users/benn/Developments/sidepitch/sidepitch_camaleon/app/models/exception_handler/exception.rb
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
/Users/benn/Developments/sidepitch/sidepitch_camaleon/db/migrate/20201020172240_create_errors.exception_handler.rb:5:in `<class:CreateErrors>'
/Users/benn/Developments/sidepitch/sidepitch_camaleon/db/migrate/20201020172240_create_errors.exception_handler.rb:2:in `<top (required)>'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:986:in `load_migration'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:982:in `migration'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1350:in `use_transaction?'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1342:in `ddl_transaction'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1036:in `up'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/Users/benn/.rvm/gems/ruby-2.5.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/benn/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/Users/benn/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)`

**Comment by texpert** [comment]
@benn82 , could you retry without bootsnap?

**Comment by benn82** [comment]
@texpert I did but still the same. That migration file generated by Camaleon.

**Comment by texpert** [comment]
All Camaleon's migration files are here - https://github.com/owen2345/camaleon-cms/tree/master/db/migrate - there is no such migration.

Are you running `rake db:migrate` with `bundle exec`?

**Comment by benn82** [comment]
![image](https://user-images.githubusercontent.com/4177595/96630404-d408b900-12c9-11eb-9b62-8c81080a3dca.png)

It's generated by Camaleon. But anyway, it works after I deleted this file.

**Comment by benn82** [comment]
Thank you @texpert !

**Comment by texpert** [comment]
I've found it - this is, again, not from Camaleon, but from the exception_handler gem - https://github.com/richpeck/exception_handler/blob/master/db/migrate/000000_create_errors.rb

**Comment by benn82** [comment]
Got it @texpert . Thank you again. :)
