### ISSUE TITLE
The document page: http://camaleon.tuzitio.com/docs.html is down. I cannot check documents

### ISSUE THREAD

**Issue by troniez** [owen2345/camaleon-cms#982]
Got an error when access that page: 

We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

**Comment by owen2345** [comment]
Fixed!

**Comment by troniez** [comment]
Hi @owen2345, 
Hope you are doing well,
Now, I acess any document details,they down again: for example: 

http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/get-started.html

http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/installation-1.html

Regards,

**Comment by owen2345** [comment]
Fixed, thanks for reporting!
