### ISSUE TITLE
Invitation email when admin create account

### ISSUE THREAD

**Issue by troniez** [owen2345/camaleon-cms#983]
Hi all, 

Any chance for sending an Invitation email for when admin create new user? 

and then when new user click confirm link in email, let user redirect to reset password page to finish flow create new user?

**Comment by owen2345** [comment]
Hi @troniez 

unfortunately that feature is not auto included in CamaleonCMS. But you can easily add it using ```user_created``` hook:
https://github.com/owen2345/camaleon-cms/blob/master/app/controllers/camaleon_cms/admin/users_controller.rb#L74

Regards!

**Comment by troniez** [comment]
Thanks for your help! Working!
