### ISSUE TITLE
Simple clean install

### ISSUE THREAD

**Issue by hrcosteira** [owen2345/camaleon-cms#984]
Hi,

i've been trying to follow the simple steps to install a clean version on ruby 2.7.2 and rails 6.1 and I can't even start the server. Does anyone has a manual on the steps we need to take to have a working version of the CMS? 

`=> Booting Puma
=> Rails 6.0.3.4 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	40: from bin/rails:2:in `<main>'
	39: from bin/rails:2:in `load'
	38: from /Users/xxx/Work/cms/bin/spring:7:in `<top (required)>'
	37: from /Users/xxx/Work/cms/bin/spring:7:in `tap'
	36: from /Users/xxx/Work/cms/bin/spring:10:in `block in <top (required)>'
	35: from /Users/xxx/Work/cms/bin/spring:10:in `require'
	34: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	33: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	32: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	31: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	30: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	29: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	28: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	27: from /Users/xxx/Work/cms/bin/rails:5:in `<top (required)>'
	26: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	25: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	24: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	23: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	22: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	21: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	20: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	19: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	18: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
	17: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	16: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	15: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	14: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	12: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	11: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
	10: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	 9: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:37:in `start'
	 8: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	 7: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	 6: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	 5: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	 4: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	 3: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	 2: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	 1: from /Users/xxx/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
config.ru:6:in `block in <main>': undefined method `load_server' for #<Cms::Application:0x00007f9b0cb72100> (NoMethodError)
Did you mean?  load_seed`

**Comment by texpert** [comment]
Seems that you haven't upgraded Rails - you're still running the 6.0.3.4 version which has no `load_server` defined yet.

**Comment by hrcosteira** [comment]
I took it down to 6.0.3.4 because on 6.1 i get this error when I run 'rails generate camaleon_cms:install'

/Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/core_ext/hash/keys.rb:52:in `block in assert_valid_keys': Unknown key: :source. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :before_add, :after_add, :before_remove, :after_remove, :extend, :counter_cache, :join_table, :index_errors, :ensuring_owner_was (ArgumentError)
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/core_ext/hash/keys.rb:50:in `each_key'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/core_ext/hash/keys.rb:50:in `assert_valid_keys'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.1/lib/active_record/associations/builder/association.rb:69:in `validate_options'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.1/lib/active_record/associations/builder/association.rb:42:in `create_reflection'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.1/lib/active_record/associations/builder/association.rb:32:in `build'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.1/lib/active_record/associations.rb:1458:in `has_many'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/camaleon_cms-2.5.3.1/app/models/camaleon_cms/post_type.rb:10:in `<class:PostType>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/camaleon_cms-2.5.3.1/app/models/camaleon_cms/post_type.rb:1:in `<main>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:523:in `block in load_file'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:715:in `new_constants_in'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:522:in `load_file'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:419:in `block in require_or_load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:39:in `block in load_interlock'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:39:in `load_interlock'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:402:in `require_or_load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:558:in `load_missing_constant'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:213:in `const_missing'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/camaleon_cms-2.5.3.1/config/initializers/model_alias.rb:16:in `<main>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:326:in `block in load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:326:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/notifications.rb:205:in `instrument'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/engine.rb:680:in `load_config_initializer'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/engine.rb:633:in `each'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:50:in `each'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
	from /Users/xxx/Work/cms/config/environment.rb:5:in `<main>'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/xxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'

**Comment by texpert** [comment]
Ah, just got it that Rails 6.1 support is available yet only on camaleon_cms master branch - hasn't been released yet. 

Could you, please, try the master branch?

Also, @owen2345 , could we have, please, a new release to support Rails 6.1?!

**Comment by owen2345** [comment]
Released v2.6.0
https://github.com/owen2345/camaleon-cms/blob/master/CHANGELOG.md

So sorry guys, I forgot to release the new version.

**Comment by hrcosteira** [comment]
Thanks! Now we go a little further. I'm just getting a PG::DuplicateTable: ERROR:  relation "active_storage_blobs" already exists when I try to run migrations. Any clue?

**Comment by texpert** [comment]
Hm, I think camaleon-cms isn't using ActiveStorage yet.

**Comment by hrcosteira** [comment]
My bad.... 

rake db:drop / db:create / db:migrate

I guess I had some problems from everything that I've been trying to get this working before. 

Thanks for the help. Everything seems to be working.

**Comment by texpert** [comment]
Glad it is working, @hrcosteira !

Feel free to close the issue, if everything's OK.
